import { AppData } from '../types';

export const germanData: AppData = 
{
  "meta": {
    "source_language": "zh-TW",
    "target_language": "de-DE",
    "version": "2.3",
    "description": "台灣人快速語言學習 - 德文完整版 (包含所有原始列表單字與完整句型 - IPA 發音版)"
  },
  "categories": [
    {
      "id": "greetings",
      "name": "常用句",
      "items": [
        {
          "id": "greet-001",
          "term_zh": "你好",
          "term_target": "Hallo",
          "pronunciation": ["/ˈhalo/"],
          "example": { "sentence": "Hallo, wie geht's?", "translation": "你好，你好嗎？" },
          "usage_note": "最通用的問候。",
          "image_file": "hello.png"
        },
        {
          "id": "greet-002",
          "term_zh": "再見",
          "term_target": "Auf Wiedersehen",
          "pronunciation": ["/aʊf ˈviːdɐzeːən/"],
          "example": { "sentence": "Auf Wiedersehen, bis bald.", "translation": "再見，待會見。" },
          "usage_note": "正式道別。朋友間常用 Tschüss。",
          "image_file": "goodbye.png"
        },
        {
          "id": "greet-003",
          "term_zh": "謝謝你",
          "term_target": "Danke",
          "pronunciation": ["/ˈdaŋkə/"],
          "example": { "sentence": "Danke schön.", "translation": "非常謝謝你。" },
          "usage_note": "通用感謝語。",
          "image_file": "thank_you.png"
        },
        {
          "id": "greet-004",
          "term_zh": "對不起",
          "term_target": "Entschuldigung",
          "pronunciation": ["/ɛntˈʃʊldɪɡʊŋ/"],
          "example": { "sentence": "Entschuldigung, ich bin zu spät.", "translation": "對不起，我遲到了。" },
          "usage_note": "道歉或藉過時使用。",
          "image_file": "sorry.png"
        },
        {
          "id": "greet-005",
          "term_zh": "早安",
          "term_target": "Guten Morgen",
          "pronunciation": ["/ˌɡuːtn̩ ˈmɔʁɡn̩/"],
          "example": { "sentence": "Guten Morgen, Mama.", "translation": "早安，媽。" },
          "usage_note": "大約早上10-11點前使用。",
          "image_file": "good_morning.png"
        },
        {
          "id": "greet-006",
          "term_zh": "請問... / 借過",
          "term_target": "Entschuldigung",
          "pronunciation": ["/ɛntˈʃʊldɪɡʊŋ/"],
          "example": { "sentence": "Entschuldigung, darf ich mal vorbei?", "translation": "不好意思，藉過一下。" },
          "usage_note": "引起注意或請求讓路都用這個。",
          "image_file": "excuse_me.png"
        },
        {
          "id": "greet-007",
          "term_zh": "我不懂",
          "term_target": "Ich verstehe nicht",
          "pronunciation": ["/ɪç fɛɐ̯ˈʃteːə nɪçt/"],
          "example": { "sentence": "Ich verstehe kein Deutsch.", "translation": "我不懂德文。" },
          "usage_note": "聽不懂時直接說。",
          "image_file": "dont_understand.png"
        },
        {
          "id": "greet-008",
          "term_zh": "這是什麼？",
          "term_target": "Was ist das?",
          "pronunciation": ["/vas ɪst das/"],
          "example": { "sentence": "Was ist das? Essen?", "translation": "這是什麼？食物嗎？" },
          "usage_note": "指著東西問。",
          "image_file": "what_is_this.png"
        },
        {
          "id": "greet-009",
          "term_zh": "我想要這個",
          "term_target": "Ich möchte das",
          "pronunciation": ["/ɪç ˈmœçtə das/"],
          "example": { "sentence": "Ich möchte das, bitte.", "translation": "麻煩我要這個。" },
          "usage_note": "表達願望。",
          "image_file": "i_want_this.png"
        },
        {
          "id": "greet-010",
          "term_zh": "請給我...",
          "term_target": "Ich hätte gerne...",
          "pronunciation": ["/ɪç ˈhɛtə ˈɡɛʁnə/"],
          "example": { "sentence": "Ich hätte gerne Wasser.", "translation": "請給我水。" },
          "usage_note": "點餐時非常有禮貌的說法。",
          "image_file": "please_give_me.png"
        },
        {
          "id": "greet-011",
          "term_zh": "廁所在哪裡？",
          "term_target": "Wo ist die Toilette?",
          "pronunciation": ["/vo ɪst di toˈlɛtə/"],
          "example": { "sentence": "Entschuldigung, wo ist die Toilette?", "translation": "請問廁所在哪？" },
          "usage_note": "旅遊必備。",
          "image_file": "where_bathroom.png"
        },
        {
          "id": "greet-012",
          "term_zh": "多少錢？",
          "term_target": "Wie viel kostet das?",
          "pronunciation": ["/vi fiːl ˈkɔstət das/"],
          "example": { "sentence": "Wie viel kostet das?", "translation": "這個多少錢？" },
          "usage_note": "購物用語。",
          "image_file": "how_much.png"
        },
        {
          "id": "greet-013",
          "term_zh": "請幫我",
          "term_target": "Helfen Sie mir bitte",
          "pronunciation": ["/ˈhɛlfn̩ ziː miːɐ̯ ˈbɪtə/"],
          "example": { "sentence": "Können Sie mir helfen?", "translation": "能幫我嗎？" },
          "usage_note": "尋求協助 (對陌生人用 Sie)。",
          "image_file": "help_me.png"
        },
        {
          "id": "greet-014",
          "term_zh": "你可以再說一次嗎？",
          "term_target": "Können Sie das wiederholen?",
          "pronunciation": ["/ˈkœnən ziː das viːdɐˈhoːlən/"],
          "example": { "sentence": "Wie bitte? Können Sie das wiederholen?", "translation": "蛤？能再說一次嗎？" },
          "usage_note": "沒聽清楚時。",
          "image_file": "say_again.png"
        },
        {
          "id": "greet-015",
          "term_zh": "你可以講慢一點嗎？",
          "term_target": "Können Sie langsamer sprechen?",
          "pronunciation": ["/ˈkœnən ziː ˈlaŋzamɐ ˈʃpʁɛçn̩/"],
          "example": { "sentence": "Bitte sprechen Sie langsamer.", "translation": "拜託請講慢一點。" },
          "usage_note": "Langsam 是「慢」。",
          "image_file": "speak_slowly.png"
        }
      ]
    },
    {
      "id": "pronouns",
      "name": "主詞（代名詞）",
      "items": [
        { "id": "pro-01", "term_zh": "我", "term_target": "Ich", "pronunciation": ["/ɪç/"], "example": {"sentence": "Ich bin aus Taiwan.", "translation": "我來自台灣。"}, "usage_note": "第一人稱。", "image_file": "i.png" },
        { "id": "pro-02", "term_zh": "你", "term_target": "Du / Sie", "pronunciation": ["/duː/", "/ziː/"], "example": {"sentence": "Wer bist du?", "translation": "你是誰？"}, "usage_note": "Du(朋友/平輩)，Sie(長輩/陌生人/正式)。", "image_file": "you.png" },
        { "id": "pro-03", "term_zh": "他", "term_target": "Er", "pronunciation": ["/eːɐ̯/"], "example": {"sentence": "Er ist Lehrer.", "translation": "他是老師。"}, "usage_note": "男性。", "image_file": "he.png" },
        { "id": "pro-04", "term_zh": "她", "term_target": "Sie", "pronunciation": ["/ziː/"], "example": {"sentence": "Sie ist nett.", "translation": "她很親切。"}, "usage_note": "女性 (注意S小寫，除非句首)。", "image_file": "she.png" },
        { "id": "pro-05", "term_zh": "我們", "term_target": "Wir", "pronunciation": ["/viːɐ̯/"], "example": {"sentence": "Wir sind Familie.", "translation": "我們是家人。"}, "usage_note": "第一人稱複數。", "image_file": "we.png" },
        { "id": "pro-06", "term_zh": "他們", "term_target": "Sie", "pronunciation": ["/ziː/"], "example": {"sentence": "Sie essen.", "translation": "他們在吃。"}, "usage_note": "他們/她們 (S小寫)。", "image_file": "they.png" },
        { "id": "pro-07", "term_zh": "這個", "term_target": "Das / Dies", "pronunciation": ["/das/", "/diːs/"], "example": {"sentence": "Das ist gut.", "translation": "這很好。"}, "usage_note": "Das 既是定冠詞也是代名詞。", "image_file": "this.png" },
        { "id": "pro-08", "term_zh": "那個/它", "term_target": "Das / Es", "pronunciation": ["/das/", "/ɛs/"], "example": {"sentence": "Was ist das?", "translation": "那是什麼？"}, "usage_note": "Es 代指中性名詞或「它」。", "image_file": "that.png" },
        { "id": "pro-09", "term_zh": "他的", "term_target": "Sein", "pronunciation": ["/zaɪn/"], "example": {"sentence": "Sein Auto.", "translation": "他的車。"}, "usage_note": "需隨名詞性別變化 (Seine)。", "image_file": "his.png" },
        { "id": "pro-10", "term_zh": "她的", "term_target": "Ihr", "pronunciation": ["/iːɐ̯/"], "example": {"sentence": "Ihre Tasche.", "translation": "她的包包。"}, "usage_note": "需隨名詞性別變化。", "image_file": "her.png" },
        { "id": "pro-11", "term_zh": "你的", "term_target": "Dein / Ihr", "pronunciation": ["/daɪn/", "/iːɐ̯/"], "example": {"sentence": "Dein Name.", "translation": "你的名字。"}, "usage_note": "Dein(非正式)，Ihr(正式)。", "image_file": "your.png" },
        { "id": "pro-12", "term_zh": "他們的", "term_target": "Ihr", "pronunciation": ["/iːɐ̯/"], "example": {"sentence": "Ihr Haus.", "translation": "他們的家。"}, "usage_note": "需隨名詞性別變化。", "image_file": "their.png" },
        { "id": "pro-13", "term_zh": "我們的", "term_target": "Unser", "pronunciation": ["/ˈʊnzɐ/"], "example": {"sentence": "Unsere Schule.", "translation": "我們的學校。"}, "usage_note": "需隨名詞性別變化。", "image_file": "our.png" },
        { "id": "pro-14", "term_zh": "這些", "term_target": "Diese", "pronunciation": ["/ˈdiːzə/"], "example": {"sentence": "Diese Bücher.", "translation": "這些書。"}, "usage_note": "複數。", "image_file": "these.png" },
        { "id": "pro-15", "term_zh": "那些", "term_target": "Jene / Die", "pronunciation": ["/ˈjeːnə/", "/diː/"], "example": {"sentence": "Jene Vögel.", "translation": "那些鳥。"}, "usage_note": "遠處複數。", "image_file": "those.png" }
      ]
    },
    {
      "id": "verbs",
      "name": "動詞",
      "items": [
        { "id": "v-01", "term_zh": "是", "term_target": "Sein", "pronunciation": ["/zaɪn/"], "example": {"sentence": "Ich bin Student.", "translation": "我是學生。"}, "usage_note": "不規則變化 (bin, bist, ist...)。", "image_file": "be.png" },
        { "id": "v-02", "term_zh": "有", "term_target": "Haben", "pronunciation": ["/ˈhaːbn̩/"], "example": {"sentence": "Ich habe Geld.", "translation": "我有錢。"}, "usage_note": "擁有。", "image_file": "have.png" },
        { "id": "v-03", "term_zh": "去", "term_target": "Gehen", "pronunciation": ["/ˈɡeːən/"], "example": {"sentence": "Ich gehe nach Hause.", "translation": "我回家。"}, "usage_note": "走路去/移動。", "image_file": "go.png" },
        { "id": "v-04", "term_zh": "做", "term_target": "Machen / Tun", "pronunciation": ["/ˈmaxn̩/", "/tuːn/"], "example": {"sentence": "Hausaufgaben machen.", "translation": "做作業。"}, "usage_note": "Machen 最常用。", "image_file": "do.png" },
        { "id": "v-05", "term_zh": "說", "term_target": "Sagen", "pronunciation": ["/ˈzaːɡn̩/"], "example": {"sentence": "Sag Hallo.", "translation": "說你好。"}, "usage_note": "說出內容。", "image_file": "say.png" },
        { "id": "v-06", "term_zh": "知道", "term_target": "Wissen / Kennen", "pronunciation": ["/ˈvɪsn̩/", "/ˈkɛnən/"], "example": {"sentence": "Ich weiß nicht. Ich kenne ihn.", "translation": "我不知道。我認識他。"}, "usage_note": "Wissen(知識)，Kennen(認識人/地)。", "image_file": "know.png" },
        { "id": "v-07", "term_zh": "想/思考", "term_target": "Denken", "pronunciation": ["/ˈdɛŋkn̩/"], "example": {"sentence": "Ich denke schon.", "translation": "我想是的。"}, "usage_note": "思考。", "image_file": "think.png" },
        { "id": "v-08", "term_zh": "看見", "term_target": "Sehen", "pronunciation": ["/ˈzeːən/"], "example": {"sentence": "Ich sehe einen Vogel.", "translation": "我看見一隻鳥。"}, "usage_note": "看。", "image_file": "see.png" },
        { "id": "v-09", "term_zh": "製作", "term_target": "Machen", "pronunciation": ["/ˈmaxn̩/"], "example": {"sentence": "Kaffee machen.", "translation": "煮咖啡。"}, "usage_note": "同「做」。", "image_file": "make.png" },
        { "id": "v-10", "term_zh": "來", "term_target": "Kommen", "pronunciation": ["/ˈkɔmən/"], "example": {"sentence": "Komm hierher.", "translation": "來這裡。"}, "usage_note": "過來。", "image_file": "come.png" },
        { "id": "v-11", "term_zh": "需要", "term_target": "Brauchen", "pronunciation": ["/ˈbʁaʊxn̩/"], "example": {"sentence": "Ich brauche Wasser.", "translation": "我需要水。"}, "usage_note": "需要。", "image_file": "need.png" },
        { "id": "v-12", "term_zh": "使用", "term_target": "Benutzen", "pronunciation": ["/bəˈnʊt͡sn̩/"], "example": {"sentence": "Einen Stift benutzen.", "translation": "用筆。"}, "usage_note": "使用。", "image_file": "use.png" },
        { "id": "v-13", "term_zh": "找到", "term_target": "Finden", "pronunciation": ["/ˈfɪndn̩/"], "example": {"sentence": "Arbeit finden.", "translation": "找工作。"}, "usage_note": "發現/覺得。", "image_file": "find.png" },
        { "id": "v-14", "term_zh": "給", "term_target": "Geben", "pronunciation": ["/ˈɡeːbn̩/"], "example": {"sentence": "Gib mir das.", "translation": "給我那個。"}, "usage_note": "給予。", "image_file": "give.png" },
        { "id": "v-15", "term_zh": "告訴", "term_target": "Erzählen / Sagen", "pronunciation": ["/ɛɐ̯ˈt͡sɛːlən/", "/ˈzaːɡn̩/"], "example": {"sentence": "Erzähl mir.", "translation": "告訴我(故事/經過)。"}, "usage_note": "告知。", "image_file": "tell.png" },
        { "id": "v-16", "term_zh": "工作", "term_target": "Arbeiten", "pronunciation": ["/ˈaʁbaɪtn̩/"], "example": {"sentence": "Ich arbeite hier.", "translation": "我在這工作。"}, "usage_note": "勞動。", "image_file": "work.png" },
        { "id": "v-17", "term_zh": "喜歡", "term_target": "Mögen", "pronunciation": ["/ˈmøːɡn̩/"], "example": {"sentence": "Ich mag das.", "translation": "我喜歡這個。"}, "usage_note": "喜好。", "image_file": "like.png" },
        { "id": "v-18", "term_zh": "起床/醒來", "term_target": "Aufstehen", "pronunciation": ["/ˈaʊfˌʃteːən/"], "example": {"sentence": "Ich stehe um 7 Uhr auf.", "translation": "我七點起床。"}, "usage_note": "可分動詞 (auf-stehen)。", "image_file": "wake_up.png" },
        { "id": "v-19", "term_zh": "說話", "term_target": "Sprechen", "pronunciation": ["/ˈʃpʁɛçn̩/"], "example": {"sentence": "Deutsch sprechen.", "translation": "說德文。"}, "usage_note": "講語言。", "image_file": "speak.png" },
        { "id": "v-20", "term_zh": "聽見", "term_target": "Hören", "pronunciation": ["/ˈhøːʁən/"], "example": {"sentence": "Hörst du mich?", "translation": "聽得到我嗎？"}, "usage_note": "聽。", "image_file": "hear.png" },
        { "id": "v-21", "term_zh": "寫", "term_target": "Schreiben", "pronunciation": ["/ˈʃʁaɪbn̩/"], "example": {"sentence": "Einen Namen schreiben.", "translation": "寫名字。"}, "usage_note": "書寫。", "image_file": "write.png" },
        { "id": "v-22", "term_zh": "閱讀", "term_target": "Lesen", "pronunciation": ["/ˈleːzn̩/"], "example": {"sentence": "Ein Buch lesen.", "translation": "看書。"}, "usage_note": "閱讀。", "image_file": "read.png" },
        { "id": "v-23", "term_zh": "等待", "term_target": "Warten", "pronunciation": ["/ˈvaʁtn̩/"], "example": {"sentence": "Warte auf mich.", "translation": "等我。"}, "usage_note": "等候。", "image_file": "wait.png" },
        { "id": "v-24", "term_zh": "嘗試", "term_target": "Versuchen / Probieren", "pronunciation": ["/fɛɐ̯ˈzuːxn̩/", "/pʁoˈbiːʁən/"], "example": {"sentence": "Probier das.", "translation": "試試這個(食物)。"}, "usage_note": "Probieren(試吃), Versuchen(嘗試)。", "image_file": "try.png" },
        { "id": "v-25", "term_zh": "付錢", "term_target": "Bezahlen", "pronunciation": ["/bəˈt͡saːlən/"], "example": {"sentence": "Die Rechnung bezahlen.", "translation": "付帳單。"}, "usage_note": "支付。", "image_file": "pay.png" },
        { "id": "v-26", "term_zh": "住", "term_target": "Wohnen / Leben", "pronunciation": ["/ˈvoːnən/", "/ˈleːbn̩/"], "example": {"sentence": "Ich wohne in Taipeh.", "translation": "我住台北。"}, "usage_note": "Wohnen(居住), Leben(生活)。", "image_file": "live.png" },
        { "id": "v-27", "term_zh": "走路", "term_target": "Gehen / Laufen", "pronunciation": ["/ˈɡeːən/", "/ˈlaʊfn̩/"], "example": {"sentence": "Nach Hause laufen.", "translation": "走路回家。"}, "usage_note": "Laufen 也可指跑。", "image_file": "walk.png" },
        { "id": "v-28", "term_zh": "打開", "term_target": "Öffnen / Aufmachen", "pronunciation": ["/ˈœfnən/", "/ˈaʊfˌmaxn̩/"], "example": {"sentence": "Die Tür öffnen.", "translation": "開門。"}, "usage_note": "開啟。", "image_file": "open.png" },
        { "id": "v-29", "term_zh": "關閉", "term_target": "Schließen / Zumachen", "pronunciation": ["/ˈʃliːsn̩/", "/ˈt͡suːˌmaxn̩/"], "example": {"sentence": "Das Fenster schließen.", "translation": "關窗。"}, "usage_note": "關上。", "image_file": "close.png" },
        { "id": "v-30", "term_zh": "幫助", "term_target": "Helfen", "pronunciation": ["/ˈhɛlfn̩/"], "example": {"sentence": "Hilf mir.", "translation": "幫我。"}, "usage_note": "協助。", "image_file": "help.png" },
        { "id": "v-31", "term_zh": "吃", "term_target": "Essen", "pronunciation": ["/ˈɛsn̩/"], "example": {"sentence": "Mittagessen essen.", "translation": "吃午餐。"}, "usage_note": "進食。", "image_file": "eat.png" },
        { "id": "v-32", "term_zh": "睡覺", "term_target": "Schlafen", "pronunciation": ["/ˈʃlaːfn̩/"], "example": {"sentence": "Ich gehe schlafen.", "translation": "我要去睡覺了。"}, "usage_note": "睡眠。", "image_file": "sleep.png" },
        { "id": "v-33", "term_zh": "買", "term_target": "Kaufen", "pronunciation": ["/ˈkaʊfn̩/"], "example": {"sentence": "Ein Auto kaufen.", "translation": "買車。"}, "usage_note": "購買。", "image_file": "buy.png" },
        { "id": "v-34", "term_zh": "乘坐/拿", "term_target": "Nehmen", "pronunciation": ["/ˈneːmən/"], "example": {"sentence": "Den Bus nehmen.", "translation": "搭公車。"}, "usage_note": "Nehmen(拿/搭乘)。", "image_file": "take.png" },
        { "id": "v-35", "term_zh": "得到/拿", "term_target": "Bekommen / Holen", "pronunciation": ["/bəˈkɔmən/", "/ˈhoːlən/"], "example": {"sentence": "Arbeit bekommen.", "translation": "得到工作。"}, "usage_note": "獲得。", "image_file": "get.png" },
        { "id": "v-36", "term_zh": "選擇", "term_target": "Wählen / Aussuchen", "pronunciation": ["/ˈvɛːlən/", "/ˈaʊsˌzuːxn̩/"], "example": {"sentence": "Wähl eins.", "translation": "選一個。"}, "usage_note": "挑選。", "image_file": "choose.png" },
        { "id": "v-37", "term_zh": "進入", "term_target": "Eintreten / Hingehen", "pronunciation": ["/ˈaɪnˌtʁeːtn̩/", "/ˈhɪnˌɡeːən/"], "example": {"sentence": "In das Zimmer gehen.", "translation": "進房間。"}, "usage_note": "進入。", "image_file": "enter.png" },
        { "id": "v-38", "term_zh": "到達", "term_target": "Ankommen", "pronunciation": ["/ˈanˌkɔmən/"], "example": {"sentence": "Pünktlich ankommen.", "translation": "準時到達。"}, "usage_note": "可分動詞 (an-kommen)。", "image_file": "arrive.png" },
        { "id": "v-39", "term_zh": "帶來", "term_target": "Bringen", "pronunciation": ["/ˈbʁɪŋən/"], "example": {"sentence": "Wasser bringen.", "translation": "帶水來。"}, "usage_note": "攜帶。", "image_file": "bring.png" },
        { "id": "v-40", "term_zh": "變成", "term_target": "Werden", "pronunciation": ["/ˈveːɐ̯dn̩/"], "example": {"sentence": "Lehrer werden.", "translation": "變成老師。"}, "usage_note": "變化。", "image_file": "become.png" },
        { "id": "v-41", "term_zh": "開始", "term_target": "Anfangen / Beginnen", "pronunciation": ["/ˈanˌfaŋən/", "/bəˈɡɪnən/"], "example": {"sentence": "Jetzt anfangen.", "translation": "現在開始。"}, "usage_note": "可分 (an-fangen)。", "image_file": "start.png" },
        { "id": "v-42", "term_zh": "結束", "term_target": "Beenden / Aufhören", "pronunciation": ["/bəˈʔɛndn̩/", "/ˈaʊfˌhøːʁən/"], "example": {"sentence": "Die Arbeit beenden.", "translation": "工作結束。"}, "usage_note": "完成。", "image_file": "finish.png" },
        { "id": "v-43", "term_zh": "停止", "term_target": "Stoppen / Anhalten", "pronunciation": ["/ˈstɔpn̩/", "/ˈanˌhaltn̩/"], "example": {"sentence": "Hier stoppen.", "translation": "停在這裡。"}, "usage_note": "停止。", "image_file": "stop.png" },
        { "id": "v-44", "term_zh": "記住", "term_target": "Sich erinnern", "pronunciation": ["/zɪç ɛɐ̯ˈʔɪnɐn/"], "example": {"sentence": "Erinnerst du dich an mich?", "translation": "記得我嗎？"}, "usage_note": "反身動詞。", "image_file": "remember.png" },
        { "id": "v-45", "term_zh": "見面", "term_target": "Treffen", "pronunciation": ["/ˈtʁɛfn̩/"], "example": {"sentence": "Freunde treffen.", "translation": "跟朋友碰面。"}, "usage_note": "會面。", "image_file": "meet.png" },
        { "id": "v-46", "term_zh": "放", "term_target": "Legen / Stellen", "pronunciation": ["/ˈleːɡn̩/", "/ˈʃtɛlən/"], "example": {"sentence": "Leg es hierhin.", "translation": "平放這裡。"}, "usage_note": "Legen(平放), Stellen(豎放)。", "image_file": "put.png" },
        { "id": "v-47", "term_zh": "寄送", "term_target": "Senden / Schicken", "pronunciation": ["/ˈzɛndn̩/", "/ˈʃɪkn̩/"], "example": {"sentence": "Eine E-Mail senden.", "translation": "寄信。"}, "usage_note": "傳送。", "image_file": "send.png" },
        { "id": "v-48", "term_zh": "開車", "term_target": "Fahren", "pronunciation": ["/ˈfaːʁən/"], "example": {"sentence": "Auto fahren.", "translation": "開車。"}, "usage_note": "駕駛。", "image_file": "drive.png" },
        { "id": "v-49", "term_zh": "讀書", "term_target": "Lernen / Studieren", "pronunciation": ["/ˈlɛʁnən/", "/ʃtuˈdiːʁən/"], "example": {"sentence": "Deutsch lernen.", "translation": "學德文。"}, "usage_note": "Lernen(學習), Studieren(上大學)。", "image_file": "study.png" },
        { "id": "v-50", "term_zh": "回去", "term_target": "Zurückgehen", "pronunciation": ["/tsuˈʁʏkˌɡeːən/"], "example": {"sentence": "Nach Hause zurückgehen.", "translation": "回家。"}, "usage_note": "歸返。", "image_file": "go_back.png" }
      ]
    },
    {
      "id": "adjectives",
      "name": "形容詞",
      "items": [
        { "id": "adj-01", "term_zh": "好的", "term_target": "Gut", "pronunciation": ["/ɡuːt/"], "example": {"sentence": "Gute Arbeit.", "translation": "做得好。"}, "usage_note": "正面。", "image_file": "good.png" },
        { "id": "adj-02", "term_zh": "壞的", "term_target": "Schlecht", "pronunciation": ["/ʃlɛçt/"], "example": {"sentence": "Schlechter Tag.", "translation": "壞的一天。"}, "usage_note": "負面。", "image_file": "bad.png" },
        { "id": "adj-03", "term_zh": "新的", "term_target": "Neu", "pronunciation": ["/nɔʏ/"], "example": {"sentence": "Neues Handy.", "translation": "新手機。"}, "usage_note": "全新。", "image_file": "new.png" },
        { "id": "adj-04", "term_zh": "大的", "term_target": "Groß", "pronunciation": ["/ɡʁoːs/"], "example": {"sentence": "Großes Haus.", "translation": "大房子。"}, "usage_note": "體積大。", "image_file": "big.png" },
        { "id": "adj-05", "term_zh": "小的", "term_target": "Klein", "pronunciation": ["/klaɪn/"], "example": {"sentence": "Kleine Katze.", "translation": "小貓。"}, "usage_note": "體積小。", "image_file": "small.png" },
        { "id": "adj-06", "term_zh": "熱的", "term_target": "Heiß", "pronunciation": ["/haɪs/"], "example": {"sentence": "Heißes Wasser.", "translation": "熱水。"}, "usage_note": "高溫。", "image_file": "hot.png" },
        { "id": "adj-07", "term_zh": "冷的", "term_target": "Kalt", "pronunciation": ["/kalt/"], "example": {"sentence": "Kaltes Getränk.", "translation": "冷飲。"}, "usage_note": "低溫。", "image_file": "cold.png" },
        { "id": "adj-08", "term_zh": "簡單的", "term_target": "Einfach", "pronunciation": ["/ˈaɪnfan/"], "example": {"sentence": "Es ist einfach.", "translation": "這很簡單。"}, "usage_note": "容易。", "image_file": "easy.png" },
        { "id": "adj-09", "term_zh": "困難的", "term_target": "Schwierig", "pronunciation": ["/ˈʃviːʁɪç/"], "example": {"sentence": "Es ist schwierig.", "translation": "很難。"}, "usage_note": "難。", "image_file": "difficult.png" },
        { "id": "adj-10", "term_zh": "美味的", "term_target": "Lecker", "pronunciation": ["/ˈlɛkɐ/"], "example": {"sentence": "Leckeres Essen.", "translation": "好吃的食物。"}, "usage_note": "好吃。", "image_file": "delicious.png" },
        { "id": "adj-11", "term_zh": "忙碌的", "term_target": "Beschäftigt", "pronunciation": ["/bəˈʃɛftɪçt/"], "example": {"sentence": "Ich bin beschäftigt.", "translation": "我很忙。"}, "usage_note": "沒空。", "image_file": "busy.png" },
        { "id": "adj-12", "term_zh": "疲累的", "term_target": "Müde", "pronunciation": ["/ˈmyːdə/"], "example": {"sentence": "Ich bin müde.", "translation": "我累了。"}, "usage_note": "狀態。", "image_file": "tired.png" },
        { "id": "adj-13", "term_zh": "快樂的", "term_target": "Glücklich / Froh", "pronunciation": ["/ˈɡlʏklɪç/", "/fʁoː/"], "example": {"sentence": "Frohes Fest.", "translation": "佳節愉快。"}, "usage_note": "心情。", "image_file": "happy.png" },
        { "id": "adj-14", "term_zh": "悲傷的", "term_target": "Traurig", "pronunciation": ["/ˈtʁaʊʁɪç/"], "example": {"sentence": "Traurige Geschichte.", "translation": "悲傷的故事。"}, "usage_note": "難過。", "image_file": "sad.png" },
        { "id": "adj-15", "term_zh": "乾淨的", "term_target": "Sauber", "pronunciation": ["/ˈzaʊbɐ/"], "example": {"sentence": "Sauberes Zimmer.", "translation": "乾淨的房間。"}, "usage_note": "無髒汙。", "image_file": "clean.png" },
        { "id": "adj-16", "term_zh": "髒的", "term_target": "Schmutzig", "pronunciation": ["/ˈʃmʊt͡sɪç/"], "example": {"sentence": "Schmutzige Hände.", "translation": "髒手。"}, "usage_note": "不乾淨。", "image_file": "dirty.png" },
        { "id": "adj-17", "term_zh": "便宜的", "term_target": "Billig / Günstig", "pronunciation": ["/ˈbɪlɪç/", "/ˈɡʏnstɪç/"], "example": {"sentence": "Es ist billig.", "translation": "這很便宜。"}, "usage_note": "價格低。", "image_file": "cheap.png" },
        { "id": "adj-18", "term_zh": "昂貴的", "term_target": "Teuer", "pronunciation": ["/ˈtɔʏɐ/"], "example": {"sentence": "Zu teuer.", "translation": "太貴了。"}, "usage_note": "價格高。", "image_file": "expensive.png" },
        { "id": "adj-19", "term_zh": "重要的", "term_target": "Wichtig", "pronunciation": ["/ˈvɪçtɪç/"], "example": {"sentence": "Wichtiger Termin.", "translation": "重要會議。"}, "usage_note": "關鍵。", "image_file": "important.png" },
        { "id": "adj-20", "term_zh": "相同的", "term_target": "Gleich", "pronunciation": ["/ɡlaɪç/"], "example": {"sentence": "Der gleiche Ort.", "translation": "同個地方。"}, "usage_note": "一樣。", "image_file": "same.png" },
        { "id": "adj-21", "term_zh": "第一的", "term_target": "Erste", "pronunciation": ["/ˈeːɐ̯stə/"], "example": {"sentence": "Das erste Mal.", "translation": "第一次。"}, "usage_note": "順序。", "image_file": "first.png" },
        { "id": "adj-22", "term_zh": "上一個", "term_target": "Letzte", "pronunciation": ["/ˈlɛt͡stə/"], "example": {"sentence": "Letzte Woche.", "translation": "上週。"}, "usage_note": "過去的/最後的。", "image_file": "last.png" },
        { "id": "adj-23", "term_zh": "下一個", "term_target": "Nächste", "pronunciation": ["/ˈnɛːçstə/"], "example": {"sentence": "Nächste Station.", "translation": "下一站。"}, "usage_note": "接下來。", "image_file": "next.png" },
        { "id": "adj-24", "term_zh": "長的", "term_target": "Lang", "pronunciation": ["/laŋ/"], "example": {"sentence": "Langes Haar.", "translation": "長髮。"}, "usage_note": "長度。", "image_file": "long.png" },
        { "id": "adj-25", "term_zh": "多的", "term_target": "Viel / Viele", "pronunciation": ["/fiːl/", "/ˈfiːlə/"], "example": {"sentence": "Viele Leute.", "translation": "很多人。"}, "usage_note": "Viel(不可數), Viele(可數)。", "image_file": "many.png" },
        { "id": "adj-26", "term_zh": "高的", "term_target": "Hoch / Groß", "pronunciation": ["/hoːx/", "/ɡʁoːs/"], "example": {"sentence": "Hohes Gebäude.", "translation": "高樓。"}, "usage_note": "Hoch(建築), Groß(人)。", "image_file": "tall.png" },
        { "id": "adj-27", "term_zh": "年輕的", "term_target": "Jung", "pronunciation": ["/jʊŋ/"], "example": {"sentence": "Junger Mann.", "translation": "年輕人。"}, "usage_note": "年紀小。", "image_file": "young.png" },
        { "id": "adj-28", "term_zh": "老的/舊的", "term_target": "Alt", "pronunciation": ["/alt/"], "example": {"sentence": "Altes Buch.", "translation": "舊書。"}, "usage_note": "人或物皆可。", "image_file": "old.png" },
        { "id": "adj-29", "term_zh": "近的", "term_target": "Nah", "pronunciation": ["/naː/"], "example": {"sentence": "In der Nähe.", "translation": "在這附近。"}, "usage_note": "距離近。", "image_file": "near.png" },
        { "id": "adj-30", "term_zh": "遠的", "term_target": "Weit", "pronunciation": ["/vaɪt/"], "example": {"sentence": "Es ist weit.", "translation": "很遠。"}, "usage_note": "距離遠。", "image_file": "far.png" },
        { "id": "adj-31", "term_zh": "快的", "term_target": "Schnell", "pronunciation": ["/ʃnɛl/"], "example": {"sentence": "Schnelles Auto.", "translation": "快車。"}, "usage_note": "速度快。", "image_file": "fast.png" },
        { "id": "adj-32", "term_zh": "慢的", "term_target": "Langsam", "pronunciation": ["/ˈlaŋzam/"], "example": {"sentence": "Langsames Internet.", "translation": "網路慢。"}, "usage_note": "速度慢。", "image_file": "slow.png" },
        { "id": "adj-33", "term_zh": "正確的", "term_target": "Richtig", "pronunciation": ["/ˈʁɪçtɪç/"], "example": {"sentence": "Richtige Antwort.", "translation": "正確答案。"}, "usage_note": "對的。", "image_file": "correct.png" },
        { "id": "adj-34", "term_zh": "錯誤的", "term_target": "Falsch", "pronunciation": ["/falʃ/"], "example": {"sentence": "Das ist falsch.", "translation": "是錯的。"}, "usage_note": "不對。", "image_file": "wrong.png" },
        { "id": "adj-35", "term_zh": "不同的", "term_target": "Anders / Verschieden", "pronunciation": ["/ˈandɐs/", "/fɛɐ̯ˈʃiːdn̩/"], "example": {"sentence": "Andere Farbe.", "translation": "不同顏色。"}, "usage_note": "差異。", "image_file": "different.png" },
        { "id": "adj-36", "term_zh": "真的", "term_target": "Echt / Wirklich", "pronunciation": ["/ɛçt/", "/ˈvɪʁklɪç/"], "example": {"sentence": "Echtes Gold.", "translation": "真金。"}, "usage_note": "真實。", "image_file": "real.png" },
        { "id": "adj-37", "term_zh": "有趣的", "term_target": "Interessant", "pronunciation": ["/ɪntəʁɛˈsant/"], "example": {"sentence": "Interessantes Buch.", "translation": "有趣的書。"}, "usage_note": "有意思。", "image_file": "interesting.png" },
        { "id": "adj-38", "term_zh": "飢餓的", "term_target": "Hungrig", "pronunciation": ["/ˈhʊŋʁɪç/"], "example": {"sentence": "Ich habe Hunger.", "translation": "我餓了(我有飢餓)。"}, "usage_note": "名詞用法較常見。", "image_file": "hungry.png" },
        { "id": "adj-39", "term_zh": "有名的", "term_target": "Berühmt", "pronunciation": ["/bəˈʁyːmt/"], "example": {"sentence": "Berühmter Schauspieler.", "translation": "知名演員。"}, "usage_note": "知名。", "image_file": "famous.png" },
        { "id": "adj-40", "term_zh": "外國的", "term_target": "Ausländisch", "pronunciation": ["/ˈaʊsˌlɛndɪʃ/"], "example": {"sentence": "Ausland.", "translation": "外國。"}, "usage_note": "國外。", "image_file": "foreign.png" },
        { "id": "adj-41", "term_zh": "聰明的", "term_target": "Klug / Intelligent", "pronunciation": ["/kluːk/", "/ɪntɛliˈɡɛnt/"], "example": {"sentence": "Kluges Kind.", "translation": "聰明的孩子。"}, "usage_note": "腦袋好。", "image_file": "intelligent.png" },
        { "id": "adj-42", "term_zh": "危險的", "term_target": "Gefährlich", "pronunciation": ["/ɡəˈfɛːɐ̯lɪç/"], "example": {"sentence": "Es ist gefährlich.", "translation": "這很危險。"}, "usage_note": "警示。", "image_file": "dangerous.png" },
        { "id": "adj-43", "term_zh": "仁慈的", "term_target": "Nett / Freundlich", "pronunciation": ["/nɛt/", "/ˈfʁɔʏntlɪç/"], "example": {"sentence": "Netter Mensch.", "translation": "好人。"}, "usage_note": "友善。", "image_file": "kind.png" },
        { "id": "adj-44", "term_zh": "所有的", "term_target": "Alle", "pronunciation": ["/ˈalə/"], "example": {"sentence": "Den ganzen Tag.", "translation": "整天。"}, "usage_note": "全部。", "image_file": "every.png" },
        { "id": "adj-45", "term_zh": "喜愛的", "term_target": "Lieblings-", "pronunciation": ["/ˈliːplɪŋs/"], "example": {"sentence": "Lieblingsessen.", "translation": "最愛的食物。"}, "usage_note": "前綴詞 (如 Lieblingsbuch)。", "image_file": "favorite.png" }
      ]
    },
    {
      "id": "nouns",
      "name": "名詞",
      "items": [
        { "id": "n-01", "term_zh": "水", "term_target": "Wasser", "pronunciation": ["/ˈvasɐ/"], "example": {"sentence": "Wasser trinken.", "translation": "喝水。"}, "usage_note": "中性 (Das Wasser)。", "image_file": "water.png" },
        { "id": "n-02", "term_zh": "食物", "term_target": "Essen", "pronunciation": ["/ˈɛsn̩/"], "example": {"sentence": "Leckeres Essen.", "translation": "好吃的食物。"}, "usage_note": "中性 (Das Essen)。", "image_file": "food.png" },
        { "id": "n-03", "term_zh": "錢", "term_target": "Geld", "pronunciation": ["/ɡɛlt/"], "example": {"sentence": "Kein Geld.", "translation": "沒錢。"}, "usage_note": "中性 (Das Geld)。", "image_file": "money.png" },
        { "id": "n-04", "term_zh": "廁所", "term_target": "Toilette", "pronunciation": ["/toˈlɛtə/"], "example": {"sentence": "Zur Toilette gehen.", "translation": "去廁所。"}, "usage_note": "陰性 (Die Toilette)。", "image_file": "bathroom.png" },
        { "id": "n-05", "term_zh": "人", "term_target": "Mensch / Leute", "pronunciation": ["/mɛnʃ/", "/ˈlɔʏtə/"], "example": {"sentence": "Viele Leute.", "translation": "很多人。"}, "usage_note": "Mensch(單/陽), Leute(複)。", "image_file": "people.png" },
        { "id": "n-06", "term_zh": "時間", "term_target": "Zeit", "pronunciation": ["/t͡saɪt/"], "example": {"sentence": "Keine Zeit.", "translation": "沒時間。"}, "usage_note": "陰性 (Die Zeit)。", "image_file": "time.png" },
        { "id": "n-07", "term_zh": "朋友", "term_target": "Freund", "pronunciation": ["/fʁɔʏnt/"], "example": {"sentence": "Mein Freund.", "translation": "我朋友。"}, "usage_note": "陽性 (Der Freund)。", "image_file": "friend.png" },
        { "id": "n-08", "term_zh": "家庭", "term_target": "Familie", "pronunciation": ["faˈmiːli̯ə/"], "example": {"sentence": "Große Familie.", "translation": "大家庭。"}, "usage_note": "陰性 (Die Familie)。", "image_file": "family.png" },
        { "id": "n-09", "term_zh": "手機", "term_target": "Handy", "pronunciation": ["/ˈhɛndi/"], "example": {"sentence": "Mein Handy.", "translation": "我手機。"}, "usage_note": "中性 (Das Handy)。", "image_file": "phone.png" },
        { "id": "n-10", "term_zh": "車", "term_target": "Auto", "pronunciation": ["/ˈaʊto/"], "example": {"sentence": "Auto fahren.", "translation": "開車。"}, "usage_note": "中性 (Das Auto)。", "image_file": "car.png" },
        { "id": "n-11", "term_zh": "巴士", "term_target": "Bus", "pronunciation": ["/bʊs/"], "example": {"sentence": "Bus nehmen.", "translation": "搭公車。"}, "usage_note": "陽性 (Der Bus)。", "image_file": "bus.png" },
        { "id": "n-12", "term_zh": "火車", "term_target": "Zug", "pronunciation": ["/t͡suːk/"], "example": {"sentence": "Zug fahren.", "translation": "搭火車。"}, "usage_note": "陽性 (Der Zug)。", "image_file": "train.png" },
        { "id": "n-13", "term_zh": "捷運/地鐵", "term_target": "U-Bahn", "pronunciation": ["/ˈuːbaːn/"], "example": {"sentence": "U-Bahn Station.", "translation": "地鐵站。"}, "usage_note": "陰性 (Die U-Bahn)。", "image_file": "subway.png" },
        { "id": "n-14", "term_zh": "車站", "term_target": "Bahnhof", "pronunciation": ["/ˈbaːnhoːf/"], "example": {"sentence": "Zum Bahnhof.", "translation": "去車站。"}, "usage_note": "陽性 (Der Bahnhof)。", "image_file": "station.png" },
        { "id": "n-15", "term_zh": "機場", "term_target": "Flughafen", "pronunciation": ["/ˈfluːkhaːfn̩/"], "example": {"sentence": "Zum Flughafen.", "translation": "去機場。"}, "usage_note": "陽性 (Der Flughafen)。", "image_file": "airport.png" },
        { "id": "n-16", "term_zh": "票", "term_target": "Ticket / Fahrkarte", "pronunciation": ["/ˈtɪkɪt/", "/ˈfaːɐ̯ˌkaʁtə/"], "example": {"sentence": "Ein Ticket, bitte.", "translation": "請給我一張票。"}, "usage_note": "Das Ticket / Die Fahrkarte。", "image_file": "ticket.png" },
        { "id": "n-17", "term_zh": "飯店", "term_target": "Hotel", "pronunciation": ["hoˈtɛl/"], "example": {"sentence": "Hotel buchen.", "translation": "訂飯店。"}, "usage_note": "中性 (Das Hotel)。", "image_file": "hotel.png" },
        { "id": "n-18", "term_zh": "護照", "term_target": "Reisepass", "pronunciation": ["/ˈʁaɪzəˌpas/"], "example": {"sentence": "Reisepass zeigen.", "translation": "出示護照。"}, "usage_note": "陽性 (Der Reisepass)。", "image_file": "passport.png" },
        { "id": "n-19", "term_zh": "地圖", "term_target": "Karte", "pronunciation": ["/ˈkaʁtə/"], "example": {"sentence": "Auf die Karte schauen.", "translation": "看地圖。"}, "usage_note": "陰性 (Die Karte)。", "image_file": "map.png" },
        { "id": "n-20", "term_zh": "警察", "term_target": "Polizei", "pronunciation": ["/poliˈt͡saɪ/"], "example": {"sentence": "Polizei rufen.", "translation": "叫警察。"}, "usage_note": "陰性 (Die Polizei)。", "image_file": "police.png" },
        { "id": "n-21", "term_zh": "台灣人", "term_target": "Taiwaner", "pronunciation": ["/taɪˈvaːnɐ/"], "example": {"sentence": "Ich bin Taiwaner.", "translation": "我是台灣人。"}, "usage_note": "國籍 (男)。女用 Taiwanerin。", "image_file": "taiwanese.png" },
        { "id": "n-22", "term_zh": "孩子", "term_target": "Kind", "pronunciation": ["/kɪnt/"], "example": {"sentence": "Kleines Kind.", "translation": "小孩。"}, "usage_note": "中性 (Das Kind)。", "image_file": "child.png" },
        { "id": "n-23", "term_zh": "學生", "term_target": "Student", "pronunciation": ["/ʃtuˈdɛnt/"], "example": {"sentence": "Ich bin Student.", "translation": "我是學生。"}, "usage_note": "陽性 (Der Student)。中小學生用 Schüler。", "image_file": "student.png" },
        { "id": "n-24", "term_zh": "文化", "term_target": "Kultur", "pronunciation": ["kʊlˈtuːɐ̯/"], "example": {"sentence": "Deutsche Kultur.", "translation": "德國文化。"}, "usage_note": "陰性 (Die Kultur)。", "image_file": "culture.png" },
        { "id": "n-25", "term_zh": "問題", "term_target": "Problem", "pronunciation": ["pʁoˈbleːm/"], "example": {"sentence": "Kein Problem.", "translation": "沒問題。"}, "usage_note": "中性 (Das Problem)。", "image_file": "problem.png" },
        { "id": "n-26", "term_zh": "公司", "term_target": "Firma", "pronunciation": ["/ˈfɪʁma/"], "example": {"sentence": "Große Firma.", "translation": "大公司。"}, "usage_note": "陰性 (Die Firma)。", "image_file": "company.png" },
        { "id": "n-27", "term_zh": "男性", "term_target": "Mann", "pronunciation": ["/man/"], "example": {"sentence": "Er ist ein Mann.", "translation": "他是男人。"}, "usage_note": "陽性 (Der Mann)。", "image_file": "man.png" },
        { "id": "n-28", "term_zh": "女性", "term_target": "Frau", "pronunciation": ["/fʁaʊ/"], "example": {"sentence": "Sie ist eine Frau.", "translation": "她是女人。"}, "usage_note": "陰性 (Die Frau)。", "image_file": "woman.png" },
        { "id": "n-29", "term_zh": "學校", "term_target": "Schule", "pronunciation": ["/ˈʃuːlə/"], "example": {"sentence": "Zur Schule gehen.", "translation": "去學校。"}, "usage_note": "陰性 (Die Schule)。", "image_file": "school.png" },
        { "id": "n-30", "term_zh": "老師", "term_target": "Lehrer", "pronunciation": ["/ˈleːʁɐ/"], "example": {"sentence": "Deutschlehrer.", "translation": "德文老師。"}, "usage_note": "陽性 (Der Lehrer)。", "image_file": "teacher.png" },
        { "id": "n-31", "term_zh": "電影", "term_target": "Film", "pronunciation": ["/fɪlm/"], "example": {"sentence": "Film schauen.", "translation": "看電影。"}, "usage_note": "陽性 (Der Film)。", "image_file": "movie.png" },
        { "id": "n-32", "term_zh": "電腦", "term_target": "Computer", "pronunciation": ["kɔmˈpjuːtɐ/"], "example": {"sentence": "Computer benutzen.", "translation": "用電腦。"}, "usage_note": "陽性 (Der Computer)。", "image_file": "computer.png" },
        { "id": "n-33", "term_zh": "市場", "term_target": "Markt", "pronunciation": ["/maʁkt/"], "example": {"sentence": "Zum Markt.", "translation": "去市場。"}, "usage_note": "陽性 (Der Markt)。", "image_file": "market.png" },
        { "id": "n-34", "term_zh": "衣服", "term_target": "Kleidung", "pronunciation": ["/ˈklaɪdʊŋ/"], "example": {"sentence": "Kleidung kaufen.", "translation": "買衣服。"}, "usage_note": "陰性 (Die Kleidung)。", "image_file": "clothes.png" },
        { "id": "n-35", "term_zh": "商店", "term_target": "Geschäft / Laden", "pronunciation": ["/ɡəˈʃɛft/", "/ˈlaːdn̩/"], "example": {"sentence": "Ins Geschäft.", "translation": "進店裡。"}, "usage_note": "Das Geschäft / Der Laden。", "image_file": "shop.png" },
        { "id": "n-36", "term_zh": "街道", "term_target": "Straße", "pronunciation": ["/ˈʃtʁaːsə/"], "example": {"sentence": "Auf der Straße.", "translation": "在街上。"}, "usage_note": "陰性 (Die Straße)。", "image_file": "street.png" },
        { "id": "n-37", "term_zh": "房子", "term_target": "Haus", "pronunciation": ["/haʊs/"], "example": {"sentence": "Mein Haus.", "translation": "我家。"}, "usage_note": "中性 (Das Haus)。", "image_file": "house.png" },
        { "id": "n-38", "term_zh": "母親", "term_target": "Mutter", "pronunciation": ["/ˈmʊtɐ/"], "example": {"sentence": "Meine Mutter.", "translation": "我媽媽。"}, "usage_note": "陰性 (Die Mutter)。", "image_file": "mother.png" },
        { "id": "n-39", "term_zh": "父親", "term_target": "Vater", "pronunciation": ["/ˈfaːtɐ/"], "example": {"sentence": "Mein Vater.", "translation": "我爸爸。"}, "usage_note": "陽性 (Der Vater)。", "image_file": "father.png" },
        { "id": "n-40", "term_zh": "中文", "term_target": "Chinesisch", "pronunciation": ["çiˈneːzɪʃ/"], "example": {"sentence": "Chinesisch sprechen.", "translation": "說中文。"}, "usage_note": "語言。", "image_file": "chinese.png" },
        { "id": "n-41", "term_zh": "包包", "term_target": "Tasche", "pronunciation": ["/ˈtaʃə/"], "example": {"sentence": "Große Tasche.", "translation": "大包包。"}, "usage_note": "陰性 (Die Tasche)。", "image_file": "bag.png" },
        { "id": "n-42", "term_zh": "杯子", "term_target": "Tasse / Becher", "pronunciation": ["/ˈtasə/", "/ˈbɛçɐ/"], "example": {"sentence": "Tasse Tee.", "translation": "一杯茶。"}, "usage_note": "Die Tasse / Der Becher。", "image_file": "cup.png" },
        { "id": "n-43", "term_zh": "醫生", "term_target": "Arzt", "pronunciation": ["/aːɐ̯t͡st/"], "example": {"sentence": "Zum Arzt gehen.", "translation": "看醫生。"}, "usage_note": "陽性 (Der Arzt)。", "image_file": "doctor.png" },
        { "id": "n-44", "term_zh": "醫院", "term_target": "Krankenhaus", "pronunciation": ["/ˈkʁaŋkn̩ˌhaʊs/"], "example": {"sentence": "Ins Krankenhaus.", "translation": "去醫院。"}, "usage_note": "中性 (Das Krankenhaus)。", "image_file": "hospital.png" },
        { "id": "n-45", "term_zh": "座位", "term_target": "Sitzplatz", "pronunciation": ["/ˈzɪt͡sˌplat͡s/"], "example": {"sentence": "Platz nehmen.", "translation": "請坐。"}, "usage_note": "陽性 (Der Sitzplatz)。", "image_file": "seat.png" },
        { "id": "n-46", "term_zh": "門", "term_target": "Tür", "pronunciation": ["/tyːɐ̯/"], "example": {"sentence": "Tür öffnen.", "translation": "開門。"}, "usage_note": "陰性 (Die Tür)。", "image_file": "door.png" },
        { "id": "n-47", "term_zh": "房間", "term_target": "Zimmer", "pronunciation": ["/ˈt͡sɪmɐ/"], "example": {"sentence": "Mein Zimmer.", "translation": "我房間。"}, "usage_note": "中性 (Das Zimmer)。", "image_file": "room.png" },
        { "id": "n-48", "term_zh": "行李", "term_target": "Gepäck", "pronunciation": ["/ɡəˈpɛk/"], "example": {"sentence": "Viel Gepäck.", "translation": "很多行李。"}, "usage_note": "中性 (Das Gepäck)。", "image_file": "luggage.png" },
        { "id": "n-49", "term_zh": "櫃檯", "term_target": "Schalter", "pronunciation": ["/ˈʃaltɐ/"], "example": {"sentence": "Am Schalter.", "translation": "在櫃檯。"}, "usage_note": "陽性 (Der Schalter)。", "image_file": "counter.png" },
        { "id": "n-50", "term_zh": "大廳", "term_target": "Lobby", "pronunciation": ["/ˈlɔbi/"], "example": {"sentence": "In der Lobby.", "translation": "在大廳。"}, "usage_note": "陰性 (Die Lobby)。", "image_file": "lobby.png" },
        { "id": "n-51", "term_zh": "預定", "term_target": "Reservierung", "pronunciation": ["/ʁezɛʁˈviːʁʊŋ/"], "example": {"sentence": "Habe Reservierung.", "translation": "有預約。"}, "usage_note": "陰性 (Die Reservierung)。", "image_file": "reservation.png" },
        { "id": "n-52", "term_zh": "入住", "term_target": "Check-in", "pronunciation": ["/tʃɛk ˈɪn/"], "example": {"sentence": "Zum Check-in.", "translation": "辦理入住。"}, "usage_note": "陽性 (Der Check-in)。", "image_file": "check_in.png" },
        { "id": "n-53", "term_zh": "退房", "term_target": "Check-out", "pronunciation": ["/tʃɛk ˈaʊt/"], "example": {"sentence": "Check-out Zeit.", "translation": "退房時間。"}, "usage_note": "陽性 (Der Check-out)。", "image_file": "check_out.png" },
        { "id": "n-54", "term_zh": "飲料", "term_target": "Getränk", "pronunciation": ["/ɡəˈtʁɛŋk/"], "example": {"sentence": "Kaltes Getränk.", "translation": "冷飲。"}, "usage_note": "中性 (Das Getränk)。", "image_file": "drink.png" },
        { "id": "n-55", "term_zh": "菜單", "term_target": "Speisekarte", "pronunciation": ["/ˈʃpaɪzəˌkaʁtə/"], "example": {"sentence": "Die Karte, bitte.", "translation": "請給菜單。"}, "usage_note": "陰性 (Die Speisekarte)。", "image_file": "menu.png" },
        { "id": "n-56", "term_zh": "午餐", "term_target": "Mittagessen", "pronunciation": ["/ˈmɪtaːkˌʔɛsn̩/"], "example": {"sentence": "Zum Mittagessen.", "translation": "吃午餐。"}, "usage_note": "中性 (Das Mittagessen)。", "image_file": "lunch.png" },
        { "id": "n-57", "term_zh": "晚餐", "term_target": "Abendessen", "pronunciation": ["/ˈaːbn̩tˌʔɛsn̩/"], "example": {"sentence": "Zum Abendessen.", "translation": "吃晚餐。"}, "usage_note": "中性 (Das Abendessen)。", "image_file": "dinner.png" },
        { "id": "n-58", "term_zh": "帳單", "term_target": "Rechnung", "pronunciation": ["/ˈʁɛçnʊŋ/"], "example": {"sentence": "Die Rechnung, bitte.", "translation": "麻煩結帳。"}, "usage_note": "陰性 (Die Rechnung)。", "image_file": "bill.png" },
        { "id": "n-59", "term_zh": "價錢", "term_target": "Preis", "pronunciation": ["/pʁaɪs/"], "example": {"sentence": "Guter Preis.", "translation": "好價格。"}, "usage_note": "陽性 (Der Preis)。", "image_file": "price.png" },
        { "id": "n-60", "term_zh": "收據", "term_target": "Quittung", "pronunciation": ["/ˈkvɪtʊŋ/"], "example": {"sentence": "Die Quittung, bitte.", "translation": "請給收據。"}, "usage_note": "陰性 (Die Quittung)。", "image_file": "receipt.png" },
        { "id": "n-61", "term_zh": "尺寸", "term_target": "Größe", "pronunciation": ["/ˈɡʁøːsə/"], "example": {"sentence": "Große Größe.", "translation": "大尺寸。"}, "usage_note": "陰性 (Die Größe)。", "image_file": "size.png" },
        { "id": "n-62", "term_zh": "入口", "term_target": "Eingang", "pronunciation": ["/ˈaɪnˌɡaŋ/"], "example": {"sentence": "Wo ist der Eingang?", "translation": "入口在哪？"}, "usage_note": "陽性 (Der Eingang)。", "image_file": "entrance.png" },
        { "id": "n-63", "term_zh": "出口", "term_target": "Ausgang", "pronunciation": ["/ˈaʊsˌɡaŋ/"], "example": {"sentence": "Hier ist der Ausgang.", "translation": "出口在這。"}, "usage_note": "陽性 (Der Ausgang)。", "image_file": "exit.png" },
        { "id": "n-64", "term_zh": "台灣", "term_target": "Taiwan", "pronunciation": ["/taɪˈvaːn/"], "example": {"sentence": "Ich mag Taiwan.", "translation": "我愛台灣。"}, "usage_note": "地名。", "image_file": "taiwan.png" },
        { "id": "n-65", "term_zh": "一切事物", "term_target": "Alles", "pronunciation": ["/ˈaləs/"], "example": {"sentence": "Alles ist gut.", "translation": "一切都好。"}, "usage_note": "所有。", "image_file": "everything.png" },
        { "id": "n-66", "term_zh": "錢包", "term_target": "Geldbeutel", "pronunciation": ["/ˈɡɛltˌbɔʏtl̩/"], "example": {"sentence": "Geldbeutel verloren.", "translation": "掉了錢包。"}, "usage_note": "陽性 (Der Geldbeutel)。", "image_file": "wallet.png" },
        { "id": "n-67", "term_zh": "身分證", "term_target": "Ausweis", "pronunciation": ["/ˈaʊsˌvaɪs/"], "example": {"sentence": "Ausweis zeigen.", "translation": "出示證件。"}, "usage_note": "陽性 (Der Ausweis)。", "image_file": "id.png" },
        { "id": "n-68", "term_zh": "餐廳", "term_target": "Restaurant", "pronunciation": ["/ʁɛstoˈʁã/"], "example": {"sentence": "Gutes Restaurant.", "translation": "好餐廳。"}, "usage_note": "中性 (Das Restaurant)。", "image_file": "restaurant.png" },
        { "id": "n-69", "term_zh": "場所", "term_target": "Ort / Platz", "pronunciation": ["/ɔʁt/", "/plat͡s/"], "example": {"sentence": "Schöner Ort.", "translation": "好地方。"}, "usage_note": "陽性 (Der Ort)。", "image_file": "place.png" },
        { "id": "n-70", "term_zh": "店員", "term_target": "Verkäufer", "pronunciation": ["/fɛɐ̯ˈkɔʏfɐ/"], "example": {"sentence": "Verkäufer fragen.", "translation": "問店員。"}, "usage_note": "陽性 (Der Verkäufer)。", "image_file": "clerk.png" },
        { "id": "n-71", "term_zh": "超市", "term_target": "Supermarkt", "pronunciation": ["/ˈzuːpɐˌmaʁkt/"], "example": {"sentence": "Zum Supermarkt.", "translation": "去超市。"}, "usage_note": "陽性 (Der Supermarkt)。", "image_file": "supermarket.png" },
        { "id": "n-72", "term_zh": "月台", "term_target": "Gleis", "pronunciation": ["/ɡlaɪs/"], "example": {"sentence": "Gleis 1.", "translation": "第一月台。"}, "usage_note": "中性 (Das Gleis)。", "image_file": "platform.png" }
      ]
    },
    {
      "id": "adverbs",
      "name": "副詞",
      "items": [
        { "id": "adv-01", "term_zh": "現在", "term_target": "Jetzt", "pronunciation": ["/jɛt͡st/"], "example": {"sentence": "Mach es jetzt.", "translation": "現在做。"}, "usage_note": "目前。", "image_file": "now.png" },
        { "id": "adv-02", "term_zh": "非常", "term_target": "Sehr", "pronunciation": ["/zeːɐ̯/"], "example": {"sentence": "Sehr gut.", "translation": "非常好。"}, "usage_note": "強調。", "image_file": "very.png" },
        { "id": "adv-03", "term_zh": "真的", "term_target": "Wirklich", "pronunciation": ["/ˈvɪʁklɪç/"], "example": {"sentence": "Wirklich?", "translation": "真的嗎？"}, "usage_note": "確認或強調。", "image_file": "really.png" },
        { "id": "adv-04", "term_zh": "經常", "term_target": "Oft", "pronunciation": ["/ɔft/"], "example": {"sentence": "Ich komme oft.", "translation": "我常來。"}, "usage_note": "頻率。", "image_file": "often.png" },
        { "id": "adv-05", "term_zh": "通常", "term_target": "Normalerweise", "pronunciation": ["/nɔʁˈmaːləˌvaɪzə/"], "example": {"sentence": "Normalerweise um 6.", "translation": "通常在六點。"}, "usage_note": "習慣。", "image_file": "usually.png" },
        { "id": "adv-06", "term_zh": "只有", "term_target": "Nur", "pronunciation": ["/nuːɐ̯/"], "example": {"sentence": "Nur einer.", "translation": "只有一個。"}, "usage_note": "唯一。", "image_file": "only.png" },
        { "id": "adv-07", "term_zh": "再次", "term_target": "Noch einmal", "pronunciation": ["/nɔx ˈaɪnmaːl/"], "example": {"sentence": "Versuch es noch einmal.", "translation": "再試一次。"}, "usage_note": "重複。", "image_file": "again.png" },
        { "id": "adv-08", "term_zh": "一起", "term_target": "Zusammen", "pronunciation": ["/t͡suˈzamən/"], "example": {"sentence": "Zusammen gehen.", "translation": "一起去。"}, "usage_note": "共同。", "image_file": "together.png" },
        { "id": "adv-09", "term_zh": "或許", "term_target": "Vielleicht", "pronunciation": ["/fiˈlaɪçt/"], "example": {"sentence": "Vielleicht später.", "translation": "也許等下。"}, "usage_note": "不確定。", "image_file": "maybe.png" },
        { "id": "adv-10", "term_zh": "很快", "term_target": "Bald", "pronunciation": ["/balt/"], "example": {"sentence": "Bis bald.", "translation": "待會見(很快見)。"}, "usage_note": "不久後。", "image_file": "soon.png" },
        { "id": "adv-11", "term_zh": "已經", "term_target": "Schon / Bereits", "pronunciation": ["/ʃoːn/", "/bəˈʁaɪt͡s/"], "example": {"sentence": "Schon fertig.", "translation": "已經做好了。"}, "usage_note": "完成。", "image_file": "already.png" },
        { "id": "adv-12", "term_zh": "大約", "term_target": "Ungefähr / Etwa", "pronunciation": ["/ˈʊnɡəˌfɛːɐ̯/", "/ˈɛtva/"], "example": {"sentence": "Ungefähr 10 Minuten.", "translation": "大約10分鐘。"}, "usage_note": "概數。", "image_file": "about.png" },
        { "id": "adv-13", "term_zh": "一點點", "term_target": "Ein bisschen", "pronunciation": ["/aɪn ˈbɪsçən/"], "example": {"sentence": "Ein bisschen scharf.", "translation": "一點點辣。"}, "usage_note": "少量。", "image_file": "a_little.png" },
        { "id": "adv-14", "term_zh": "之後", "term_target": "Später", "pronunciation": ["/ˈʃpɛːtɐ/"], "example": {"sentence": "Bis später.", "translation": "待會見。"}, "usage_note": "稍後。", "image_file": "later.png" },
        { "id": "adv-15", "term_zh": "仍然", "term_target": "Immer noch", "pronunciation": ["/ˈɪmɐ nɔx/"], "example": {"sentence": "Immer noch hier.", "translation": "還在這裡。"}, "usage_note": "持續。", "image_file": "still.png" },
        { "id": "adv-16", "term_zh": "一般來說", "term_target": "Allgemein", "pronunciation": ["/alɡəˈmaɪn/"], "example": {"sentence": "Allgemein gesagt.", "translation": "一般來說。"}, "usage_note": "通常。", "image_file": "normally.png" }
      ]
    },
    {
      "id": "questions",
      "name": "疑問詞",
      "items": [
        { "id": "q-01", "term_zh": "什麼", "term_target": "Was", "pronunciation": ["/vas/"], "example": {"sentence": "Was ist das?", "translation": "這是什麼？"}, "usage_note": "問事物。", "image_file": "what.png" },
        { "id": "q-02", "term_zh": "哪裡", "term_target": "Wo", "pronunciation": ["/voː/"], "example": {"sentence": "Wo bist du?", "translation": "你在哪？"}, "usage_note": "問地點。", "image_file": "where.png" },
        { "id": "q-03", "term_zh": "何時", "term_target": "Wann", "pronunciation": ["/van/"], "example": {"sentence": "Wann gehen wir?", "translation": "何時去？"}, "usage_note": "問時間。", "image_file": "when.png" },
        { "id": "q-04", "term_zh": "誰", "term_target": "Wer", "pronunciation": ["/veːɐ̯/"], "example": {"sentence": "Wer ist das?", "translation": "那是誰？"}, "usage_note": "問人。", "image_file": "who.png" },
        { "id": "q-05", "term_zh": "為什麼", "term_target": "Warum", "pronunciation": ["/vaˈʁʊm/"], "example": {"sentence": "Warum?", "translation": "為什麼？"}, "usage_note": "問原因。", "image_file": "why.png" },
        { "id": "q-06", "term_zh": "如何", "term_target": "Wie", "pronunciation": ["/viː/"], "example": {"sentence": "Wie geht es dir?", "translation": "你好嗎？"}, "usage_note": "問狀況。", "image_file": "how.png" },
        { "id": "q-07", "term_zh": "多少(錢)", "term_target": "Wie viel", "pronunciation": ["/viː fiːl/"], "example": {"sentence": "Wie viel kostet das?", "translation": "多少錢？"}, "usage_note": "不可數/價格。", "image_file": "how_much.png" },
        { "id": "q-08", "term_zh": "多久/多少(量)", "term_target": "Wie lange", "pronunciation": ["/viː ˈlaŋə/"], "example": {"sentence": "Wie lange?", "translation": "要多久？"}, "usage_note": "時間長度。", "image_file": "how_long.png" },
        { "id": "q-09", "term_zh": "哪一個", "term_target": "Welche", "pronunciation": ["/ˈvɛlçə/"], "example": {"sentence": "Welches?", "translation": "哪一個？"}, "usage_note": "選擇。", "image_file": "which.png" }
      ]
    },
    {
      "id": "time_place",
      "name": "時間與場所",
      "items": [
        { "id": "tp-01", "term_zh": "今天", "term_target": "Heute", "pronunciation": ["/ˈhɔʏtə/"], "example": {"sentence": "Heute ist es warm.", "translation": "今天很熱。"}, "usage_note": "本日。", "image_file": "today.png" },
        { "id": "tp-02", "term_zh": "明天", "term_target": "Morgen", "pronunciation": ["/ˈmɔʁɡn̩/"], "example": {"sentence": "Bis morgen.", "translation": "明天見。"}, "usage_note": "隔天。", "image_file": "tomorrow.png" },
        { "id": "tp-03", "term_zh": "昨天", "term_target": "Gestern", "pronunciation": ["/ˈɡɛstɐn/"], "example": {"sentence": "Gestern war ich da.", "translation": "昨天我去了。"}, "usage_note": "前一天。", "image_file": "yesterday.png" },
        { "id": "tp-04", "term_zh": "這裡", "term_target": "Hier", "pronunciation": ["/hiːɐ̯/"], "example": {"sentence": "Komm her.", "translation": "來這。"}, "usage_note": "近處。", "image_file": "here.png" },
        { "id": "tp-05", "term_zh": "那裡", "term_target": "Dort", "pronunciation": ["/dɔʁt/"], "example": {"sentence": "Geh dort hin.", "translation": "去那。"}, "usage_note": "遠處。", "image_file": "there.png" },
        { "id": "tp-06", "term_zh": "早上", "term_target": "Morgen", "pronunciation": ["/ˈmɔʁɡn̩/"], "example": {"sentence": "Am Morgen.", "translation": "在早上。"}, "usage_note": "上午 (大寫)。", "image_file": "morning.png" },
        { "id": "tp-07", "term_zh": "晚上/夜晚", "term_target": "Nacht / Abend", "pronunciation": ["/naxt/", "/ˈaːbn̩t/"], "example": {"sentence": "Gute Nacht.", "translation": "晚安。"}, "usage_note": "Abend(傍晚/晚上), Nacht(深夜/睡前)。", "image_file": "night.png" },
        { "id": "tp-08", "term_zh": "前面", "term_target": "Vorne", "pronunciation": ["/ˈfɔʁnə/"], "example": {"sentence": "Da vorne.", "translation": "在前面。"}, "usage_note": "前方。", "image_file": "front.png" },
        { "id": "tp-09", "term_zh": "後面", "term_target": "Hinten", "pronunciation": ["/ˈhɪntn̩/"], "example": {"sentence": "Da hinten.", "translation": "在後面。"}, "usage_note": "後方。", "image_file": "behind.png" },
        { "id": "tp-10", "term_zh": "左邊", "term_target": "Links", "pronunciation": ["/lɪŋks/"], "example": {"sentence": "Nach links.", "translation": "左轉。"}, "usage_note": "左。", "image_file": "left.png" },
        { "id": "tp-11", "term_zh": "右邊", "term_target": "Rechts", "pronunciation": ["/ʁɛçt͡s/"], "example": {"sentence": "Nach rechts.", "translation": "右轉。"}, "usage_note": "右。", "image_file": "right.png" },
        { "id": "tp-12", "term_zh": "天(日)", "term_target": "Tag", "pronunciation": ["/taːk/"], "example": {"sentence": "Ein Tag.", "translation": "一天。"}, "usage_note": "日子。", "image_file": "day.png" },
        { "id": "tp-13", "term_zh": "年", "term_target": "Jahr", "pronunciation": ["/jaːɐ̯/"], "example": {"sentence": "Dieses Jahr.", "translation": "今年。"}, "usage_note": "年度。", "image_file": "year.png" },
        { "id": "tp-14", "term_zh": "月", "term_target": "Monat", "pronunciation": ["/ˈmoːnat/"], "example": {"sentence": "Diesen Monat.", "translation": "這個月。"}, "usage_note": "月份。", "image_file": "month.png" },
        { "id": "tp-15", "term_zh": "週", "term_target": "Woche", "pronunciation": ["/ˈvɔxə/"], "example": {"sentence": "Nächste Woche.", "translation": "下週。"}, "usage_note": "星期。", "image_file": "week.png" },
        { "id": "tp-16", "term_zh": "下午", "term_target": "Nachmittag", "pronunciation": ["/ˈnaːxˌmɪtaːk/"], "example": {"sentence": "Am Nachmittag.", "translation": "下午。"}, "usage_note": "PM。", "image_file": "afternoon.png" },
        { "id": "tp-17", "term_zh": "中午", "term_target": "Mittag", "pronunciation": ["/ˈmɪtaːk/"], "example": {"sentence": "Am Mittag.", "translation": "在中午。"}, "usage_note": "12點。", "image_file": "noon.png" },
        { "id": "tp-18", "term_zh": "旁邊", "term_target": "Neben", "pronunciation": ["/ˈneːbn̩/"], "example": {"sentence": "Neben mir.", "translation": "在我旁邊。"}, "usage_note": "側邊。", "image_file": "beside.png" },
        { "id": "tp-19", "term_zh": "對面", "term_target": "Gegenüber", "pronunciation": ["/ɡeːɡn̩ˈʔyːbɐ/"], "example": {"sentence": "Gegenüber der Bank.", "translation": "銀行對面。"}, "usage_note": "對側。", "image_file": "across_from.png" },
        { "id": "tp-20", "term_zh": "春天", "term_target": "Frühling", "pronunciation": ["/ˈfʁyːlɪŋ/"], "example": {"sentence": "Der Frühling.", "translation": "春天。"}, "usage_note": "季節。", "image_file": "spring.png" },
        { "id": "tp-21", "term_zh": "夏天", "term_target": "Sommer", "pronunciation": ["/ˈzɔmɐ/"], "example": {"sentence": "Heißer Sommer.", "translation": "炎熱的夏天。"}, "usage_note": "季節。", "image_file": "summer.png" },
        { "id": "tp-22", "term_zh": "秋天", "term_target": "Herbst", "pronunciation": ["/hɛʁpst/"], "example": {"sentence": "Kühler Herbst.", "translation": "涼爽的秋天。"}, "usage_note": "季節。", "image_file": "autumn.png" },
        { "id": "tp-23", "term_zh": "冬天", "term_target": "Winter", "pronunciation": ["/ˈvɪntɐ/"], "example": {"sentence": "Kalter Winter.", "translation": "寒冷的冬天。"}, "usage_note": "季節。", "image_file": "winter.png" }
      ]
    },
    {
      "id": "numbers",
      "name": "數字",
      "items": [
        { "id": "num-0", "term_zh": "0", "term_target": "Null", "pronunciation": ["/nʊl/"], "example": {"sentence": "Null Grad.", "translation": "零度。"}, "usage_note": "零。", "image_file": "zero.png" },
        { "id": "num-1", "term_zh": "1", "term_target": "Eins", "pronunciation": ["/aɪns/"], "example": {"sentence": "Eine Minute.", "translation": "一分鐘。"}, "usage_note": "一。", "image_file": "one.png" },
        { "id": "num-2", "term_zh": "2", "term_target": "Zwei", "pronunciation": ["/t͡svaɪ/"], "example": {"sentence": "Zwei Tage.", "translation": "兩天。"}, "usage_note": "二。", "image_file": "two.png" },
        { "id": "num-3", "term_zh": "3", "term_target": "Drei", "pronunciation": ["/dʁaɪ/"], "example": {"sentence": "Drei Personen.", "translation": "三人。"}, "usage_note": "三。", "image_file": "three.png" },
        { "id": "num-4", "term_zh": "4", "term_target": "Vier", "pronunciation": ["/fiːɐ̯/"], "example": {"sentence": "Vier Jahreszeiten.", "translation": "四季。"}, "usage_note": "四。", "image_file": "four.png" },
        { "id": "num-5", "term_zh": "5", "term_target": "Fünf", "pronunciation": ["/fʏnf/"], "example": {"sentence": "Fünf Euro.", "translation": "五歐元。"}, "usage_note": "五。", "image_file": "five.png" },
        { "id": "num-6", "term_zh": "6", "term_target": "Sechs", "pronunciation": ["/zɛks/"], "example": {"sentence": "Sechs Stunden.", "translation": "六小時。"}, "usage_note": "六。", "image_file": "six.png" },
        { "id": "num-7", "term_zh": "7", "term_target": "Sieben", "pronunciation": ["/ˈziːbn̩/"], "example": {"sentence": "Sieben Tage.", "translation": "七天。"}, "usage_note": "七。", "image_file": "seven.png" },
        { "id": "num-8", "term_zh": "8", "term_target": "Acht", "pronunciation": ["/axt/"], "example": {"sentence": "Acht Jahre.", "translation": "八歲。"}, "usage_note": "八。", "image_file": "eight.png" },
        { "id": "num-9", "term_zh": "9", "term_target": "Neun", "pronunciation": ["/nɔʏn/"], "example": {"sentence": "Neun Uhr.", "translation": "九點。"}, "usage_note": "九。", "image_file": "nine.png" },
        { "id": "num-10", "term_zh": "10", "term_target": "Zehn", "pronunciation": ["/t͡seːn/"], "example": {"sentence": "Zehn Euro.", "translation": "十歐元。"}, "usage_note": "十。", "image_file": "ten.png" },
        { "id": "num-11", "term_zh": "11", "term_target": "Elf", "pronunciation": ["/ɛlf/"], "example": {"sentence": "Elf Jahre.", "translation": "11歲。"}, "usage_note": "十一。", "image_file": "eleven.png" },
        { "id": "num-12", "term_zh": "12", "term_target": "Zwölf", "pronunciation": ["/t͡svœlf/"], "example": {"sentence": "Zwölf Monate.", "translation": "12個月。"}, "usage_note": "十二。", "image_file": "twelve.png" },
        { "id": "num-15", "term_zh": "15", "term_target": "Fünfzehn", "pronunciation": ["/ˈfʏnft͡seːn/"], "example": {"sentence": "Fünfzehn Minuten.", "translation": "15分鐘。"}, "usage_note": "十五。", "image_file": "fifteen.png" },
        { "id": "num-20", "term_zh": "20", "term_target": "Zwanzig", "pronunciation": ["/ˈt͡svant͡sɪç/"], "example": {"sentence": "Zwanzig Euro.", "translation": "20歐元。"}, "usage_note": "二十。", "image_file": "twenty.png" },
        { "id": "num-50", "term_zh": "50", "term_target": "Fünfzig", "pronunciation": ["/ˈfʏnft͡sɪç/"], "example": {"sentence": "Fünfzig Prozent.", "translation": "50%。"}, "usage_note": "五十。", "image_file": "fifty.png" },
        { "id": "num-100", "term_zh": "100", "term_target": "Hundert", "pronunciation": ["/ˈhʊndɐt/"], "example": {"sentence": "Hundert Punkte.", "translation": "一百分。"}, "usage_note": "百。", "image_file": "hundred.png" },
        { "id": "num-1000", "term_zh": "1000", "term_target": "Tausend", "pronunciation": ["/ˈtaʊzn̩t/"], "example": {"sentence": "Tausend Dank.", "translation": "萬分感謝。"}, "usage_note": "千。", "image_file": "thousand.png" },
        { "id": "num-10000", "term_zh": "10000", "term_target": "Zehntausend", "pronunciation": ["/ˈt͡seːnˌtaʊzn̩t/"], "example": {"sentence": "Zehntausend Euro.", "translation": "一萬歐元。"}, "usage_note": "一萬。", "image_file": "ten_thousand.png" }
      ]
    },
    {
      "id": "grammar",
      "name": "基本句型",
      "items": [
        { "id": "g-01", "term_zh": "我是...", "term_target": "Ich bin...", "pronunciation": ["/ɪç bɪn/"], "example": {"sentence": "Ich bin Student.", "translation": "我是學生。"}, "usage_note": "本質/身分。", "image_file": "i_am.png" },
        { "id": "g-02", "term_zh": "我正在...", "term_target": "Ich (verbo)... gerade", "pronunciation": ["/ɪç ... ɡəˈʁaːdə/"], "example": {"sentence": "Ich esse gerade.", "translation": "我正在吃。"}, "usage_note": "用 gerade (正) 表示進行。", "image_file": "ing.png" },
        { "id": "g-03", "term_zh": "我能夠...", "term_target": "Ich kann...", "pronunciation": ["/ɪç kan/"], "example": {"sentence": "Ich kann schwimmen.", "translation": "我會游泳。"}, "usage_note": "能力。", "image_file": "can.png" },
        { "id": "g-04", "term_zh": "我喜歡做...", "term_target": "Ich mag...", "pronunciation": ["/ɪç maːk/"], "example": {"sentence": "Ich mag lesen.", "translation": "我喜歡閱讀。"}, "usage_note": "興趣。", "image_file": "like_ing.png" },
        { "id": "g-05", "term_zh": "我想做...", "term_target": "Ich will...", "pronunciation": ["/ɪç vɪl/"], "example": {"sentence": "Ich will gehen.", "translation": "我想去。"}, "usage_note": "慾望。", "image_file": "want_to.png" },
        { "id": "g-06", "term_zh": "你是...嗎?", "term_target": "Bist du...?", "pronunciation": ["/bɪst duː/"], "example": {"sentence": "Bist du Student?", "translation": "你是學生嗎？"}, "usage_note": "問狀態。", "image_file": "are_you.png" },
        { "id": "g-07", "term_zh": "不要...", "term_target": "Nicht...", "pronunciation": ["/nɪçt/"], "example": {"sentence": "Nicht anfassen.", "translation": "不要碰。"}, "usage_note": "禁止/否定命令。", "image_file": "dont.png" },
        { "id": "g-08", "term_zh": "你有做...嗎?", "term_target": "Machst du...?", "pronunciation": ["/maxst duː/"], "example": {"sentence": "Machst du Sport?", "translation": "你有運動嗎？"}, "usage_note": "一般疑問句。", "image_file": "do_you.png" },
        { "id": "g-09", "term_zh": "你曾經...嗎?", "term_target": "Hast du schon mal...?", "pronunciation": ["/hast duː ʃoːn maːl/"], "example": {"sentence": "Warst du schon mal in Deutschland?", "translation": "你有去過德國嗎？"}, "usage_note": "問經驗(完成式)。", "image_file": "have_you_ever.png" },
        { "id": "g-10", "term_zh": "你何時做...?", "term_target": "Wann...?", "pronunciation": ["/van/"], "example": {"sentence": "Wann schläfst du?", "translation": "你何時睡？"}, "usage_note": "問時間點。", "image_file": "when_do_you.png" },
        { "id": "g-11", "term_zh": "你在哪裡做...?", "term_target": "Wo...?", "pronunciation": ["/voː/"], "example": {"sentence": "Wo wohnst du?", "translation": "你住哪裡？"}, "usage_note": "問地點。", "image_file": "where_do_you.png" },
        { "id": "g-12", "term_zh": "你如何做...?", "term_target": "Wie...?", "pronunciation": ["/viː/"], "example": {"sentence": "Wie gehst du?", "translation": "你怎麼去？"}, "usage_note": "問方法。", "image_file": "how_do_you.png" },
        { "id": "g-13", "term_zh": "我不是...", "term_target": "Ich bin kein...", "pronunciation": ["/ɪç bɪn kaɪn/"], "example": {"sentence": "Ich bin kein Arzt.", "translation": "我不是醫生。"}, "usage_note": "否定名詞用 kein。", "image_file": "i_am_not.png" },
        { "id": "g-14", "term_zh": "我不做...", "term_target": "Ich (verbo) nicht", "pronunciation": ["/ɪç ... nɪçt/"], "example": {"sentence": "Ich rauche nicht.", "translation": "我不抽菸。"}, "usage_note": "否定動作。", "image_file": "i_dont.png" },
        { "id": "g-15", "term_zh": "我不能...", "term_target": "Ich kann nicht...", "pronunciation": ["/ɪç kan nɪçt/"], "example": {"sentence": "Ich kann nicht gehen.", "translation": "我不能去。"}, "usage_note": "否定能力。", "image_file": "i_cant.png" },
        { "id": "g-16", "term_zh": "我未曾...", "term_target": "Ich habe noch nie...", "pronunciation": ["/ɪç haːbə nɔx niː/"], "example": {"sentence": "Ich habe das noch nie gegessen.", "translation": "我沒吃過這個。"}, "usage_note": "無此經驗。", "image_file": "i_have_never.png" },
        { "id": "g-17", "term_zh": "我不必...", "term_target": "Ich muss nicht...", "pronunciation": ["/ɪç mʊs nɪçt/"], "example": {"sentence": "Ich muss nicht gehen.", "translation": "我不必去。"}, "usage_note": "無義務。", "image_file": "i_dont_have_to.png" },
        { "id": "g-18", "term_zh": "如果...的話", "term_target": "Wenn...", "pronunciation": ["/vɛn/"], "example": {"sentence": "Wenn du willst.", "translation": "如果你想。",}, "usage_note": "假設條件。", "image_file": "if.png" },
        { "id": "g-19", "term_zh": "當...時", "term_target": "Als...", "pronunciation": ["/als/"], "example": {"sentence": "Als ich ein Kind war.", "translation": "小時候(當我是孩子時)。"}, "usage_note": "時間條件(過去)。", "image_file": "when_condition.png" },
        { "id": "g-20", "term_zh": "請你...好嗎?", "term_target": "Können Sie...?", "pronunciation": ["/kœnən ziː/"], "example": {"sentence": "Können Sie mir helfen?", "translation": "可以幫我嗎？"}, "usage_note": "請求。", "image_file": "can_you.png" },
        { "id": "g-21", "term_zh": "我們來做...吧", "term_target": "Lass uns...", "pronunciation": ["/las ʊns/"], "example": {"sentence": "Lass uns essen.", "translation": "我們去吃吧。"}, "usage_note": "提議。", "image_file": "lets.png" },
        { "id": "g-22", "term_zh": "我認為...", "term_target": "Ich denke...", "pronunciation": ["/ɪç dɛŋkə/"], "example": {"sentence": "Ich denke, es ist gut.", "translation": "我認為這很好。"}, "usage_note": "表達想法。", "image_file": "i_think.png" },
        { "id": "g-23", "term_zh": "我必須...", "term_target": "Ich muss...", "pronunciation": ["/ɪç mʊs/"], "example": {"sentence": "Ich muss arbeiten.", "translation": "我必須工作。"}, "usage_note": "義務。", "image_file": "i_have_to.png" },
        { "id": "g-24", "term_zh": "做某事是...的", "term_target": "Es ist ... zu (infinitiv)", "pronunciation": ["/ɛs ɪst/"], "example": {"sentence": "Es ist gut zu essen.", "translation": "吃東西是很好的。"}, "usage_note": "描述動作。", "image_file": "it_is_to.png" },
        { "id": "g-25", "term_zh": "我可以...嗎?", "term_target": "Darf ich...?", "pronunciation": ["/daʁf ɪç/"], "example": {"sentence": "Darf ich reinkommen?", "translation": "我可以進來嗎？"}, "usage_note": "請求許可。", "image_file": "can_i.png" },
        { "id": "g-26", "term_zh": "我比較喜歡...", "term_target": "Ich bevorzuge...", "pronunciation": ["/ɪç bəˈfoːɐ̯t͡suːɡə/"], "example": {"sentence": "Ich bevorzuge Tee.", "translation": "我比較喜歡茶。"}, "usage_note": "偏好。", "image_file": "prefer.png" },
        { "id": "g-27", "term_zh": "A比B更...", "term_target": "A ist ...er als B", "pronunciation": ["/a ɪst ...ɐ als be/"], "example": {"sentence": "Das ist teurer als das.", "translation": "這比那個貴。"}, "usage_note": "比較級。", "image_file": "more_than.png" },
        { "id": "g-28", "term_zh": "有(存在)...", "term_target": "Es gibt...", "pronunciation": ["/ɛs ɡiːpt/"], "example": {"sentence": "Es gibt einen Hund.", "translation": "有一隻狗。"}, "usage_note": "存在。", "image_file": "there_is.png" },
        { "id": "g-29", "term_zh": "我曾經是/當時是...", "term_target": "Ich war...", "pronunciation": ["/ɪç vaːɐ̯/"], "example": {"sentence": "Ich war Student.", "translation": "我曾經是學生。"}, "usage_note": "過去狀態。", "image_file": "i_was.png" },
        { "id": "g-30", "term_zh": "我將要...", "term_target": "Ich werde...", "pronunciation": ["/ɪç veːɐ̯də/"], "example": {"sentence": "Ich werde gehen.", "translation": "我將要去。"}, "usage_note": "未來意。", "image_file": "i_will.png" },
        { "id": "g-31", "term_zh": "我曾經做過...", "term_target": "Ich habe ... gemacht", "pronunciation": ["/ɪç haːbə ... ɡəˈmaxt/"], "example": {"sentence": "Ich habe meine Hausaufgaben gemacht.", "translation": "我做了功課。"}, "usage_note": "過去動作。", "image_file": "i_did.png" }
      ]
    }
  ]
};