import { AppData } from '../types';

export const englishData: AppData = {
  "meta": {
    "source_language": "zh-TW",
    "target_language": "en-US",
    "version": "2.3",
    "description": "台灣人快速語言學習 - 英文完整版 (包含所有原始列表單字與完整句型 - 僅保留 KK 音標)"
  },
  "categories": [
    {
      "id": "greetings",
      "name": "常用句",
      "items": [
        {
          "id": "greet-001",
          "term_zh": "你好",
          "term_target": "Hello",
          "pronunciation": ["/həˈloʊ/"],
          "example": { "sentence": "Hello, how are you?", "translation": "你好，你好嗎？" },
          "usage_note": "最通用的打招呼。",
          "image_file": "hello.png"
        },
        {
          "id": "greet-002",
          "term_zh": "再見",
          "term_target": "Good bye",
          "pronunciation": ["/gʊd baɪ/"],
          "example": { "sentence": "Good bye, see you.", "translation": "再見，待會見。" },
          "usage_note": "也可以說 Bye-bye。",
          "image_file": "goodbye.png"
        },
        {
          "id": "greet-003",
          "term_zh": "謝謝你",
          "term_target": "Thank you",
          "pronunciation": ["/ˈθæŋk ju/"],
          "example": { "sentence": "Thank you very much.", "translation": "非常謝謝你。" },
          "usage_note": "咬舌音 th 很重要。",
          "image_file": "thank_you.png"
        },
        {
          "id": "greet-004",
          "term_zh": "對不起",
          "term_target": "I'm sorry",
          "pronunciation": ["/aɪm ˈsɑri/"],
          "example": { "sentence": "I'm sorry for the mistake.", "translation": "抱歉我弄錯了。" },
          "usage_note": "做錯事時使用。",
          "image_file": "sorry.png"
        },
        {
          "id": "greet-005",
          "term_zh": "早安",
          "term_target": "Good morning",
          "pronunciation": ["/gʊd ˈmɔrnɪŋ/"],
          "example": { "sentence": "Good morning, mom.", "translation": "早安，媽。" },
          "usage_note": "中午12點前使用。",
          "image_file": "good_morning.png"
        },
        {
          "id": "greet-006",
          "term_zh": "請問... / 借過",
          "term_target": "Excuse me",
          "pronunciation": ["/ɪkˈskjus mi/"],
          "example": { "sentence": "Excuse me, coming through.", "translation": "借過，我要過去。" },
          "usage_note": "問路、借過、引起注意時用。",
          "image_file": "excuse_me.png"
        },
        {
          "id": "greet-007",
          "term_zh": "我不懂",
          "term_target": "I don't understand",
          "pronunciation": ["/aɪ doʊnt ˌʌndɚˈstænd/"],
          "example": { "sentence": "I don't understand English.", "translation": "我不懂英文。" },
          "usage_note": "聽不懂時直接說。",
          "image_file": "dont_understand.png"
        },
        {
          "id": "greet-008",
          "term_zh": "這是什麼？",
          "term_target": "What is this?",
          "pronunciation": ["/hwɑt ɪz ðɪs/"],
          "example": { "sentence": "What is this? Food?", "translation": "這是什麼？食物嗎？" },
          "usage_note": "好奇時必用。",
          "image_file": "what_is_this.png"
        },
        {
          "id": "greet-009",
          "term_zh": "我想要這個",
          "term_target": "I want this",
          "pronunciation": ["/aɪ wɑnt ðɪs/"],
          "example": { "sentence": "I want this one.", "translation": "我要這個。" },
          "usage_note": "直接表達購買意願。",
          "image_file": "i_want_this.png"
        },
        {
          "id": "greet-010",
          "term_zh": "請給我...",
          "term_target": "Please give me...",
          "pronunciation": ["/pliz gɪv mi/"],
          "example": { "sentence": "Please give me water.", "translation": "請給我水。" },
          "usage_note": "索取物品。",
          "image_file": "please_give_me.png"
        },
        {
          "id": "greet-011",
          "term_zh": "廁所在哪裡？",
          "term_target": "Where is the bathroom?",
          "pronunciation": ["/wɛr ɪz ðə ˈbæθˌrum/"],
          "example": { "sentence": "Excuse me, where is the bathroom?", "translation": "請問廁所在哪？" },
          "usage_note": "出國最重要的一句話。",
          "image_file": "where_bathroom.png"
        },
        {
          "id": "greet-012",
          "term_zh": "多少錢？",
          "term_target": "How much is it?",
          "pronunciation": ["/haʊ mʌtʃ ɪz ɪt/"],
          "example": { "sentence": "How much is it?", "translation": "這多少錢？" },
          "usage_note": "購物必備。",
          "image_file": "how_much.png"
        },
        {
          "id": "greet-013",
          "term_zh": "請幫我",
          "term_target": "Please help me",
          "pronunciation": ["/pliz hɛlp mi/"],
          "example": { "sentence": "Please help me carry this.", "translation": "請幫我拿這個。" },
          "usage_note": "尋求協助。",
          "image_file": "help_me.png"
        },
        {
          "id": "greet-014",
          "term_zh": "你可以再說一次嗎？",
          "term_target": "Can you say that again?",
          "pronunciation": ["/kæn ju seɪ ðæt əˈgɛn/"],
          "example": { "sentence": "Sorry, can you say that again?", "translation": "抱歉，能再說一次嗎？" },
          "usage_note": "沒聽清楚時使用。",
          "image_file": "say_again.png"
        },
        {
          "id": "greet-015",
          "term_zh": "你可以講慢一點嗎？",
          "term_target": "Can you speak slowly?",
          "pronunciation": ["/kæn ju spik ˈsloʊli/"],
          "example": { "sentence": "Can you speak slowly?", "translation": "可以講慢一點嗎？" },
          "usage_note": "外國人講太快時使用。",
          "image_file": "speak_slowly.png"
        }
      ]
    },
    {
      "id": "pronouns",
      "name": "主詞（代名詞）",
      "items": [
        { "id": "pro-01", "term_zh": "我", "term_target": "I", "pronunciation": ["/aɪ/"], "example": {"sentence": "I am here.", "translation": "我在這。"}, "usage_note": "永遠大寫。", "image_file": "i.png" },
        { "id": "pro-02", "term_zh": "你", "term_target": "you", "pronunciation": ["/ju/"], "example": {"sentence": "You are nice.", "translation": "你很好。"}, "usage_note": "單複數同形。", "image_file": "you.png" },
        { "id": "pro-03", "term_zh": "他", "term_target": "he", "pronunciation": ["/hi/"], "example": {"sentence": "He is my dad.", "translation": "他是我爸。"}, "usage_note": "男生。", "image_file": "he.png" },
        { "id": "pro-04", "term_zh": "她", "term_target": "she", "pronunciation": ["/ʃi/"], "example": {"sentence": "She is my mom.", "translation": "她是我媽。"}, "usage_note": "女生。", "image_file": "she.png" },
        { "id": "pro-05", "term_zh": "我們", "term_target": "we", "pronunciation": ["/wi/"], "example": {"sentence": "We are family.", "translation": "我們是家人。"}, "usage_note": "包含自己。", "image_file": "we.png" },
        { "id": "pro-06", "term_zh": "他們", "term_target": "they", "pronunciation": ["/ðeɪ/"], "example": {"sentence": "They are students.", "translation": "他們是學生。"}, "usage_note": "不分男女。", "image_file": "they.png" },
        { "id": "pro-07", "term_zh": "這個", "term_target": "this", "pronunciation": ["/ðɪs/"], "example": {"sentence": "This is mine.", "translation": "這是我的。"}, "usage_note": "近的單數。", "image_file": "this.png" },
        { "id": "pro-08", "term_zh": "那個/它", "term_target": "that / it", "pronunciation": ["/ðæt/ /ɪt/"], "example": {"sentence": "That is a cat.", "translation": "那是一隻貓。"}, "usage_note": "遠的用That，無生命用It。", "image_file": "that.png" },
        { "id": "pro-09", "term_zh": "他的", "term_target": "his", "pronunciation": ["/hɪz/"], "example": {"sentence": "His car.", "translation": "他的車。"}, "usage_note": "所有格。", "image_file": "his.png" },
        { "id": "pro-10", "term_zh": "她的", "term_target": "her", "pronunciation": ["/hɝ/"], "example": {"sentence": "Her bag.", "translation": "她的包包。"}, "usage_note": "所有格。", "image_file": "her.png" },
        { "id": "pro-11", "term_zh": "你的", "term_target": "your", "pronunciation": ["/jʊr/"], "example": {"sentence": "Your turn.", "translation": "換你了。"}, "usage_note": "所有格。", "image_file": "your.png" },
        { "id": "pro-12", "term_zh": "他們的", "term_target": "their", "pronunciation": ["/ðɛr/"], "example": {"sentence": "Their house.", "translation": "他們的房子。"}, "usage_note": "所有格。", "image_file": "their.png" },
        { "id": "pro-13", "term_zh": "我們的", "term_target": "our", "pronunciation": ["/ˈaʊr/"], "example": {"sentence": "Our school.", "translation": "我們的學校。"}, "usage_note": "所有格。", "image_file": "our.png" },
        { "id": "pro-14", "term_zh": "這些", "term_target": "these", "pronunciation": ["/ðiz/"], "example": {"sentence": "These are books.", "translation": "這些是書。"}, "usage_note": "近的複數。", "image_file": "these.png" },
        { "id": "pro-15", "term_zh": "那些", "term_target": "those", "pronunciation": ["/ðoʊz/"], "example": {"sentence": "Those are birds.", "translation": "那些是鳥。"}, "usage_note": "遠的複數。", "image_file": "those.png" }
      ]
    },
    {
      "id": "verbs",
      "name": "動詞",
      "items": [
        { "id": "v-01", "term_zh": "是", "term_target": "be (am/are/is)", "pronunciation": ["/bi/"], "example": {"sentence": "I am happy.", "translation": "我很快樂。"}, "usage_note": "連結主詞和狀態。", "image_file": "be.png" },
        { "id": "v-02", "term_zh": "有（擁有）", "term_target": "have", "pronunciation": ["/hæv/"], "example": {"sentence": "I have money.", "translation": "我有錢。"}, "usage_note": "擁有。", "image_file": "have.png" },
        { "id": "v-03", "term_zh": "去", "term_target": "go", "pronunciation": ["/goʊ/"], "example": {"sentence": "Go home.", "translation": "回家。"}, "usage_note": "離開去某處。", "image_file": "go.png" },
        { "id": "v-04", "term_zh": "做", "term_target": "do", "pronunciation": ["/du/"], "example": {"sentence": "Do homework.", "translation": "做功課。"}, "usage_note": "執行動作。", "image_file": "do.png" },
        { "id": "v-05", "term_zh": "說(內容)", "term_target": "say", "pronunciation": ["/seɪ/"], "example": {"sentence": "Say hello.", "translation": "說你好。"}, "usage_note": "說出內容。", "image_file": "say.png" },
        { "id": "v-06", "term_zh": "知道", "term_target": "know", "pronunciation": ["/noʊ/"], "example": {"sentence": "I know you.", "translation": "我認識你。"}, "usage_note": "K不發音。", "image_file": "know.png" },
        { "id": "v-07", "term_zh": "想/思考", "term_target": "think", "pronunciation": ["/θɪŋk/"], "example": {"sentence": "I think so.", "translation": "我也這麼覺得。"}, "usage_note": "表達意見。", "image_file": "think.png" },
        { "id": "v-08", "term_zh": "看見", "term_target": "see", "pronunciation": ["/si/"], "example": {"sentence": "I see you.", "translation": "我看到你了。"}, "usage_note": "自然看見。", "image_file": "see.png" },
        { "id": "v-09", "term_zh": "製作", "term_target": "make", "pronunciation": ["/meɪk/"], "example": {"sentence": "Make coffee.", "translation": "泡咖啡。"}, "usage_note": "產生新東西。", "image_file": "make.png" },
        { "id": "v-10", "term_zh": "來", "term_target": "come", "pronunciation": ["/kʌm/"], "example": {"sentence": "Come here.", "translation": "過來這裡。"}, "usage_note": "往說話者靠近。", "image_file": "come.png" },
        { "id": "v-11", "term_zh": "需要", "term_target": "need", "pronunciation": ["/nid/"], "example": {"sentence": "I need water.", "translation": "我需要水。"}, "usage_note": "必要。", "image_file": "need.png" },
        { "id": "v-12", "term_zh": "使用", "term_target": "use", "pronunciation": ["/juz/"], "example": {"sentence": "Use a pen.", "translation": "用筆。"}, "usage_note": "利用工具。", "image_file": "use.png" },
        { "id": "v-13", "term_zh": "找到", "term_target": "find", "pronunciation": ["/faɪnd/"], "example": {"sentence": "Find a job.", "translation": "找工作。"}, "usage_note": "搜尋後得到。", "image_file": "find.png" },
        { "id": "v-14", "term_zh": "給", "term_target": "give", "pronunciation": ["/gɪv/"], "example": {"sentence": "Give me that.", "translation": "給我那個。"}, "usage_note": "交付。", "image_file": "give.png" },
        { "id": "v-15", "term_zh": "告訴", "term_target": "tell", "pronunciation": ["/tɛl/"], "example": {"sentence": "Tell me why.", "translation": "告訴我為什麼。"}, "usage_note": "告知資訊。", "image_file": "tell.png" },
        { "id": "v-16", "term_zh": "工作", "term_target": "work", "pronunciation": ["/wɝk/"], "example": {"sentence": "I work here.", "translation": "我在這工作。"}, "usage_note": "上班或運作。", "image_file": "work.png" },
        { "id": "v-17", "term_zh": "喜歡", "term_target": "like", "pronunciation": ["/laɪk/"], "example": {"sentence": "I like it.", "translation": "我喜歡它。"}, "usage_note": "喜好。", "image_file": "like.png" },
        { "id": "v-18", "term_zh": "起床/醒來", "term_target": "wake up", "pronunciation": ["/weɪk ʌp/"], "example": {"sentence": "Wake up now.", "translation": "現在醒來。"}, "usage_note": "睜開眼。", "image_file": "wake_up.png" },
        { "id": "v-19", "term_zh": "說話", "term_target": "speak", "pronunciation": ["/spik/"], "example": {"sentence": "Speak English.", "translation": "說英文。"}, "usage_note": "講語言。", "image_file": "speak.png" },
        { "id": "v-20", "term_zh": "聽見", "term_target": "hear", "pronunciation": ["/hɪr/"], "example": {"sentence": "Can you hear me?", "translation": "聽得到我嗎？"}, "usage_note": "自然聽見。", "image_file": "hear.png" },
        { "id": "v-21", "term_zh": "寫", "term_target": "write", "pronunciation": ["/raɪt/"], "example": {"sentence": "Write a name.", "translation": "寫名字。"}, "usage_note": "書寫。", "image_file": "write.png" },
        { "id": "v-22", "term_zh": "閱讀", "term_target": "read", "pronunciation": ["/rid/"], "example": {"sentence": "Read a book.", "translation": "看書。"}, "usage_note": "閱讀文字。", "image_file": "read.png" },
        { "id": "v-23", "term_zh": "等待", "term_target": "wait", "pronunciation": ["/weɪt/"], "example": {"sentence": "Wait for me.", "translation": "等我。"}, "usage_note": "等候。", "image_file": "wait.png" },
        { "id": "v-24", "term_zh": "嘗試", "term_target": "try", "pronunciation": ["/traɪ/"], "example": {"sentence": "Try this food.", "translation": "試試這食物。"}, "usage_note": "試驗。", "image_file": "try.png" },
        { "id": "v-25", "term_zh": "付錢", "term_target": "pay", "pronunciation": ["/peɪ/"], "example": {"sentence": "Pay the bill.", "translation": "付帳單。"}, "usage_note": "支付。", "image_file": "pay.png" },
        { "id": "v-26", "term_zh": "住", "term_target": "live", "pronunciation": ["/lɪv/"], "example": {"sentence": "I live in Taipei.", "translation": "我住台北。"}, "usage_note": "居住。", "image_file": "live.png" },
        { "id": "v-27", "term_zh": "走路", "term_target": "walk", "pronunciation": ["/wɔk/"], "example": {"sentence": "Walk home.", "translation": "走路回家。"}, "usage_note": "步行。", "image_file": "walk.png" },
        { "id": "v-28", "term_zh": "打開", "term_target": "open", "pronunciation": ["/ˈoʊpən/"], "example": {"sentence": "Open the door.", "translation": "開門。"}, "usage_note": "開啟。", "image_file": "open.png" },
        { "id": "v-29", "term_zh": "關閉", "term_target": "close", "pronunciation": ["/kloʊz/"], "example": {"sentence": "Close the window.", "translation": "關窗。"}, "usage_note": "關上。", "image_file": "close.png" },
        { "id": "v-30", "term_zh": "幫助", "term_target": "help", "pronunciation": ["/hɛlp/"], "example": {"sentence": "Help me.", "translation": "幫我。"}, "usage_note": "協助。", "image_file": "help.png" },
        { "id": "v-31", "term_zh": "吃", "term_target": "eat", "pronunciation": ["/it/"], "example": {"sentence": "Eat lunch.", "translation": "吃午餐。"}, "usage_note": "進食。", "image_file": "eat.png" },
        { "id": "v-32", "term_zh": "睡覺", "term_target": "sleep", "pronunciation": ["/slip/"], "example": {"sentence": "Go to sleep.", "translation": "去睡覺。"}, "usage_note": "睡眠。", "image_file": "sleep.png" },
        { "id": "v-33", "term_zh": "買", "term_target": "buy", "pronunciation": ["/baɪ/"], "example": {"sentence": "Buy a car.", "translation": "買車。"}, "usage_note": "購買。", "image_file": "buy.png" },
        { "id": "v-34", "term_zh": "乘坐/拿", "term_target": "take", "pronunciation": ["/teɪk/"], "example": {"sentence": "Take a bus.", "translation": "搭公車。"}, "usage_note": "搭乘交通工具或拿取。", "image_file": "take.png" },
        { "id": "v-35", "term_zh": "得到/拿", "term_target": "get", "pronunciation": ["/gɛt/"], "example": {"sentence": "Get a gift.", "translation": "收到禮物。"}, "usage_note": "獲得。", "image_file": "get.png" },
        { "id": "v-36", "term_zh": "選擇", "term_target": "choose", "pronunciation": ["/tʃuz/"], "example": {"sentence": "Choose one.", "translation": "選一個。"}, "usage_note": "挑選。", "image_file": "choose.png" },
        { "id": "v-37", "term_zh": "進入", "term_target": "enter", "pronunciation": ["/ˈɛntɚ/"], "example": {"sentence": "Enter the room.", "translation": "進房間。"}, "usage_note": "進入。", "image_file": "enter.png" },
        { "id": "v-38", "term_zh": "到達", "term_target": "arrive", "pronunciation": ["/əˈraɪv/"], "example": {"sentence": "Arrive at 6.", "translation": "六點到達。"}, "usage_note": "抵達。", "image_file": "arrive.png" },
        { "id": "v-39", "term_zh": "帶來", "term_target": "bring", "pronunciation": ["/brɪŋ/"], "example": {"sentence": "Bring water.", "translation": "帶水來。"}, "usage_note": "攜帶。", "image_file": "bring.png" },
        { "id": "v-40", "term_zh": "變成", "term_target": "become", "pronunciation": ["/bɪˈkʌm/"], "example": {"sentence": "Become a teacher.", "translation": "變成老師。"}, "usage_note": "變化。", "image_file": "become.png" },
        { "id": "v-41", "term_zh": "開始", "term_target": "start", "pronunciation": ["/stɑrt/"], "example": {"sentence": "Start now.", "translation": "現在開始。"}, "usage_note": "開始。", "image_file": "start.png" },
        { "id": "v-42", "term_zh": "結束", "term_target": "finish", "pronunciation": ["/ˈfɪnɪʃ/"], "example": {"sentence": "Finish work.", "translation": "工作結束。"}, "usage_note": "完成。", "image_file": "finish.png" },
        { "id": "v-43", "term_zh": "停止", "term_target": "stop", "pronunciation": ["/stɑp/"], "example": {"sentence": "Stop here.", "translation": "停在這裡。"}, "usage_note": "停止。", "image_file": "stop.png" },
        { "id": "v-44", "term_zh": "記住", "term_target": "remember", "pronunciation": ["/rɪˈmɛmbɚ/"], "example": {"sentence": "Remember me.", "translation": "記得我。"}, "usage_note": "記憶。", "image_file": "remember.png" },
        { "id": "v-45", "term_zh": "見面", "term_target": "meet", "pronunciation": ["/mit/"], "example": {"sentence": "Meet a friend.", "translation": "見朋友。"}, "usage_note": "會面。", "image_file": "meet.png" },
        { "id": "v-46", "term_zh": "放", "term_target": "put", "pronunciation": ["/pʊt/"], "example": {"sentence": "Put it here.", "translation": "放這裡。"}, "usage_note": "放置。", "image_file": "put.png" },
        { "id": "v-47", "term_zh": "寄送", "term_target": "send", "pronunciation": ["/sɛnd/"], "example": {"sentence": "Send email.", "translation": "寄信。"}, "usage_note": "傳送。", "image_file": "send.png" },
        { "id": "v-48", "term_zh": "開車", "term_target": "drive", "pronunciation": ["/draɪv/"], "example": {"sentence": "Drive a car.", "translation": "開車。"}, "usage_note": "駕駛。", "image_file": "drive.png" },
        { "id": "v-49", "term_zh": "讀書", "term_target": "study", "pronunciation": ["/ˈstʌdi/"], "example": {"sentence": "Study hard.", "translation": "用功讀書。"}, "usage_note": "學習。", "image_file": "study.png" },
        { "id": "v-50", "term_zh": "回去", "term_target": "go back", "pronunciation": ["/goʊ bæk/"], "example": {"sentence": "Go back home.", "translation": "回家。"}, "usage_note": "歸返。", "image_file": "go_back.png" }
      ]
    },
    {
      "id": "adjectives",
      "name": "形容詞",
      "items": [
        { "id": "adj-01", "term_zh": "好的", "term_target": "good", "pronunciation": ["/gʊd/"], "example": {"sentence": "Good job.", "translation": "做得好。"}, "usage_note": "正面。", "image_file": "good.png" },
        { "id": "adj-02", "term_zh": "壞的", "term_target": "bad", "pronunciation": ["/bæd/"], "example": {"sentence": "Bad boy.", "translation": "壞男孩。"}, "usage_note": "負面。", "image_file": "bad.png" },
        { "id": "adj-03", "term_zh": "新的", "term_target": "new", "pronunciation": ["/nu/"], "example": {"sentence": "New phone.", "translation": "新手機。"}, "usage_note": "全新。", "image_file": "new.png" },
        { "id": "adj-04", "term_zh": "大的", "term_target": "big", "pronunciation": ["/bɪg/"], "example": {"sentence": "Big house.", "translation": "大房子。"}, "usage_note": "體積大。", "image_file": "big.png" },
        { "id": "adj-05", "term_zh": "小的", "term_target": "small", "pronunciation": ["/smɔl/"], "example": {"sentence": "Small size.", "translation": "小尺寸。"}, "usage_note": "體積小。", "image_file": "small.png" },
        { "id": "adj-06", "term_zh": "熱的", "term_target": "hot", "pronunciation": ["/hɑt/"], "example": {"sentence": "Hot water.", "translation": "熱水。"}, "usage_note": "高溫。", "image_file": "hot.png" },
        { "id": "adj-07", "term_zh": "冷的", "term_target": "cold", "pronunciation": ["/koʊld/"], "example": {"sentence": "Cold drink.", "translation": "冷飲。"}, "usage_note": "低溫。", "image_file": "cold.png" },
        { "id": "adj-08", "term_zh": "簡單的", "term_target": "easy", "pronunciation": ["/ˈizi/"], "example": {"sentence": "It is easy.", "translation": "很簡單。"}, "usage_note": "容易。", "image_file": "easy.png" },
        { "id": "adj-09", "term_zh": "困難的", "term_target": "difficult", "pronunciation": ["/ˈdɪfəˌkʌlt/"], "example": {"sentence": "It is difficult.", "translation": "很難。"}, "usage_note": "難。", "image_file": "difficult.png" },
        { "id": "adj-10", "term_zh": "美味的", "term_target": "delicious", "pronunciation": ["/dɪˈlɪʃəs/"], "example": {"sentence": "Delicious food.", "translation": "美食。"}, "usage_note": "好吃。", "image_file": "delicious.png" },
        { "id": "adj-11", "term_zh": "忙碌的", "term_target": "busy", "pronunciation": ["/ˈbɪzi/"], "example": {"sentence": "I am busy.", "translation": "我很忙。"}, "usage_note": "沒空。", "image_file": "busy.png" },
        { "id": "adj-12", "term_zh": "疲累的", "term_target": "tired", "pronunciation": ["/taɪrd/"], "example": {"sentence": "I am tired.", "translation": "我累了。"}, "usage_note": "累。", "image_file": "tired.png" },
        { "id": "adj-13", "term_zh": "快樂的", "term_target": "happy", "pronunciation": ["/ˈhæpi/"], "example": {"sentence": "Happy birthday.", "translation": "生日快樂。"}, "usage_note": "高興。", "image_file": "happy.png" },
        { "id": "adj-14", "term_zh": "悲傷的", "term_target": "sad", "pronunciation": ["/sæd/"], "example": {"sentence": "Sad story.", "translation": "悲傷的故事。"}, "usage_note": "難過。", "image_file": "sad.png" },
        { "id": "adj-15", "term_zh": "乾淨的", "term_target": "clean", "pronunciation": ["/klin/"], "example": {"sentence": "Clean room.", "translation": "乾淨的房間。"}, "usage_note": "無髒汙。", "image_file": "clean.png" },
        { "id": "adj-16", "term_zh": "髒的", "term_target": "dirty", "pronunciation": ["/ˈdɝti/"], "example": {"sentence": "Dirty hands.", "translation": "髒手。"}, "usage_note": "不乾淨。", "image_file": "dirty.png" },
        { "id": "adj-17", "term_zh": "便宜的", "term_target": "cheap", "pronunciation": ["/tʃip/"], "example": {"sentence": "It is cheap.", "translation": "很便宜。"}, "usage_note": "價格低。", "image_file": "cheap.png" },
        { "id": "adj-18", "term_zh": "昂貴的", "term_target": "expensive", "pronunciation": ["/ɪkˈspɛnsɪv/"], "example": {"sentence": "Too expensive.", "translation": "太貴了。"}, "usage_note": "價格高。", "image_file": "expensive.png" },
        { "id": "adj-19", "term_zh": "重要的", "term_target": "important", "pronunciation": ["/ɪmˈpɔrtənt/"], "example": {"sentence": "Important meeting.", "translation": "重要會議。"}, "usage_note": "關鍵。", "image_file": "important.png" },
        { "id": "adj-20", "term_zh": "相同的", "term_target": "same", "pronunciation": ["/seɪm/"], "example": {"sentence": "Same place.", "translation": "同個地方。"}, "usage_note": "一樣。", "image_file": "same.png" },
        { "id": "adj-21", "term_zh": "第一的", "term_target": "first", "pronunciation": ["/fɝst/"], "example": {"sentence": "First time.", "translation": "第一次。"}, "usage_note": "順序。", "image_file": "first.png" },
        { "id": "adj-22", "term_zh": "上一個", "term_target": "last", "pronunciation": ["/læst/"], "example": {"sentence": "Last week.", "translation": "上週。"}, "usage_note": "最後或上一個。", "image_file": "last.png" },
        { "id": "adj-23", "term_zh": "下一個", "term_target": "next", "pronunciation": ["/nɛkst/"], "example": {"sentence": "Next station.", "translation": "下一站。"}, "usage_note": "接下來。", "image_file": "next.png" },
        { "id": "adj-24", "term_zh": "長的", "term_target": "long", "pronunciation": ["/lɔŋ/"], "example": {"sentence": "Long hair.", "translation": "長髮。"}, "usage_note": "長度。", "image_file": "long.png" },
        { "id": "adj-25", "term_zh": "多的", "term_target": "many", "pronunciation": ["/ˈmɛni/"], "example": {"sentence": "Many people.", "translation": "很多人。"}, "usage_note": "可數名詞用。", "image_file": "many.png" },
        { "id": "adj-26", "term_zh": "高的", "term_target": "tall", "pronunciation": ["/tɔl/"], "example": {"sentence": "Tall building.", "translation": "高樓。"}, "usage_note": "高度。", "image_file": "tall.png" },
        { "id": "adj-27", "term_zh": "年輕的", "term_target": "young", "pronunciation": ["/jʌŋ/"], "example": {"sentence": "Young man.", "translation": "年輕人。"}, "usage_note": "年紀小。", "image_file": "young.png" },
        { "id": "adj-28", "term_zh": "老的/舊的", "term_target": "old", "pronunciation": ["/oʊld/"], "example": {"sentence": "Old book.", "translation": "舊書。"}, "usage_note": "人或物皆可。", "image_file": "old.png" },
        { "id": "adj-29", "term_zh": "近的", "term_target": "near", "pronunciation": ["/nɪr/"], "example": {"sentence": "Near here.", "translation": "在這附近。"}, "usage_note": "距離近。", "image_file": "near.png" },
        { "id": "adj-30", "term_zh": "遠的", "term_target": "far", "pronunciation": ["/fɑr/"], "example": {"sentence": "Far away.", "translation": "很遠。"}, "usage_note": "距離遠。", "image_file": "far.png" },
        { "id": "adj-31", "term_zh": "快的", "term_target": "fast", "pronunciation": ["/fæst/"], "example": {"sentence": "Run fast.", "translation": "跑得快。"}, "usage_note": "速度快。", "image_file": "fast.png" },
        { "id": "adj-32", "term_zh": "慢的", "term_target": "slow", "pronunciation": ["/sloʊ/"], "example": {"sentence": "Walk slow.", "translation": "走得慢。"}, "usage_note": "速度慢。", "image_file": "slow.png" },
        { "id": "adj-33", "term_zh": "正確的", "term_target": "correct", "pronunciation": ["/kəˈrɛkt/"], "example": {"sentence": "Correct answer.", "translation": "正確答案。"}, "usage_note": "對的。", "image_file": "correct.png" },
        { "id": "adj-34", "term_zh": "錯誤的", "term_target": "wrong", "pronunciation": ["/rɔŋ/"], "example": {"sentence": "Wrong way.", "translation": "錯的路。"}, "usage_note": "不對。", "image_file": "wrong.png" },
        { "id": "adj-35", "term_zh": "不同的", "term_target": "different", "pronunciation": ["/ˈdɪfrənt/"], "example": {"sentence": "Different color.", "translation": "不同顏色。"}, "usage_note": "差異。", "image_file": "different.png" },
        { "id": "adj-36", "term_zh": "真的", "term_target": "real", "pronunciation": ["/riəl/"], "example": {"sentence": "Real gold.", "translation": "真金。"}, "usage_note": "真實。", "image_file": "real.png" },
        { "id": "adj-37", "term_zh": "有趣的", "term_target": "interesting", "pronunciation": ["/ˈɪntrɪstɪŋ/"], "example": {"sentence": "Interesting book.", "translation": "有趣的書。"}, "usage_note": "有意思。", "image_file": "interesting.png" },
        { "id": "adj-38", "term_zh": "飢餓的", "term_target": "hungry", "pronunciation": ["/ˈhʌŋgri/"], "example": {"sentence": "I am hungry.", "translation": "我餓了。"}, "usage_note": "餓。", "image_file": "hungry.png" },
        { "id": "adj-39", "term_zh": "有名的", "term_target": "famous", "pronunciation": ["/ˈfeɪməs/"], "example": {"sentence": "Famous singer.", "translation": "知名歌手。"}, "usage_note": "知名。", "image_file": "famous.png" },
        { "id": "adj-40", "term_zh": "外國的", "term_target": "foreign", "pronunciation": ["/ˈfɔrən/"], "example": {"sentence": "Foreign country.", "translation": "外國。"}, "usage_note": "國外。", "image_file": "foreign.png" },
        { "id": "adj-41", "term_zh": "聰明的", "term_target": "smart", "pronunciation": ["/smɑrt/"], "example": {"sentence": "Smart phone.", "translation": "智慧型手機。"}, "usage_note": "腦袋好。", "image_file": "intelligent.png" },
        { "id": "adj-42", "term_zh": "危險的", "term_target": "dangerous", "pronunciation": ["/ˈdeɪndʒərəs/"], "example": {"sentence": "It is dangerous.", "translation": "這很危險。"}, "usage_note": "警示。", "image_file": "dangerous.png" },
        { "id": "adj-43", "term_zh": "仁慈的", "term_target": "kind", "pronunciation": ["/kaɪnd/"], "example": {"sentence": "Kind person.", "translation": "好心人。"}, "usage_note": "溫柔。", "image_file": "kind.png" },
        { "id": "adj-44", "term_zh": "所有的", "term_target": "every", "pronunciation": ["/ˈɛvri/"], "example": {"sentence": "Every day.", "translation": "每一天。"}, "usage_note": "每一個。", "image_file": "every.png" },
        { "id": "adj-45", "term_zh": "喜愛的", "term_target": "favorite", "pronunciation": ["/ˈfeɪvərɪt/"], "example": {"sentence": "Favorite food.", "translation": "最愛的食物。"}, "usage_note": "中意。", "image_file": "favorite.png" }
      ]
    },
    {
      "id": "nouns",
      "name": "名詞",
      "items": [
        { "id": "n-01", "term_zh": "水", "term_target": "water", "pronunciation": ["/ˈwɑtɚ/"], "example": {"sentence": "Drink water.", "translation": "喝水。"}, "usage_note": "不可數。", "image_file": "water.png" },
        { "id": "n-02", "term_zh": "食物", "term_target": "food", "pronunciation": ["/fud/"], "example": {"sentence": "Good food.", "translation": "好吃的食物。"}, "usage_note": "吃的東西。", "image_file": "food.png" },
        { "id": "n-03", "term_zh": "錢", "term_target": "money", "pronunciation": ["/ˈmʌni/"], "example": {"sentence": "No money.", "translation": "沒錢。"}, "usage_note": "不可數。", "image_file": "money.png" },
        { "id": "n-04", "term_zh": "廁所", "term_target": "bathroom / restroom", "pronunciation": ["/ˈbæθˌrum/"], "example": {"sentence": "Go to bathroom.", "translation": "去廁所。"}, "usage_note": "公共場合用Restroom。", "image_file": "bathroom.png" },
        { "id": "n-05", "term_zh": "人", "term_target": "people", "pronunciation": ["/ˈpipəl/"], "example": {"sentence": "Many people.", "translation": "很多人。"}, "usage_note": "複數。", "image_file": "people.png" },
        { "id": "n-06", "term_zh": "時間", "term_target": "time", "pronunciation": ["/taɪm/"], "example": {"sentence": "What time?", "translation": "幾點？"}, "usage_note": "時刻。", "image_file": "time.png" },
        { "id": "n-07", "term_zh": "朋友", "term_target": "friend", "pronunciation": ["/frɛnd/"], "example": {"sentence": "My friend.", "translation": "我朋友。"}, "usage_note": "友人。", "image_file": "friend.png" },
        { "id": "n-08", "term_zh": "家庭", "term_target": "family", "pronunciation": ["/ˈfæməli/"], "example": {"sentence": "Big family.", "translation": "大家庭。"}, "usage_note": "家人。", "image_file": "family.png" },
        { "id": "n-09", "term_zh": "手機", "term_target": "phone", "pronunciation": ["/foʊn/"], "example": {"sentence": "My phone.", "translation": "我手機。"}, "usage_note": "電話。", "image_file": "phone.png" },
        { "id": "n-10", "term_zh": "車", "term_target": "car", "pronunciation": ["/kɑr/"], "example": {"sentence": "Drive a car.", "translation": "開車。"}, "usage_note": "汽車。", "image_file": "car.png" },
        { "id": "n-11", "term_zh": "巴士", "term_target": "bus", "pronunciation": ["/bʌs/"], "example": {"sentence": "Take a bus.", "translation": "搭公車。"}, "usage_note": "公車。", "image_file": "bus.png" },
        { "id": "n-12", "term_zh": "火車", "term_target": "train", "pronunciation": ["/treɪn/"], "example": {"sentence": "By train.", "translation": "搭火車。"}, "usage_note": "列車。", "image_file": "train.png" },
        { "id": "n-13", "term_zh": "捷運/地鐵", "term_target": "subway / metro", "pronunciation": ["/ˈsʌbˌweɪ/"], "example": {"sentence": "MRT station.", "translation": "捷運站。"}, "usage_note": "地下鐵。", "image_file": "subway.png" },
        { "id": "n-14", "term_zh": "車站", "term_target": "station", "pronunciation": ["/ˈsteɪʃən/"], "example": {"sentence": "Bus station.", "translation": "公車站。"}, "usage_note": "站點。", "image_file": "station.png" },
        { "id": "n-15", "term_zh": "機場", "term_target": "airport", "pronunciation": ["/ˈɛrˌpɔrt/"], "example": {"sentence": "Go to airport.", "translation": "去機場。"}, "usage_note": "搭飛機處。", "image_file": "airport.png" },
        { "id": "n-16", "term_zh": "票", "term_target": "ticket", "pronunciation": ["/ˈtɪkɪt/"], "example": {"sentence": "One ticket.", "translation": "一張票。"}, "usage_note": "入場券或車票。", "image_file": "ticket.png" },
        { "id": "n-17", "term_zh": "飯店", "term_target": "hotel", "pronunciation": ["/hoʊˈtɛl/"], "example": {"sentence": "Book a hotel.", "translation": "訂飯店。"}, "usage_note": "住宿。", "image_file": "hotel.png" },
        { "id": "n-18", "term_zh": "護照", "term_target": "passport", "pronunciation": ["/ˈpæsˌpɔrt/"], "example": {"sentence": "Show passport.", "translation": "出示護照。"}, "usage_note": "出國必備。", "image_file": "passport.png" },
        { "id": "n-19", "term_zh": "地圖", "term_target": "map", "pronunciation": ["/mæp/"], "example": {"sentence": "Google map.", "translation": "谷歌地圖。"}, "usage_note": "指引。", "image_file": "map.png" },
        { "id": "n-20", "term_zh": "警察", "term_target": "police", "pronunciation": ["/pəˈlis/"], "example": {"sentence": "Call police.", "translation": "叫警察。"}, "usage_note": "求救用。", "image_file": "police.png" },
        { "id": "n-21", "term_zh": "台灣人", "term_target": "Taiwanese", "pronunciation": ["/ˌtaɪwɑˈniz/"], "example": {"sentence": "I am Taiwanese.", "translation": "我是台灣人。"}, "usage_note": "國籍。", "image_file": "taiwanese.png" },
        { "id": "n-22", "term_zh": "孩子", "term_target": "child", "pronunciation": ["/tʃaɪld/"], "example": {"sentence": "Small child.", "translation": "小孩。"}, "usage_note": "兒童。", "image_file": "child.png" },
        { "id": "n-23", "term_zh": "學生", "term_target": "student", "pronunciation": ["/ˈstudənt/"], "example": {"sentence": "I am a student.", "translation": "我是學生。"}, "usage_note": "在學者。", "image_file": "student.png" },
        { "id": "n-24", "term_zh": "文化", "term_target": "culture", "pronunciation": ["/ˈkʌltʃɚ/"], "example": {"sentence": "Local culture.", "translation": "當地文化。"}, "usage_note": "文化。", "image_file": "culture.png" },
        { "id": "n-25", "term_zh": "問題", "term_target": "problem", "pronunciation": ["/ˈprɑbləm/"], "example": {"sentence": "No problem.", "translation": "沒問題。"}, "usage_note": "難題。", "image_file": "problem.png" },
        { "id": "n-26", "term_zh": "公司", "term_target": "company", "pronunciation": ["/ˈkʌmpəni/"], "example": {"sentence": "Big company.", "translation": "大公司。"}, "usage_note": "上班地點。", "image_file": "company.png" },
        { "id": "n-27", "term_zh": "男性", "term_target": "man", "pronunciation": ["/mæn/"], "example": {"sentence": "He is a man.", "translation": "他是男人。"}, "usage_note": "性別。", "image_file": "man.png" },
        { "id": "n-28", "term_zh": "女性", "term_target": "woman", "pronunciation": ["/ˈwʊmən/"], "example": {"sentence": "She is a woman.", "translation": "她是女人。"}, "usage_note": "性別。", "image_file": "woman.png" },
        { "id": "n-29", "term_zh": "學校", "term_target": "school", "pronunciation": ["/skul/"], "example": {"sentence": "Go to school.", "translation": "去學校。"}, "usage_note": "教育機構。", "image_file": "school.png" },
        { "id": "n-30", "term_zh": "老師", "term_target": "teacher", "pronunciation": ["/ˈtitʃɚ/"], "example": {"sentence": "English teacher.", "translation": "英文老師。"}, "usage_note": "師長。", "image_file": "teacher.png" },
        { "id": "n-31", "term_zh": "電影", "term_target": "movie", "pronunciation": ["/ˈmuvi/"], "example": {"sentence": "Watch a movie.", "translation": "看電影。"}, "usage_note": "影片。", "image_file": "movie.png" },
        { "id": "n-32", "term_zh": "電腦", "term_target": "computer", "pronunciation": ["/kəmˈpjutɚ/"], "example": {"sentence": "Use computer.", "translation": "用電腦。"}, "usage_note": "PC。", "image_file": "computer.png" },
        { "id": "n-33", "term_zh": "市場", "term_target": "market", "pronunciation": ["/ˈmɑrkɪt/"], "example": {"sentence": "Night market.", "translation": "夜市。"}, "usage_note": "市集。", "image_file": "market.png" },
        { "id": "n-34", "term_zh": "衣服", "term_target": "clothes", "pronunciation": ["/kloʊðz/"], "example": {"sentence": "Buy clothes.", "translation": "買衣服。"}, "usage_note": "衣物。", "image_file": "clothes.png" },
        { "id": "n-35", "term_zh": "商店", "term_target": "shop", "pronunciation": ["/ʃɑp/"], "example": {"sentence": "Coffee shop.", "translation": "咖啡店。"}, "usage_note": "店家。", "image_file": "shop.png" },
        { "id": "n-36", "term_zh": "街道", "term_target": "street", "pronunciation": ["/strit/"], "example": {"sentence": "On the street.", "translation": "在街上。"}, "usage_note": "道路。", "image_file": "street.png" },
        { "id": "n-37", "term_zh": "房子", "term_target": "house", "pronunciation": ["/haʊs/"], "example": {"sentence": "My house.", "translation": "我家。"}, "usage_note": "住宅。", "image_file": "house.png" },
        { "id": "n-38", "term_zh": "母親", "term_target": "mother", "pronunciation": ["/ˈmʌðɚ/"], "example": {"sentence": "My mother.", "translation": "我媽媽。"}, "usage_note": "媽媽。", "image_file": "mother.png" },
        { "id": "n-39", "term_zh": "父親", "term_target": "father", "pronunciation": ["/ˈfɑðɚ/"], "example": {"sentence": "My father.", "translation": "我爸爸。"}, "usage_note": "爸爸。", "image_file": "father.png" },
        { "id": "n-40", "term_zh": "中文", "term_target": "Chinese", "pronunciation": ["/tʃaɪˈniz/"], "example": {"sentence": "Speak Chinese.", "translation": "說中文。"}, "usage_note": "語言。", "image_file": "chinese.png" },
        { "id": "n-41", "term_zh": "包包", "term_target": "bag", "pronunciation": ["/bæg/"], "example": {"sentence": "Big bag.", "translation": "大包包。"}, "usage_note": "提包。", "image_file": "bag.png" },
        { "id": "n-42", "term_zh": "杯子", "term_target": "cup", "pronunciation": ["/kʌp/"], "example": {"sentence": "Cup of tea.", "translation": "一杯茶。"}, "usage_note": "杯具。", "image_file": "cup.png" },
        { "id": "n-43", "term_zh": "醫生", "term_target": "doctor", "pronunciation": ["/ˈdɑktɚ/"], "example": {"sentence": "See a doctor.", "translation": "看醫生。"}, "usage_note": "醫師。", "image_file": "doctor.png" },
        { "id": "n-44", "term_zh": "醫院", "term_target": "hospital", "pronunciation": ["/ˈhɑspɪtəl/"], "example": {"sentence": "Go to hospital.", "translation": "去醫院。"}, "usage_note": "醫療院所。", "image_file": "hospital.png" },
        { "id": "n-45", "term_zh": "座位", "term_target": "seat", "pronunciation": ["/sit/"], "example": {"sentence": "Take a seat.", "translation": "請坐。"}, "usage_note": "位子。", "image_file": "seat.png" },
        { "id": "n-46", "term_zh": "門", "term_target": "door", "pronunciation": ["/dɔr/"], "example": {"sentence": "Open the door.", "translation": "開門。"}, "usage_note": "門戶。", "image_file": "door.png" },
        { "id": "n-47", "term_zh": "房間", "term_target": "room", "pronunciation": ["/rum/"], "example": {"sentence": "My room.", "translation": "我房間。"}, "usage_note": "室內。", "image_file": "room.png" },
        { "id": "n-48", "term_zh": "行李", "term_target": "luggage", "pronunciation": ["/ˈlʌgɪdʒ/"], "example": {"sentence": "Heavy luggage.", "translation": "很重的行李。"}, "usage_note": "包裹。", "image_file": "luggage.png" },
        { "id": "n-49", "term_zh": "櫃檯", "term_target": "counter", "pronunciation": ["/ˈkaʊntɚ/"], "example": {"sentence": "At the counter.", "translation": "在櫃檯。"}, "usage_note": "服務台。", "image_file": "counter.png" },
        { "id": "n-50", "term_zh": "大廳", "term_target": "lobby", "pronunciation": ["/ˈlɑbi/"], "example": {"sentence": "Wait in lobby.", "translation": "在大廳等。"}, "usage_note": "接待處。", "image_file": "lobby.png" },
        { "id": "n-51", "term_zh": "預定", "term_target": "reservation", "pronunciation": ["/ˌrɛzɚˈveɪʃən/"], "example": {"sentence": "Make a reservation.", "translation": "做預約。"}, "usage_note": "預約。", "image_file": "reservation.png" },
        { "id": "n-52", "term_zh": "入住", "term_target": "check-in", "pronunciation": ["/tʃɛk ɪn/"], "example": {"sentence": "Check-in time.", "translation": "入住時間。"}, "usage_note": "Check-in。", "image_file": "check_in.png" },
        { "id": "n-53", "term_zh": "退房", "term_target": "check-out", "pronunciation": ["/tʃɛk aʊt/"], "example": {"sentence": "Check-out now.", "translation": "現在退房。"}, "usage_note": "Check-out。", "image_file": "check_out.png" },
        { "id": "n-54", "term_zh": "飲料", "term_target": "drink", "pronunciation": ["/drɪŋk/"], "example": {"sentence": "Cold drink.", "translation": "冷飲。"}, "usage_note": "飲品。", "image_file": "drink.png" },
        { "id": "n-55", "term_zh": "菜單", "term_target": "menu", "pronunciation": ["/ˈmɛnju/"], "example": {"sentence": "Menu please.", "translation": "請給菜單。"}, "usage_note": "Menu。", "image_file": "menu.png" },
        { "id": "n-56", "term_zh": "午餐", "term_target": "lunch", "pronunciation": ["/lʌntʃ/"], "example": {"sentence": "Eat lunch.", "translation": "吃午餐。"}, "usage_note": "中餐。", "image_file": "lunch.png" },
        { "id": "n-57", "term_zh": "晚餐", "term_target": "dinner", "pronunciation": ["/ˈdɪnɚ/"], "example": {"sentence": "Eat dinner.", "translation": "吃晚餐。"}, "usage_note": "晚餐。", "image_file": "dinner.png" },
        { "id": "n-58", "term_zh": "帳單", "term_target": "bill", "pronunciation": ["/bɪl/"], "example": {"sentence": "Check the bill.", "translation": "確認帳單。"}, "usage_note": "買單。", "image_file": "bill.png" },
        { "id": "n-59", "term_zh": "價錢", "term_target": "price", "pronunciation": ["/praɪs/"], "example": {"sentence": "Good price.", "translation": "好價格。"}, "usage_note": "價格。", "image_file": "price.png" },
        { "id": "n-60", "term_zh": "收據", "term_target": "receipt", "pronunciation": ["/rɪˈsit/"], "example": {"sentence": "Receipt please.", "translation": "請給收據。"}, "usage_note": "統一發票。", "image_file": "receipt.png" },
        { "id": "n-61", "term_zh": "尺寸", "term_target": "size", "pronunciation": ["/saɪz/"], "example": {"sentence": "Big size.", "translation": "大尺寸。"}, "usage_note": "大小。", "image_file": "size.png" },
        { "id": "n-62", "term_zh": "入口", "term_target": "entrance", "pronunciation": ["/ˈɛntrəns/"], "example": {"sentence": "Main entrance.", "translation": "正門入口。"}, "usage_note": "進去的地方。", "image_file": "entrance.png" },
        { "id": "n-63", "term_zh": "出口", "term_target": "exit", "pronunciation": ["/ˈɛgzɪt/"], "example": {"sentence": "Exit here.", "translation": "這裡出口。"}, "usage_note": "出去的地方。", "image_file": "exit.png" },
        { "id": "n-64", "term_zh": "台灣", "term_target": "Taiwan", "pronunciation": ["/taɪˈwɑn/"], "example": {"sentence": "I love Taiwan.", "translation": "我愛台灣。"}, "usage_note": "地名。", "image_file": "taiwan.png" },
        { "id": "n-65", "term_zh": "一切事物", "term_target": "everything", "pronunciation": ["/ˈɛvriˌθɪŋ/"], "example": {"sentence": "Everything is good.", "translation": "一切都好。"}, "usage_note": "所有。", "image_file": "everything.png" },
        { "id": "n-66", "term_zh": "錢包", "term_target": "wallet", "pronunciation": ["/ˈwɑlɪt/"], "example": {"sentence": "Lost wallet.", "translation": "掉了錢包。"}, "usage_note": "皮夾。", "image_file": "wallet.png" },
        { "id": "n-67", "term_zh": "身分證", "term_target": "ID card", "pronunciation": ["/aɪ di kɑrd/"], "example": {"sentence": "Show ID card.", "translation": "出示證件。"}, "usage_note": "ID。", "image_file": "id.png" },
        { "id": "n-68", "term_zh": "餐廳", "term_target": "restaurant", "pronunciation": ["/ˈrɛstərənt/"], "example": {"sentence": "Nice restaurant.", "translation": "好餐廳。"}, "usage_note": "食堂。", "image_file": "restaurant.png" },
        { "id": "n-69", "term_zh": "場所", "term_target": "place", "pronunciation": ["/pleɪs/"], "example": {"sentence": "Good place.", "translation": "好地方。"}, "usage_note": "地點。", "image_file": "place.png" },
        { "id": "n-70", "term_zh": "店員", "term_target": "clerk", "pronunciation": ["/klɝk/"], "example": {"sentence": "Ask the clerk.", "translation": "問店員。"}, "usage_note": "工作人員。", "image_file": "clerk.png" },
        { "id": "n-71", "term_zh": "超市", "term_target": "supermarket", "pronunciation": ["/ˈsupɚˌmɑrkɪt/"], "example": {"sentence": "Go to supermarket.", "translation": "去超市。"}, "usage_note": "量販店。", "image_file": "supermarket.png" },
        { "id": "n-72", "term_zh": "月台", "term_target": "platform", "pronunciation": ["/ˈplætˌfɔrm/"], "example": {"sentence": "Platform 1.", "translation": "第一月台。"}, "usage_note": "車站月台。", "image_file": "platform.png" }
      ]
    },
    {
      "id": "adverbs",
      "name": "副詞",
      "items": [
        { "id": "adv-01", "term_zh": "現在", "term_target": "now", "pronunciation": ["/naʊ/"], "example": {"sentence": "Do it now.", "translation": "現在做。"}, "usage_note": "目前。", "image_file": "now.png" },
        { "id": "adv-02", "term_zh": "非常", "term_target": "very", "pronunciation": ["/ˈvɛri/"], "example": {"sentence": "Very good.", "translation": "非常好。"}, "usage_note": "強調。", "image_file": "very.png" },
        { "id": "adv-03", "term_zh": "真的", "term_target": "really", "pronunciation": ["/ˈriəli/"], "example": {"sentence": "Really?", "translation": "真的嗎？"}, "usage_note": "確認或強調。", "image_file": "really.png" },
        { "id": "adv-04", "term_zh": "經常", "term_target": "often", "pronunciation": ["/ˈɔfən/"], "example": {"sentence": "I often come here.", "translation": "我常來這。"}, "usage_note": "頻率。", "image_file": "often.png" },
        { "id": "adv-05", "term_zh": "通常", "term_target": "usually", "pronunciation": ["/ˈjuʒʊəli/"], "example": {"sentence": "Usually at 6.", "translation": "通常在六點。"}, "usage_note": "習慣。", "image_file": "usually.png" },
        { "id": "adv-06", "term_zh": "只有", "term_target": "only", "pronunciation": ["/ˈoʊnli/"], "example": {"sentence": "Only one.", "translation": "只有一個。"}, "usage_note": "唯一。", "image_file": "only.png" },
        { "id": "adv-07", "term_zh": "再次", "term_target": "again", "pronunciation": ["/əˈgɛn/"], "example": {"sentence": "Try again.", "translation": "再試一次。"}, "usage_note": "重複。", "image_file": "again.png" },
        { "id": "adv-08", "term_zh": "一起", "term_target": "together", "pronunciation": ["/təˈgɛðɚ/"], "example": {"sentence": "Go together.", "translation": "一起去。"}, "usage_note": "共同。", "image_file": "together.png" },
        { "id": "adv-09", "term_zh": "或許", "term_target": "maybe", "pronunciation": ["/ˈmeɪbi/"], "example": {"sentence": "Maybe later.", "translation": "也許等下。"}, "usage_note": "不確定。", "image_file": "maybe.png" },
        { "id": "adv-10", "term_zh": "很快", "term_target": "soon", "pronunciation": ["/sun/"], "example": {"sentence": "See you soon.", "translation": "待會見。"}, "usage_note": "不久後。", "image_file": "soon.png" },
        { "id": "adv-11", "term_zh": "已經", "term_target": "already", "pronunciation": ["/ɔlˈrɛdi/"], "example": {"sentence": "Already done.", "translation": "已經做好了。"}, "usage_note": "完成。", "image_file": "already.png" },
        { "id": "adv-12", "term_zh": "大約", "term_target": "about", "pronunciation": ["/əˈbaʊt/"], "example": {"sentence": "About 10 minutes.", "translation": "大約10分鐘。"}, "usage_note": "概數。", "image_file": "about.png" },
        { "id": "adv-13", "term_zh": "一點點", "term_target": "a little", "pronunciation": ["/ə ˈlɪtḷ/"], "example": {"sentence": "A little spicy.", "translation": "一點點辣。"}, "usage_note": "少量。", "image_file": "a_little.png" },
        { "id": "adv-14", "term_zh": "之後", "term_target": "later", "pronunciation": ["/ˈleɪtɚ/"], "example": {"sentence": "See you later.", "translation": "待會見。"}, "usage_note": "稍後。", "image_file": "later.png" },
        { "id": "adv-15", "term_zh": "仍然", "term_target": "still", "pronunciation": ["/stɪl/"], "example": {"sentence": "Still here.", "translation": "還在這裡。"}, "usage_note": "持續。", "image_file": "still.png" },
        { "id": "adv-16", "term_zh": "一般來說", "term_target": "normally", "pronunciation": ["/ˈnɔrmḷi/"], "example": {"sentence": "Normally I walk.", "translation": "一般我走路。"}, "usage_note": "通常。", "image_file": "normally.png" }
      ]
    },
    {
      "id": "questions",
      "name": "疑問詞",
      "items": [
        { "id": "q-01", "term_zh": "什麼", "term_target": "what", "pronunciation": ["/hwɑt/"], "example": {"sentence": "What is it?", "translation": "它是什麼？"}, "usage_note": "問事物。", "image_file": "what.png" },
        { "id": "q-02", "term_zh": "哪裡", "term_target": "where", "pronunciation": ["/wɛr/"], "example": {"sentence": "Where are you?", "translation": "你在哪？"}, "usage_note": "問地點。", "image_file": "where.png" },
        { "id": "q-03", "term_zh": "何時", "term_target": "when", "pronunciation": ["/hwɛn/"], "example": {"sentence": "When to go?", "translation": "何時去？"}, "usage_note": "問時間。", "image_file": "when.png" },
        { "id": "q-04", "term_zh": "誰", "term_target": "who", "pronunciation": ["/hu/"], "example": {"sentence": "Who is he?", "translation": "他是誰？"}, "usage_note": "問人。", "image_file": "who.png" },
        { "id": "q-05", "term_zh": "為什麼", "term_target": "why", "pronunciation": ["/hwaɪ/"], "example": {"sentence": "Why?", "translation": "為什麼？"}, "usage_note": "問原因。", "image_file": "why.png" },
        { "id": "q-06", "term_zh": "如何", "term_target": "how", "pronunciation": ["/haʊ/"], "example": {"sentence": "How are you?", "translation": "你好嗎？"}, "usage_note": "問狀況。", "image_file": "how.png" },
        { "id": "q-07", "term_zh": "多少(錢/量)", "term_target": "how much", "pronunciation": ["/haʊ mʌtʃ/"], "example": {"sentence": "How much?", "translation": "多少錢？"}, "usage_note": "不可數。", "image_file": "how_much.png" },
        { "id": "q-08", "term_zh": "多久(時間)", "term_target": "how long", "pronunciation": ["/haʊ lɔŋ/"], "example": {"sentence": "How long?", "translation": "要多久？"}, "usage_note": "時間長度。", "image_file": "how_long.png" },
        { "id": "q-09", "term_zh": "哪一個", "term_target": "which", "pronunciation": ["/hwɪtʃ/"], "example": {"sentence": "Which one?", "translation": "哪一個？"}, "usage_note": "選擇。", "image_file": "which.png" }
      ]
    },
    {
      "id": "time_place",
      "name": "時間與場所",
      "items": [
        { "id": "tp-01", "term_zh": "今天", "term_target": "today", "pronunciation": ["/təˈdeɪ/"], "example": {"sentence": "Not today.", "translation": "不是今天。"}, "usage_note": "本日。", "image_file": "today.png" },
        { "id": "tp-02", "term_zh": "明天", "term_target": "tomorrow", "pronunciation": ["/təˈmɔroʊ/"], "example": {"sentence": "See you tomorrow.", "translation": "明天見。"}, "usage_note": "隔天。", "image_file": "tomorrow.png" },
        { "id": "tp-03", "term_zh": "昨天", "term_target": "yesterday", "pronunciation": ["/ˈjɛstɚdeɪ/"], "example": {"sentence": "Yesterday morning.", "translation": "昨天早上。"}, "usage_note": "前一天。", "image_file": "yesterday.png" },
        { "id": "tp-04", "term_zh": "這裡", "term_target": "here", "pronunciation": ["/hɪr/"], "example": {"sentence": "Come here.", "translation": "來這。"}, "usage_note": "近處。", "image_file": "here.png" },
        { "id": "tp-05", "term_zh": "那裡", "term_target": "there", "pronunciation": ["/ðɛr/"], "example": {"sentence": "Go there.", "translation": "去那。"}, "usage_note": "遠處。", "image_file": "there.png" },
        { "id": "tp-06", "term_zh": "早上", "term_target": "morning", "pronunciation": ["/ˈmɔrnɪŋ/"], "example": {"sentence": "In the morning.", "translation": "在早上。"}, "usage_note": "上午。", "image_file": "morning.png" },
        { "id": "tp-07", "term_zh": "晚上/夜晚", "term_target": "night", "pronunciation": ["/naɪt/"], "example": {"sentence": "Good night.", "translation": "晚安。"}, "usage_note": "睡前。", "image_file": "night.png" },
        { "id": "tp-08", "term_zh": "前面", "term_target": "in front of", "pronunciation": ["/ɪn frʌnt ʌv/"], "example": {"sentence": "In front of you.", "translation": "在你前面。"}, "usage_note": "前方。", "image_file": "front.png" },
        { "id": "tp-09", "term_zh": "後面", "term_target": "behind", "pronunciation": ["/bɪˈhaɪnd/"], "example": {"sentence": "Behind the door.", "translation": "門後。"}, "usage_note": "後方。", "image_file": "behind.png" },
        { "id": "tp-10", "term_zh": "左邊", "term_target": "left", "pronunciation": ["/lɛft/"], "example": {"sentence": "Turn left.", "translation": "左轉。"}, "usage_note": "左。", "image_file": "left.png" },
        { "id": "tp-11", "term_zh": "右邊", "term_target": "right", "pronunciation": ["/raɪt/"], "example": {"sentence": "Turn right.", "translation": "右轉。"}, "usage_note": "右。", "image_file": "right.png" },
        { "id": "tp-12", "term_zh": "天(日)", "term_target": "day", "pronunciation": ["/deɪ/"], "example": {"sentence": "One day.", "translation": "一天。"}, "usage_note": "日子。", "image_file": "day.png" },
        { "id": "tp-13", "term_zh": "年", "term_target": "year", "pronunciation": ["/jɪr/"], "example": {"sentence": "This year.", "translation": "今年。"}, "usage_note": "年度。", "image_file": "year.png" },
        { "id": "tp-14", "term_zh": "月", "term_target": "month", "pronunciation": ["/mʌnθ/"], "example": {"sentence": "This month.", "translation": "這個月。"}, "usage_note": "月份。", "image_file": "month.png" },
        { "id": "tp-15", "term_zh": "週", "term_target": "week", "pronunciation": ["/wik/"], "example": {"sentence": "Next week.", "translation": "下週。"}, "usage_note": "星期。", "image_file": "week.png" },
        { "id": "tp-16", "term_zh": "下午", "term_target": "afternoon", "pronunciation": ["/ˌæftɚˈnun/"], "example": {"sentence": "Good afternoon.", "translation": "午安。"}, "usage_note": "PM。", "image_file": "afternoon.png" },
        { "id": "tp-17", "term_zh": "中午", "term_target": "noon", "pronunciation": ["/nun/"], "example": {"sentence": "At noon.", "translation": "在中午。"}, "usage_note": "12點。", "image_file": "noon.png" },
        { "id": "tp-18", "term_zh": "旁邊", "term_target": "beside / next to", "pronunciation": ["/bɪˈsaɪd/"], "example": {"sentence": "Sit beside me.", "translation": "坐我旁邊。"}, "usage_note": "側邊。", "image_file": "beside.png" },
        { "id": "tp-19", "term_zh": "對面", "term_target": "across from", "pronunciation": ["/əˈkrɔs frʌm/"], "example": {"sentence": "Across from bank.", "translation": "銀行對面。"}, "usage_note": "對側。", "image_file": "across_from.png" },
        { "id": "tp-20", "term_zh": "春天", "term_target": "spring", "pronunciation": ["/sprɪŋ/"], "example": {"sentence": "Spring is here.", "translation": "春天來了。"}, "usage_note": "季節。", "image_file": "spring.png" },
        { "id": "tp-21", "term_zh": "夏天", "term_target": "summer", "pronunciation": ["/ˈsʌmɚ/"], "example": {"sentence": "Hot summer.", "translation": "炎熱的夏天。"}, "usage_note": "季節。", "image_file": "summer.png" },
        { "id": "tp-22", "term_zh": "秋天", "term_target": "autumn / fall", "pronunciation": ["/ˈɔtəm/"], "example": {"sentence": "Cool autumn.", "translation": "涼爽的秋天。"}, "usage_note": "季節。", "image_file": "autumn.png" },
        { "id": "tp-23", "term_zh": "冬天", "term_target": "winter", "pronunciation": ["/ˈwɪntɚ/"], "example": {"sentence": "Cold winter.", "translation": "寒冷的冬天。"}, "usage_note": "季節。", "image_file": "winter.png" }
      ]
    },
    {
      "id": "numbers",
      "name": "數字",
      "items": [
        { "id": "num-0", "term_zh": "0", "term_target": "zero", "pronunciation": ["/ˈzɪroʊ/"], "example": {"sentence": "Zero point.", "translation": "零分。"}, "usage_note": "零。", "image_file": "zero.png" },
        { "id": "num-1", "term_zh": "1", "term_target": "one", "pronunciation": ["/wʌn/"], "example": {"sentence": "One apple.", "translation": "一顆蘋果。"}, "usage_note": "一。", "image_file": "one.png" },
        { "id": "num-2", "term_zh": "2", "term_target": "two", "pronunciation": ["/tu/"], "example": {"sentence": "Two days.", "translation": "兩天。"}, "usage_note": "二。", "image_file": "two.png" },
        { "id": "num-3", "term_zh": "3", "term_target": "three", "pronunciation": ["/θri/"], "example": {"sentence": "Three people.", "translation": "三人。"}, "usage_note": "咬舌音。", "image_file": "three.png" },
        { "id": "num-4", "term_zh": "4", "term_target": "four", "pronunciation": ["/fɔr/"], "example": {"sentence": "Four seasons.", "translation": "四季。"}, "usage_note": "四。", "image_file": "four.png" },
        { "id": "num-5", "term_zh": "5", "term_target": "five", "pronunciation": ["/faɪv/"], "example": {"sentence": "Five stars.", "translation": "五星。"}, "usage_note": "五。", "image_file": "five.png" },
        { "id": "num-6", "term_zh": "6", "term_target": "six", "pronunciation": ["/sɪks/"], "example": {"sentence": "Six o'clock.", "translation": "六點。"}, "usage_note": "六。", "image_file": "six.png" },
        { "id": "num-7", "term_zh": "7", "term_target": "seven", "pronunciation": ["/ˈsɛvən/"], "example": {"sentence": "Seven days.", "translation": "七天。"}, "usage_note": "七。", "image_file": "seven.png" },
        { "id": "num-8", "term_zh": "8", "term_target": "eight", "pronunciation": ["/eɪt/"], "example": {"sentence": "Eight years old.", "translation": "八歲。"}, "usage_note": "八。", "image_file": "eight.png" },
        { "id": "num-9", "term_zh": "9", "term_target": "nine", "pronunciation": ["/naɪn/"], "example": {"sentence": "Nine PM.", "translation": "晚上九點。"}, "usage_note": "九。", "image_file": "nine.png" },
        { "id": "num-10", "term_zh": "10", "term_target": "ten", "pronunciation": ["/tɛn/"], "example": {"sentence": "Ten dollars.", "translation": "十元。"}, "usage_note": "十。", "image_file": "ten.png" },
        { "id": "num-11", "term_zh": "11", "term_target": "eleven", "pronunciation": ["/ɪˈlɛvən/"], "example": {"sentence": "Eleven o'clock.", "translation": "11點。"}, "usage_note": "十一。", "image_file": "eleven.png" },
        { "id": "num-12", "term_zh": "12", "term_target": "twelve", "pronunciation": ["/twɛlv/"], "example": {"sentence": "Twelve months.", "translation": "12個月。"}, "usage_note": "十二。", "image_file": "twelve.png" },
        { "id": "num-15", "term_zh": "15", "term_target": "fifteen", "pronunciation": ["/fɪfˈtin/"], "example": {"sentence": "Fifteen minutes.", "translation": "15分鐘。"}, "usage_note": "十五。", "image_file": "fifteen.png" },
        { "id": "num-20", "term_zh": "20", "term_target": "twenty", "pronunciation": ["/ˈtwɛnti/"], "example": {"sentence": "Twenty minutes.", "translation": "20分鐘。"}, "usage_note": "二十。", "image_file": "twenty.png" },
        { "id": "num-50", "term_zh": "50", "term_target": "fifty", "pronunciation": ["/ˈfɪfti/"], "example": {"sentence": "Fifty percent.", "translation": "50%。"}, "usage_note": "五十。", "image_file": "fifty.png" },
        { "id": "num-100", "term_zh": "100", "term_target": "one hundred", "pronunciation": ["/wʌn ˈhʌndrəd/"], "example": {"sentence": "100 points.", "translation": "一百分。"}, "usage_note": "百。", "image_file": "hundred.png" },
        { "id": "num-1000", "term_zh": "1000", "term_target": "one thousand", "pronunciation": ["/wʌn ˈθaʊzənd/"], "example": {"sentence": "1000 years.", "translation": "一千年。"}, "usage_note": "千。", "image_file": "thousand.png" },
        { "id": "num-10000", "term_zh": "10000", "term_target": "ten thousand", "pronunciation": ["/tɛn ˈθaʊzənd/"], "example": {"sentence": "Ten thousand dollars.", "translation": "一萬元。"}, "usage_note": "一萬。", "image_file": "ten_thousand.png" }
      ]
    },
    {
      "id": "grammar",
      "name": "基本句型",
      "items": [
        { "id": "g-01", "term_zh": "我是...", "term_target": "I am...", "pronunciation": ["/aɪ æm/"], "example": {"sentence": "I am happy.", "translation": "我很快樂。"}, "usage_note": "狀態。", "image_file": "i_am.png" },
        { "id": "g-02", "term_zh": "我正在...", "term_target": "I am ...ing", "pronunciation": ["/aɪ æm ...ɪŋ/"], "example": {"sentence": "I am eating.", "translation": "我正在吃。"}, "usage_note": "進行式。", "image_file": "ing.png" },
        { "id": "g-03", "term_zh": "我能夠...", "term_target": "I can...", "pronunciation": ["/aɪ kæn/"], "example": {"sentence": "I can swim.", "translation": "我會游泳。"}, "usage_note": "能力。", "image_file": "can.png" },
        { "id": "g-04", "term_zh": "我喜歡做...", "term_target": "I like ...ing", "pronunciation": ["/aɪ laɪk ...ɪŋ/"], "example": {"sentence": "I like reading.", "translation": "我喜歡閱讀。"}, "usage_note": "興趣。", "image_file": "like_ing.png" },
        { "id": "g-05", "term_zh": "我想做...", "term_target": "I want to...", "pronunciation": ["/aɪ wɑnt tu/"], "example": {"sentence": "I want to go.", "translation": "我想走。"}, "usage_note": "慾望。", "image_file": "want_to.png" },
        { "id": "g-06", "term_zh": "你是...嗎?", "term_target": "Are you...?", "pronunciation": ["/ɑr ju/"], "example": {"sentence": "Are you ready?", "translation": "準備好了嗎？"}, "usage_note": "問狀態。", "image_file": "are_you.png" },
        { "id": "g-07", "term_zh": "不要...", "term_target": "Don't...", "pronunciation": ["/doʊnt/"], "example": {"sentence": "Don't touch.", "translation": "不要碰。"}, "usage_note": "禁止。", "image_file": "dont.png" },
        { "id": "g-08", "term_zh": "你有做...嗎?", "term_target": "Do you...?", "pronunciation": ["/du ju/"], "example": {"sentence": "Do you eat spicy food?", "translation": "你吃辣嗎？"}, "usage_note": "問習慣或意願。", "image_file": "do_you.png" },
        { "id": "g-09", "term_zh": "你曾經...嗎?", "term_target": "Have you ever...?", "pronunciation": ["/hæv ju ˈɛvɚ/"], "example": {"sentence": "Have you ever been to Japan?", "translation": "你曾經去過日本嗎？"}, "usage_note": "問經驗。", "image_file": "have_you_ever.png" },
        { "id": "g-10", "term_zh": "你何時做...?", "term_target": "When do you...?", "pronunciation": ["/hwɛn du ju/"], "example": {"sentence": "When do you sleep?", "translation": "你何時睡覺？"}, "usage_note": "問時間點。", "image_file": "when_do_you.png" },
        { "id": "g-11", "term_zh": "你在哪裡做...?", "term_target": "Where do you...?", "pronunciation": ["/wɛr du ju/"], "example": {"sentence": "Where do you live?", "translation": "你住哪裡？"}, "usage_note": "問地點。", "image_file": "where_do_you.png" },
        { "id": "g-12", "term_zh": "你如何做...?", "term_target": "How do you...?", "pronunciation": ["/haʊ du ju/"], "example": {"sentence": "How do you go to school?", "translation": "你怎麼去學校？"}, "usage_note": "問方法。", "image_file": "how_do_you.png" },
        { "id": "g-13", "term_zh": "我不是...", "term_target": "I am not...", "pronunciation": ["/aɪ æm nɑt/"], "example": {"sentence": "I am not tired.", "translation": "我不累。"}, "usage_note": "否定狀態。", "image_file": "i_am_not.png" },
        { "id": "g-14", "term_zh": "我不做...", "term_target": "I don't...", "pronunciation": ["/aɪ doʊnt/"], "example": {"sentence": "I don't smoke.", "translation": "我不抽菸。"}, "usage_note": "否定動作。", "image_file": "i_dont.png" },
        { "id": "g-15", "term_zh": "我不能...", "term_target": "I can't...", "pronunciation": ["/aɪ kænt/"], "example": {"sentence": "I can't swim.", "translation": "我不會游泳。"}, "usage_note": "否定能力。", "image_file": "i_cant.png" },
        { "id": "g-16", "term_zh": "我未曾...", "term_target": "I have never...", "pronunciation": ["/aɪ hæv ˈnɛvɚ/"], "example": {"sentence": "I have never eaten this.", "translation": "我沒吃過這個。"}, "usage_note": "無此經驗。", "image_file": "i_have_never.png" },
        { "id": "g-17", "term_zh": "我不必...", "term_target": "I don't have to...", "pronunciation": ["/aɪ doʊnt hæv tu/"], "example": {"sentence": "I don't have to go.", "translation": "我不必去。"}, "usage_note": "無義務。", "image_file": "i_dont_have_to.png" },
        { "id": "g-18", "term_zh": "如果...的話", "term_target": "If..., ...", "pronunciation": ["/ɪf/"], "example": {"sentence": "If you like, take it.", "translation": "如果你喜歡，拿去吧。"}, "usage_note": "假設條件。", "image_file": "if.png" },
        { "id": "g-19", "term_zh": "當...時", "term_target": "When..., ...", "pronunciation": ["/hwɛn/"], "example": {"sentence": "When I eat, I am happy.", "translation": "當我吃東西時，我很開心。"}, "usage_note": "時間條件。", "image_file": "when_condition.png" },
        { "id": "g-20", "term_zh": "請你...好嗎?", "term_target": "Can you...?", "pronunciation": ["/kæn ju/"], "example": {"sentence": "Can you help me?", "translation": "請你幫我好嗎？"}, "usage_note": "請求。", "image_file": "can_you.png" },
        { "id": "g-21", "term_zh": "我們來做...吧", "term_target": "Let's...", "pronunciation": ["/lɛts/"], "example": {"sentence": "Let's go.", "translation": "我們走吧。"}, "usage_note": "提議。", "image_file": "lets.png" },
        { "id": "g-22", "term_zh": "我認為...", "term_target": "I think...", "pronunciation": ["/aɪ θɪŋk/"], "example": {"sentence": "I think it is good.", "translation": "我認為這很好。"}, "usage_note": "表達想法。", "image_file": "i_think.png" },
        { "id": "g-23", "term_zh": "我必須...", "term_target": "I have to...", "pronunciation": ["/aɪ hæv tu/"], "example": {"sentence": "I have to work.", "translation": "我必須工作。"}, "usage_note": "義務。", "image_file": "i_have_to.png" },
        { "id": "g-24", "term_zh": "做某事是...的", "term_target": "It is ... to ...", "pronunciation": ["/ɪt ɪz ... tu .../"], "example": {"sentence": "It is good to eat.", "translation": "吃東西是很好的。"}, "usage_note": "描述動作。", "image_file": "it_is_to.png" },
        { "id": "g-25", "term_zh": "我可以...嗎?", "term_target": "Can I...?", "pronunciation": ["/kæn aɪ/"], "example": {"sentence": "Can I go?", "translation": "我可以走嗎？"}, "usage_note": "請求許可。", "image_file": "can_i.png" },
        { "id": "g-26", "term_zh": "我比較喜歡...", "term_target": "I prefer...", "pronunciation": ["/aɪ prɪˈfɝ/"], "example": {"sentence": "I prefer tea.", "translation": "我比較喜歡茶。"}, "usage_note": "偏好。", "image_file": "prefer.png" },
        { "id": "g-27", "term_zh": "A比B更...", "term_target": "A is more ... than B", "pronunciation": ["/... mɔr ... ðæn .../"], "example": {"sentence": "This is more expensive than that.", "translation": "這比那個貴。"}, "usage_note": "比較級。", "image_file": "more_than.png" },
        { "id": "g-28", "term_zh": "有(存在)...", "term_target": "There is / There are", "pronunciation": ["/ðɛr ɪz / ðɛr ɑr/"], "example": {"sentence": "There is a dog.", "translation": "那裡有一隻狗。"}, "usage_note": "存在。", "image_file": "there_is.png" },
        { "id": "g-29", "term_zh": "我曾經是/當時是...", "term_target": "I was...", "pronunciation": ["/aɪ wʌz/"], "example": {"sentence": "I was a student.", "translation": "我曾經是學生。"}, "usage_note": "過去狀態。", "image_file": "i_was.png" },
        { "id": "g-30", "term_zh": "我將要...", "term_target": "I will...", "pronunciation": ["/aɪ wɪl/"], "example": {"sentence": "I will go.", "translation": "我將要去。"}, "usage_note": "未來式。", "image_file": "i_will.png" },
        { "id": "g-31", "term_zh": "我曾經做過...", "term_target": "I did...", "pronunciation": ["/aɪ dɪd/"], "example": {"sentence": "I did my homework.", "translation": "我做了功課。"}, "usage_note": "過去動作。", "image_file": "i_did.png" }
      ]
    }
  ]
};