import { AppData } from '../types';

export const spanishData: AppData = 
{
  "meta": {
    "source_language": "zh-TW",
    "target_language": "es-ES",
    "version": "2.3",
    "description": "台灣人快速語言學習 - 西班牙文完整版 (包含所有原始列表單字與完整句型 - IPA 發音版)"
  },
  "categories": [
    {
      "id": "greetings",
      "name": "常用句",
      "items": [
        {
          "id": "greet-001",
          "term_zh": "你好",
          "term_target": "Hola",
          "pronunciation": ["/ˈola/"],
          "example": { "sentence": "Hola, ¿cómo estás?", "translation": "你好，你好嗎？" },
          "usage_note": "H 不發音。最通用的問候。",
          "image_file": "hello.png"
        },
        {
          "id": "greet-002",
          "term_zh": "再見",
          "term_target": "Adiós",
          "pronunciation": ["/aˈdjos/"],
          "example": { "sentence": "Adiós, hasta luego.", "translation": "再見，待會見。" },
          "usage_note": "正式的道別。",
          "image_file": "goodbye.png"
        },
        {
          "id": "greet-003",
          "term_zh": "謝謝你",
          "term_target": "Gracias",
          "pronunciation": ["/ˈgɾasjas/"],
          "example": { "sentence": "Muchas gracias.", "translation": "非常謝謝你。" },
          "usage_note": "通用感謝語。",
          "image_file": "thank_you.png"
        },
        {
          "id": "greet-004",
          "term_zh": "對不起",
          "term_target": "Lo siento",
          "pronunciation": ["/lo ˈsjento/"],
          "example": { "sentence": "Lo siento mucho.", "translation": "我很抱歉。" },
          "usage_note": "表達遺憾或歉意。",
          "image_file": "sorry.png"
        },
        {
          "id": "greet-005",
          "term_zh": "早安",
          "term_target": "Buenos días",
          "pronunciation": ["/ˈbwenos ˈdias/"],
          "example": { "sentence": "Buenos días, mamá.", "translation": "早安，媽。" },
          "usage_note": "中午以前使用。",
          "image_file": "good_morning.png"
        },
        {
          "id": "greet-006",
          "term_zh": "請問... / 借過",
          "term_target": "Perdón / Disculpe",
          "pronunciation": ["/peɾˈdon/", "/disˈkulpe/"],
          "example": { "sentence": "Perdón, ¿dónde está el baño?", "translation": "不好意思，請問廁所在哪？" },
          "usage_note": "借過用 Perdón，正式發問用 Disculpe。",
          "image_file": "excuse_me.png"
        },
        {
          "id": "greet-007",
          "term_zh": "我不懂",
          "term_target": "No entiendo",
          "pronunciation": ["/no enˈtjendo/"],
          "example": { "sentence": "Lo siento, no entiendo español.", "translation": "抱歉，我不懂西班牙文。" },
          "usage_note": "聽不懂時直接說。",
          "image_file": "dont_understand.png"
        },
        {
          "id": "greet-008",
          "term_zh": "這是什麼？",
          "term_target": "¿Qué es esto?",
          "pronunciation": ["/ˈke es ˈesto/"],
          "example": { "sentence": "¿Qué es esto? ¿Es comida?", "translation": "這是什麼？是食物嗎？" },
          "usage_note": "指著東西問。",
          "image_file": "what_is_this.png"
        },
        {
          "id": "greet-009",
          "term_zh": "我想要這個",
          "term_target": "Quiero esto",
          "pronunciation": ["/ˈkjeɾo ˈesto/"],
          "example": { "sentence": "Quiero esto, por favor.", "translation": "麻煩我要這個。" },
          "usage_note": "表達願望。",
          "image_file": "i_want_this.png"
        },
        {
          "id": "greet-010",
          "term_zh": "請給我...",
          "term_target": "Deme..., por favor",
          "pronunciation": ["/ˈdeme... poɾ faˈβoɾ/"],
          "example": { "sentence": "Deme agua, por favor.", "translation": "請給我水。" },
          "usage_note": "點餐時禮貌用法。",
          "image_file": "please_give_me.png"
        },
        {
          "id": "greet-011",
          "term_zh": "廁所在哪裡？",
          "term_target": "¿Dónde está el baño?",
          "pronunciation": ["/ˈdonde esˈta el ˈβaɲo/"],
          "example": { "sentence": "Perdón, ¿dónde está el baño?", "translation": "請問廁所在哪？" },
          "usage_note": "旅遊必備。",
          "image_file": "where_bathroom.png"
        },
        {
          "id": "greet-012",
          "term_zh": "多少錢？",
          "term_target": "¿Cuánto cuesta?",
          "pronunciation": ["/ˈkwanto ˈkwesta/"],
          "example": { "sentence": "¿Cuánto cuesta esto?", "translation": "這個多少錢？" },
          "usage_note": "購物用語。",
          "image_file": "how_much.png"
        },
        {
          "id": "greet-013",
          "term_zh": "請幫我",
          "term_target": "Ayúdeme, por favor",
          "pronunciation": ["/aˈjudeme poɾ faˈβoɾ/"],
          "example": { "sentence": "Ayúdeme con la maleta.", "translation": "請幫我拿行李。" },
          "usage_note": "尋求協助。",
          "image_file": "help_me.png"
        },
        {
          "id": "greet-014",
          "term_zh": "你可以再說一次嗎？",
          "term_target": "¿Puede repetir?",
          "pronunciation": ["/ˈpwede repeˈtiɾ/"],
          "example": { "sentence": "No escuché, ¿puede repetir?", "translation": "沒聽到，能再說一次嗎？" },
          "usage_note": "沒聽清楚時。",
          "image_file": "say_again.png"
        },
        {
          "id": "greet-015",
          "term_zh": "你可以講慢一點嗎？",
          "term_target": "¿Puede hablar más despacio?",
          "pronunciation": ["/ˈpwede aˈβlaɾ mas desˈpasjo/"],
          "example": { "sentence": "Por favor, hable más despacio.", "translation": "拜託請講慢一點。" },
          "usage_note": "Despacio 是「慢」。",
          "image_file": "speak_slowly.png"
        }
      ]
    },
    {
      "id": "pronouns",
      "name": "主詞（代名詞）",
      "items": [
        { "id": "pro-01", "term_zh": "我", "term_target": "Yo", "pronunciation": ["/jo/"], "example": {"sentence": "Yo soy de Taiwán.", "translation": "我來自台灣。"}, "usage_note": "第一人稱。", "image_file": "i.png" },
        { "id": "pro-02", "term_zh": "你", "term_target": "Tú / Usted", "pronunciation": ["/tu/", "/usˈted/"], "example": {"sentence": "¿Tú eres estudiante?", "translation": "你是學生嗎？"}, "usage_note": "Tú(朋友/平輩)，Usted(長輩/正式)。", "image_file": "you.png" },
        { "id": "pro-03", "term_zh": "他", "term_target": "Él", "pronunciation": ["/el/"], "example": {"sentence": "Él es mi padre.", "translation": "他是我爸。"}, "usage_note": "注意有重音符號。", "image_file": "he.png" },
        { "id": "pro-04", "term_zh": "她", "term_target": "Ella", "pronunciation": ["/ˈeja/"], "example": {"sentence": "Ella es bonita.", "translation": "她很漂亮。"}, "usage_note": "LL發音近似「Y」。", "image_file": "she.png" },
        { "id": "pro-05", "term_zh": "我們", "term_target": "Nosotros", "pronunciation": ["/noˈsotɾos/"], "example": {"sentence": "Nosotros somos familia.", "translation": "我們是家人。"}, "usage_note": "若全是女生用 Nosotras。", "image_file": "we.png" },
        { "id": "pro-06", "term_zh": "他們", "term_target": "Ellos", "pronunciation": ["/ˈejos/"], "example": {"sentence": "Ellos comen.", "translation": "他們在吃。"}, "usage_note": "全是女生用 Ellas。", "image_file": "they.png" },
        { "id": "pro-07", "term_zh": "這個", "term_target": "Esto / Este / Esta", "pronunciation": ["/ˈesto/"], "example": {"sentence": "Esto es mío.", "translation": "這是我的。"}, "usage_note": "Esto(中性/未知事物)，Este(陽性)，Esta(陰性)。", "image_file": "this.png" },
        { "id": "pro-08", "term_zh": "那個/它", "term_target": "Eso / Ese / Esa", "pronunciation": ["/ˈeso/"], "example": {"sentence": "¿Qué es eso?", "translation": "那是什麼？"}, "usage_note": "指對方那邊的東西。", "image_file": "that.png" },
        { "id": "pro-09", "term_zh": "他的", "term_target": "Su", "pronunciation": ["/su/"], "example": {"sentence": "Su coche.", "translation": "他的車。"}, "usage_note": "所有格。", "image_file": "his.png" },
        { "id": "pro-10", "term_zh": "她的", "term_target": "Su", "pronunciation": ["/su/"], "example": {"sentence": "Su bolsa.", "translation": "她的包包。"}, "usage_note": "與「他的」同形。", "image_file": "her.png" },
        { "id": "pro-11", "term_zh": "你的", "term_target": "Tu", "pronunciation": ["/tu/"], "example": {"sentence": "Tu nombre.", "translation": "你的名字。"}, "usage_note": "無重音符號。", "image_file": "your.png" },
        { "id": "pro-12", "term_zh": "他們的", "term_target": "Su", "pronunciation": ["/su/"], "example": {"sentence": "Su casa.", "translation": "他們的家。"}, "usage_note": "複數也是 Su (接單數名詞時)。", "image_file": "their.png" },
        { "id": "pro-13", "term_zh": "我們的", "term_target": "Nuestro", "pronunciation": ["/ˈnwestɾo/"], "example": {"sentence": "Nuestro amigo.", "translation": "我們的朋友。"}, "usage_note": "需隨名詞性別變化 (Nuestra)。", "image_file": "our.png" },
        { "id": "pro-14", "term_zh": "這些", "term_target": "Estos", "pronunciation": ["/ˈestos/"], "example": {"sentence": "Estos libros.", "translation": "這些書。"}, "usage_note": "近處複數。", "image_file": "these.png" },
        { "id": "pro-15", "term_zh": "那些", "term_target": "Esos", "pronunciation": ["/ˈesos/"], "example": {"sentence": "Esos pájaros.", "translation": "那些鳥。"}, "usage_note": "遠處複數。", "image_file": "those.png" }
      ]
    },
    {
      "id": "verbs",
      "name": "動詞",
      "items": [
        { "id": "v-01", "term_zh": "是", "term_target": "Ser / Estar", "pronunciation": ["/seɾ/", "/esˈtaɾ/"], "example": {"sentence": "Soy estudiante. Estoy feliz.", "translation": "我是學生。我很快樂。"}, "usage_note": "Ser(本質/身分)，Estar(狀態/位置)。", "image_file": "be.png" },
        { "id": "v-02", "term_zh": "有", "term_target": "Tener / Haber", "pronunciation": ["/teˈneɾ/", "/aˈβeɾ/"], "example": {"sentence": "Tengo dinero. Hay un perro.", "translation": "我有錢。有一隻狗(Hay)。"}, "usage_note": "Tener(擁有)，Haber(存在/助動詞)。", "image_file": "have.png" },
        { "id": "v-03", "term_zh": "去", "term_target": "Ir", "pronunciation": ["/iɾ/"], "example": {"sentence": "Voy a casa.", "translation": "我要回家。", }, "usage_note": "不規則動詞。", "image_file": "go.png" },
        { "id": "v-04", "term_zh": "做", "term_target": "Hacer", "pronunciation": ["/aˈθeɾ/"], "example": {"sentence": "Hacer la tarea.", "translation": "做作業。"}, "usage_note": "H 不發音。", "image_file": "do.png" },
        { "id": "v-05", "term_zh": "說", "term_target": "Decir", "pronunciation": ["/deˈθiɾ/"], "example": {"sentence": "Di hola.", "translation": "說你好。"}, "usage_note": "說出內容。", "image_file": "say.png" },
        { "id": "v-06", "term_zh": "知道", "term_target": "Saber / Conocer", "pronunciation": ["/saˈβeɾ/", "/konoˈθeɾ/"], "example": {"sentence": "No sé. Conozco a Juan.", "translation": "我不知道。我認識胡安。"}, "usage_note": "Saber(知識)，Conocer(認識人/地)。", "image_file": "know.png" },
        { "id": "v-07", "term_zh": "想/思考", "term_target": "Pensar", "pronunciation": ["/penˈsaɾ/"], "example": {"sentence": "Pienso que sí.", "translation": "我想是的。"}, "usage_note": "思考。", "image_file": "think.png" },
        { "id": "v-08", "term_zh": "看見", "term_target": "Ver", "pronunciation": ["/beɾ/"], "example": {"sentence": "Veo un pájaro.", "translation": "我看見一隻鳥。"}, "usage_note": "看。", "image_file": "see.png" },
        { "id": "v-09", "term_zh": "製作", "term_target": "Hacer", "pronunciation": ["/aˈθeɾ/"], "example": {"sentence": "Hacer café.", "translation": "煮咖啡。"}, "usage_note": "同「做」。", "image_file": "make.png" },
        { "id": "v-10", "term_zh": "來", "term_target": "Venir", "pronunciation": ["/beˈniɾ/"], "example": {"sentence": "Ven aquí.", "translation": "來這裡。"}, "usage_note": "過來。", "image_file": "come.png" },
        { "id": "v-11", "term_zh": "需要", "term_target": "Necesitar", "pronunciation": ["/neθesiˈtaɾ/"], "example": {"sentence": "Necesito agua.", "translation": "我需要水。"}, "usage_note": "需要。", "image_file": "need.png" },
        { "id": "v-12", "term_zh": "使用", "term_target": "Usar", "pronunciation": ["/uˈsaɾ/"], "example": {"sentence": "Usar un bolígrafo.", "translation": "用原子筆。"}, "usage_note": "使用。", "image_file": "use.png" },
        { "id": "v-13", "term_zh": "找到", "term_target": "Encontrar", "pronunciation": ["/enkonˈtɾaɾ/"], "example": {"sentence": "Encontrar trabajo.", "translation": "找工作。"}, "usage_note": "發現/找到。", "image_file": "find.png" },
        { "id": "v-14", "term_zh": "給", "term_target": "Dar", "pronunciation": ["/daɾ/"], "example": {"sentence": "Dame eso.", "translation": "給我那個。"}, "usage_note": "給予。", "image_file": "give.png" },
        { "id": "v-15", "term_zh": "告訴", "term_target": "Contar / Decir", "pronunciation": ["/konˈtaɾ/", "/deˈθiɾ/"], "example": {"sentence": "Cuéntame.", "translation": "告訴我(故事/經過)。"}, "usage_note": "告知。", "image_file": "tell.png" },
        { "id": "v-16", "term_zh": "工作", "term_target": "Trabajar", "pronunciation": ["/tɾaβaˈxaɾ/"], "example": {"sentence": "Trabajo aquí.", "translation": "我在這工作。"}, "usage_note": "勞動。", "image_file": "work.png" },
        { "id": "v-17", "term_zh": "喜歡", "term_target": "Gustar", "pronunciation": ["/gusˈtaɾ/"], "example": {"sentence": "Me gusta.", "translation": "我喜歡 (字面:它使我喜歡)。"}, "usage_note": "用法特殊：Me gusta (單數), Me gustan (複數)。", "image_file": "like.png" },
        { "id": "v-18", "term_zh": "起床/醒來", "term_target": "Levantarse", "pronunciation": ["/leβanˈtaɾse/"], "example": {"sentence": "Me levanto a las 7.", "translation": "我七點起床。"}, "usage_note": "反身動詞。", "image_file": "wake_up.png" },
        { "id": "v-19", "term_zh": "說話", "term_target": "Hablar", "pronunciation": ["/aˈβlaɾ/"], "example": {"sentence": "Hablar español.", "translation": "說西班牙文。"}, "usage_note": "講語言。", "image_file": "speak.png" },
        { "id": "v-20", "term_zh": "聽見", "term_target": "Oír / Escuchar", "pronunciation": ["/oˈiɾ/", "/eskuˈtʃaɾ/"], "example": {"sentence": "¿Me oyes?", "translation": "聽得到我嗎？"}, "usage_note": "Oír(聽見), Escuchar(聆聽)。", "image_file": "hear.png" },
        { "id": "v-21", "term_zh": "寫", "term_target": "Escribir", "pronunciation": ["/eskɾiˈβiɾ/"], "example": {"sentence": "Escribir un nombre.", "translation": "寫名字。"}, "usage_note": "書寫。", "image_file": "write.png" },
        { "id": "v-22", "term_zh": "閱讀", "term_target": "Leer", "pronunciation": ["/leˈeɾ/"], "example": {"sentence": "Leer un libro.", "translation": "看書。"}, "usage_note": "閱讀。", "image_file": "read.png" },
        { "id": "v-23", "term_zh": "等待", "term_target": "Esperar", "pronunciation": ["/espeˈɾaɾ/"], "example": {"sentence": "Espérame.", "translation": "等我。"}, "usage_note": "也有「希望」的意思。", "image_file": "wait.png" },
        { "id": "v-24", "term_zh": "嘗試", "term_target": "Probar / Intentar", "pronunciation": ["/pɾoˈβaɾ/", "/intenˈtaɾ/"], "example": {"sentence": "Prueba esto.", "translation": "試試這個(食物)。"}, "usage_note": "Probar(試吃/試穿), Intentar(企圖)。", "image_file": "try.png" },
        { "id": "v-25", "term_zh": "付錢", "term_target": "Pagar", "pronunciation": ["/paˈɣaɾ/"], "example": {"sentence": "Pagar la cuenta.", "translation": "付帳單。"}, "usage_note": "支付。", "image_file": "pay.png" },
        { "id": "v-26", "term_zh": "住", "term_target": "Vivir", "pronunciation": ["/biˈβiɾ/"], "example": {"sentence": "Vivo en Taipéi.", "translation": "我住台北。"}, "usage_note": "居住。", "image_file": "live.png" },
        { "id": "v-27", "term_zh": "走路", "term_target": "Caminar / Andar", "pronunciation": ["/kamiˈnaɾ/", "/anˈdaɾ/"], "example": {"sentence": "Caminar a casa.", "translation": "走路回家。"}, "usage_note": "步行。", "image_file": "walk.png" },
        { "id": "v-28", "term_zh": "打開", "term_target": "Abrir", "pronunciation": ["/aˈβɾiɾ/"], "example": {"sentence": "Abrir la puerta.", "translation": "開門。"}, "usage_note": "開啟。", "image_file": "open.png" },
        { "id": "v-29", "term_zh": "關閉", "term_target": "Cerrar", "pronunciation": ["/θeˈraɾ/"], "example": {"sentence": "Cerrar la ventana.", "translation": "關窗。"}, "usage_note": "關上。", "image_file": "close.png" },
        { "id": "v-30", "term_zh": "幫助", "term_target": "Ayudar", "pronunciation": ["/aʝuˈdaɾ/"], "example": {"sentence": "Ayúdame.", "translation": "幫我。"}, "usage_note": "協助。", "image_file": "help.png" },
        { "id": "v-31", "term_zh": "吃", "term_target": "Comer", "pronunciation": ["/koˈmeɾ/"], "example": {"sentence": "Comer almuerzo.", "translation": "吃午餐。"}, "usage_note": "進食。", "image_file": "eat.png" },
        { "id": "v-32", "term_zh": "睡覺", "term_target": "Dormir", "pronunciation": ["/doɾˈmiɾ/"], "example": {"sentence": "Me voy a dormir.", "translation": "我要去睡覺了。"}, "usage_note": "睡眠。", "image_file": "sleep.png" },
        { "id": "v-33", "term_zh": "買", "term_target": "Comprar", "pronunciation": ["/komˈpɾaɾ/"], "example": {"sentence": "Comprar un coche.", "translation": "買車。"}, "usage_note": "購買。", "image_file": "buy.png" },
        { "id": "v-34", "term_zh": "乘坐/拿", "term_target": "Tomar / Coger", "pronunciation": ["/toˈmaɾ/", "/koˈxeɾ/"], "example": {"sentence": "Tomar un autobús.", "translation": "搭公車。"}, "usage_note": "Tomar(通用)，Coger(在某些拉美國家有不雅含義，慎用)。", "image_file": "take.png" },
        { "id": "v-35", "term_zh": "得到/拿", "term_target": "Conseguir / Obtener", "pronunciation": ["/konseˈɣiɾ/", "/obteˈneɾ/"], "example": {"sentence": "Conseguir trabajo.", "translation": "找到(得到)工作。"}, "usage_note": "獲得。", "image_file": "get.png" },
        { "id": "v-36", "term_zh": "選擇", "term_target": "Elegir", "pronunciation": ["/eleˈxiɾ/"], "example": {"sentence": "Elige uno.", "translation": "選一個。"}, "usage_note": "挑選。", "image_file": "choose.png" },
        { "id": "v-37", "term_zh": "進入", "term_target": "Entrar", "pronunciation": ["/enˈtɾaɾ/"], "example": {"sentence": "Entrar en la casa.", "translation": "進屋。"}, "usage_note": "進入。", "image_file": "enter.png" },
        { "id": "v-38", "term_zh": "到達", "term_target": "Llegar", "pronunciation": ["/ʎeˈɣaɾ/"], "example": {"sentence": "Llegar a tiempo.", "translation": "準時到達。"}, "usage_note": "抵達。", "image_file": "arrive.png" },
        { "id": "v-39", "term_zh": "帶來", "term_target": "Traer", "pronunciation": ["/tɾaˈeɾ/"], "example": {"sentence": "Trae agua.", "translation": "帶水來。"}, "usage_note": "攜帶至此。", "image_file": "bring.png" },
        { "id": "v-40", "term_zh": "變成", "term_target": "Convertirse / Llegar a ser", "pronunciation": ["/kombeɾˈtiɾse/", "/ʎeˈɣaɾ a seɾ/"], "example": {"sentence": "Se convirtió en rey.", "translation": "他變成了國王。"}, "usage_note": "變化。", "image_file": "become.png" },
        { "id": "v-41", "term_zh": "開始", "term_target": "Empezar / Comenzar", "pronunciation": ["/empeˈθaɾ/", "/komenˈθaɾ/"], "example": {"sentence": "Empezar ahora.", "translation": "現在開始。"}, "usage_note": "開始。", "image_file": "start.png" },
        { "id": "v-42", "term_zh": "結束", "term_target": "Terminar", "pronunciation": ["/teɾmiˈnaɾ/"], "example": {"sentence": "Terminar el trabajo.", "translation": "工作結束。"}, "usage_note": "完成。", "image_file": "finish.png" },
        { "id": "v-43", "term_zh": "停止", "term_target": "Parar", "pronunciation": ["/paˈɾaɾ/"], "example": {"sentence": "Para aquí.", "translation": "停在這裡。"}, "usage_note": "停止。", "image_file": "stop.png" },
        { "id": "v-44", "term_zh": "記住", "term_target": "Recordar", "pronunciation": ["/rekoɾˈdaɾ/"], "example": {"sentence": "Recuérdame.", "translation": "記得我。"}, "usage_note": "記憶。", "image_file": "remember.png" },
        { "id": "v-45", "term_zh": "見面", "term_target": "Encontrarse / Quedar", "pronunciation": ["/enkonˈtɾaɾse/", "/keˈdaɾ/"], "example": {"sentence": "Quedar con amigos.", "translation": "跟朋友碰面。"}, "usage_note": "會面。", "image_file": "meet.png" },
        { "id": "v-46", "term_zh": "放", "term_target": "Poner", "pronunciation": ["/poˈneɾ/"], "example": {"sentence": "Ponlo aquí.", "translation": "放這裡。"}, "usage_note": "放置。", "image_file": "put.png" },
        { "id": "v-47", "term_zh": "寄送", "term_target": "Enviar", "pronunciation": ["/emˈbjaɾ/"], "example": {"sentence": "Enviar un correo.", "translation": "寄信。"}, "usage_note": "傳送。", "image_file": "send.png" },
        { "id": "v-48", "term_zh": "開車", "term_target": "Conducir / Manejar", "pronunciation": ["/konduˈθiɾ/", "/maneˈxaɾ/"], "example": {"sentence": "Conducir un coche.", "translation": "開車。"}, "usage_note": "Manejar(拉美常用)。", "image_file": "drive.png" },
        { "id": "v-49", "term_zh": "讀書", "term_target": "Estudiar", "pronunciation": ["/estuˈdjaɾ/"], "example": {"sentence": "Estudiar español.", "translation": "讀西班牙文。"}, "usage_note": "學習。", "image_file": "study.png" },
        { "id": "v-50", "term_zh": "回去", "term_target": "Volver / Regresar", "pronunciation": ["/bolˈbeɾ/", "/reɣɾeˈsaɾ/"], "example": {"sentence": "Volver a casa.", "translation": "回家。"}, "usage_note": "歸返。", "image_file": "go_back.png" }
      ]
    },
    {
      "id": "adjectives",
      "name": "形容詞",
      "items": [
        { "id": "adj-01", "term_zh": "好的", "term_target": "Bueno/a", "pronunciation": ["/ˈbweno/"], "example": {"sentence": "Buen trabajo.", "translation": "做得好。"}, "usage_note": "放在陽性單數名詞前去o變成Buen。", "image_file": "good.png" },
        { "id": "adj-02", "term_zh": "壞的", "term_target": "Malo/a", "pronunciation": ["/ˈmalo/"], "example": {"sentence": "Mal día.", "translation": "壞的一天。"}, "usage_note": "放在陽性單數名詞前去o變成Mal。", "image_file": "bad.png" },
        { "id": "adj-03", "term_zh": "新的", "term_target": "Nuevo/a", "pronunciation": ["/ˈnweβo/"], "example": {"sentence": "Teléfono nuevo.", "translation": "新手機。"}, "usage_note": "全新。", "image_file": "new.png" },
        { "id": "adj-04", "term_zh": "大的", "term_target": "Grande", "pronunciation": ["/ˈgɾande/"], "example": {"sentence": "Casa grande.", "translation": "大房子。"}, "usage_note": "單數皆為Grande。前置時變Gran。", "image_file": "big.png" },
        { "id": "adj-05", "term_zh": "小的", "term_target": "Pequeño/a", "pronunciation": ["/peˈkeɲo/"], "example": {"sentence": "Gato pequeño.", "translation": "小貓。"}, "usage_note": "體積小。", "image_file": "small.png" },
        { "id": "adj-06", "term_zh": "熱的", "term_target": "Caliente / Caluroso", "pronunciation": ["/kaˈljente/", "/kaluˈɾoso/"], "example": {"sentence": "Agua caliente.", "translation": "熱水。"}, "usage_note": "Caliente(物品)，Caluroso(天氣)。", "image_file": "hot.png" },
        { "id": "adj-07", "term_zh": "冷的", "term_target": "Frío/a", "pronunciation": ["/ˈfɾio/"], "example": {"sentence": "Bebida fría.", "translation": "冷飲。"}, "usage_note": "低溫。", "image_file": "cold.png" },
        { "id": "adj-08", "term_zh": "簡單的", "term_target": "Fácil", "pronunciation": ["/ˈfaθil/"], "example": {"sentence": "Es fácil.", "translation": "很簡單。"}, "usage_note": "容易。", "image_file": "easy.png" },
        { "id": "adj-09", "term_zh": "困難的", "term_target": "Difícil", "pronunciation": ["/diˈfiθil/"], "example": {"sentence": "Es difícil.", "translation": "很難。"}, "usage_note": "難。", "image_file": "difficult.png" },
        { "id": "adj-10", "term_zh": "美味的", "term_target": "Delicioso/a / Rico/a", "pronunciation": ["/deliˈθjoso/", "/ˈriko/"], "example": {"sentence": "Comida rica.", "translation": "好吃的食物。"}, "usage_note": "Rico 也可指有錢。", "image_file": "delicious.png" },
        { "id": "adj-11", "term_zh": "忙碌的", "term_target": "Ocupado/a", "pronunciation": ["/okuˈpado/"], "example": {"sentence": "Estoy ocupado.", "translation": "我很忙。"}, "usage_note": "沒空。", "image_file": "busy.png" },
        { "id": "adj-12", "term_zh": "疲累的", "term_target": "Cansado/a", "pronunciation": ["/kanˈsado/"], "example": {"sentence": "Estoy cansado.", "translation": "我累了。"}, "usage_note": "狀態。", "image_file": "tired.png" },
        { "id": "adj-13", "term_zh": "快樂的", "term_target": "Feliz / Contento/a", "pronunciation": ["/feˈliθ/", "/konˈtento/"], "example": {"sentence": "Feliz cumpleaños.", "translation": "生日快樂。"}, "usage_note": "Feliz 不分陰陽。", "image_file": "happy.png" },
        { "id": "adj-14", "term_zh": "悲傷的", "term_target": "Triste", "pronunciation": ["/ˈtɾiste/"], "example": {"sentence": "Historia triste.", "translation": "悲傷的故事。"}, "usage_note": "不分陰陽。", "image_file": "sad.png" },
        { "id": "adj-15", "term_zh": "乾淨的", "term_target": "Limpio/a", "pronunciation": ["/ˈlimpjo/"], "example": {"sentence": "Habitación limpia.", "translation": "乾淨的房間。"}, "usage_note": "無髒汙。", "image_file": "clean.png" },
        { "id": "adj-16", "term_zh": "髒的", "term_target": "Sucio/a", "pronunciation": ["/ˈsuθjo/"], "example": {"sentence": "Manos sucias.", "translation": "髒手。"}, "usage_note": "不乾淨。", "image_file": "dirty.png" },
        { "id": "adj-17", "term_zh": "便宜的", "term_target": "Barato/a", "pronunciation": ["/baˈɾato/"], "example": {"sentence": "Es barato.", "translation": "很便宜。"}, "usage_note": "價格低。", "image_file": "cheap.png" },
        { "id": "adj-18", "term_zh": "昂貴的", "term_target": "Caro/a", "pronunciation": ["/ˈkaɾo/"], "example": {"sentence": "Demasiado caro.", "translation": "太貴了。"}, "usage_note": "價格高。", "image_file": "expensive.png" },
        { "id": "adj-19", "term_zh": "重要的", "term_target": "Importante", "pronunciation": ["/impoɾˈtante/"], "example": {"sentence": "Reunión importante.", "translation": "重要會議。"}, "usage_note": "不分陰陽。", "image_file": "important.png" },
        { "id": "adj-20", "term_zh": "相同的", "term_target": "Mismo/a", "pronunciation": ["/ˈmismo/"], "example": {"sentence": "El mismo lugar.", "translation": "同個地方。"}, "usage_note": "一樣。", "image_file": "same.png" },
        { "id": "adj-21", "term_zh": "第一的", "term_target": "Primero/a", "pronunciation": ["/pɾiˈmeɾo/"], "example": {"sentence": "Primera vez.", "translation": "第一次。"}, "usage_note": "順序。陽性單數前變 Primer。", "image_file": "first.png" },
        { "id": "adj-22", "term_zh": "上一個", "term_target": "Pasado/a / Anterior", "pronunciation": ["/paˈsado/", "/anteˈɾjoɾ/"], "example": {"sentence": "La semana pasada.", "translation": "上週。"}, "usage_note": "過去的。", "image_file": "last.png" },
        { "id": "adj-23", "term_zh": "下一個", "term_target": "Próximo/a / Siguiente", "pronunciation": ["/ˈpɾoksimo/", "/siˈɣjente/"], "example": {"sentence": "La próxima estación.", "translation": "下一站。"}, "usage_note": "接下來。", "image_file": "next.png" },
        { "id": "adj-24", "term_zh": "長的", "term_target": "Largo/a", "pronunciation": ["/ˈlaɾɣo/"], "example": {"sentence": "Pelo largo.", "translation": "長髮。"}, "usage_note": "長度。", "image_file": "long.png" },
        { "id": "adj-25", "term_zh": "多的", "term_target": "Mucho/a", "pronunciation": ["/ˈmutʃo/"], "example": {"sentence": "Mucha gente.", "translation": "很多人。"}, "usage_note": "數量多。", "image_file": "many.png" },
        { "id": "adj-26", "term_zh": "高的", "term_target": "Alto/a", "pronunciation": ["/ˈalto/"], "example": {"sentence": "Edificio alto.", "translation": "高樓。"}, "usage_note": "高度。", "image_file": "tall.png" },
        { "id": "adj-27", "term_zh": "年輕的", "term_target": "Joven", "pronunciation": ["/ˈxoβen/"], "example": {"sentence": "Hombre joven.", "translation": "年輕人。"}, "usage_note": "不分陰陽。", "image_file": "young.png" },
        { "id": "adj-28", "term_zh": "老的/舊的", "term_target": "Viejo/a", "pronunciation": ["/ˈbjexo/"], "example": {"sentence": "Libro viejo.", "translation": "舊書。"}, "usage_note": "人或物皆可，形容人有時較不禮貌，可用Mayor。", "image_file": "old.png" },
        { "id": "adj-29", "term_zh": "近的", "term_target": "Cerca", "pronunciation": ["/ˈθeɾka/"], "example": {"sentence": "Está cerca.", "translation": "很近。"}, "usage_note": "距離近(副詞用法常見)。", "image_file": "near.png" },
        { "id": "adj-30", "term_zh": "遠的", "term_target": "Lejos", "pronunciation": ["/ˈlexos/"], "example": {"sentence": "Está lejos.", "translation": "很遠。"}, "usage_note": "距離遠(副詞用法常見)。", "image_file": "far.png" },
        { "id": "adj-31", "term_zh": "快的", "term_target": "Rápido/a", "pronunciation": ["/ˈrapiðo/"], "example": {"sentence": "Coche rápido.", "translation": "快車。"}, "usage_note": "速度快。", "image_file": "fast.png" },
        { "id": "adj-32", "term_zh": "慢的", "term_target": "Lento/a", "pronunciation": ["/ˈlento/"], "example": {"sentence": "Internet lento.", "translation": "網路慢。"}, "usage_note": "速度慢。", "image_file": "slow.png" },
        { "id": "adj-33", "term_zh": "正確的", "term_target": "Correcto/a", "pronunciation": ["/koˈrekto/"], "example": {"sentence": "Respuesta correcta.", "translation": "正確答案。"}, "usage_note": "對的。", "image_file": "correct.png" },
        { "id": "adj-34", "term_zh": "錯誤的", "term_target": "Incorrecto/a", "pronunciation": ["/inkoˈrekto/"], "example": {"sentence": "Es incorrecto.", "translation": "是錯的。"}, "usage_note": "不對。", "image_file": "wrong.png" },
        { "id": "adj-35", "term_zh": "不同的", "term_target": "Diferente", "pronunciation": ["/difeˈɾente/"], "example": {"sentence": "Color diferente.", "translation": "不同顏色。"}, "usage_note": "不分陰陽。", "image_file": "different.png" },
        { "id": "adj-36", "term_zh": "真的", "term_target": "Real / Verdadero/a", "pronunciation": ["/reˈal/", "/beɾdaˈdeɾo/"], "example": {"sentence": "Amor verdadero.", "translation": "真愛。"}, "usage_note": "真實。", "image_file": "real.png" },
        { "id": "adj-37", "term_zh": "有趣的", "term_target": "Interesante", "pronunciation": ["/inteɾeˈsante/"], "example": {"sentence": "Libro interesante.", "translation": "有趣的書。"}, "usage_note": "有意思。", "image_file": "interesting.png" },
        { "id": "adj-38", "term_zh": "飢餓的", "term_target": "Hambriento/a", "pronunciation": ["/amˈbɾjento/"], "example": {"sentence": "Tengo hambre.", "translation": "我餓了(我有飢餓)。"}, "usage_note": "西文常用 Tener hambre (有飢餓)。", "image_file": "hungry.png" },
        { "id": "adj-39", "term_zh": "有名的", "term_target": "Famoso/a", "pronunciation": ["/faˈmoso/"], "example": {"sentence": "Actor famoso.", "translation": "知名演員。"}, "usage_note": "知名。", "image_file": "famous.png" },
        { "id": "adj-40", "term_zh": "外國的", "term_target": "Extranjero/a", "pronunciation": ["/extɾaŋˈxeɾo/"], "example": {"sentence": "País extranjero.", "translation": "外國。"}, "usage_note": "國外。", "image_file": "foreign.png" },
        { "id": "adj-41", "term_zh": "聰明的", "term_target": "Inteligente", "pronunciation": ["/inteliˈxente/"], "example": {"sentence": "Chico inteligente.", "translation": "聰明的男孩。"}, "usage_note": "不分陰陽。", "image_file": "intelligent.png" },
        { "id": "adj-42", "term_zh": "危險的", "term_target": "Peligroso/a", "pronunciation": ["/peliˈɣɾoso/"], "example": {"sentence": "Es peligroso.", "translation": "這很危險。"}, "usage_note": "警示。", "image_file": "dangerous.png" },
        { "id": "adj-43", "term_zh": "仁慈的", "term_target": "Amable", "pronunciation": ["/aˈmaβle/"], "example": {"sentence": "Persona amable.", "translation": "親切的人。"}, "usage_note": "不分陰陽。", "image_file": "kind.png" },
        { "id": "adj-44", "term_zh": "所有的", "term_target": "Todo/a", "pronunciation": ["/ˈtodo/"], "example": {"sentence": "Todo el día.", "translation": "整天。"}, "usage_note": "全部。", "image_file": "every.png" },
        { "id": "adj-45", "term_zh": "喜愛的", "term_target": "Favorito/a", "pronunciation": ["/faβoˈɾito/"], "example": {"sentence": "Comida favorita.", "translation": "最愛的食物。"}, "usage_note": "中意。", "image_file": "favorite.png" }
      ]
    },
    {
      "id": "nouns",
      "name": "名詞",
      "items": [
        { "id": "n-01", "term_zh": "水", "term_target": "Agua", "pronunciation": ["/ˈaɣwa/"], "example": {"sentence": "Beber agua.", "translation": "喝水。"}, "usage_note": "陰性名詞，但單數前用 El agua。", "image_file": "water.png" },
        { "id": "n-02", "term_zh": "食物", "term_target": "Comida", "pronunciation": ["/koˈmiða/"], "example": {"sentence": "Comida rica.", "translation": "好吃的食物。"}, "usage_note": "吃的東西。", "image_file": "food.png" },
        { "id": "n-03", "term_zh": "錢", "term_target": "Dinero", "pronunciation": ["/diˈneɾo/"], "example": {"sentence": "No tengo dinero.", "translation": "沒錢。"}, "usage_note": "不可數。", "image_file": "money.png" },
        { "id": "n-04", "term_zh": "廁所", "term_target": "Baño", "pronunciation": ["/ˈbaɲo/"], "example": {"sentence": "Ir al baño.", "translation": "去廁所。"}, "usage_note": "衛生間。", "image_file": "bathroom.png" },
        { "id": "n-05", "term_zh": "人", "term_target": "Persona / Gente", "pronunciation": ["/peɾˈsona/", "/ˈxente/"], "example": {"sentence": "Mucha gente.", "translation": "很多人。"}, "usage_note": "Persona(單數/可數)，Gente(集合名詞)。", "image_file": "people.png" },
        { "id": "n-06", "term_zh": "時間", "term_target": "Tiempo", "pronunciation": ["/ˈtjempo/"], "example": {"sentence": "¿Qué hora es?", "translation": "幾點了？(問時刻用Hora)。"}, "usage_note": "Tiempo(長度/天氣)，Hora(時刻)。", "image_file": "time.png" },
        { "id": "n-07", "term_zh": "朋友", "term_target": "Amigo/a", "pronunciation": ["/aˈmiɣo/"], "example": {"sentence": "Mi amigo.", "translation": "我朋友。"}, "usage_note": "友人。", "image_file": "friend.png" },
        { "id": "n-08", "term_zh": "家庭", "term_target": "Familia", "pronunciation": ["/faˈmilja/"], "example": {"sentence": "Familia grande.", "translation": "大家庭。"}, "usage_note": "家人。", "image_file": "family.png" },
        { "id": "n-09", "term_zh": "手機", "term_target": "Móvil / Celular", "pronunciation": ["/ˈmoβil/", "/θeluˈlaɾ/"], "example": {"sentence": "Mi móvil.", "translation": "我手機。"}, "usage_note": "西班牙用Móvil，拉美用Celular。", "image_file": "phone.png" },
        { "id": "n-10", "term_zh": "車", "term_target": "Coche / Carro", "pronunciation": ["/ˈkotʃe/", "/ˈkaro/"], "example": {"sentence": "Conducir un coche.", "translation": "開車。"}, "usage_note": "西班牙用Coche，拉美用Carro/Auto。", "image_file": "car.png" },
        { "id": "n-11", "term_zh": "巴士", "term_target": "Autobús", "pronunciation": ["/autoˈβus/"], "example": {"sentence": "Tomar el autobús.", "translation": "搭公車。"}, "usage_note": "公車。", "image_file": "bus.png" },
        { "id": "n-12", "term_zh": "火車", "term_target": "Tren", "pronunciation": ["/tɾen/"], "example": {"sentence": "Viajar en tren.", "translation": "搭火車旅行。"}, "usage_note": "列車。", "image_file": "train.png" },
        { "id": "n-13", "term_zh": "捷運/地鐵", "term_target": "Metro", "pronunciation": ["/ˈmetɾo/"], "example": {"sentence": "Estación de metro.", "translation": "地鐵站。"}, "usage_note": "地下鐵。", "image_file": "subway.png" },
        { "id": "n-14", "term_zh": "車站", "term_target": "Estación", "pronunciation": ["/estaˈθjon/"], "example": {"sentence": "Estación de tren.", "translation": "火車站。"}, "usage_note": "站點。", "image_file": "station.png" },
        { "id": "n-15", "term_zh": "機場", "term_target": "Aeropuerto", "pronunciation": ["/aeɾoˈpweɾto/"], "example": {"sentence": "Ir al aeropuerto.", "translation": "去機場。"}, "usage_note": "搭飛機處。", "image_file": "airport.png" },
        { "id": "n-16", "term_zh": "票", "term_target": "Billete / Boleto", "pronunciation": ["/biˈʎete/", "/boˈleto/"], "example": {"sentence": "Un billete, por favor.", "translation": "請給我一張票。"}, "usage_note": "西班牙用Billete，拉美用Boleto。", "image_file": "ticket.png" },
        { "id": "n-17", "term_zh": "飯店", "term_target": "Hotel", "pronunciation": ["/oˈtel/"], "example": {"sentence": "Reservar un hotel.", "translation": "訂飯店。"}, "usage_note": "H 不發音。", "image_file": "hotel.png" },
        { "id": "n-18", "term_zh": "護照", "term_target": "Pasaporte", "pronunciation": ["/pasaˈpoɾte/"], "example": {"sentence": "Su pasaporte, por favor.", "translation": "請出示護照。"}, "usage_note": "出國必備。", "image_file": "passport.png" },
        { "id": "n-19", "term_zh": "地圖", "term_target": "Mapa", "pronunciation": ["/ˈmapa/"], "example": {"sentence": "Mirar el mapa.", "translation": "看地圖。"}, "usage_note": "陽性名詞 (El mapa)。", "image_file": "map.png" },
        { "id": "n-20", "term_zh": "警察", "term_target": "Policía", "pronunciation": ["/poliˈθia/"], "example": {"sentence": "Llamar a la policía.", "translation": "叫警察。"}, "usage_note": "求救用。", "image_file": "police.png" },
        { "id": "n-21", "term_zh": "台灣人", "term_target": "Taiuanés/esa", "pronunciation": ["/tajwaˈnes/"], "example": {"sentence": "Soy taiuanés.", "translation": "我是台灣人。"}, "usage_note": "國籍。", "image_file": "taiwanese.png" },
        { "id": "n-22", "term_zh": "孩子", "term_target": "Niño/a", "pronunciation": ["/ˈniɲo/"], "example": {"sentence": "Niño pequeño.", "translation": "小孩。"}, "usage_note": "兒童。", "image_file": "child.png" },
        { "id": "n-23", "term_zh": "學生", "term_target": "Estudiante", "pronunciation": ["/estuˈðjante/"], "example": {"sentence": "Soy estudiante.", "translation": "我是學生。"}, "usage_note": "不分陰陽。", "image_file": "student.png" },
        { "id": "n-24", "term_zh": "文化", "term_target": "Cultura", "pronunciation": ["/kulˈtuɾa/"], "example": {"sentence": "Cultura local.", "translation": "當地文化。"}, "usage_note": "文化。", "image_file": "culture.png" },
        { "id": "n-25", "term_zh": "問題", "term_target": "Problema", "pronunciation": ["/pɾoˈβlema/"], "example": {"sentence": "No hay problema.", "translation": "沒問題。"}, "usage_note": "陽性名詞 (El problema)。", "image_file": "problem.png" },
        { "id": "n-26", "term_zh": "公司", "term_target": "Empresa / Compañía", "pronunciation": ["/emˈpɾesa/", "/kompaˈɲia/"], "example": {"sentence": "Empresa grande.", "translation": "大公司。"}, "usage_note": "上班地點。", "image_file": "company.png" },
        { "id": "n-27", "term_zh": "男性", "term_target": "Hombre", "pronunciation": ["/ˈombɾe/"], "example": {"sentence": "Es un hombre.", "translation": "他是男人。"}, "usage_note": "性別。", "image_file": "man.png" },
        { "id": "n-28", "term_zh": "女性", "term_target": "Mujer", "pronunciation": ["/muˈxeɾ/"], "example": {"sentence": "Es una mujer.", "translation": "她是女人。"}, "usage_note": "性別。", "image_file": "woman.png" },
        { "id": "n-29", "term_zh": "學校", "term_target": "Escuela", "pronunciation": ["/esˈkwela/"], "example": {"sentence": "Ir a la escuela.", "translation": "去學校。"}, "usage_note": "教育機構。", "image_file": "school.png" },
        { "id": "n-30", "term_zh": "老師", "term_target": "Profesor/a", "pronunciation": ["/pɾofeˈsoɾ/"], "example": {"sentence": "Profesor de español.", "translation": "西班牙文老師。"}, "usage_note": "師長。", "image_file": "teacher.png" },
        { "id": "n-31", "term_zh": "電影", "term_target": "Película", "pronunciation": ["/peˈlikula/"], "example": {"sentence": "Ver una película.", "translation": "看電影。"}, "usage_note": "影片。", "image_file": "movie.png" },
        { "id": "n-32", "term_zh": "電腦", "term_target": "Ordenador / Computadora", "pronunciation": ["/oɾdenaˈdoɾ/", "/komputaˈdoɾa/"], "example": {"sentence": "Usar el ordenador.", "translation": "用電腦。"}, "usage_note": "西班牙用Ordenador，拉美用Computadora。", "image_file": "computer.png" },
        { "id": "n-33", "term_zh": "市場", "term_target": "Mercado", "pronunciation": ["/meɾˈkaðo/"], "example": {"sentence": "Mercado nocturno.", "translation": "夜市。"}, "usage_note": "市集。", "image_file": "market.png" },
        { "id": "n-34", "term_zh": "衣服", "term_target": "Ropa", "pronunciation": ["/ˈropa/"], "example": {"sentence": "Comprar ropa.", "translation": "買衣服。"}, "usage_note": "集合名詞(單數)。", "image_file": "clothes.png" },
        { "id": "n-35", "term_zh": "商店", "term_target": "Tienda", "pronunciation": ["/ˈtjenda/"], "example": {"sentence": "Tienda de ropa.", "translation": "服飾店。"}, "usage_note": "店家。", "image_file": "shop.png" },
        { "id": "n-36", "term_zh": "街道", "term_target": "Calle", "pronunciation": ["/ˈkaʎe/"], "example": {"sentence": "En la calle.", "translation": "在街上。"}, "usage_note": "道路。", "image_file": "street.png" },
        { "id": "n-37", "term_zh": "房子", "term_target": "Casa", "pronunciation": ["/ˈkasa/"], "example": {"sentence": "Mi casa.", "translation": "我家。"}, "usage_note": "住宅。", "image_file": "house.png" },
        { "id": "n-38", "term_zh": "母親", "term_target": "Madre", "pronunciation": ["/ˈmaðɾe/"], "example": {"sentence": "Mi madre.", "translation": "我媽媽。"}, "usage_note": "口語常用 Mamá。", "image_file": "mother.png" },
        { "id": "n-39", "term_zh": "父親", "term_target": "Padre", "pronunciation": ["/ˈpaðɾe/"], "example": {"sentence": "Mi padre.", "translation": "我爸爸。"}, "usage_note": "口語常用 Papá。", "image_file": "father.png" },
        { "id": "n-40", "term_zh": "中文", "term_target": "Chino", "pronunciation": ["/ˈtʃino/"], "example": {"sentence": "Hablar chino.", "translation": "說中文。"}, "usage_note": "語言。", "image_file": "chinese.png" },
        { "id": "n-41", "term_zh": "包包", "term_target": "Bolso / Mochila", "pronunciation": ["/ˈbolso/", "/moˈtʃila/"], "example": {"sentence": "Bolso grande.", "translation": "大包包。"}, "usage_note": "Mochila是後背包。", "image_file": "bag.png" },
        { "id": "n-42", "term_zh": "杯子", "term_target": "Taza / Vaso", "pronunciation": ["/ˈtaθa/", "/ˈbaso/"], "example": {"sentence": "Taza de té.", "translation": "一杯茶。"}, "usage_note": "Taza(有把手), Vaso(玻璃杯)。", "image_file": "cup.png" },
        { "id": "n-43", "term_zh": "醫生", "term_target": "Médico/a / Doctor/a", "pronunciation": ["/ˈmeðiko/", "/dokˈtoɾ/"], "example": {"sentence": "Ir al médico.", "translation": "看醫生。"}, "usage_note": "醫師。", "image_file": "doctor.png" },
        { "id": "n-44", "term_zh": "醫院", "term_target": "Hospital", "pronunciation": ["/ospiˈtal/"], "example": {"sentence": "Ir al hospital.", "translation": "去醫院。"}, "usage_note": "H 不發音。", "image_file": "hospital.png" },
        { "id": "n-45", "term_zh": "座位", "term_target": "Asiento", "pronunciation": ["/aˈsjento/"], "example": {"sentence": "Tomar asiento.", "translation": "請坐。"}, "usage_note": "位子。", "image_file": "seat.png" },
        { "id": "n-46", "term_zh": "門", "term_target": "Puerta", "pronunciation": ["/ˈpweɾta/"], "example": {"sentence": "Abrir la puerta.", "translation": "開門。"}, "usage_note": "門戶。", "image_file": "door.png" },
        { "id": "n-47", "term_zh": "房間", "term_target": "Habitación", "pronunciation": ["/aβitaˈθjon/"], "example": {"sentence": "Mi habitación.", "translation": "我房間。"}, "usage_note": "室內。", "image_file": "room.png" },
        { "id": "n-48", "term_zh": "行李", "term_target": "Equipaje", "pronunciation": ["/ekiˈpaxe/"], "example": {"sentence": "Mucho equipaje.", "translation": "很多行李。"}, "usage_note": "包裹。", "image_file": "luggage.png" },
        { "id": "n-49", "term_zh": "櫃檯", "term_target": "Mostrador", "pronunciation": ["/mostɾaˈdoɾ/"], "example": {"sentence": "En el mostrador.", "translation": "在櫃檯。"}, "usage_note": "服務台。", "image_file": "counter.png" },
        { "id": "n-50", "term_zh": "大廳", "term_target": "Vestíbulo", "pronunciation": ["/besˈtiβulo/"], "example": {"sentence": "Esperar en el vestíbulo.", "translation": "在大廳等。"}, "usage_note": "接待處。", "image_file": "lobby.png" },
        { "id": "n-51", "term_zh": "預定", "term_target": "Reserva", "pronunciation": ["/reˈseɾβa/"], "example": {"sentence": "Hacer una reserva.", "translation": "做預約。"}, "usage_note": "預約。", "image_file": "reservation.png" },
        { "id": "n-52", "term_zh": "入住", "term_target": "Registro / Check-in", "pronunciation": ["/reˈxistɾo/", "/tʃek in/"], "example": {"sentence": "Hacer el check-in.", "translation": "辦理入住。"}, "usage_note": "常用英文借詞。", "image_file": "check_in.png" },
        { "id": "n-53", "term_zh": "退房", "term_target": "Salida / Check-out", "pronunciation": ["/saˈliða/", "/tʃek aut/"], "example": {"sentence": "Hora de salida.", "translation": "退房時間。"}, "usage_note": "常用英文借詞。", "image_file": "check_out.png" },
        { "id": "n-54", "term_zh": "飲料", "term_target": "Bebida", "pronunciation": ["/beˈβiða/"], "example": {"sentence": "Bebida fría.", "translation": "冷飲。"}, "usage_note": "飲品。", "image_file": "drink.png" },
        { "id": "n-55", "term_zh": "菜單", "term_target": "Menú / Carta", "pronunciation": ["/meˈnu/", "/ˈkaɾta/"], "example": {"sentence": "El menú, por favor.", "translation": "請給菜單。"}, "usage_note": "Menu。", "image_file": "menu.png" },
        { "id": "n-56", "term_zh": "午餐", "term_target": "Almuerzo", "pronunciation": ["/alˈmweɾθo/"], "example": {"sentence": "Comer el almuerzo.", "translation": "吃午餐。"}, "usage_note": "中餐。", "image_file": "lunch.png" },
        { "id": "n-57", "term_zh": "晚餐", "term_target": "Cena", "pronunciation": ["/ˈθena/"], "example": {"sentence": "Comer la cena.", "translation": "吃晚餐。"}, "usage_note": "晚餐。", "image_file": "dinner.png" },
        { "id": "n-58", "term_zh": "帳單", "term_target": "Cuenta", "pronunciation": ["/ˈkwenta/"], "example": {"sentence": "La cuenta, por favor.", "translation": "麻煩結帳。"}, "usage_note": "買單。", "image_file": "bill.png" },
        { "id": "n-59", "term_zh": "價錢", "term_target": "Precio", "pronunciation": ["/ˈpɾeθjo/"], "example": {"sentence": "Buen precio.", "translation": "好價格。"}, "usage_note": "價格。", "image_file": "price.png" },
        { "id": "n-60", "term_zh": "收據", "term_target": "Recibo", "pronunciation": ["/reˈθiβo/"], "example": {"sentence": "El recibo, por favor.", "translation": "請給收據。"}, "usage_note": "證明。", "image_file": "receipt.png" },
        { "id": "n-61", "term_zh": "尺寸", "term_target": "Talla / Tamaño", "pronunciation": ["/ˈtaʎa/ /taˈmaɲo/"], "example": {"sentence": "Talla grande.", "translation": "大尺寸。"}, "usage_note": "Talla(衣服), Tamaño(物體)。", "image_file": "size.png" },
        { "id": "n-62", "term_zh": "入口", "term_target": "Entrada", "pronunciation": ["/enˈtɾaða/"], "example": {"sentence": "Entrada principal.", "translation": "正門入口。"}, "usage_note": "進去的地方。", "image_file": "entrance.png" },
        { "id": "n-63", "term_zh": "出口", "term_target": "Salida", "pronunciation": ["/saˈliða/"], "example": {"sentence": "Salida de emergencia.", "translation": "緊急出口。"}, "usage_note": "出去的地方。", "image_file": "exit.png" },
        { "id": "n-64", "term_zh": "台灣", "term_target": "Taiwán", "pronunciation": ["/taiˈwan/"], "example": {"sentence": "Amo Taiwán.", "translation": "我愛台灣。"}, "usage_note": "地名。", "image_file": "taiwan.png" },
        { "id": "n-65", "term_zh": "一切事物", "term_target": "Todo", "pronunciation": ["/ˈtodo/"], "example": {"sentence": "Todo está bien.", "translation": "一切都好。"}, "usage_note": "所有。", "image_file": "everything.png" },
        { "id": "n-66", "term_zh": "錢包", "term_target": "Cartera / Billetera", "pronunciation": ["/kaɾˈteɾa/", "/biʎeˈteɾa/"], "example": {"sentence": "Perdí mi cartera.", "translation": "掉了錢包。"}, "usage_note": "皮夾。", "image_file": "wallet.png" },
        { "id": "n-67", "term_zh": "身分證", "term_target": "DNI / Identificación", "pronunciation": ["/de ene i/", "/identifikaˈθjon/"], "example": {"sentence": "Su identificación, por favor.", "translation": "請出示證件。"}, "usage_note": "ID。", "image_file": "id.png" },
        { "id": "n-68", "term_zh": "餐廳", "term_target": "Restaurante", "pronunciation": ["/restauˈɾante/"], "example": {"sentence": "Buen restaurante.", "translation": "好餐廳。"}, "usage_note": "食堂。", "image_file": "restaurant.png" },
        { "id": "n-69", "term_zh": "場所", "term_target": "Lugar", "pronunciation": ["/luˈɣaɾ/"], "example": {"sentence": "Buen lugar.", "translation": "好地方。"}, "usage_note": "地點。", "image_file": "place.png" },
        { "id": "n-70", "term_zh": "店員", "term_target": "Dependiente/a", "pronunciation": ["/depenˈdjente/"], "example": {"sentence": "Preguntar al dependiente.", "translation": "問店員。"}, "usage_note": "工作人員。", "image_file": "clerk.png" },
        { "id": "n-71", "term_zh": "超市", "term_target": "Supermercado", "pronunciation": ["/supeɾmeɾˈkaðo/"], "example": {"sentence": "Ir al supermercado.", "translation": "去超市。"}, "usage_note": "量販店。", "image_file": "supermarket.png" },
        { "id": "n-72", "term_zh": "月台", "term_target": "Andén / Plataforma", "pronunciation": ["/anˈden/", "/plataˈfoɾma/"], "example": {"sentence": "Andén 1.", "translation": "第一月台。"}, "usage_note": "車站月台。", "image_file": "platform.png" }
      ]
    },
    {
      "id": "adverbs",
      "name": "副詞",
      "items": [
        { "id": "adv-01", "term_zh": "現在", "term_target": "Ahora", "pronunciation": ["/aˈoɾa/"], "example": {"sentence": "Hazlo ahora.", "translation": "現在做。"}, "usage_note": "目前。", "image_file": "now.png" },
        { "id": "adv-02", "term_zh": "非常", "term_target": "Muy", "pronunciation": ["/muj/"], "example": {"sentence": "Muy bien.", "translation": "非常好。"}, "usage_note": "強調。", "image_file": "very.png" },
        { "id": "adv-03", "term_zh": "真的", "term_target": "Realmente / De verdad", "pronunciation": ["/realˈmente/", "/de beɾˈðað/"], "example": {"sentence": "¿De verdad?", "translation": "真的嗎？"}, "usage_note": "確認或強調。", "image_file": "really.png" },
        { "id": "adv-04", "term_zh": "經常", "term_target": "A menudo", "pronunciation": ["/a meˈnuðo/"], "example": {"sentence": "Vengo a menudo.", "translation": "我常來。"}, "usage_note": "頻率。", "image_file": "often.png" },
        { "id": "adv-05", "term_zh": "通常", "term_target": "Normalmente / Usualmente", "pronunciation": ["/noɾmalˈmente/", "/uswalˈmente/"], "example": {"sentence": "Normalmente camino.", "translation": "通常我走路。"}, "usage_note": "習慣。", "image_file": "usually.png" },
        { "id": "adv-06", "term_zh": "只有", "term_target": "Solo / Solamente", "pronunciation": ["/ˈsolo/", "/solaˈmente/"], "example": {"sentence": "Solo uno.", "translation": "只有一個。"}, "usage_note": "唯一。", "image_file": "only.png" },
        { "id": "adv-07", "term_zh": "再次", "term_target": "Otra vez / De nuevo", "pronunciation": ["/ˈotɾa beθ/", "/de ˈnweβo/"], "example": {"sentence": "Inténtalo otra vez.", "translation": "再試一次。"}, "usage_note": "重複。", "image_file": "again.png" },
        { "id": "adv-08", "term_zh": "一起", "term_target": "Juntos", "pronunciation": ["/ˈxuntos/"], "example": {"sentence": "Ir juntos.", "translation": "一起去。"}, "usage_note": "共同。", "image_file": "together.png" },
        { "id": "adv-09", "term_zh": "或許", "term_target": "Tal vez / Quizás", "pronunciation": ["/tal ˈbeθ/", "/kiˈθas/"], "example": {"sentence": "Tal vez más tarde.", "translation": "也許等下。"}, "usage_note": "不確定。", "image_file": "maybe.png" },
        { "id": "adv-10", "term_zh": "很快", "term_target": "Pronto", "pronunciation": ["/ˈpɾonto/"], "example": {"sentence": "Nos vemos pronto.", "translation": "待會見(很快見)。"}, "usage_note": "不久後。", "image_file": "soon.png" },
        { "id": "adv-11", "term_zh": "已經", "term_target": "Ya", "pronunciation": ["/ʝa/"], "example": {"sentence": "Ya está hecho.", "translation": "已經做好了。"}, "usage_note": "完成。", "image_file": "already.png" },
        { "id": "adv-12", "term_zh": "大約", "term_target": "Alrededor de / Unos", "pronunciation": ["/alɾeðeˈðoɾ de/", "/ˈunos/"], "example": {"sentence": "Unos 10 minutos.", "translation": "大約10分鐘。"}, "usage_note": "概數。", "image_file": "about.png" },
        { "id": "adv-13", "term_zh": "一點點", "term_target": "Un poco", "pronunciation": ["/um ˈpoko/"], "example": {"sentence": "Un poco picante.", "translation": "一點點辣。"}, "usage_note": "少量。", "image_file": "a_little.png" },
        { "id": "adv-14", "term_zh": "之後", "term_target": "Después / Más tarde", "pronunciation": ["/desˈpwes/", "/mas ˈtaɾðe/"], "example": {"sentence": "Nos vemos más tarde.", "translation": "待會見。"}, "usage_note": "稍後。", "image_file": "later.png" },
        { "id": "adv-15", "term_zh": "仍然", "term_target": "Todavía / Aún", "pronunciation": ["/toðaˈβia/", "/aˈun/"], "example": {"sentence": "Todavía aquí.", "translation": "還在這裡。"}, "usage_note": "持續。", "image_file": "still.png" },
        { "id": "adv-16", "term_zh": "一般來說", "term_target": "Generalmente", "pronunciation": ["/xeneɾalˈmente/"], "example": {"sentence": "Generalmente es así.", "translation": "一般是那樣。"}, "usage_note": "通常。", "image_file": "normally.png" }
      ]
    },
    {
      "id": "questions",
      "name": "疑問詞",
      "items": [
        { "id": "q-01", "term_zh": "什麼", "term_target": "Qué", "pronunciation": ["/ke/"], "example": {"sentence": "¿Qué es esto?", "translation": "這是什麼？"}, "usage_note": "問事物。", "image_file": "what.png" },
        { "id": "q-02", "term_zh": "哪裡", "term_target": "Dónde", "pronunciation": ["/ˈdonde/"], "example": {"sentence": "¿Dónde estás?", "translation": "你在哪？"}, "usage_note": "問地點。", "image_file": "where.png" },
        { "id": "q-03", "term_zh": "何時", "term_target": "Cuándo", "pronunciation": ["/ˈkwando/"], "example": {"sentence": "¿Cuándo vamos?", "translation": "何時去？"}, "usage_note": "問時間。", "image_file": "when.png" },
        { "id": "q-04", "term_zh": "誰", "term_target": "Quién", "pronunciation": ["/kjen/"], "example": {"sentence": "¿Quién es él?", "translation": "他是誰？"}, "usage_note": "問人。", "image_file": "who.png" },
        { "id": "q-05", "term_zh": "為什麼", "term_target": "Por qué", "pronunciation": ["/poɾ ˈke/"], "example": {"sentence": "¿Por qué?", "translation": "為什麼？"}, "usage_note": "問原因。", "image_file": "why.png" },
        { "id": "q-06", "term_zh": "如何", "term_target": "Cómo", "pronunciation": ["/ˈkomo/"], "example": {"sentence": "¿Cómo estás?", "translation": "你好嗎？"}, "usage_note": "問狀況。", "image_file": "how.png" },
        { "id": "q-07", "term_zh": "多少(錢)", "term_target": "Cuánto", "pronunciation": ["/ˈkwanto/"], "example": {"sentence": "¿Cuánto cuesta?", "translation": "多少錢？"}, "usage_note": "不可數/價格。", "image_file": "how_much.png" },
        { "id": "q-08", "term_zh": "多久/多少(量)", "term_target": "Cuánto tiempo", "pronunciation": ["/ˈkwanto ˈtjempo/"], "example": {"sentence": "¿Cuánto tiempo?", "translation": "要多久？"}, "usage_note": "時間長度。", "image_file": "how_long.png" },
        { "id": "q-09", "term_zh": "哪一個", "term_target": "Cuál", "pronunciation": ["/kwal/"], "example": {"sentence": "¿Cuál prefieres?", "translation": "你喜歡哪一個？"}, "usage_note": "選擇。", "image_file": "which.png" }
      ]
    },
    {
      "id": "time_place",
      "name": "時間與場所",
      "items": [
        { "id": "tp-01", "term_zh": "今天", "term_target": "Hoy", "pronunciation": ["/oi/"], "example": {"sentence": "Hoy hace calor.", "translation": "今天很熱。"}, "usage_note": "本日。", "image_file": "today.png" },
        { "id": "tp-02", "term_zh": "明天", "term_target": "Mañana", "pronunciation": ["/maˈɲana/"], "example": {"sentence": "Hasta mañana.", "translation": "明天見。"}, "usage_note": "隔天。", "image_file": "tomorrow.png" },
        { "id": "tp-03", "term_zh": "昨天", "term_target": "Ayer", "pronunciation": ["/aˈʝeɾ/"], "example": {"sentence": "Ayer fui.", "translation": "昨天我去了。"}, "usage_note": "前一天。", "image_file": "yesterday.png" },
        { "id": "tp-04", "term_zh": "這裡", "term_target": "Aquí", "pronunciation": ["/aˈki/"], "example": {"sentence": "Ven aquí.", "translation": "來這。"}, "usage_note": "近處。", "image_file": "here.png" },
        { "id": "tp-05", "term_zh": "那裡", "term_target": "Allí / Allá", "pronunciation": ["/aˈʎi/"], "example": {"sentence": "Ve allí.", "translation": "去那。"}, "usage_note": "遠處。", "image_file": "there.png" },
        { "id": "tp-06", "term_zh": "早上", "term_target": "Mañana", "pronunciation": ["/maˈɲana/"], "example": {"sentence": "Por la mañana.", "translation": "在早上。"}, "usage_note": "上午(同明天)。", "image_file": "morning.png" },
        { "id": "tp-07", "term_zh": "晚上/夜晚", "term_target": "Noche", "pronunciation": ["/ˈnotʃe/"], "example": {"sentence": "Buenas noches.", "translation": "晚安。"}, "usage_note": "睡前。", "image_file": "night.png" },
        { "id": "tp-08", "term_zh": "前面", "term_target": "Delante", "pronunciation": ["/deˈlante/"], "example": {"sentence": "Delante de mí.", "translation": "在我前面。"}, "usage_note": "前方。", "image_file": "front.png" },
        { "id": "tp-09", "term_zh": "後面", "term_target": "Detrás", "pronunciation": ["/deˈtɾas/"], "example": {"sentence": "Detrás de la puerta.", "translation": "門後。"}, "usage_note": "後方。", "image_file": "behind.png" },
        { "id": "tp-10", "term_zh": "左邊", "term_target": "Izquierda", "pronunciation": ["/iθˈkjeɾða/"], "example": {"sentence": "A la izquierda.", "translation": "左轉。"}, "usage_note": "左。", "image_file": "left.png" },
        { "id": "tp-11", "term_zh": "右邊", "term_target": "Derecha", "pronunciation": ["/deˈɾetʃa/"], "example": {"sentence": "A la derecha.", "translation": "右轉。"}, "usage_note": "右。", "image_file": "right.png" },
        { "id": "tp-12", "term_zh": "天(日)", "term_target": "Día", "pronunciation": ["/ˈdia/"], "example": {"sentence": "Un día.", "translation": "一天。"}, "usage_note": "日子。", "image_file": "day.png" },
        { "id": "tp-13", "term_zh": "年", "term_target": "Año", "pronunciation": ["/ˈaɲo/"], "example": {"sentence": "Este año.", "translation": "今年。"}, "usage_note": "年度。", "image_file": "year.png" },
        { "id": "tp-14", "term_zh": "月", "term_target": "Mes", "pronunciation": ["/mes/"], "example": {"sentence": "Este mes.", "translation": "這個月。"}, "usage_note": "月份。", "image_file": "month.png" },
        { "id": "tp-15", "term_zh": "週", "term_target": "Semana", "pronunciation": ["/seˈmana/"], "example": {"sentence": "La próxima semana.", "translation": "下週。"}, "usage_note": "星期。", "image_file": "week.png" },
        { "id": "tp-16", "term_zh": "下午", "term_target": "Tarde", "pronunciation": ["/ˈtaɾðe/"], "example": {"sentence": "Por la tarde.", "translation": "下午。"}, "usage_note": "PM。", "image_file": "afternoon.png" },
        { "id": "tp-17", "term_zh": "中午", "term_target": "Mediodía", "pronunciation": ["/meðjoˈðia/"], "example": {"sentence": "Al mediodía.", "translation": "在中午。"}, "usage_note": "12點。", "image_file": "noon.png" },
        { "id": "tp-18", "term_zh": "旁邊", "term_target": "Al lado", "pronunciation": ["/al ˈlaðo/"], "example": {"sentence": "Al lado de mí.", "translation": "坐我旁邊。"}, "usage_note": "側邊。", "image_file": "beside.png" },
        { "id": "tp-19", "term_zh": "對面", "term_target": "Enfrente", "pronunciation": ["/emˈfɾente/"], "example": {"sentence": "Enfrente del banco.", "translation": "銀行對面。"}, "usage_note": "對側。", "image_file": "across_from.png" },
        { "id": "tp-20", "term_zh": "春天", "term_target": "Primavera", "pronunciation": ["/pɾimaˈβeɾa/"], "example": {"sentence": "La primavera.", "translation": "春天。"}, "usage_note": "季節。", "image_file": "spring.png" },
        { "id": "tp-21", "term_zh": "夏天", "term_target": "Verano", "pronunciation": ["/beˈɾano/"], "example": {"sentence": "Verano caluroso.", "translation": "炎熱的夏天。"}, "usage_note": "季節。", "image_file": "summer.png" },
        { "id": "tp-22", "term_zh": "秋天", "term_target": "Otoño", "pronunciation": ["/oˈtoɲo/"], "example": {"sentence": "Otoño fresco.", "translation": "涼爽的秋天。"}, "usage_note": "季節。", "image_file": "autumn.png" },
        { "id": "tp-23", "term_zh": "冬天", "term_target": "Invierno", "pronunciation": ["/imˈbjeɾno/"], "example": {"sentence": "Invierno frío.", "translation": "寒冷的冬天。"}, "usage_note": "季節。", "image_file": "winter.png" }
      ]
    },
    {
      "id": "numbers",
      "name": "數字",
      "items": [
        { "id": "num-0", "term_zh": "0", "term_target": "Cero", "pronunciation": ["/ˈθeɾo/"], "example": {"sentence": "Cero grados.", "translation": "零度。"}, "usage_note": "零。", "image_file": "zero.png" },
        { "id": "num-1", "term_zh": "1", "term_target": "Uno", "pronunciation": ["/ˈuno/"], "example": {"sentence": "Un minuto.", "translation": "一分鐘。"}, "usage_note": "在陽性名詞前變 Un。", "image_file": "one.png" },
        { "id": "num-2", "term_zh": "2", "term_target": "Dos", "pronunciation": ["/dos/"], "example": {"sentence": "Dos días.", "translation": "兩天。"}, "usage_note": "二。", "image_file": "two.png" },
        { "id": "num-3", "term_zh": "3", "term_target": "Tres", "pronunciation": ["/tɾes/"], "example": {"sentence": "Tres personas.", "translation": "三人。"}, "usage_note": "三。", "image_file": "three.png" },
        { "id": "num-4", "term_zh": "4", "term_target": "Cuatro", "pronunciation": ["/ˈkwatɾo/"], "example": {"sentence": "Cuatro estaciones.", "translation": "四季。"}, "usage_note": "四。", "image_file": "four.png" },
        { "id": "num-5", "term_zh": "5", "term_target": "Cinco", "pronunciation": ["/ˈθinko/"], "example": {"sentence": "Cinco euros.", "translation": "五歐元。"}, "usage_note": "五。", "image_file": "five.png" },
        { "id": "num-6", "term_zh": "6", "term_target": "Seis", "pronunciation": ["/seis/"], "example": {"sentence": "Seis horas.", "translation": "六小時。"}, "usage_note": "六。", "image_file": "six.png" },
        { "id": "num-7", "term_zh": "7", "term_target": "Siete", "pronunciation": ["/ˈsjete/"], "example": {"sentence": "Siete días.", "translation": "七天。"}, "usage_note": "七。", "image_file": "seven.png" },
        { "id": "num-8", "term_zh": "8", "term_target": "Ocho", "pronunciation": ["/ˈotʃo/"], "example": {"sentence": "Ocho años.", "translation": "八歲。"}, "usage_note": "八。", "image_file": "eight.png" },
        { "id": "num-9", "term_zh": "9", "term_target": "Nueve", "pronunciation": ["/ˈnweβe/"], "example": {"sentence": "Nueve de la noche.", "translation": "晚上九點。"}, "usage_note": "九。", "image_file": "nine.png" },
        { "id": "num-10", "term_zh": "10", "term_target": "Diez", "pronunciation": ["/djeθ/"], "example": {"sentence": "Diez euros.", "translation": "十歐元。"}, "usage_note": "十。", "image_file": "ten.png" },
        { "id": "num-11", "term_zh": "11", "term_target": "Once", "pronunciation": ["/ˈonθe/"], "example": {"sentence": "Once años.", "translation": "11歲。"}, "usage_note": "十一。", "image_file": "eleven.png" },
        { "id": "num-12", "term_zh": "12", "term_target": "Doce", "pronunciation": ["/ˈdoθe/"], "example": {"sentence": "Doce meses.", "translation": "12個月。"}, "usage_note": "十二。", "image_file": "twelve.png" },
        { "id": "num-15", "term_zh": "15", "term_target": "Quince", "pronunciation": ["/ˈkinθe/"], "example": {"sentence": "Quince minutos.", "translation": "15分鐘。"}, "usage_note": "十五。", "image_file": "fifteen.png" },
        { "id": "num-20", "term_zh": "20", "term_target": "Veinte", "pronunciation": ["/ˈbeinte/"], "example": {"sentence": "Veinte euros.", "translation": "20歐元。"}, "usage_note": "二十。", "image_file": "twenty.png" },
        { "id": "num-50", "term_zh": "50", "term_target": "Cincuenta", "pronunciation": ["/θinˈkwenta/"], "example": {"sentence": "Cincuenta por ciento.", "translation": "50%。"}, "usage_note": "五十。", "image_file": "fifty.png" },
        { "id": "num-100", "term_zh": "100", "term_target": "Cien", "pronunciation": ["/θjen/"], "example": {"sentence": "Cien puntos.", "translation": "一百分。"}, "usage_note": "超過一百用 Ciento...", "image_file": "hundred.png" },
        { "id": "num-1000", "term_zh": "1000", "term_target": "Mil", "pronunciation": ["/mil/"], "example": {"sentence": "Mil gracias.", "translation": "萬分感謝(一千個謝謝)。"}, "usage_note": "千。", "image_file": "thousand.png" },
        { "id": "num-10000", "term_zh": "10000", "term_target": "Diez mil", "pronunciation": ["/djeθ mil/"], "example": {"sentence": "Diez mil dólares.", "translation": "一萬元。"}, "usage_note": "一萬。", "image_file": "ten_thousand.png" }
      ]
    },
    {
      "id": "grammar",
      "name": "基本句型",
      "items": [
        { "id": "g-01", "term_zh": "我是...", "term_target": "Soy...", "pronunciation": ["/soi/"], "example": {"sentence": "Soy estudiante.", "translation": "我是學生。"}, "usage_note": "本質/身分。", "image_file": "i_am.png" },
        { "id": "g-02", "term_zh": "我正在...", "term_target": "Estoy ...-ando/-iendo", "pronunciation": ["/esˈtoi/"], "example": {"sentence": "Estoy comiendo.", "translation": "我正在吃。"}, "usage_note": "進行式 Estar + 副動詞。", "image_file": "ing.png" },
        { "id": "g-03", "term_zh": "我能夠...", "term_target": "Puedo...", "pronunciation": ["/ˈpweðo/"], "example": {"sentence": "Puedo nadar.", "translation": "我會游泳。"}, "usage_note": "能力。", "image_file": "can.png" },
        { "id": "g-04", "term_zh": "我喜歡做...", "term_target": "Me gusta...", "pronunciation": ["/me ˈgusta/"], "example": {"sentence": "Me gusta leer.", "translation": "我喜歡閱讀。"}, "usage_note": "興趣。", "image_file": "like_ing.png" },
        { "id": "g-05", "term_zh": "我想做...", "term_target": "Quiero...", "pronunciation": ["/ˈkjeɾo/"], "example": {"sentence": "Quiero ir.", "translation": "我想去。"}, "usage_note": "慾望。", "image_file": "want_to.png" },
        { "id": "g-06", "term_zh": "你是...嗎?", "term_target": "¿Eres...?", "pronunciation": ["/ˈeɾes/"], "example": {"sentence": "¿Eres estudiante?", "translation": "你是學生嗎？"}, "usage_note": "問狀態。", "image_file": "are_you.png" },
        { "id": "g-07", "term_zh": "不要...", "term_target": "No...", "pronunciation": ["/no/"], "example": {"sentence": "No toques.", "translation": "不要碰。"}, "usage_note": "禁止/否定命令。", "image_file": "dont.png" },
        { "id": "g-08", "term_zh": "你有做...嗎?", "term_target": "¿Haces...?", "pronunciation": ["/ˈaθes/"], "example": {"sentence": "¿Haces deporte?", "translation": "你有運動嗎？"}, "usage_note": "一般疑問句。", "image_file": "do_you.png" },
        { "id": "g-09", "term_zh": "你曾經...嗎?", "term_target": "¿Has...?", "pronunciation": ["/as/"], "example": {"sentence": "¿Has ido a España?", "translation": "你有去過西班牙嗎？"}, "usage_note": "問經驗(完成式)。", "image_file": "have_you_ever.png" },
        { "id": "g-10", "term_zh": "你何時做...?", "term_target": "¿Cuándo...?", "pronunciation": ["/ˈkwando/"], "example": {"sentence": "¿Cuándo duermes?", "translation": "你何時睡？"}, "usage_note": "問時間點。", "image_file": "when_do_you.png" },
        { "id": "g-11", "term_zh": "你在哪裡做...?", "term_target": "¿Dónde...?", "pronunciation": ["/ˈdonde/"], "example": {"sentence": "¿Dónde vives?", "translation": "你住哪裡？"}, "usage_note": "問地點。", "image_file": "where_do_you.png" },
        { "id": "g-12", "term_zh": "你如何做...?", "term_target": "¿Cómo...?", "pronunciation": ["/ˈkomo/"], "example": {"sentence": "¿Cómo vas?", "translation": "你怎麼去？"}, "usage_note": "問方法。", "image_file": "how_do_you.png" },
        { "id": "g-13", "term_zh": "我不是...", "term_target": "No soy...", "pronunciation": ["/no soi/"], "example": {"sentence": "No soy médico.", "translation": "我不是醫生。"}, "usage_note": "否定身分。", "image_file": "i_am_not.png" },
        { "id": "g-14", "term_zh": "我不做...", "term_target": "No (verbo)...", "pronunciation": ["/no/"], "example": {"sentence": "No fumo.", "translation": "我不抽菸。"}, "usage_note": "否定動作。", "image_file": "i_dont.png" },
        { "id": "g-15", "term_zh": "我不能...", "term_target": "No puedo...", "pronunciation": ["/no ˈpweðo/"], "example": {"sentence": "No puedo ir.", "translation": "我不能去。"}, "usage_note": "否定能力。", "image_file": "i_cant.png" },
        { "id": "g-16", "term_zh": "我未曾...", "term_target": "Nunca he...", "pronunciation": ["/ˈnuŋka e/"], "example": {"sentence": "Nunca he comido esto.", "translation": "我沒吃過這個。"}, "usage_note": "無此經驗。", "image_file": "i_have_never.png" },
        { "id": "g-17", "term_zh": "我不必...", "term_target": "No tengo que...", "pronunciation": ["/no ˈteŋgo ke/"], "example": {"sentence": "No tengo que ir.", "translation": "我不必去。"}, "usage_note": "無義務。", "image_file": "i_dont_have_to.png" },
        { "id": "g-18", "term_zh": "如果...的話", "term_target": "Si...", "pronunciation": ["/si/"], "example": {"sentence": "Si quieres, vamos.", "translation": "如果你想，我們走。"}, "usage_note": "假設條件。", "image_file": "if.png" },
        { "id": "g-19", "term_zh": "當...時", "term_target": "Cuando...", "pronunciation": ["/ˈkwando/"], "example": {"sentence": "Cuando era niño.", "translation": "小時候(當我是孩子時)。"}, "usage_note": "時間條件。", "image_file": "when_condition.png" },
        { "id": "g-20", "term_zh": "請你...好嗎?", "term_target": "¿Puedes...?", "pronunciation": ["/ˈpweðes/"], "example": {"sentence": "¿Puedes ayudarme?", "translation": "可以幫我嗎？"}, "usage_note": "請求。", "image_file": "can_you.png" },
        { "id": "g-21", "term_zh": "我們來做...吧", "term_target": "Vamos a...", "pronunciation": ["/ˈbamos a/"], "example": {"sentence": "Vamos a comer.", "translation": "我們去吃吧。"}, "usage_note": "提議。", "image_file": "lets.png" },
        { "id": "g-22", "term_zh": "我認為...", "term_target": "Creo que...", "pronunciation": ["/ˈkɾeo ke/"], "example": {"sentence": "Creo que es bueno.", "translation": "我認為這很好。"}, "usage_note": "表達想法。", "image_file": "i_think.png" },
        { "id": "g-23", "term_zh": "我必須...", "term_target": "Tengo que...", "pronunciation": ["/ˈteŋgo ke/"], "example": {"sentence": "Tengo que trabajar.", "translation": "我必須工作。"}, "usage_note": "義務。", "image_file": "i_have_to.png" },
        { "id": "g-24", "term_zh": "做某事是...的", "term_target": "Es ... (infinitivo)", "pronunciation": ["/es/"], "example": {"sentence": "Es bueno comer.", "translation": "吃東西是很好的。"}, "usage_note": "描述動作。", "image_file": "it_is_to.png" },
        { "id": "g-25", "term_zh": "我可以...嗎?", "term_target": "¿Puedo...?", "pronunciation": ["/ˈpweðo/"], "example": {"sentence": "¿Puedo entrar?", "translation": "我可以進來嗎？"}, "usage_note": "請求許可。", "image_file": "can_i.png" },
        { "id": "g-26", "term_zh": "我比較喜歡...", "term_target": "Prefiero...", "pronunciation": ["/pɾeˈfjeɾo/"], "example": {"sentence": "Prefiero té.", "translation": "我比較喜歡茶。"}, "usage_note": "偏好。", "image_file": "prefer.png" },
        { "id": "g-27", "term_zh": "A比B更...", "term_target": "A es más ... que B", "pronunciation": ["/a es mas... ke be/"], "example": {"sentence": "Esto es más caro que eso.", "translation": "這比那個貴。"}, "usage_note": "比較級。", "image_file": "more_than.png" },
        { "id": "g-28", "term_zh": "有(存在)...", "term_target": "Hay...", "pronunciation": ["/ai/"], "example": {"sentence": "Hay un perro.", "translation": "有一隻狗。"}, "usage_note": "存在。", "image_file": "there_is.png" },
        { "id": "g-29", "term_zh": "我曾經是/當時是...", "term_target": "Era / Fui...", "pronunciation": ["/ˈeɾa/", "/fwi/"], "example": {"sentence": "Era estudiante.", "translation": "我曾經是學生。"}, "usage_note": "過去狀態。", "image_file": "i_was.png" },
        { "id": "g-30", "term_zh": "我將要...", "term_target": "Voy a...", "pronunciation": ["/boi a/"], "example": {"sentence": "Voy a ir.", "translation": "我將要去。"}, "usage_note": "未來意。", "image_file": "i_will.png" },
        { "id": "g-31", "term_zh": "我曾經做過...", "term_target": "Hice...", "pronunciation": ["/ˈiθe/"], "example": {"sentence": "Hice mi tarea.", "translation": "我做了功課。"}, "usage_note": "過去動作。", "image_file": "i_did.png" }
      ]
    }
  ]
}