import { AppData } from '../types';

export const japaneseData: AppData = {
  "meta": {
    "name": "TW-JP Quick Learn",
    "source_language": "zh-TW",
    "target_language": "ja-JP",
    "version": "2.3",
    "description": "台灣人快速語言學習 - 日文完整版 (包含所有原始列表單字與完整句型 - 發音改為陣列版)"
  },
  "categories": [
    {
      "id": "greetings",
      "name": "常用句",
      "items": [
        {
          "id": "greet-001",
          "term_zh": "你好",
          "term_target": "こんにちは",
          "pronunciation": ["こんにちは", "Konnichiwa"],
          "example": { "sentence": "こんにちは、元気ですか？", "translation": "你好，你好嗎？" },
          "usage_note": "白天通用的問候語。",
          "image_file": "hello.png"
        },
        {
          "id": "greet-002",
          "term_zh": "再見",
          "term_target": "さようなら",
          "pronunciation": ["さようなら", "Sayounara"],
          "example": { "sentence": "では、さようなら。", "translation": "那麼，再見了。" },
          "usage_note": "比較正式。朋友間常說「バイバイ (Bye Bye)」。",
          "image_file": "goodbye.png"
        },
        {
          "id": "greet-003",
          "term_zh": "謝謝你",
          "term_target": "ありがとうございます",
          "pronunciation": ["ありがとうございます", "Arigatou gozaimasu"],
          "example": { "sentence": "手伝ってくれてありがとうございます。", "translation": "謝謝你的幫忙。" },
          "usage_note": "最有禮貌的說法。",
          "image_file": "thank_you.png"
        },
        {
          "id": "greet-004",
          "term_zh": "對不起",
          "term_target": "すみません",
          "pronunciation": ["すみません", "Sumimasen"],
          "example": { "sentence": "遅れてすみません。", "translation": "抱歉遲到了。" },
          "usage_note": "萬用詞：道歉、藉過、叫人都可用。",
          "image_file": "sorry.png"
        },
        {
          "id": "greet-005",
          "term_zh": "早安",
          "term_target": "おはようございます",
          "pronunciation": ["おはようございます", "Ohayou gozaimasu"],
          "example": { "sentence": "先生、おはようございます。", "translation": "老師，早安。" },
          "usage_note": "早上見面時使用。",
          "image_file": "good_morning.png"
        },
        {
          "id": "greet-006",
          "term_zh": "請問... / 借過",
          "term_target": "すみません",
          "pronunciation": ["すみません", "Sumimasen"],
          "example": { "sentence": "すみません、通ります。", "translation": "不好意思，藉過。" },
          "usage_note": "引起注意時很好用。",
          "image_file": "excuse_me.png"
        },
        {
          "id": "greet-007",
          "term_zh": "我不懂",
          "term_target": "わかりません",
          "pronunciation": ["わかりません", "Wakarimasen"],
          "example": { "sentence": "日本語がわかりません。", "translation": "我不懂日文。" },
          "usage_note": "聽不懂時直接說。",
          "image_file": "dont_understand.png"
        },
        {
          "id": "greet-008",
          "term_zh": "這是什麼？",
          "term_target": "これは何ですか？",
          "pronunciation": ["これはなんですか？", "Kore wa nan desu ka?"],
          "example": { "sentence": "これは何ですか？おいしいですか？", "translation": "這是什麼？好吃嗎？" },
          "usage_note": "指著東西問。",
          "image_file": "what_is_this.png"
        },
        {
          "id": "greet-009",
          "term_zh": "我想要這個",
          "term_target": "これが欲しいです",
          "pronunciation": ["これがほしいです", "Kore ga hoshii desu"],
          "example": { "sentence": "この靴が欲しいです。", "translation": "我想要這雙鞋。" },
          "usage_note": "表達願望。",
          "image_file": "i_want_this.png"
        },
        {
          "id": "greet-010",
          "term_zh": "請給我...",
          "term_target": "...をください",
          "pronunciation": ["...をください", "...o kudasai"],
          "example": { "sentence": "水をください。", "translation": "請給我水。" },
          "usage_note": "點餐必備。",
          "image_file": "please_give_me.png"
        },
        {
          "id": "greet-011",
          "term_zh": "廁所在哪裡？",
          "term_target": "トイレはどこですか？",
          "pronunciation": ["といれはどこですか？", "Toire wa doko desu ka?"],
          "example": { "sentence": "すみません、トイレはどこですか？", "translation": "請問廁所在哪？" },
          "usage_note": "旅遊最重要的一句。",
          "image_file": "where_bathroom.png"
        },
        {
          "id": "greet-012",
          "term_zh": "多少錢？",
          "term_target": "いくらですか？",
          "pronunciation": ["いくらですか？", "Ikura desu ka?"],
          "example": { "sentence": "これはいくらですか？", "translation": "這多少錢？" },
          "usage_note": "購物用語。",
          "image_file": "how_much.png"
        },
        {
          "id": "greet-013",
          "term_zh": "請幫我",
          "term_target": "手伝ってください",
          "pronunciation": ["てつだってください", "Tetsudatte kudasai"],
          "example": { "sentence": "荷物を手伝ってください。", "translation": "請幫我拿行李。" },
          "usage_note": "尋求協助。",
          "image_file": "help_me.png"
        },
        {
          "id": "greet-014",
          "term_zh": "你可以再說一次嗎？",
          "term_target": "もう一度言ってもらえますか？",
          "pronunciation": ["もういちどいってもらえますか？", "Mou ichido itte moraemasu ka?"],
          "example": { "sentence": "すみません、もう一度言ってもらえますか？", "translation": "不好意思，能再說一次嗎？" },
          "usage_note": "沒聽清楚時。",
          "image_file": "say_again.png"
        },
        {
          "id": "greet-015",
          "term_zh": "你可以講慢一點嗎？",
          "term_target": "もっとゆっくり話してもらえますか？",
          "pronunciation": ["もっとゆっくりはなしてもらえますか？", "Motto yukkuri hanashite moraemasu ka?"],
          "example": { "sentence": "ゆっくり話してください。", "translation": "請講慢一點。" },
          "usage_note": "請對方放慢速度。",
          "image_file": "speak_slowly.png"
        }
      ]
    },
     {
      "id": "pronouns",
      "name": "主詞（代名詞）",
      "items": [
        { "id": "pro-01", "term_zh": "我", "term_target": "私", "pronunciation": ["わたし", "Watashi"], "example": {"sentence": "私は台湾人です。", "translation": "我是台灣人。"}, "usage_note": "最通用的自稱。", "image_file": "i.png" },
        { "id": "pro-02", "term_zh": "你", "term_target": "あなた", "pronunciation": ["あなた", "Anata"], "example": {"sentence": "あなたは学生ですか？", "translation": "你是學生嗎？"}, "usage_note": "日文少直接用「你」，通常稱呼名字。", "image_file": "you.png" },
        { "id": "pro-03", "term_zh": "他", "term_target": "彼", "pronunciation": ["かれ", "Kare"], "example": {"sentence": "彼は先生です。", "translation": "他是老師。"}, "usage_note": "也可指男朋友。", "image_file": "he.png" },
        { "id": "pro-04", "term_zh": "她", "term_target": "彼女", "pronunciation": ["かのじょ", "Kanojo"], "example": {"sentence": "彼女は親切です。", "translation": "她很親切。"}, "usage_note": "也可指女朋友。", "image_file": "she.png" },
        { "id": "pro-05", "term_zh": "我們", "term_target": "私たち", "pronunciation": ["わたしたち", "Watashitachi"], "example": {"sentence": "私たちは家族です。", "translation": "我們是家人。"}, "usage_note": "複數形。", "image_file": "we.png" },
        { "id": "pro-06", "term_zh": "他們", "term_target": "彼ら", "pronunciation": ["かれら", "Karera"], "example": {"sentence": "彼らは学生です。", "translation": "他們是學生。"}, "usage_note": "指第三人稱複數。", "image_file": "they.png" },
        { "id": "pro-07", "term_zh": "這個", "term_target": "これ", "pronunciation": ["これ", "Kore"], "example": {"sentence": "これはペンです。", "translation": "這是筆。"}, "usage_note": "近處。", "image_file": "this.png" },
        { "id": "pro-08", "term_zh": "那個/它", "term_target": "それ / あれ", "pronunciation": ["それ / あれ", "Sore / Are"], "example": {"sentence": "それは何ですか？", "translation": "那個(你手上的)是什麼？"}, "usage_note": "Sore(對方那), Are(遠處)。", "image_file": "that.png" },
        { "id": "pro-09", "term_zh": "他的", "term_target": "彼の", "pronunciation": ["かれの", "Kare no"], "example": {"sentence": "彼の車。", "translation": "他的車。"}, "usage_note": "所有格加「の」。", "image_file": "his.png" },
        { "id": "pro-10", "term_zh": "她的", "term_target": "彼女の", "pronunciation": ["かのじょの", "Kanojo no"], "example": {"sentence": "彼女のカバン。", "translation": "她的包包。"}, "usage_note": "所有格。", "image_file": "her.png" },
        { "id": "pro-11", "term_zh": "你的", "term_target": "あなたの", "pronunciation": ["あなたの", "Anata no"], "example": {"sentence": "あなたの名前。", "translation": "你的名字。"}, "usage_note": "所有格。", "image_file": "your.png" },
        { "id": "pro-12", "term_zh": "他們的", "term_target": "彼らの", "pronunciation": ["かれらの", "Karera no"], "example": {"sentence": "彼らの家。", "translation": "他們的家。"}, "usage_note": "所有格。", "image_file": "their.png" },
        { "id": "pro-13", "term_zh": "我們的", "term_target": "私たちの", "pronunciation": ["わたしたちの", "Watashitachi no"], "example": {"sentence": "私たちの学校。", "translation": "我們的學校。"}, "usage_note": "所有格。", "image_file": "our.png" },
        { "id": "pro-14", "term_zh": "這些", "term_target": "これら", "pronunciation": ["これら", "Korera"], "example": {"sentence": "これらは本です。", "translation": "這些是書。"}, "usage_note": "近處複數。", "image_file": "these.png" },
        { "id": "pro-15", "term_zh": "那些", "term_target": "あれら", "pronunciation": ["あれら", "Arera"], "example": {"sentence": "あれらは鳥です。", "translation": "那些是鳥。"}, "usage_note": "遠處複數。", "image_file": "those.png" }
      ]
    },
    {
      "id": "verbs",
      "name": "動詞",
      "items": [
        { "id": "v-01", "term_zh": "是", "term_target": "です", "pronunciation": ["です", "Desu"], "example": {"sentence": "私は学生です。", "translation": "我是學生。"}, "usage_note": "句尾助動詞。", "image_file": "be.png" },
        { "id": "v-02", "term_zh": "有（擁有/存在）", "term_target": "あります / います", "pronunciation": ["あります / います", "Arimasu / Imasu"], "example": {"sentence": "お金があります。", "translation": "我有錢。"}, "usage_note": "物品用Arimasu，人用Imasu。", "image_file": "have.png" },
        { "id": "v-03", "term_zh": "去", "term_target": "行きます", "pronunciation": ["いきます", "Ikimasu"], "example": {"sentence": "家へ行きます。", "translation": "去家裡。"}, "usage_note": "移動。", "image_file": "go.png" },
        { "id": "v-04", "term_zh": "做", "term_target": "します", "pronunciation": ["します", "Shimasu"], "example": {"sentence": "宿題をします。", "translation": "做作業。"}, "usage_note": "執行動作。", "image_file": "do.png" },
        { "id": "v-05", "term_zh": "說", "term_target": "言います", "pronunciation": ["いいます", "Iimasu"], "example": {"sentence": "こんにちはと言います。", "translation": "說你好。"}, "usage_note": "說出內容。", "image_file": "say.png" },
        { "id": "v-06", "term_zh": "知道", "term_target": "知っています", "pronunciation": ["しっています", "Shitteimasu"], "example": {"sentence": "あなたを知っています。", "translation": "我認識你。"}, "usage_note": "表示狀態。", "image_file": "know.png" },
        { "id": "v-07", "term_zh": "想/思考", "term_target": "思います", "pronunciation": ["おもいます", "Omoimasu"], "example": {"sentence": "そう思います。", "translation": "我也這麼覺得。"}, "usage_note": "表達意見。", "image_file": "think.png" },
        { "id": "v-08", "term_zh": "看見", "term_target": "見ます", "pronunciation": ["みます", "Mimasu"], "example": {"sentence": "映画を見ます。", "translation": "看電影。"}, "usage_note": "觀看。", "image_file": "see.png" },
        { "id": "v-09", "term_zh": "製作", "term_target": "作ります", "pronunciation": ["つくります", "Tsukurimasu"], "example": {"sentence": "料理を作ります。", "translation": "做飯。"}, "usage_note": "製造。", "image_file": "make.png" },
        { "id": "v-10", "term_zh": "來", "term_target": "来ます", "pronunciation": ["きます", "Kimasu"], "example": {"sentence": "ここへ来ます。", "translation": "來這裡。"}, "usage_note": "前來。", "image_file": "come.png" },
        { "id": "v-11", "term_zh": "需要", "term_target": "いります", "pronunciation": ["いります", "Irimasu"], "example": {"sentence": "水がいります。", "translation": "需要水。"}, "usage_note": "需要。", "image_file": "need.png" },
        { "id": "v-12", "term_zh": "使用", "term_target": "使います", "pronunciation": ["つかいます", "Tsukaimasu"], "example": {"sentence": "ペンを使います。", "translation": "用筆。"}, "usage_note": "利用工具。", "image_file": "use.png" },
        { "id": "v-13", "term_zh": "找到", "term_target": "見つけます", "pronunciation": ["みつけます", "Mitsukemasu"], "example": {"sentence": "仕事を見つけます。", "translation": "找工作。"}, "usage_note": "發現。", "image_file": "find.png" },
        { "id": "v-14", "term_zh": "給", "term_target": "あげます", "pronunciation": ["あげます", "Agemasu"], "example": {"sentence": "これをあげます。", "translation": "給你這個。"}, "usage_note": "我給別人。", "image_file": "give.png" },
        { "id": "v-15", "term_zh": "告訴", "term_target": "教えます", "pronunciation": ["おしえます", "Oshiemasu"], "example": {"sentence": "名前を教えてください。", "translation": "請告訴我名字。"}, "usage_note": "教導或告知。", "image_file": "tell.png" },
        { "id": "v-16", "term_zh": "工作", "term_target": "働きます", "pronunciation": ["はたらきます", "Hatarakimasu"], "example": {"sentence": "ここで働きます。", "translation": "在這工作。"}, "usage_note": "勞動。", "image_file": "work.png" },
        { "id": "v-17", "term_zh": "喜歡", "term_target": "好きです", "pronunciation": ["すきです", "Suki desu"], "example": {"sentence": "猫が好きです。", "translation": "我喜歡貓。"}, "usage_note": "形容動詞。", "image_file": "like.png" },
        { "id": "v-18", "term_zh": "起床/醒來", "term_target": "起きます", "pronunciation": ["おきます", "Okimasu"], "example": {"sentence": "早く起きます。", "translation": "早起。"}, "usage_note": "起床。", "image_file": "wake_up.png" },
        { "id": "v-19", "term_zh": "說話", "term_target": "話します", "pronunciation": ["はなします", "Hanashimasu"], "example": {"sentence": "日本語を話します。", "translation": "說日文。"}, "usage_note": "交談。", "image_file": "speak.png" },
        { "id": "v-20", "term_zh": "聽見", "term_target": "聞こえます", "pronunciation": ["きこえます", "Kikoemasu"], "example": {"sentence": "聞こえますか？", "translation": "聽得見嗎？"}, "usage_note": "自然聽見。", "image_file": "hear.png" },
        { "id": "v-21", "term_zh": "寫", "term_target": "書きます", "pronunciation": ["かきます", "Kakimasu"], "example": {"sentence": "名前を書きます。", "translation": "寫名字。"}, "usage_note": "書寫。", "image_file": "write.png" },
        { "id": "v-22", "term_zh": "閱讀", "term_target": "読みます", "pronunciation": ["よみます", "Yomimasu"], "example": {"sentence": "本を読みます。", "translation": "看書。"}, "usage_note": "讀文字。", "image_file": "read.png" },
        { "id": "v-23", "term_zh": "等待", "term_target": "待ちます", "pronunciation": ["まちます", "Machimasu"], "example": {"sentence": "待ってください。", "translation": "請等一下。"}, "usage_note": "等候。", "image_file": "wait.png" },
        { "id": "v-24", "term_zh": "嘗試", "term_target": "やってみます", "pronunciation": ["やってみます", "Yattemimasu"], "example": {"sentence": "これをやってみます。", "translation": "試試看這個。"}, "usage_note": "試做。", "image_file": "try.png" },
        { "id": "v-25", "term_zh": "付錢", "term_target": "払います", "pronunciation": ["はらいます", "Haraimasu"], "example": {"sentence": "お金を払います。", "translation": "付錢。"}, "usage_note": "支付。", "image_file": "pay.png" },
        { "id": "v-26", "term_zh": "住", "term_target": "住みます", "pronunciation": ["すみます", "Sumimasu"], "example": {"sentence": "東京に住んでいます。", "translation": "住在東京。"}, "usage_note": "居住。", "image_file": "live.png" },
        { "id": "v-27", "term_zh": "走路", "term_target": "歩きます", "pronunciation": ["あるきます", "Arukimasu"], "example": {"sentence": "歩いて帰ります。", "translation": "走路回家。"}, "usage_note": "步行。", "image_file": "walk.png" },
        { "id": "v-28", "term_zh": "打開", "term_target": "開けます", "pronunciation": ["あけます", "Akemasu"], "example": {"sentence": "ドアを開けます。", "translation": "開門。"}, "usage_note": "開啟。", "image_file": "open.png" },
        { "id": "v-29", "term_zh": "關閉", "term_target": "閉めます", "pronunciation": ["しめます", "Shimemasu"], "example": {"sentence": "窓を閉めます。", "translation": "關窗。"}, "usage_note": "關上。", "image_file": "close.png" },
        { "id": "v-30", "term_zh": "幫助", "term_target": "手伝います", "pronunciation": ["てつだいます", "Tetsudaimasu"], "example": {"sentence": "手伝ってください。", "translation": "請幫我。"}, "usage_note": "協助。", "image_file": "help.png" },
        { "id": "v-31", "term_zh": "吃", "term_target": "食べます", "pronunciation": ["たべます", "Tabemasu"], "example": {"sentence": "ご飯を食べます。", "translation": "吃飯。"}, "usage_note": "進食。", "image_file": "eat.png" },
        { "id": "v-32", "term_zh": "睡覺", "term_target": "寝ます", "pronunciation": ["ねます", "Nemasu"], "example": {"sentence": "もう寝ます。", "translation": "要睡了。"}, "usage_note": "睡眠。", "image_file": "sleep.png" },
        { "id": "v-33", "term_zh": "買", "term_target": "買います", "pronunciation": ["かいます", "Kaimasu"], "example": {"sentence": "車を買います。", "translation": "買車。"}, "usage_note": "購買。", "image_file": "buy.png" },
        { "id": "v-34", "term_zh": "乘坐", "term_target": "乗ります", "pronunciation": ["のります", "Norimasu"], "example": {"sentence": "バスに乗ります。", "translation": "搭公車。"}, "usage_note": "搭乘交通工具。", "image_file": "take.png" },
        { "id": "v-35", "term_zh": "得到/拿", "term_target": "もらいます / とります", "pronunciation": ["もらいます / とります", "Moraimasu / Torimasu"], "example": {"sentence": "プレゼントをもらいます。", "translation": "收到禮物。"}, "usage_note": "拿取。", "image_file": "get.png" },
        { "id": "v-36", "term_zh": "選擇", "term_target": "選びます", "pronunciation": ["えらびます", "Erabimasu"], "example": {"sentence": "好きなのを選びます。", "translation": "選喜歡的。"}, "usage_note": "挑選。", "image_file": "choose.png" },
        { "id": "v-37", "term_zh": "進入", "term_target": "入ります", "pronunciation": ["はいります", "Hairimasu"], "example": {"sentence": "部屋に入ります。", "translation": "進房間。"}, "usage_note": "進入。", "image_file": "enter.png" },
        { "id": "v-38", "term_zh": "到達", "term_target": "着きます", "pronunciation": ["つきます", "Tsukimasu"], "example": {"sentence": "駅に着きます。", "translation": "到達車站。"}, "usage_note": "抵達。", "image_file": "arrive.png" },
        { "id": "v-39", "term_zh": "帶來", "term_target": "持ってきます", "pronunciation": ["もってきます", "Mottekimasu"], "example": {"sentence": "傘を持ってきます。", "translation": "帶傘來。"}, "usage_note": "攜帶。", "image_file": "bring.png" },
        { "id": "v-40", "term_zh": "變成", "term_target": "なります", "pronunciation": ["なります", "Narimasu"], "example": {"sentence": "先生になります。", "translation": "變成老師。"}, "usage_note": "變化。", "image_file": "become.png" },
        { "id": "v-41", "term_zh": "開始", "term_target": "始めます", "pronunciation": ["はじめます", "Hajimemasu"], "example": {"sentence": "勉強を始めます。", "translation": "開始讀書。"}, "usage_note": "開始。", "image_file": "start.png" },
        { "id": "v-42", "term_zh": "結束", "term_target": "終わります", "pronunciation": ["おわります", "Owarimasu"], "example": {"sentence": "仕事が終わります。", "translation": "工作結束。"}, "usage_note": "結束。", "image_file": "finish.png" },
        { "id": "v-43", "term_zh": "停止", "term_target": "止まります", "pronunciation": ["とまります", "Tomarimasu"], "example": {"sentence": "車が止まります。", "translation": "車子停下。"}, "usage_note": "停止。", "image_file": "stop.png" },
        { "id": "v-44", "term_zh": "記住", "term_target": "覚えています", "pronunciation": ["おぼえています", "Oboeteimasu"], "example": {"sentence": "単語を覚えます。", "translation": "記單字。"}, "usage_note": "記憶。", "image_file": "remember.png" },
        { "id": "v-45", "term_zh": "見面", "term_target": "会います", "pronunciation": ["あいます", "Aimasu"], "example": {"sentence": "友達に会います。", "translation": "見朋友。"}, "usage_note": "會面。", "image_file": "meet.png" },
        { "id": "v-46", "term_zh": "放", "term_target": "置きます", "pronunciation": ["おきます", "Okimasu"], "example": {"sentence": "ここに置きます。", "translation": "放這裡。"}, "usage_note": "放置。", "image_file": "put.png" },
        { "id": "v-47", "term_zh": "寄送", "term_target": "送ります", "pronunciation": ["おくります", "Okurimasu"], "example": {"sentence": "メールを送ります。", "translation": "寄信。"}, "usage_note": "傳送。", "image_file": "send.png" },
        { "id": "v-48", "term_zh": "開車", "term_target": "運転します", "pronunciation": ["うんてんします", "Untenshimasu"], "example": {"sentence": "車を運転します。", "translation": "開車。"}, "usage_note": "駕駛。", "image_file": "drive.png" },
        { "id": "v-49", "term_zh": "讀書", "term_target": "勉強します", "pronunciation": ["べんきょうします", "Benkyoushimasu"], "example": {"sentence": "日本語を勉強します。", "translation": "讀日文。"}, "usage_note": "學習。", "image_file": "study.png" },
        { "id": "v-50", "term_zh": "回去", "term_target": "帰ります", "pronunciation": ["かえります", "Kaerimasu"], "example": {"sentence": "家へ帰ります。", "translation": "回家。"}, "usage_note": "歸返。", "image_file": "go_back.png" }
      ]
    },
    {
      "id": "adjectives",
      "name": "形容詞",
      "items": [
        { "id": "adj-01", "term_zh": "好的", "term_target": "いい", "pronunciation": ["いい", "Ii"], "example": {"sentence": "いい天気です。", "translation": "好天氣。"}, "usage_note": "正面。", "image_file": "good.png" },
        { "id": "adj-02", "term_zh": "壞的", "term_target": "悪い", "pronunciation": ["わるい", "Warui"], "example": {"sentence": "気分が悪いです。", "translation": "不舒服/心情不好。"}, "usage_note": "負面。", "image_file": "bad.png" },
        { "id": "adj-03", "term_zh": "新的", "term_target": "新しい", "pronunciation": ["あたらしい", "Atarashii"], "example": {"sentence": "新しいスマホ。", "translation": "新手機。"}, "usage_note": "全新。", "image_file": "new.png" },
        { "id": "adj-04", "term_zh": "大的", "term_target": "大きい", "pronunciation": ["おおきい", "Ookii"], "example": {"sentence": "大きい家。", "translation": "大房子。"}, "usage_note": "體積大。", "image_file": "big.png" },
        { "id": "adj-05", "term_zh": "小的", "term_target": "小さい", "pronunciation": ["ちいさい", "Chiisai"], "example": {"sentence": "小さいサイズ。", "translation": "小尺寸。"}, "usage_note": "體積小。", "image_file": "small.png" },
        { "id": "adj-06", "term_zh": "熱的", "term_target": "暑い / 熱い", "pronunciation": ["あつい", "Atsui"], "example": {"sentence": "お湯が熱いです。", "translation": "熱水很燙。"}, "usage_note": "天氣用「暑」，物體用「熱」。", "image_file": "hot.png" },
        { "id": "adj-07", "term_zh": "冷的", "term_target": "寒い / 冷たい", "pronunciation": ["さむい / つめたい", "Samui / Tsumetai"], "example": {"sentence": "今日は寒いです。", "translation": "今天好冷。"}, "usage_note": "天氣用「寒」，物體用「冷」。", "image_file": "cold.png" },
        { "id": "adj-08", "term_zh": "簡單的", "term_target": "簡単", "pronunciation": ["かんたん", "Kantan"], "example": {"sentence": "これは簡単です。", "translation": "這很簡單。"}, "usage_note": "容易。", "image_file": "easy.png" },
        { "id": "adj-09", "term_zh": "困難的", "term_target": "難しい", "pronunciation": ["むずかしい", "Muzukashii"], "example": {"sentence": "日本語は難しいです。", "translation": "日文很難。"}, "usage_note": "難。", "image_file": "difficult.png" },
        { "id": "adj-10", "term_zh": "美味的", "term_target": "おいしい", "pronunciation": ["おいしい", "Oishii"], "example": {"sentence": "おいしい料理。", "translation": "好吃的菜。"}, "usage_note": "好吃。", "image_file": "delicious.png" },
        { "id": "adj-11", "term_zh": "忙碌的", "term_target": "忙しい", "pronunciation": ["いそがしい", "Isogashii"], "example": {"sentence": "仕事が忙しいです。", "translation": "工作很忙。"}, "usage_note": "沒空。", "image_file": "busy.png" },
        { "id": "adj-12", "term_zh": "疲累的", "term_target": "疲れた", "pronunciation": ["つかれた", "Tsukareta"], "example": {"sentence": "疲れました。", "translation": "累了。"}, "usage_note": "狀態。", "image_file": "tired.png" },
        { "id": "adj-13", "term_zh": "快樂的/高興的", "term_target": "嬉しい", "pronunciation": ["うれしい", "Ureshii"], "example": {"sentence": "会えて嬉しいです。", "translation": "見到你很高興。"}, "usage_note": "心情。", "image_file": "happy.png" },
        { "id": "adj-14", "term_zh": "悲傷的", "term_target": "悲しい", "pronunciation": ["かなしい", "Kanashii"], "example": {"sentence": "悲しいニュース。", "translation": "悲傷的新聞。"}, "usage_note": "難過。", "image_file": "sad.png" },
        { "id": "adj-15", "term_zh": "乾淨的/漂亮的", "term_target": "きれい", "pronunciation": ["きれい", "Kirei"], "example": {"sentence": "きれいな部屋。", "translation": "乾淨的房間。"}, "usage_note": "也可指美麗。", "image_file": "clean.png" },
        { "id": "adj-16", "term_zh": "髒的", "term_target": "汚い", "pronunciation": ["きたない", "Kitanai"], "example": {"sentence": "手が汚いです。", "translation": "手很髒。"}, "usage_note": "不乾淨。", "image_file": "dirty.png" },
        { "id": "adj-17", "term_zh": "便宜的", "term_target": "安い", "pronunciation": ["やすい", "Yasui"], "example": {"sentence": "これは安いです。", "translation": "這很便宜。"}, "usage_note": "價格低。", "image_file": "cheap.png" },
        { "id": "adj-18", "term_zh": "昂貴的", "term_target": "高い", "pronunciation": ["たかい", "Takai"], "example": {"sentence": "値段が高いです。", "translation": "價格很貴。"}, "usage_note": "價格高。", "image_file": "expensive.png" },
        { "id": "adj-19", "term_zh": "重要的", "term_target": "大切", "pronunciation": ["たいせつ", "Taisetsu"], "example": {"sentence": "大切な友達。", "translation": "重要的朋友。"}, "usage_note": "珍貴。", "image_file": "important.png" },
        { "id": "adj-20", "term_zh": "相同的", "term_target": "同じ", "pronunciation": ["おなじ", "Onaji"], "example": {"sentence": "同じ場所。", "translation": "同個地方。"}, "usage_note": "一樣。", "image_file": "same.png" },
        { "id": "adj-21", "term_zh": "第一的", "term_target": "一番", "pronunciation": ["いちばん", "Ichiban"], "example": {"sentence": "一番好きです。", "translation": "最喜歡。"}, "usage_note": "順序或程度。", "image_file": "first.png" },
        { "id": "adj-22", "term_zh": "上一個", "term_target": "前の", "pronunciation": ["まえの", "Mae no"], "example": {"sentence": "前の日。", "translation": "前一天。"}, "usage_note": "之前的。", "image_file": "last.png" },
        { "id": "adj-23", "term_zh": "下一個", "term_target": "次の", "pronunciation": ["つぎの", "Tsugi no"], "example": {"sentence": "次の駅。", "translation": "下一站。"}, "usage_note": "接下來。", "image_file": "next.png" },
        { "id": "adj-24", "term_zh": "長的", "term_target": "長い", "pronunciation": ["ながい", "Nagai"], "example": {"sentence": "長い髪。", "translation": "長髮。"}, "usage_note": "長度。", "image_file": "long.png" },
        { "id": "adj-25", "term_zh": "多的", "term_target": "多い", "pronunciation": ["おおい", "Ooi"], "example": {"sentence": "人が多い。", "translation": "人很多。"}, "usage_note": "數量多。", "image_file": "many.png" },
        { "id": "adj-26", "term_zh": "高的", "term_target": "高い", "pronunciation": ["たかい", "Takai"], "example": {"sentence": "背が高い。", "translation": "個子高。"}, "usage_note": "高度。", "image_file": "tall.png" },
        { "id": "adj-27", "term_zh": "年輕的", "term_target": "若い", "pronunciation": ["わかい", "Wakai"], "example": {"sentence": "若い人。", "translation": "年輕人。"}, "usage_note": "年紀小。", "image_file": "young.png" },
        { "id": "adj-28", "term_zh": "老的/舊的", "term_target": "古い", "pronunciation": ["ふるい", "Furui"], "example": {"sentence": "古い本。", "translation": "舊書。"}, "usage_note": "物品舊。老人用「年寄り」。", "image_file": "old.png" },
        { "id": "adj-29", "term_zh": "近的", "term_target": "近い", "pronunciation": ["ちかい", "Chikai"], "example": {"sentence": "駅に近い。", "translation": "離車站近。"}, "usage_note": "距離近。", "image_file": "near.png" },
        { "id": "adj-30", "term_zh": "遠的", "term_target": "遠い", "pronunciation": ["とおい", "Tooi"], "example": {"sentence": "家から遠い。", "translation": "離家遠。"}, "usage_note": "距離遠。", "image_file": "far.png" },
        { "id": "adj-31", "term_zh": "快的", "term_target": "速い", "pronunciation": ["はやい", "Hayai"], "example": {"sentence": "足が速い。", "translation": "跑得快。"}, "usage_note": "速度快。", "image_file": "fast.png" },
        { "id": "adj-32", "term_zh": "慢的", "term_target": "遅い", "pronunciation": ["おそい", "Osoi"], "example": {"sentence": "歩くのが遅い。", "translation": "走得慢。"}, "usage_note": "速度慢。", "image_file": "slow.png" },
        { "id": "adj-33", "term_zh": "正確的", "term_target": "正しい", "pronunciation": ["ただしい", "Tadashii"], "example": {"sentence": "正しい答え。", "translation": "正確答案。"}, "usage_note": "對的。", "image_file": "correct.png" },
        { "id": "adj-34", "term_zh": "錯誤的", "term_target": "間違い", "pronunciation": ["まちがい", "Machigai"], "example": {"sentence": "それは間違いです。", "translation": "那是錯的。"}, "usage_note": "名詞用法。", "image_file": "wrong.png" },
        { "id": "adj-35", "term_zh": "不同的", "term_target": "違う", "pronunciation": ["ちがう", "Chigau"], "example": {"sentence": "色が違う。", "translation": "顏色不同。"}, "usage_note": "動詞作形容用。", "image_file": "different.png" },
        { "id": "adj-36", "term_zh": "真的", "term_target": "本当の", "pronunciation": ["ほんとうの", "Hontou no"], "example": {"sentence": "本当の話。", "translation": "真的事。"}, "usage_note": "真實。", "image_file": "real.png" },
        { "id": "adj-37", "term_zh": "有趣的", "term_target": "面白い", "pronunciation": ["おもしろい", "Omoshiroi"], "example": {"sentence": "面白い映画。", "translation": "有趣的電影。"}, "usage_note": "好笑或有意思。", "image_file": "interesting.png" },
        { "id": "adj-38", "term_zh": "飢餓的", "term_target": "お腹が空いた", "pronunciation": ["おなかがすいた", "Onaka ga suita"], "example": {"sentence": "お腹が空きました。", "translation": "肚子餓了。"}, "usage_note": "慣用語。", "image_file": "hungry.png" },
        { "id": "adj-39", "term_zh": "有名的", "term_target": "有名", "pronunciation": ["ゆうめい", "Yuumei"], "example": {"sentence": "有名な人。", "translation": "有名的人。"}, "usage_note": "知名。", "image_file": "famous.png" },
        { "id": "adj-40", "term_zh": "外國的", "term_target": "外国の", "pronunciation": ["がいこくの", "Gaikoku no"], "example": {"sentence": "外国の車。", "translation": "外國車。"}, "usage_note": "國外。", "image_file": "foreign.png" },
        { "id": "adj-41", "term_zh": "聰明的", "term_target": "頭がいい", "pronunciation": ["あたまがいい", "Atama ga ii"], "example": {"sentence": "彼は頭がいい。", "translation": "他很聰明。"}, "usage_note": "腦袋好。", "image_file": "intelligent.png" },
        { "id": "adj-42", "term_zh": "危險的", "term_target": "危ない", "pronunciation": ["あぶない", "Abunai"], "example": {"sentence": "危ない！", "translation": "危險！"}, "usage_note": "警示。", "image_file": "dangerous.png" },
        { "id": "adj-43", "term_zh": "仁慈的", "term_target": "親切 / 優しい", "pronunciation": ["しんせつ / やさしい", "Shinsetsu / Yasashii"], "example": {"sentence": "親切な人。", "translation": "親切的人。"}, "usage_note": "溫柔。", "image_file": "kind.png" },
        { "id": "adj-44", "term_zh": "所有的", "term_target": "全て", "pronunciation": ["すべて", "Subete"], "example": {"sentence": "全ての人。", "translation": "所有的人。"}, "usage_note": "全部。", "image_file": "every.png" },
        { "id": "adj-45", "term_zh": "喜愛的", "term_target": "お気に入り", "pronunciation": ["おきにいり", "Okiniiri"], "example": {"sentence": "お気に入りの店。", "translation": "喜愛的店。"}, "usage_note": "中意。", "image_file": "favorite.png" }
      ]
    },
    {
      "id": "nouns",
      "name": "名詞",
      "items": [
        { "id": "n-01", "term_zh": "水", "term_target": "水", "pronunciation": ["みず", "Mizu"], "example": {"sentence": "水を飲みます。", "translation": "喝水。"}, "usage_note": "冷水。", "image_file": "water.png" },
        { "id": "n-02", "term_zh": "食物", "term_target": "食べ物", "pronunciation": ["たべもの", "Tabemono"], "example": {"sentence": "おいしい食べ物。", "translation": "好吃的食物。"}, "usage_note": "泛指食物。", "image_file": "food.png" },
        { "id": "n-03", "term_zh": "錢", "term_target": "お金", "pronunciation": ["おかね", "Okane"], "example": {"sentence": "お金がありません。", "translation": "沒錢。"}, "usage_note": "前面加O較禮貌。", "image_file": "money.png" },
        { "id": "n-04", "term_zh": "廁所", "term_target": "トイレ", "pronunciation": ["といれ", "Toire"], "example": {"sentence": "トイレに行きます。", "translation": "去廁所。"}, "usage_note": "外來語。", "image_file": "bathroom.png" },
        { "id": "n-05", "term_zh": "人", "term_target": "人", "pronunciation": ["ひと", "Hito"], "example": {"sentence": "あの人。", "translation": "那個人。"}, "usage_note": "泛指人。", "image_file": "people.png" },
        { "id": "n-06", "term_zh": "時間", "term_target": "時間", "pronunciation": ["じかん", "Jikan"], "example": {"sentence": "時間がありません。", "translation": "沒時間。"}, "usage_note": "時刻。", "image_file": "time.png" },
        { "id": "n-07", "term_zh": "朋友", "term_target": "友達", "pronunciation": ["ともだち", "Tomodachi"], "example": {"sentence": "私の友達。", "translation": "我朋友。"}, "usage_note": "友人。", "image_file": "friend.png" },
        { "id": "n-08", "term_zh": "家庭/家人", "term_target": "家族", "pronunciation": ["かぞく", "Kazoku"], "example": {"sentence": "大家族。", "translation": "大家庭。"}, "usage_note": "家人。", "image_file": "family.png" },
        { "id": "n-09", "term_zh": "手機", "term_target": "携帯 / スマホ", "pronunciation": ["けいたい / すまほ", "Keitai / Sumaho"], "example": {"sentence": "私のスマホ。", "translation": "我手機。"}, "usage_note": "智慧型手機常說 Sumaho。", "image_file": "phone.png" },
        { "id": "n-10", "term_zh": "車", "term_target": "車", "pronunciation": ["くるま", "Kuruma"], "example": {"sentence": "車を運転します。", "translation": "開車。"}, "usage_note": "汽車。", "image_file": "car.png" },
        { "id": "n-11", "term_zh": "巴士", "term_target": "バス", "pronunciation": ["ばす", "Basu"], "example": {"sentence": "バスに乗ります。", "translation": "搭公車。"}, "usage_note": "公車。", "image_file": "bus.png" },
        { "id": "n-12", "term_zh": "火車", "term_target": "電車", "pronunciation": ["でんしゃ", "Densha"], "example": {"sentence": "電車で行きます。", "translation": "搭電車去。"}, "usage_note": "電聯車。", "image_file": "train.png" },
        { "id": "n-13", "term_zh": "捷運/地鐵", "term_target": "地下鉄", "pronunciation": ["ちかてつ", "Chikatetsu"], "example": {"sentence": "地下鉄の駅。", "translation": "地鐵站。"}, "usage_note": "地下鐵。", "image_file": "subway.png" },
        { "id": "n-14", "term_zh": "車站", "term_target": "駅", "pronunciation": ["えき", "Eki"], "example": {"sentence": "駅はどこですか？", "translation": "車站在哪？"}, "usage_note": "站點。", "image_file": "station.png" },
        { "id": "n-15", "term_zh": "機場", "term_target": "空港", "pronunciation": ["くうこう", "Kuukou"], "example": {"sentence": "空港へ行きます。", "translation": "去機場。"}, "usage_note": "搭飛機處。", "image_file": "airport.png" },
        { "id": "n-16", "term_zh": "票", "term_target": "切符 / チケット", "pronunciation": ["きっぷ / ちけっと", "Kippu / Chiketto"], "example": {"sentence": "切符を買います。", "translation": "買車票。"}, "usage_note": "車票用 Kippu，入場券用 Chiketto。", "image_file": "ticket.png" },
        { "id": "n-17", "term_zh": "飯店", "term_target": "ホテル", "pronunciation": ["ほてる", "Hoteru"], "example": {"sentence": "ホテルを予約します。", "translation": "訂飯店。"}, "usage_note": "住宿。", "image_file": "hotel.png" },
        { "id": "n-18", "term_zh": "護照", "term_target": "パスポート", "pronunciation": ["ぱすぽーと", "Pasupooto"], "example": {"sentence": "パスポートを見せます。", "translation": "出示護照。"}, "usage_note": "出國必備。", "image_file": "passport.png" },
        { "id": "n-19", "term_zh": "地圖", "term_target": "地図", "pronunciation": ["ちず", "Chizu"], "example": {"sentence": "地図を見ます。", "translation": "看地圖。"}, "usage_note": "指引。", "image_file": "map.png" },
        { "id": "n-20", "term_zh": "警察", "term_target": "警察", "pronunciation": ["けいさつ", "Keisatsu"], "example": {"sentence": "警察を呼びます。", "translation": "叫警察。"}, "usage_note": "求救用。", "image_file": "police.png" },
        { "id": "n-21", "term_zh": "台灣人", "term_target": "台湾人", "pronunciation": ["たいわんじん", "Taiwanjin"], "example": {"sentence": "私は台湾人です。", "translation": "我是台灣人。"}, "usage_note": "國籍。", "image_file": "taiwanese.png" },
        { "id": "n-22", "term_zh": "孩子", "term_target": "子供", "pronunciation": ["こども", "Kodomo"], "example": {"sentence": "子供がいます。", "translation": "有孩子。"}, "usage_note": "兒童。", "image_file": "child.png" },
        { "id": "n-23", "term_zh": "學生", "term_target": "学生", "pronunciation": ["がくせい", "Gakusei"], "example": {"sentence": "私は学生です。", "translation": "我是學生。"}, "usage_note": "在學者。", "image_file": "student.png" },
        { "id": "n-24", "term_zh": "文化", "term_target": "文化", "pronunciation": ["ぶんか", "Bunka"], "example": {"sentence": "日本の文化。", "translation": "日本文化。"}, "usage_note": "文化。", "image_file": "culture.png" },
        { "id": "n-25", "term_zh": "問題", "term_target": "問題", "pronunciation": ["もんだい", "Mondai"], "example": {"sentence": "問題ありません。", "translation": "沒問題。"}, "usage_note": "難題。", "image_file": "problem.png" },
        { "id": "n-26", "term_zh": "公司", "term_target": "会社", "pronunciation": ["かいしゃ", "Kaisha"], "example": {"sentence": "会社へ行きます。", "translation": "去公司。"}, "usage_note": "上班地點。", "image_file": "company.png" },
        { "id": "n-27", "term_zh": "男性", "term_target": "男性", "pronunciation": ["だんせい", "Dansei"], "example": {"sentence": "男性用。", "translation": "男性用。"}, "usage_note": "性別。", "image_file": "man.png" },
        { "id": "n-28", "term_zh": "女性", "term_target": "女性", "pronunciation": ["じょせい", "Josei"], "example": {"sentence": "女性用。", "translation": "女性用。"}, "usage_note": "性別。", "image_file": "woman.png" },
        { "id": "n-29", "term_zh": "學校", "term_target": "学校", "pronunciation": ["がっこう", "Gakkou"], "example": {"sentence": "学校へ行きます。", "translation": "去學校。"}, "usage_note": "教育機構。", "image_file": "school.png" },
        { "id": "n-30", "term_zh": "老師", "term_target": "先生", "pronunciation": ["せんせい", "Sensei"], "example": {"sentence": "先生、こんにちは。", "translation": "老師好。"}, "usage_note": "師長。", "image_file": "teacher.png" },
        { "id": "n-31", "term_zh": "電影", "term_target": "映画", "pronunciation": ["えいが", "Eiga"], "example": {"sentence": "映画を見ます。", "translation": "看電影。"}, "usage_note": "影片。", "image_file": "movie.png" },
        { "id": "n-32", "term_zh": "電腦", "term_target": "パソコン", "pronunciation": ["ぱそこん", "Pasokon"], "example": {"sentence": "パソコンを使います。", "translation": "用電腦。"}, "usage_note": "PC。", "image_file": "computer.png" },
        { "id": "n-33", "term_zh": "市場", "term_target": "市場", "pronunciation": ["いちば", "Ichiba"], "example": {"sentence": "市場で買います。", "translation": "在市場買。"}, "usage_note": "市集。", "image_file": "market.png" },
        { "id": "n-34", "term_zh": "衣服", "term_target": "服", "pronunciation": ["ふく", "Fuku"], "example": {"sentence": "服を買います。", "translation": "買衣服。"}, "usage_note": "衣物。", "image_file": "clothes.png" },
        { "id": "n-35", "term_zh": "商店", "term_target": "店", "pronunciation": ["みせ", "Mise"], "example": {"sentence": "店に入ります。", "translation": "進店裡。"}, "usage_note": "店家。", "image_file": "shop.png" },
        { "id": "n-36", "term_zh": "街道", "term_target": "道", "pronunciation": ["みち", "Michi"], "example": {"sentence": "この道。", "translation": "這條路。"}, "usage_note": "道路。", "image_file": "street.png" },
        { "id": "n-37", "term_zh": "房子", "term_target": "家", "pronunciation": ["いえ", "Ie"], "example": {"sentence": "大きい家。", "translation": "大房子。"}, "usage_note": "住宅。", "image_file": "house.png" },
        { "id": "n-38", "term_zh": "母親", "term_target": "お母さん", "pronunciation": ["おかあさん", "Okaasan"], "example": {"sentence": "私のお母さん。", "translation": "我媽媽。"}, "usage_note": "媽媽。", "image_file": "mother.png" },
        { "id": "n-39", "term_zh": "父親", "term_target": "お父さん", "pronunciation": ["おとうさん", "Otoosan"], "example": {"sentence": "私のお父さん。", "translation": "我爸爸。"}, "usage_note": "爸爸。", "image_file": "father.png" },
        { "id": "n-40", "term_zh": "中文", "term_target": "中国語", "pronunciation": ["ちゅうごくご", "Chuugokugo"], "example": {"sentence": "中国語を話します。", "translation": "說中文。"}, "usage_note": "語言。", "image_file": "chinese.png" },
        { "id": "n-41", "term_zh": "包包", "term_target": "カバン", "pronunciation": ["かばん", "Kaban"], "example": {"sentence": "カバンを持ちます。", "translation": "拿包包。"}, "usage_note": "提包。", "image_file": "bag.png" },
        { "id": "n-42", "term_zh": "杯子", "term_target": "コップ", "pronunciation": ["こっぷ", "Koppu"], "example": {"sentence": "コップの水。", "translation": "杯子裡的水。"}, "usage_note": "杯具。", "image_file": "cup.png" },
        { "id": "n-43", "term_zh": "醫生", "term_target": "医者", "pronunciation": ["いしゃ", "Isha"], "example": {"sentence": "医者に行きます。", "translation": "看醫生。"}, "usage_note": "醫師。", "image_file": "doctor.png" },
        { "id": "n-44", "term_zh": "醫院", "term_target": "病院", "pronunciation": ["びょういん", "Byouin"], "example": {"sentence": "病院へ行きます。", "translation": "去醫院。"}, "usage_note": "醫療院所。", "image_file": "hospital.png" },
        { "id": "n-45", "term_zh": "座位", "term_target": "席", "pronunciation": ["せき", "Seki"], "example": {"sentence": "席がありますか？", "translation": "有位子嗎？"}, "usage_note": "位子。", "image_file": "seat.png" },
        { "id": "n-46", "term_zh": "門", "term_target": "ドア", "pronunciation": ["どあ", "Doa"], "example": {"sentence": "ドアを開けます。", "translation": "開門。"}, "usage_note": "門戶。", "image_file": "door.png" },
        { "id": "n-47", "term_zh": "房間", "term_target": "部屋", "pronunciation": ["へや", "Heya"], "example": {"sentence": "私の部屋。", "translation": "我房間。"}, "usage_note": "室內。", "image_file": "room.png" },
        { "id": "n-48", "term_zh": "行李", "term_target": "荷物", "pronunciation": ["にもつ", "Nimotsu"], "example": {"sentence": "荷物が多い。", "translation": "行李很多。"}, "usage_note": "包裹。", "image_file": "luggage.png" },
        { "id": "n-49", "term_zh": "櫃檯", "term_target": "カウンター", "pronunciation": ["かうんたー", "Kauntaa"], "example": {"sentence": "カウンターで払います。", "translation": "櫃檯結帳。"}, "usage_note": "服務台。", "image_file": "counter.png" },
        { "id": "n-50", "term_zh": "大廳", "term_target": "ロビー", "pronunciation": ["ろびー", "Robii"], "example": {"sentence": "ロビーで待ちます。", "translation": "大廳等。"}, "usage_note": "接待處。", "image_file": "lobby.png" },
        { "id": "n-51", "term_zh": "預定", "term_target": "予約", "pronunciation": ["よやく", "Yoyaku"], "example": {"sentence": "予約しました。", "translation": "預約了。"}, "usage_note": "預約。", "image_file": "reservation.png" },
        { "id": "n-52", "term_zh": "入住", "term_target": "チェックイン", "pronunciation": ["ちぇっくいん", "Chekkuin"], "example": {"sentence": "チェックインお願いします。", "translation": "麻煩辦理入住。"}, "usage_note": "Check-in。", "image_file": "check_in.png" },
        { "id": "n-53", "term_zh": "退房", "term_target": "チェックアウト", "pronunciation": ["ちぇっくあうと", "Chekkuauto"], "example": {"sentence": "チェックアウトは何時ですか？", "translation": "退房是幾點？"}, "usage_note": "Check-out。", "image_file": "check_out.png" },
        { "id": "n-54", "term_zh": "飲料", "term_target": "飲み物", "pronunciation": ["のみもの", "Nomimono"], "example": {"sentence": "飲み物は？", "translation": "飲料呢？"}, "usage_note": "飲品。", "image_file": "drink.png" },
        { "id": "n-55", "term_zh": "菜單", "term_target": "メニュー", "pronunciation": ["めにゅー", "Menyuu"], "example": {"sentence": "メニューをください。", "translation": "請給菜單。"}, "usage_note": "Menu。", "image_file": "menu.png" },
        { "id": "n-56", "term_zh": "午餐", "term_target": "昼ごはん", "pronunciation": ["ひるごはん", "Hirugohan"], "example": {"sentence": "昼ごはんを食べます。", "translation": "吃午餐。"}, "usage_note": "中餐。", "image_file": "lunch.png" },
        { "id": "n-57", "term_zh": "晚餐", "term_target": "晩ごはん", "pronunciation": ["ばんごはん", "Bangohan"], "example": {"sentence": "晩ごはんを食べます。", "translation": "吃晚餐。"}, "usage_note": "晚餐。", "image_file": "dinner.png" },
        { "id": "n-58", "term_zh": "帳單", "term_target": "お会計", "pronunciation": ["おかいけい", "Okaikei"], "example": {"sentence": "お会計お願いします。", "translation": "麻煩結帳。"}, "usage_note": "買單。", "image_file": "bill.png" },
        { "id": "n-59", "term_zh": "價錢", "term_target": "値段", "pronunciation": ["ねだん", "Nedan"], "example": {"sentence": "値段が高い。", "translation": "價錢高。"}, "usage_note": "價格。", "image_file": "price.png" },
        { "id": "n-60", "term_zh": "收據", "term_target": "レシート", "pronunciation": ["れしーと", "Reshiito"], "example": {"sentence": "レシートください。", "translation": "請給收據。"}, "usage_note": "統一發票。", "image_file": "receipt.png" },
        { "id": "n-61", "term_zh": "尺寸", "term_target": "サイズ", "pronunciation": ["さいず", "Saizu"], "example": {"sentence": "サイズが合わない。", "translation": "尺寸不合。"}, "usage_note": "大小。", "image_file": "size.png" },
        { "id": "n-62", "term_zh": "入口", "term_target": "入口", "pronunciation": ["いりぐち", "Iriguchi"], "example": {"sentence": "入口はどこ？", "translation": "入口在哪？"}, "usage_note": "進去的地方。", "image_file": "entrance.png" },
        { "id": "n-63", "term_zh": "出口", "term_target": "出口", "pronunciation": ["でぐち", "Deguchi"], "example": {"sentence": "出口はあそこ。", "translation": "出口在那。"}, "usage_note": "出去的地方。", "image_file": "exit.png" },
        { "id": "n-64", "term_zh": "台灣", "term_target": "台湾", "pronunciation": ["たいわん", "Taiwan"], "example": {"sentence": "台湾から来ました。", "translation": "來自台灣。"}, "usage_note": "地名。", "image_file": "taiwan.png" },
        { "id": "n-65", "term_zh": "一切事物", "term_target": "全部", "pronunciation": ["ぜんぶ", "Zenbu"], "example": {"sentence": "全部好き。", "translation": "全部喜歡。"}, "usage_note": "所有。", "image_file": "everything.png" },
        { "id": "n-66", "term_zh": "錢包", "term_target": "財布", "pronunciation": ["さいふ", "Saifu"], "example": {"sentence": "財布を忘れた。", "translation": "忘了錢包。"}, "usage_note": "皮夾。", "image_file": "wallet.png" },
        { "id": "n-67", "term_zh": "身分證", "term_target": "身分証", "pronunciation": ["みぶんしょう", "Mibunshou"], "example": {"sentence": "身分証を見せる。", "translation": "出示證件。"}, "usage_note": "ID。", "image_file": "id.png" },
        { "id": "n-68", "term_zh": "餐廳", "term_target": "レストラン", "pronunciation": ["れすとらん", "Resutoran"], "example": {"sentence": "いいレストラン。", "translation": "好的餐廳。"}, "usage_note": "食堂。", "image_file": "restaurant.png" },
        { "id": "n-69", "term_zh": "場所", "term_target": "場所", "pronunciation": ["ばしょ", "Basho"], "example": {"sentence": "場所はどこ？", "translation": "地點在哪？"}, "usage_note": "地點。", "image_file": "place.png" },
        { "id": "n-70", "term_zh": "店員", "term_target": "店員", "pronunciation": ["てんいん", "Tenin"], "example": {"sentence": "店員を呼ぶ。", "translation": "叫店員。"}, "usage_note": "工作人員。", "image_file": "clerk.png" },
        { "id": "n-71", "term_zh": "超市", "term_target": "スーパー", "pronunciation": ["すーぱー", "Suupaa"], "example": {"sentence": "スーパーで買う。", "translation": "在超市買。"}, "usage_note": "量販店。", "image_file": "supermarket.png" },
        { "id": "n-72", "term_zh": "月台", "term_target": "ホーム", "pronunciation": ["ほーむ", "Hoomu"], "example": {"sentence": "ホームで待つ。", "translation": "在月台等。"}, "usage_note": "車站月台。", "image_file": "platform.png" }
      ]
    },
    {
      "id": "adverbs",
      "name": "副詞",
      "items": [
        { "id": "adv-01", "term_zh": "現在", "term_target": "今", "pronunciation": ["いま", "Ima"], "example": {"sentence": "今、行きます。", "translation": "現在去。"}, "usage_note": "目前。", "image_file": "now.png" },
        { "id": "adv-02", "term_zh": "非常", "term_target": "とても", "pronunciation": ["とても", "Totemo"], "example": {"sentence": "とてもおいしいです。", "translation": "非常好吃。"}, "usage_note": "強調。", "image_file": "very.png" },
        { "id": "adv-03", "term_zh": "真的", "term_target": "本当に", "pronunciation": ["ほんとうに", "Hontou ni"], "example": {"sentence": "本当に？", "translation": "真的嗎？"}, "usage_note": "確認或強調。", "image_file": "really.png" },
        { "id": "adv-04", "term_zh": "經常", "term_target": "よく", "pronunciation": ["よく", "Yoku"], "example": {"sentence": "よく来ます。", "translation": "常來。"}, "usage_note": "頻率。", "image_file": "often.png" },
        { "id": "adv-05", "term_zh": "通常", "term_target": "たいてい", "pronunciation": ["たいてい", "Taitei"], "example": {"sentence": "たいてい6時に起きます。", "translation": "通常六點起床。"}, "usage_note": "習慣。", "image_file": "usually.png" },
        { "id": "adv-06", "term_zh": "只有", "term_target": "だけ", "pronunciation": ["...だけ", "...dake"], "example": {"sentence": "これだけです。", "translation": "只有這個。"}, "usage_note": "唯一。", "image_file": "only.png" },
        { "id": "adv-07", "term_zh": "再次", "term_target": "また", "pronunciation": ["また", "Mata"], "example": {"sentence": "また来ます。", "translation": "會再來。"}, "usage_note": "重複。", "image_file": "again.png" },
        { "id": "adv-08", "term_zh": "一起", "term_target": "一緒に", "pronunciation": ["いっしょに", "Issho ni"], "example": {"sentence": "一緒に行きましょう。", "translation": "一起去吧。"}, "usage_note": "共同。", "image_file": "together.png" },
        { "id": "adv-09", "term_zh": "或許", "term_target": "たぶん", "pronunciation": ["たぶん", "Tabun"], "example": {"sentence": "たぶん大丈夫です。", "translation": "大概沒問題。"}, "usage_note": "不確定。", "image_file": "maybe.png" },
        { "id": "adv-10", "term_zh": "很快", "term_target": "すぐに", "pronunciation": ["すぐに", "Sugu ni"], "example": {"sentence": "すぐに行きます。", "translation": "馬上去。"}, "usage_note": "不久後。", "image_file": "soon.png" },
        { "id": "adv-11", "term_zh": "已經", "term_target": "もう", "pronunciation": ["もう", "Mou"], "example": {"sentence": "もう食べました。", "translation": "已經吃了。"}, "usage_note": "完成。", "image_file": "already.png" },
        { "id": "adv-12", "term_zh": "大約", "term_target": "ぐらい", "pronunciation": ["ぐらい", "Gurai"], "example": {"sentence": "10分ぐらい。", "translation": "大約10分鐘。"}, "usage_note": "概數。", "image_file": "about.png" },
        { "id": "adv-13", "term_zh": "一點點", "term_target": "少し", "pronunciation": ["すこし", "Sukoshi"], "example": {"sentence": "少し辛い。", "translation": "一點點辣。"}, "usage_note": "少量。", "image_file": "a_little.png" },
        { "id": "adv-14", "term_zh": "之後", "term_target": "あとで", "pronunciation": ["あとで", "Atode"], "example": {"sentence": "あとでやります。", "translation": "之後做。"}, "usage_note": "稍後。", "image_file": "later.png" },
        { "id": "adv-15", "term_zh": "仍然", "term_target": "まだ", "pronunciation": ["まだ", "Mada"], "example": {"sentence": "まだです。", "translation": "還沒。"}, "usage_note": "持續。", "image_file": "still.png" },
        { "id": "adv-16", "term_zh": "一般來說", "term_target": "普通", "pronunciation": ["ふつう", "Futsuu"], "example": {"sentence": "普通はそうです。", "translation": "一般是那樣。"}, "usage_note": "通常。", "image_file": "normally.png" }
      ]
    },
    {
      "id": "questions",
      "name": "疑問詞",
      "items": [
        { "id": "q-01", "term_zh": "什麼", "term_target": "何", "pronunciation": ["なに / なん", "Nani / Nan"], "example": {"sentence": "これは何ですか？", "translation": "這是什麼？"}, "usage_note": "問事物。", "image_file": "what.png" },
        { "id": "q-02", "term_zh": "哪裡", "term_target": "どこ", "pronunciation": ["どこ", "Doko"], "example": {"sentence": "どこですか？", "translation": "在哪裡？"}, "usage_note": "問地點。", "image_file": "where.png" },
        { "id": "q-03", "term_zh": "何時", "term_target": "いつ", "pronunciation": ["いつ", "Itsu"], "example": {"sentence": "いつ行きますか？", "translation": "何時去？"}, "usage_note": "問時間。", "image_file": "when.png" },
        { "id": "q-04", "term_zh": "誰", "term_target": "誰", "pronunciation": ["だれ", "Dare"], "example": {"sentence": "あれは誰ですか？", "translation": "那是誰？"}, "usage_note": "問人。", "image_file": "who.png" },
        { "id": "q-05", "term_zh": "為什麼", "term_target": "なぜ / どうして", "pronunciation": ["なぜ / どうして", "Naze / Doushite"], "example": {"sentence": "どうしてですか？", "translation": "為什麼？"}, "usage_note": "問原因。", "image_file": "why.png" },
        { "id": "q-06", "term_zh": "如何", "term_target": "どうやって", "pronunciation": ["どうやって", "Douyatte"], "example": {"sentence": "どうやって行きますか？", "translation": "怎麼去？"}, "usage_note": "問方法。", "image_file": "how.png" },
        { "id": "q-07", "term_zh": "多少(錢)", "term_target": "いくら", "pronunciation": ["いくら", "Ikura"], "example": {"sentence": "いくらですか？", "translation": "多少錢？"}, "usage_note": "問價格。", "image_file": "how_much.png" },
        { "id": "q-08", "term_zh": "多久/多少(量)", "term_target": "どのくらい", "pronunciation": ["どのくらい", "Dono kurai"], "example": {"sentence": "どのくらいかかりますか？", "translation": "要花多久？"}, "usage_note": "問程度或時間長度。", "image_file": "how_long.png" },
        { "id": "q-09", "term_zh": "哪一個", "term_target": "どれ", "pronunciation": ["どれ", "Dore"], "example": {"sentence": "どれですか？", "translation": "哪一個？"}, "usage_note": "選擇。", "image_file": "which.png" }
      ]
    },
    {
      "id": "time_place",
      "name": "時間與場所",
      "items": [
        { "id": "tp-01", "term_zh": "今天", "term_target": "今日", "pronunciation": ["きょう", "Kyou"], "example": {"sentence": "今日は暑いです。", "translation": "今天很熱。"}, "usage_note": "本日。", "image_file": "today.png" },
        { "id": "tp-02", "term_zh": "明天", "term_target": "明日", "pronunciation": ["あした", "Ashita"], "example": {"sentence": "また明日。", "translation": "明天見。"}, "usage_note": "隔天。", "image_file": "tomorrow.png" },
        { "id": "tp-03", "term_zh": "昨天", "term_target": "昨日", "pronunciation": ["きのう", "Kinou"], "example": {"sentence": "昨日は楽しかったです。", "translation": "昨天很開心。"}, "usage_note": "前一天。", "image_file": "yesterday.png" },
        { "id": "tp-04", "term_zh": "這裡", "term_target": "ここ", "pronunciation": ["ここ", "Koko"], "example": {"sentence": "ここに来てください。", "translation": "請來這裡。"}, "usage_note": "近處。", "image_file": "here.png" },
        { "id": "tp-05", "term_zh": "那裡", "term_target": "そこ / あそこ", "pronunciation": ["そこ / あそこ", "Soko / Asoko"], "example": {"sentence": "あそこに行きます。", "translation": "去那裡。"}, "usage_note": "Soko(對方那), Asoko(遠處)。", "image_file": "there.png" },
        { "id": "tp-06", "term_zh": "早上", "term_target": "朝", "pronunciation": ["あさ", "Asa"], "example": {"sentence": "朝ごはん。", "translation": "早餐。"}, "usage_note": "上午。", "image_file": "morning.png" },
        { "id": "tp-07", "term_zh": "晚上/夜晚", "term_target": "夜", "pronunciation": ["よる", "Yoru"], "example": {"sentence": "夜ごはん。", "translation": "晚餐。"}, "usage_note": "太陽下山後。", "image_file": "night.png" },
        { "id": "tp-08", "term_zh": "前面", "term_target": "前", "pronunciation": ["まえ", "Mae"], "example": {"sentence": "駅の前。", "translation": "車站前。"}, "usage_note": "前方。", "image_file": "front.png" },
        { "id": "tp-09", "term_zh": "後面", "term_target": "後ろ", "pronunciation": ["うしろ", "Ushiro"], "example": {"sentence": "ドアの後ろ。", "translation": "門後。"}, "usage_note": "後方。", "image_file": "behind.png" },
        { "id": "tp-10", "term_zh": "左邊", "term_target": "左", "pronunciation": ["ひだり", "Hidari"], "example": {"sentence": "左に曲がります。", "translation": "左轉。"}, "usage_note": "左。", "image_file": "left.png" },
        { "id": "tp-11", "term_zh": "右邊", "term_target": "右", "pronunciation": ["みぎ", "Migi"], "example": {"sentence": "右を見てください。", "translation": "請看右邊。"}, "usage_note": "右。", "image_file": "right.png" },
        { "id": "tp-12", "term_zh": "天(日)", "term_target": "日", "pronunciation": ["ひ", "Hi"], "example": {"sentence": "ある日。", "translation": "某一天。"}, "usage_note": "日子。", "image_file": "day.png" },
        { "id": "tp-13", "term_zh": "年", "term_target": "年", "pronunciation": ["とし", "Toshi"], "example": {"sentence": "今年。", "translation": "今年。"}, "usage_note": "年度。", "image_file": "year.png" },
        { "id": "tp-14", "term_zh": "月", "term_target": "月", "pronunciation": ["つき", "Tsuki"], "example": {"sentence": "今月。", "translation": "這個月。"}, "usage_note": "月份。", "image_file": "month.png" },
        { "id": "tp-15", "term_zh": "週", "term_target": "週", "pronunciation": ["しゅう", "Shuu"], "example": {"sentence": "来週。", "translation": "下週。"}, "usage_note": "星期。", "image_file": "week.png" },
        { "id": "tp-16", "term_zh": "下午", "term_target": "午後", "pronunciation": ["ごご", "Gogo"], "example": {"sentence": "午後2時。", "translation": "下午2點。"}, "usage_note": "PM。", "image_file": "afternoon.png" },
        { "id": "tp-17", "term_zh": "中午", "term_target": "正午 / お昼", "pronunciation": ["しょうご / おひる", "Shougo / Ohiru"], "example": {"sentence": "お昼です。", "translation": "是中午。"}, "usage_note": "12點。", "image_file": "noon.png" },
        { "id": "tp-18", "term_zh": "旁邊", "term_target": "横 / 隣", "pronunciation": ["よこ / となり", "Yoko / Tonari"], "example": {"sentence": "私の隣。", "translation": "我旁邊。"}, "usage_note": "側邊。", "image_file": "beside.png" },
        { "id": "tp-19", "term_zh": "對面", "term_target": "向かい", "pronunciation": ["むかい", "Mukai"], "example": {"sentence": "駅の向かい。", "translation": "車站對面。"}, "usage_note": "對側。", "image_file": "across_from.png" },
        { "id": "tp-20", "term_zh": "春天", "term_target": "春", "pronunciation": ["はる", "Haru"], "example": {"sentence": "春が来た。", "translation": "春天來了。"}, "usage_note": "季節。", "image_file": "spring.png" },
        { "id": "tp-21", "term_zh": "夏天", "term_target": "夏", "pronunciation": ["なつ", "Natsu"], "example": {"sentence": "暑い夏。", "translation": "炎熱的夏天。"}, "usage_note": "季節。", "image_file": "summer.png" },
        { "id": "tp-22", "term_zh": "秋天", "term_target": "秋", "pronunciation": ["あき", "Aki"], "example": {"sentence": "秋が好き。", "translation": "喜歡秋天。"}, "usage_note": "季節。", "image_file": "autumn.png" },
        { "id": "tp-23", "term_zh": "冬天", "term_target": "冬", "pronunciation": ["ふゆ", "Fuyu"], "example": {"sentence": "冬は寒い。", "translation": "冬天很冷。"}, "usage_note": "季節。", "image_file": "winter.png" }
      ]
    },
    {
      "id": "numbers",
      "name": "數字",
      "items": [
        { "id": "num-0", "term_zh": "0", "term_target": "ゼロ", "pronunciation": ["ぜろ", "Zero"], "example": {"sentence": "ゼロです。", "translation": "是零。"}, "usage_note": "零。", "image_file": "zero.png" },
        { "id": "num-1", "term_zh": "1", "term_target": "一", "pronunciation": ["いち", "Ichi"], "example": {"sentence": "一つください。", "translation": "請給我一個 (Hitotsu)。"}, "usage_note": "數數用Ichi，點餐常用Hitotsu。", "image_file": "one.png" },
        { "id": "num-2", "term_zh": "2", "term_target": "二", "pronunciation": ["に", "Ni"], "example": {"sentence": "二つください。", "translation": "請給我兩個 (Futatsu)。"}, "usage_note": "數數用Ni，點餐常用Futatsu。", "image_file": "two.png" },
        { "id": "num-3", "term_zh": "3", "term_target": "三", "pronunciation": ["さん", "San"], "example": {"sentence": "三つください。", "translation": "請給我三個 (Mittsu)。"}, "usage_note": "數數用San，點餐常用Mittsu。", "image_file": "three.png" },
        { "id": "num-4", "term_zh": "4", "term_target": "四", "pronunciation": ["よん / し", "Yon / Shi"], "example": {"sentence": "四時。", "translation": "四點 (Yoji)。"}, "usage_note": "通常念Yon。", "image_file": "four.png" },
        { "id": "num-5", "term_zh": "5", "term_target": "五", "pronunciation": ["ご", "Go"], "example": {"sentence": "五つください。", "translation": "請給我五個 (Itsutsu)。"}, "usage_note": "五。", "image_file": "five.png" },
        { "id": "num-6", "term_zh": "6", "term_target": "六", "pronunciation": ["ろく", "Roku"], "example": {"sentence": "六つ。", "translation": "六個 (Muttsu)。"}, "usage_note": "六。", "image_file": "six.png" },
        { "id": "num-7", "term_zh": "7", "term_target": "七", "pronunciation": ["なな / しち", "Nana / Shichi"], "example": {"sentence": "七時。", "translation": "七點 (Shichiji)。"}, "usage_note": "通常念Nana。", "image_file": "seven.png" },
        { "id": "num-8", "term_zh": "8", "term_target": "八", "pronunciation": ["はち", "Hachi"], "example": {"sentence": "八つ。", "translation": "八個 (Yattsu)。"}, "usage_note": "八。", "image_file": "eight.png" },
        { "id": "num-9", "term_zh": "9", "term_target": "九", "pronunciation": ["きゅう / く", "Kyuu / Ku"], "example": {"sentence": "九時。", "translation": "九點 (Kuji)。"}, "usage_note": "通常念Kyuu。", "image_file": "nine.png" },
        { "id": "num-10", "term_zh": "10", "term_target": "十", "pronunciation": ["じゅう", "Juu"], "example": {"sentence": "十個。", "translation": "十個 (Jukko)。"}, "usage_note": "十。", "image_file": "ten.png" },
        { "id": "num-11", "term_zh": "11", "term_target": "十一", "pronunciation": ["じゅういち", "Juuichi"], "example": {"sentence": "11時。", "translation": "11點。"}, "usage_note": "十一。", "image_file": "eleven.png" },
        { "id": "num-12", "term_zh": "12", "term_target": "十二", "pronunciation": ["じゅうに", "Juuni"], "example": {"sentence": "12月。", "translation": "12月。"}, "usage_note": "十二。", "image_file": "twelve.png" },
        { "id": "num-15", "term_zh": "15", "term_target": "十五", "pronunciation": ["じゅうご", "Juugo"], "example": {"sentence": "15分。", "translation": "15分。"}, "usage_note": "十五。", "image_file": "fifteen.png" },
        { "id": "num-20", "term_zh": "20", "term_target": "二十", "pronunciation": ["にじゅう", "Nijuu"], "example": {"sentence": "二十円。", "translation": "二十圓。"}, "usage_note": "二十。", "image_file": "twenty.png" },
        { "id": "num-50", "term_zh": "50", "term_target": "五十", "pronunciation": ["ごじゅう", "Gojuu"], "example": {"sentence": "五十人。", "translation": "五十人。"}, "usage_note": "五十。", "image_file": "fifty.png" },
        { "id": "num-100", "term_zh": "100", "term_target": "百", "pronunciation": ["ひゃく", "Hyaku"], "example": {"sentence": "百円。", "translation": "一百圓。"}, "usage_note": "百。", "image_file": "hundred.png" },
        { "id": "num-1000", "term_zh": "1000", "term_target": "千", "pronunciation": ["せん", "Sen"], "example": {"sentence": "一千円。", "translation": "一千圓 (Issenen)。"}, "usage_note": "千。", "image_file": "thousand.png" },
        { "id": "num-10000", "term_zh": "10000", "term_target": "一万", "pronunciation": ["いちまん", "Ichiman"], "example": {"sentence": "一万円。", "translation": "一萬圓。"}, "usage_note": "一萬。", "image_file": "ten_thousand.png" }
      ]
    },
    {
      "id": "grammar",
      "name": "基本句型",
      "items": [
        { "id": "g-01", "term_zh": "我是...", "term_target": "私は...です", "pronunciation": ["わたしは...です", "Watashi wa ... desu"], "example": {"sentence": "私は学生です。", "translation": "我是學生。"}, "usage_note": "最基本的肯定句。", "image_file": "i_am.png" },
        { "id": "g-02", "term_zh": "我正在...", "term_target": "私は...しています", "pronunciation": ["わたしは...しています", "Watashi wa ... shiteimasu"], "example": {"sentence": "私は食べています。", "translation": "我正在吃。"}, "usage_note": "進行式 (Te形+imasu)。", "image_file": "ing.png" },
        { "id": "g-03", "term_zh": "我能夠(會)...", "term_target": "私は...できます", "pronunciation": ["わたしは...できます", "Watashi wa ... dekimasu"], "example": {"sentence": "私は運転できます。", "translation": "我會開車。"}, "usage_note": "能力。", "image_file": "can.png" },
        { "id": "g-04", "term_zh": "我喜歡做...", "term_target": "私は...が好きです", "pronunciation": ["わたしは...がすきです", "Watashi wa ... ga suki desu"], "example": {"sentence": "私は読書が好きです。", "translation": "我喜歡閱讀。"}, "usage_note": "興趣。", "image_file": "like_ing.png" },
        { "id": "g-05", "term_zh": "我想做...", "term_target": "...たいです", "pronunciation": ["...たいです", "...tai desu"], "example": {"sentence": "行きたいです。", "translation": "我想去。"}, "usage_note": "動詞Masu形去掉Masu加Tai desu。", "image_file": "want_to.png" },
        { "id": "g-06", "term_zh": "你是...嗎?", "term_target": "あなたは...ですか？", "pronunciation": ["あなたは...ですか？", "Anata wa ... desu ka?" ], "example": {"sentence": "あなたは学生ですか？", "translation": "你是學生嗎？"}, "usage_note": "問句尾加 ka。", "image_file": "are_you.png" },
        { "id": "g-07", "term_zh": "不要...", "term_target": "...ないでください", "pronunciation": ["...ないでください", "...naide kudasai"], "example": {"sentence": "行かないでください。", "translation": "請不要走。"}, "usage_note": "禁止/請求。", "image_file": "dont.png" },
        { "id": "g-08", "term_zh": "你有做...嗎?", "term_target": "...しますか？", "pronunciation": ["...しますか？", "...shimasu ka?"], "example": {"sentence": "食べますか？", "translation": "你要吃嗎？"}, "usage_note": "一般疑問句。", "image_file": "do_you.png" },
        { "id": "g-09", "term_zh": "你曾經...嗎?", "term_target": "...したことがありますか？", "pronunciation": ["...したことがありますか？", "...shita koto ga arimasu ka?"], "example": {"sentence": "行ったことがありますか？", "translation": "你有去過嗎？"}, "usage_note": "問經驗 (Ta形)。", "image_file": "have_you_ever.png" },
        { "id": "g-10", "term_zh": "你何時做...?", "term_target": "いつ...しますか？", "pronunciation": ["いつ...しますか？", "Itsu ... shimasu ka?"], "example": {"sentence": "いつ寝ますか？", "translation": "你何時睡？"}, "usage_note": "問時間點。", "image_file": "when_do_you.png" },
        { "id": "g-11", "term_zh": "你在哪裡做...?", "term_target": "どこで...しますか？", "pronunciation": ["どこで...しますか？", "Doko de ... shimasu ka?"], "example": {"sentence": "どこで買いますか？", "translation": "你在哪買？"}, "usage_note": "動作發生的地點用 De。", "image_file": "where_do_you.png" },
        { "id": "g-12", "term_zh": "你如何做...?", "term_target": "どうやって...しますか？", "pronunciation": ["どうやって...しますか？", "Douyatte ... shimasu ka?"], "example": {"sentence": "どうやって行きますか？", "translation": "你怎麼去？"}, "usage_note": "問方法。", "image_file": "how_do_you.png" },
        { "id": "g-13", "term_zh": "我不是...", "term_target": "私は...ではありません", "pronunciation": ["わたしは...ではありません", "Watashi wa ... dewa arimasen"], "example": {"sentence": "私は学生ではありません。", "translation": "我不是學生。"}, "usage_note": "名詞/形容動詞否定。", "image_file": "i_am_not.png" },
        { "id": "g-14", "term_zh": "我不做...", "term_target": "...ません", "pronunciation": ["...ません", "...masen"], "example": {"sentence": "食べません。", "translation": "我不吃。"}, "usage_note": "動詞否定。", "image_file": "i_dont.png" },
        { "id": "g-15", "term_zh": "我不能(會)...", "term_target": "...できません", "pronunciation": ["...できません", "...dekimasen"], "example": {"sentence": "運転できません。", "translation": "我不會開車。"}, "usage_note": "能力否定。", "image_file": "i_cant.png" },
        { "id": "g-16", "term_zh": "我未曾...", "term_target": "一度も...したことがありません", "pronunciation": ["いちども...したことがありません", "Ichido mo ... shita koto ga arimasen"], "example": {"sentence": "一度も食べたことがありません。", "translation": "我一次都沒吃過。"}, "usage_note": "無此經驗。", "image_file": "i_have_never.png" },
        { "id": "g-17", "term_zh": "我不必...", "term_target": "...しなくてもいいです", "pronunciation": ["...しなくてもいいです", "...shinakutemo ii desu"], "example": {"sentence": "行かなくてもいいです。", "translation": "我不必去。"}, "usage_note": "無義務。", "image_file": "i_dont_have_to.png" },
        { "id": "g-18", "term_zh": "如果...的話", "term_target": "もし...なら", "pronunciation": ["もし...なら", "Moshi ... nara"], "example": {"sentence": "もし安いなら、買います。", "translation": "如果便宜的話我就買。"}, "usage_note": "假設條件。", "image_file": "if.png" },
        { "id": "g-19", "term_zh": "當...時", "term_target": "...の時", "pronunciation": ["...のとき", "...no toki"], "example": {"sentence": "子供の時。", "translation": "小時候(當我是孩子時)。"}, "usage_note": "時間條件。", "image_file": "when_condition.png" },
        { "id": "g-20", "term_zh": "請你...好嗎?", "term_target": "...してくれますか？", "pronunciation": ["...してくれますか？", "...shite kuremasu ka?"], "example": {"sentence": "手伝ってくれますか？", "translation": "可以幫我嗎？"}, "usage_note": "請求 (Te形)。", "image_file": "can_you.png" },
        { "id": "g-21", "term_zh": "我們來做...吧", "term_target": "...しましょう", "pronunciation": ["...しましょう", "...shimashou"], "example": {"sentence": "行きましょう。", "translation": "走吧。"}, "usage_note": "提議。", "image_file": "lets.png" },
        { "id": "g-22", "term_zh": "我認為...", "term_target": "...と思います", "pronunciation": ["...とおもいます", "...to omoimasu"], "example": {"sentence": "いいと思います。", "translation": "我認為很好。"}, "usage_note": "表達想法。", "image_file": "i_think.png" },
        { "id": "g-23", "term_zh": "我必須...", "term_target": "...しなければなりません", "pronunciation": ["...しなければなりません", "...shinakereba narimasen"], "example": {"sentence": "働かなければなりません。", "translation": "我必須工作。"}, "usage_note": "義務。", "image_file": "i_have_to.png" },
        { "id": "g-24", "term_zh": "做某事是...的", "term_target": "...するのは...です", "pronunciation": ["...するのは...です", "...suru no wa ... desu"], "example": {"sentence": "食べるのは楽しいです。", "translation": "吃東西是開心的。"}, "usage_note": "動詞名詞化。", "image_file": "it_is_to.png" },
        { "id": "g-25", "term_zh": "我可以...嗎?", "term_target": "...てもいいですか？", "pronunciation": ["...てもいいですか？", "...temo ii desu ka?"], "example": {"sentence": "写真を撮ってもいいですか？", "translation": "我可以拍照嗎？"}, "usage_note": "請求許可 (Te形)。", "image_file": "can_i.png" },
        { "id": "g-26", "term_zh": "我比較喜歡...", "term_target": "...の方が好きです", "pronunciation": ["...のほうがすきです", "...no hou ga suki desu"], "example": {"sentence": "これの方が好きです。", "translation": "我比較喜歡這個。"}, "usage_note": "偏好。", "image_file": "prefer.png" },
        { "id": "g-27", "term_zh": "A比B更...", "term_target": "AはBより...です", "pronunciation": ["AはBより...です", "A wa B yori ... desu"], "example": {"sentence": "これはあれより高いです。", "translation": "這比那個貴。"}, "usage_note": "比較級。", "image_file": "more_than.png" },
        { "id": "g-28", "term_zh": "有(存在)...", "term_target": "...があります / います", "pronunciation": ["...があります / います", "...ga arimasu / imasu"], "example": {"sentence": "犬がいます。", "translation": "有一隻狗。"}, "usage_note": "存在 (生物用Imasu)。", "image_file": "there_is.png" },
        { "id": "g-29", "term_zh": "我曾經是/當時是...", "term_target": "私は...でした", "pronunciation": ["わたしは...でした", "Watashi wa ... deshita"], "example": {"sentence": "私は学生でした。", "translation": "我曾經是學生。"}, "usage_note": "過去狀態。", "image_file": "i_was.png" },
        { "id": "g-30", "term_zh": "我將要...", "term_target": "私は...します", "pronunciation": ["わたしは...します", "Watashi wa ... shimasu"], "example": {"sentence": "私は行きます。", "translation": "我要去。"}, "usage_note": "日文動詞原形包含未來意。", "image_file": "i_will.png" },
        { "id": "g-31", "term_zh": "我做過(過去式)...", "term_target": "...しました", "pronunciation": ["...しました", "...shimashita"], "example": {"sentence": "宿題をしました。", "translation": "我做完功課了。"}, "usage_note": "過去動作。", "image_file": "i_did.png" }
      ]
    }
  ]
};