import { AppData } from '../types';

export const koreanData: AppData = 
{
  "meta": {
    "source_language": "zh-TW",
    "target_language": "ko-KR",
    "version": "2.3",
    "description": "台灣人快速語言學習 - 韓文完整版 (包含所有原始列表單字與完整句型 - 羅馬拼音版)"
  },
  "categories": [
    {
      "id": "greetings",
      "name": "常用句",
      "items": [
        {
          "id": "greet-001",
          "term_zh": "你好",
          "term_target": "안녕하세요",
          "pronunciation": ["Annyeonghaseyo"],
          "example": { "sentence": "안녕하세요, 잘 지내세요?", "translation": "你好，你好嗎？" },
          "usage_note": "最通用的問候，任何時間都能用。",
          "image_file": "hello.png"
        },
        {
          "id": "greet-002",
          "term_zh": "再見",
          "term_target": "안녕히 가세요",
          "pronunciation": ["Annyeonghi gaseyo"],
          "example": { "sentence": "안녕히 가세요, 또 봐요.", "translation": "慢走，再見。",  },
          "usage_note": "對離開的人說「가세요(走)」，對留下來的人說「계세요(留)」。",
          "image_file": "goodbye.png"
        },
        {
          "id": "greet-003",
          "term_zh": "謝謝你",
          "term_target": "감사합니다",
          "pronunciation": ["Gamsahamnida"],
          "example": { "sentence": "도와주셔서 감사합니다.", "translation": "謝謝你的幫忙。" },
          "usage_note": "最正式且常用的感謝。",
          "image_file": "thank_you.png"
        },
        {
          "id": "greet-004",
          "term_zh": "對不起",
          "term_target": "죄송합니다",
          "pronunciation": ["Joesonghamnida"],
          "example": { "sentence": "늦어서 죄송합니다.", "translation": "抱歉我遲到了。" },
          "usage_note": "做錯事時的道歉。",
          "image_file": "sorry.png"
        },
        {
          "id": "greet-005",
          "term_zh": "早安",
          "term_target": "좋은 아침입니다",
          "pronunciation": ["Joeun achimimnida"],
          "example": { "sentence": "좋은 아침!", "translation": "早安！" },
          "usage_note": "字面意思是「美好的早晨」。",
          "image_file": "good_morning.png"
        },
        {
          "id": "greet-006",
          "term_zh": "請問... / 借過",
          "term_target": "잠시만요 / 실례합니다",
          "pronunciation": ["Jamsimanyo", "Sillyehamnida"],
          "example": { "sentence": "잠시만요, 지나갈게요.", "translation": "借過，我要過去一下。" },
          "usage_note": "借過常用 Jamsimanyo (等一下)，發問前用 Sillyehamnida (失禮了)。",
          "image_file": "excuse_me.png"
        },
        {
          "id": "greet-007",
          "term_zh": "我不懂",
          "term_target": "이해가 안 돼요",
          "pronunciation": ["Ihaega an dwaeyo"],
          "example": { "sentence": "죄송해요, 한국어 잘 못해요.", "translation": "抱歉，我不太會韓文。" },
          "usage_note": "或說「Mollayo」(不知道)。",
          "image_file": "dont_understand.png"
        },
        {
          "id": "greet-008",
          "term_zh": "這是什麼？",
          "term_target": "이게 뭐예요?",
          "pronunciation": ["Ige mwoyeyo?"],
          "example": { "sentence": "이게 뭐예요? 맛있어요?", "translation": "這是什麼？好吃嗎？" },
          "usage_note": "指著東西問。",
          "image_file": "what_is_this.png"
        },
        {
          "id": "greet-009",
          "term_zh": "我想要這個",
          "term_target": "이거 주세요",
          "pronunciation": ["Igeo juseyo"],
          "example": { "sentence": "이거 주세요.", "translation": "請給我這個 (購買時)。" },
          "usage_note": "「請給我這個」是最自然的購買說法。",
          "image_file": "i_want_this.png"
        },
        {
          "id": "greet-010",
          "term_zh": "請給我...",
          "term_target": "... 주세요",
          "pronunciation": ["... juseyo"],
          "example": { "sentence": "물 주세요.", "translation": "請給我水。" },
          "usage_note": "名詞 + juseyo。",
          "image_file": "please_give_me.png"
        },
        {
          "id": "greet-011",
          "term_zh": "廁所在哪裡？",
          "term_target": "화장실이 어디예요?",
          "pronunciation": ["Hwajangisiri eodiyeyo?"],
          "example": { "sentence": "저기요, 화장실이 어디예요?", "translation": "不好意思，請問廁所在哪？" },
          "usage_note": "旅遊必備。",
          "image_file": "where_bathroom.png"
        },
        {
          "id": "greet-012",
          "term_zh": "多少錢？",
          "term_target": "얼마예요?",
          "pronunciation": ["Eolmayeyo?"],
          "example": { "sentence": "이거 얼마예요?", "translation": "這個多少錢？" },
          "usage_note": "購物用語。",
          "image_file": "how_much.png"
        },
        {
          "id": "greet-013",
          "term_zh": "請幫我",
          "term_target": "도와주세요",
          "pronunciation": ["Dowajuseyo"],
          "example": { "sentence": "제발 도와주세요.", "translation": "拜託請幫我。" },
          "usage_note": "尋求協助。",
          "image_file": "help_me.png"
        },
        {
          "id": "greet-014",
          "term_zh": "你可以再說一次嗎？",
          "term_target": "다시 말해 주세요",
          "pronunciation": ["Dasi malhae juseyo"],
          "example": { "sentence": "네? 다시 말해 주세요.", "translation": "蛤？請再說一次。" },
          "usage_note": "沒聽清楚時。",
          "image_file": "say_again.png"
        },
        {
          "id": "greet-015",
          "term_zh": "你可以講慢一點嗎？",
          "term_target": "천천히 말해 주세요",
          "pronunciation": ["Cheoncheonhi malhae juseyo"],
          "example": { "sentence": "너무 빨라요, 천천히 말해 주세요.", "translation": "太快了，請講慢一點。" },
          "usage_note": "Cheoncheonhi 是「慢慢地」。",
          "image_file": "speak_slowly.png"
        }
      ]
    },
    {
      "id": "pronouns",
      "name": "主詞（代名詞）",
      "items": [
        { "id": "pro-01", "term_zh": "我", "term_target": "저", "pronunciation": ["Jeo"], "example": {"sentence": "저는 대만 사람입니다.", "translation": "我是台灣人。"}, "usage_note": "謙虛的有禮貌自稱。朋友間用「나 (Na)」。", "image_file": "i.png" },
        { "id": "pro-02", "term_zh": "你", "term_target": "당신", "pronunciation": ["Dangsin"], "example": {"sentence": "당신은 누구세요?", "translation": "你是誰？"}, "usage_note": "韓文很少直呼「你」，通常稱呼職稱或名字。", "image_file": "you.png" },
        { "id": "pro-03", "term_zh": "他", "term_target": "그", "pronunciation": ["Geu"], "example": {"sentence": "그는 선생님이에요.", "translation": "他是老師。"}, "usage_note": "男性。", "image_file": "he.png" },
        { "id": "pro-04", "term_zh": "她", "term_target": "그녀", "pronunciation": ["Geunyeo"], "example": {"sentence": "그녀는 예뻐요.", "translation": "她很漂亮。"}, "usage_note": "女性。", "image_file": "she.png" },
        { "id": "pro-05", "term_zh": "我們", "term_target": "우리", "pronunciation": ["Uri"], "example": {"sentence": "우리는 가족이에요.", "translation": "我們是家人。"}, "usage_note": "常用的複數。", "image_file": "we.png" },
        { "id": "pro-06", "term_zh": "他們", "term_target": "그들", "pronunciation": ["Geudeul"], "example": {"sentence": "그들은 학생이에요.", "translation": "他們是學生。"}, "usage_note": "第三人稱複數。", "image_file": "they.png" },
        { "id": "pro-07", "term_zh": "這個", "term_target": "이거", "pronunciation": ["Igeo"], "example": {"sentence": "이거 뭐예요?", "translation": "這是什麼？"}, "usage_note": "近處。", "image_file": "this.png" },
        { "id": "pro-08", "term_zh": "那個/它", "term_target": "그거 / 저거", "pronunciation": ["Geugeo", "Jeogeo"], "example": {"sentence": "저거 주세요.", "translation": "請給我那個(遠處)。"}, "usage_note": "Geugeo (對方那), Jeogeo (遠處)。", "image_file": "that.png" },
        { "id": "pro-09", "term_zh": "他的", "term_target": "그의", "pronunciation": ["Geuui"], "example": {"sentence": "그의 차.", "translation": "他的車。"}, "usage_note": "所有格。", "image_file": "his.png" },
        { "id": "pro-10", "term_zh": "她的", "term_target": "그녀의", "pronunciation": ["Geunyeoui"], "example": {"sentence": "그녀의 가방.", "translation": "她的包包。"}, "usage_note": "所有格。", "image_file": "her.png" },
        { "id": "pro-11", "term_zh": "你的", "term_target": "당신의", "pronunciation": ["Dangsinui"], "example": {"sentence": "당신의 이름.", "translation": "你的名字。"}, "usage_note": "所有格。", "image_file": "your.png" },
        { "id": "pro-12", "term_zh": "他們的", "term_target": "그들의", "pronunciation": ["Geudeurui"], "example": {"sentence": "그들의 집.", "translation": "他們的家。"}, "usage_note": "所有格。", "image_file": "their.png" },
        { "id": "pro-13", "term_zh": "我們的", "term_target": "우리의", "pronunciation": ["Uriui"], "example": {"sentence": "우리의 학교.", "translation": "我們的學校。"}, "usage_note": "口語常簡略為「우리」。", "image_file": "our.png" },
        { "id": "pro-14", "term_zh": "這些", "term_target": "이것들", "pronunciation": ["Igeotdeul"], "example": {"sentence": "이것들은 책이에요.", "translation": "這些是書。"}, "usage_note": "複數加 deul。", "image_file": "these.png" },
        { "id": "pro-15", "term_zh": "那些", "term_target": "저것들", "pronunciation": ["Jeogeotdeul"], "example": {"sentence": "저것들은 뭐예요?", "translation": "那些是什麼？"}, "usage_note": "遠處複數。", "image_file": "those.png" }
      ]
    },
    {
      "id": "verbs",
      "name": "動詞",
      "items": [
        { "id": "v-01", "term_zh": "是", "term_target": "이에요 / 예요", "pronunciation": ["Ieyo / Yeyo"], "example": {"sentence": "저는 학생이에요.", "translation": "我是學生。"}, "usage_note": "句尾助動詞 (有收音用 Ieyo)。", "image_file": "be.png" },
        { "id": "v-02", "term_zh": "有（擁有）", "term_target": "있어요", "pronunciation": ["Isseoyo"], "example": {"sentence": "돈이 있어요.", "translation": "我有錢。"}, "usage_note": "擁有或存在。", "image_file": "have.png" },
        { "id": "v-03", "term_zh": "去", "term_target": "가요", "pronunciation": ["Gayo"], "example": {"sentence": "집에 가요.", "translation": "回家。"}, "usage_note": "移動。", "image_file": "go.png" },
        { "id": "v-04", "term_zh": "做", "term_target": "해요", "pronunciation": ["Haeyo"], "example": {"sentence": "숙제를 해요.", "translation": "做作業。"}, "usage_note": "執行動作。", "image_file": "do.png" },
        { "id": "v-05", "term_zh": "說", "term_target": "말해요", "pronunciation": ["Malhaeyo"], "example": {"sentence": "사랑한다고 말해요.", "translation": "說我愛你。"}, "usage_note": "說話。", "image_file": "say.png" },
        { "id": "v-06", "term_zh": "知道", "term_target": "알아요", "pronunciation": ["Arayo"], "example": {"sentence": "저는 알아요.", "translation": "我知道。"}, "usage_note": "知曉。", "image_file": "know.png" },
        { "id": "v-07", "term_zh": "想/思考", "term_target": "생각해요", "pronunciation": ["Saenggakaeyo"], "example": {"sentence": "그렇게 생각해요.", "translation": "我也這麼覺得。"}, "usage_note": "思考。", "image_file": "think.png" },
        { "id": "v-08", "term_zh": "看見", "term_target": "봐요", "pronunciation": ["Bwayo"], "example": {"sentence": "영화를 봐요.", "translation": "看電影。"}, "usage_note": "看。", "image_file": "see.png" },
        { "id": "v-09", "term_zh": "製作", "term_target": "만들어요", "pronunciation": ["Mandeureoyo"], "example": {"sentence": "음식을 만들어요.", "translation": "做菜。"}, "usage_note": "製造。", "image_file": "make.png" },
        { "id": "v-10", "term_zh": "來", "term_target": "와요", "pronunciation": ["Wayo"], "example": {"sentence": "여기로 와요.", "translation": "來這裡。"}, "usage_note": "過來。", "image_file": "come.png" },
        { "id": "v-11", "term_zh": "需要", "term_target": "필요해요", "pronunciation": ["Piryohaeyo"], "example": {"sentence": "물이 필요해요.", "translation": "我需要水。"}, "usage_note": "需要。", "image_file": "need.png" },
        { "id": "v-12", "term_zh": "使用", "term_target": "써요 / 사용해요", "pronunciation": ["Sseoyo", "Sayonghaeyo"], "example": {"sentence": "펜을 써요.", "translation": "用筆。"}, "usage_note": "使用。", "image_file": "use.png" },
        { "id": "v-13", "term_zh": "找到", "term_target": "찾아요", "pronunciation": ["Chajayo"], "example": {"sentence": "길을 찾아요.", "translation": "找路。"}, "usage_note": "尋找或找到。", "image_file": "find.png" },
        { "id": "v-14", "term_zh": "給", "term_target": "줘요", "pronunciation": ["Jwoyo"], "example": {"sentence": "이거 주세요.", "translation": "給我這個。"}, "usage_note": "給予。", "image_file": "give.png" },
        { "id": "v-15", "term_zh": "告訴", "term_target": "알려줘요", "pronunciation": ["Allyeojwoyo"], "example": {"sentence": "이름을 알려줘요.", "translation": "告訴我名字。"}, "usage_note": "告知。", "image_file": "tell.png" },
        { "id": "v-16", "term_zh": "工作", "term_target": "일해요", "pronunciation": ["Irhaeyo"], "example": {"sentence": "여기서 일해요.", "translation": "在這工作。"}, "usage_note": "勞動。", "image_file": "work.png" },
        { "id": "v-17", "term_zh": "喜歡", "term_target": "좋아해요", "pronunciation": ["Joahaeyo"], "example": {"sentence": "고양이를 좋아해요.", "translation": "我喜歡貓。"}, "usage_note": "喜好。", "image_file": "like.png" },
        { "id": "v-18", "term_zh": "起床/醒來", "term_target": "일어나요", "pronunciation": ["Ireonayo"], "example": {"sentence": "아침에 일어나요.", "translation": "早上起床。"}, "usage_note": "起床。", "image_file": "wake_up.png" },
        { "id": "v-19", "term_zh": "說話", "term_target": "말해요", "pronunciation": ["Malhaeyo"], "example": {"sentence": "한국어로 말해요.", "translation": "說韓文。"}, "usage_note": "講話。", "image_file": "speak.png" },
        { "id": "v-20", "term_zh": "聽見", "term_target": "들어요", "pronunciation": ["Deureoyo"], "example": {"sentence": "음악을 들어요.", "translation": "聽音樂。"}, "usage_note": "聽。", "image_file": "hear.png" },
        { "id": "v-21", "term_zh": "寫", "term_target": "써요", "pronunciation": ["Sseoyo"], "example": {"sentence": "이름을 써요.", "translation": "寫名字。"}, "usage_note": "書寫。", "image_file": "write.png" },
        { "id": "v-22", "term_zh": "閱讀", "term_target": "읽어요", "pronunciation": ["Ilgeoyo"], "example": {"sentence": "책을 읽어요.", "translation": "看書。"}, "usage_note": "讀文字。", "image_file": "read.png" },
        { "id": "v-23", "term_zh": "等待", "term_target": "기다려요", "pronunciation": ["Gidaryeoyo"], "example": {"sentence": "잠시만 기다려요.", "translation": "請等一下。"}, "usage_note": "等候。", "image_file": "wait.png" },
        { "id": "v-24", "term_zh": "嘗試", "term_target": "해봐요", "pronunciation": ["Haebwayo"], "example": {"sentence": "이거 해봐요.", "translation": "試試看這個。"}, "usage_note": "試做。", "image_file": "try.png" },
        { "id": "v-25", "term_zh": "付錢", "term_target": "내요 / 계산해요", "pronunciation": ["Naeyo", "Gyesanhaeyo"], "example": {"sentence": "제가 낼게요.", "translation": "我來付錢。"}, "usage_note": "支付。", "image_file": "pay.png" },
        { "id": "v-26", "term_zh": "住", "term_target": "살아요", "pronunciation": ["Sarayo"], "example": {"sentence": "서울에 살아요.", "translation": "住首爾。"}, "usage_note": "居住。", "image_file": "live.png" },
        { "id": "v-27", "term_zh": "走路", "term_target": "걸어요", "pronunciation": ["Georeoyo"], "example": {"sentence": "걸어서 가요.", "translation": "走路去。"}, "usage_note": "步行。", "image_file": "walk.png" },
        { "id": "v-28", "term_zh": "打開", "term_target": "열어요", "pronunciation": ["Yeoreoyo"], "example": {"sentence": "문을 열어요.", "translation": "開門。"}, "usage_note": "開啟。", "image_file": "open.png" },
        { "id": "v-29", "term_zh": "關閉", "term_target": "닫아요", "pronunciation": ["Dadayo"], "example": {"sentence": "창문을 닫아요.", "translation": "關窗。"}, "usage_note": "關上。", "image_file": "close.png" },
        { "id": "v-30", "term_zh": "幫助", "term_target": "도와줘요", "pronunciation": ["Dowajwoyo"], "example": {"sentence": "도와주세요.", "translation": "請幫我。"}, "usage_note": "協助。", "image_file": "help.png" },
        { "id": "v-31", "term_zh": "吃", "term_target": "먹어요", "pronunciation": ["Meogeoyo"], "example": {"sentence": "밥을 먹어요.", "translation": "吃飯。"}, "usage_note": "進食。", "image_file": "eat.png" },
        { "id": "v-32", "term_zh": "睡覺", "term_target": "자요", "pronunciation": ["Jayo"], "example": {"sentence": "안녕히 주무세요.", "translation": "晚安(敬語)。"}, "usage_note": "睡眠。", "image_file": "sleep.png" },
        { "id": "v-33", "term_zh": "買", "term_target": "사요", "pronunciation": ["Sayo"], "example": {"sentence": "옷을 사요.", "translation": "買衣服。"}, "usage_note": "購買。", "image_file": "buy.png" },
        { "id": "v-34", "term_zh": "乘坐/拿", "term_target": "타요", "pronunciation": ["Tayo"], "example": {"sentence": "버스를 타요.", "translation": "搭公車。"}, "usage_note": "搭乘交通工具。", "image_file": "take.png" },
        { "id": "v-35", "term_zh": "得到/拿", "term_target": "받아요", "pronunciation": ["Badayo"], "example": {"sentence": "선물을 받아요.", "translation": "收到禮物。"}, "usage_note": "獲得。", "image_file": "get.png" },
        { "id": "v-36", "term_zh": "選擇", "term_target": "골라요 / 선택해요", "pronunciation": ["Gollayo", "Seontaekaeyo"], "example": {"sentence": "하나 골라요.", "translation": "選一個。"}, "usage_note": "挑選。", "image_file": "choose.png" },
        { "id": "v-37", "term_zh": "進入", "term_target": "들어가요", "pronunciation": ["Deureogayo"], "example": {"sentence": "방에 들어가요.", "translation": "進房間。"}, "usage_note": "進入。", "image_file": "enter.png" },
        { "id": "v-38", "term_zh": "到達", "term_target": "도착해요", "pronunciation": ["Dochakaeyo"], "example": {"sentence": "도착했어요.", "translation": "到了。"}, "usage_note": "抵達。", "image_file": "arrive.png" },
        { "id": "v-39", "term_zh": "帶來", "term_target": "가져와요", "pronunciation": ["Gajyeowayo"], "example": {"sentence": "물을 가져와요.", "translation": "帶水來。"}, "usage_note": "攜帶。", "image_file": "bring.png" },
        { "id": "v-40", "term_zh": "變成", "term_target": "돼요", "pronunciation": ["Dwaeyo"], "example": {"sentence": "선생님이 돼요.", "translation": "變成老師。"}, "usage_note": "變化。", "image_file": "become.png" },
        { "id": "v-41", "term_zh": "開始", "term_target": "시작해요", "pronunciation": ["Sijakaeyo"], "example": {"sentence": "이제 시작해요.", "translation": "現在開始。"}, "usage_note": "開始。", "image_file": "start.png" },
        { "id": "v-42", "term_zh": "結束", "term_target": "끝나요", "pronunciation": ["Kkeunnayo"], "example": {"sentence": "일이 끝나요.", "translation": "工作結束。"}, "usage_note": "完成。", "image_file": "finish.png" },
        { "id": "v-43", "term_zh": "停止", "term_target": "멈춰요", "pronunciation": ["Meomchwoyo"], "example": {"sentence": "여기서 멈춰요.", "translation": "停在這裡。"}, "usage_note": "停止。", "image_file": "stop.png" },
        { "id": "v-44", "term_zh": "記住", "term_target": "기억해요", "pronunciation": ["Gieokaeyo"], "example": {"sentence": "저를 기억해요?", "translation": "記得我嗎？"}, "usage_note": "記憶。", "image_file": "remember.png" },
        { "id": "v-45", "term_zh": "見面", "term_target": "만나요", "pronunciation": ["Mannayo"], "example": {"sentence": "친구를 만나요.", "translation": "見朋友。"}, "usage_note": "會面。", "image_file": "meet.png" },
        { "id": "v-46", "term_zh": "放", "term_target": "놓아요", "pronunciation": ["Noayo"], "example": {"sentence": "여기에 놓아요.", "translation": "放這裡。"}, "usage_note": "放置。", "image_file": "put.png" },
        { "id": "v-47", "term_zh": "寄送", "term_target": "보내요", "pronunciation": ["Bonaeyo"], "example": {"sentence": "문자를 보내요.", "translation": "寄簡訊。"}, "usage_note": "傳送。", "image_file": "send.png" },
        { "id": "v-48", "term_zh": "開車", "term_target": "운전해요", "pronunciation": ["Unjeonhaeyo"], "example": {"sentence": "차를 운전해요.", "translation": "開車。"}, "usage_note": "駕駛。", "image_file": "drive.png" },
        { "id": "v-49", "term_zh": "讀書", "term_target": "공부해요", "pronunciation": ["Gongbuhaeyo"], "example": {"sentence": "열심히 공부해요.", "translation": "用功讀書。"}, "usage_note": "學習。", "image_file": "study.png" },
        { "id": "v-50", "term_zh": "回去", "term_target": "돌아가요", "pronunciation": ["Doragayo"], "example": {"sentence": "집으로 돌아가요.", "translation": "回家。"}, "usage_note": "歸返。", "image_file": "go_back.png" }
      ]
    },
    {
      "id": "adjectives",
      "name": "形容詞",
      "items": [
        { "id": "adj-01", "term_zh": "好的", "term_target": "좋아요", "pronunciation": ["Joayo"], "example": {"sentence": "날씨가 좋아요.", "translation": "天氣好。"}, "usage_note": "正面。", "image_file": "good.png" },
        { "id": "adj-02", "term_zh": "壞的", "term_target": "나빠요", "pronunciation": ["Nappayo"], "example": {"sentence": "기분이 나빠요.", "translation": "心情不好。"}, "usage_note": "負面。", "image_file": "bad.png" },
        { "id": "adj-03", "term_zh": "新的", "term_target": "새로운", "pronunciation": ["Saeroun"], "example": {"sentence": "새로운 핸드폰.", "translation": "新手機。"}, "usage_note": "修飾語。", "image_file": "new.png" },
        { "id": "adj-04", "term_zh": "大的", "term_target": "커요", "pronunciation": ["Keoyo"], "example": {"sentence": "집이 커요.", "translation": "房子大。"}, "usage_note": "體積大。", "image_file": "big.png" },
        { "id": "adj-05", "term_zh": "小的", "term_target": "작아요", "pronunciation": ["Jagayo"], "example": {"sentence": "작은 사이즈.", "translation": "小尺寸。"}, "usage_note": "體積小。", "image_file": "small.png" },
        { "id": "adj-06", "term_zh": "熱的", "term_target": "더워요 / 뜨거워요", "pronunciation": ["Deowoyo", "Tteugeowoyo"], "example": {"sentence": "날씨가 더워요.", "translation": "天氣熱。"}, "usage_note": "Deowoyo(天氣)，Tteugeowoyo(物品)。", "image_file": "hot.png" },
        { "id": "adj-07", "term_zh": "冷的", "term_target": "추워요 / 차가워요", "pronunciation": ["Chuwoyo", "Chagawoyo"], "example": {"sentence": "너무 추워요.", "translation": "太冷了。"}, "usage_note": "Chuwoyo(天氣)，Chagawoyo(物品)。", "image_file": "cold.png" },
        { "id": "adj-08", "term_zh": "簡單的", "term_target": "쉬워요", "pronunciation": ["Swiwoyo"], "example": {"sentence": "이거 쉬워요.", "translation": "這很簡單。"}, "usage_note": "容易。", "image_file": "easy.png" },
        { "id": "adj-09", "term_zh": "困難的", "term_target": "어려워요", "pronunciation": ["Eoryeowoyo"], "example": {"sentence": "한국어 어려워요.", "translation": "韓文很難。"}, "usage_note": "難。", "image_file": "difficult.png" },
        { "id": "adj-10", "term_zh": "美味的", "term_target": "맛있어요", "pronunciation": ["Masisseoyo"], "example": {"sentence": "맛있어요.", "translation": "好吃。"}, "usage_note": "好吃。", "image_file": "delicious.png" },
        { "id": "adj-11", "term_zh": "忙碌的", "term_target": "바빠요", "pronunciation": ["Bappayo"], "example": {"sentence": "저는 바빠요.", "translation": "我很忙。"}, "usage_note": "沒空。", "image_file": "busy.png" },
        { "id": "adj-12", "term_zh": "疲累的", "term_target": "피곤해요", "pronunciation": ["Pigonhaeyo"], "example": {"sentence": "조금 피곤해요.", "translation": "有點累。"}, "usage_note": "狀態。", "image_file": "tired.png" },
        { "id": "adj-13", "term_zh": "快樂的/高興的", "term_target": "기뻐요 / 행복해요", "pronunciation": ["Gippeoyo", "Haengbokaeyo"], "example": {"sentence": "만나서 기뻐요.", "translation": "很高興見到你。"}, "usage_note": "心情。", "image_file": "happy.png" },
        { "id": "adj-14", "term_zh": "悲傷的", "term_target": "슬퍼요", "pronunciation": ["Seulpeoyo"], "example": {"sentence": "슬픈 영화.", "translation": "悲傷的電影。"}, "usage_note": "難過。", "image_file": "sad.png" },
        { "id": "adj-15", "term_zh": "乾淨的", "term_target": "깨끗해요", "pronunciation": ["Kkaekkeutaeyo"], "example": {"sentence": "방이 깨끗해요.", "translation": "房間乾淨。"}, "usage_note": "無髒汙。", "image_file": "clean.png" },
        { "id": "adj-16", "term_zh": "髒的", "term_target": "더러워요", "pronunciation": ["Deoreowoyo"], "example": {"sentence": "손이 더러워요.", "translation": "手很髒。"}, "usage_note": "不乾淨。", "image_file": "dirty.png" },
        { "id": "adj-17", "term_zh": "便宜的", "term_target": "싸요", "pronunciation": ["Ssayo"], "example": {"sentence": "이거 싸요.", "translation": "這很便宜。"}, "usage_note": "價格低。", "image_file": "cheap.png" },
        { "id": "adj-18", "term_zh": "昂貴的", "term_target": "비싸요", "pronunciation": ["Bissayo"], "example": {"sentence": "너무 비싸요.", "translation": "太貴了。"}, "usage_note": "價格高。", "image_file": "expensive.png" },
        { "id": "adj-19", "term_zh": "重要的", "term_target": "중요해요", "pronunciation": ["Jung-yohaeyo"], "example": {"sentence": "중요한 약속.", "translation": "重要的約定。"}, "usage_note": "關鍵。", "image_file": "important.png" },
        { "id": "adj-20", "term_zh": "相同的", "term_target": "같아요", "pronunciation": ["Gatayo"], "example": {"sentence": "우리는 같아요.", "translation": "我們一樣。"}, "usage_note": "一樣。", "image_file": "same.png" },
        { "id": "adj-21", "term_zh": "第一的", "term_target": "첫번째", "pronunciation": ["Cheotbeonjjae"], "example": {"sentence": "첫번째 날.", "translation": "第一天。"}, "usage_note": "順序。", "image_file": "first.png" },
        { "id": "adj-22", "term_zh": "上一個", "term_target": "지난", "pronunciation": ["Jinan"], "example": {"sentence": "지난 주.", "translation": "上週。"}, "usage_note": "過去的。", "image_file": "last.png" },
        { "id": "adj-23", "term_zh": "下一個", "term_target": "다음", "pronunciation": ["Daeum"], "example": {"sentence": "다음 역.", "translation": "下一站。"}, "usage_note": "接下來。", "image_file": "next.png" },
        { "id": "adj-24", "term_zh": "長的", "term_target": "길어요", "pronunciation": ["Gireoyo"], "example": {"sentence": "머리가 길어요.", "translation": "頭髮長。"}, "usage_note": "長度。", "image_file": "long.png" },
        { "id": "adj-25", "term_zh": "多的", "term_target": "많아요", "pronunciation": ["Manayo"], "example": {"sentence": "사람이 많아요.", "translation": "人很多。"}, "usage_note": "數量多。", "image_file": "many.png" },
        { "id": "adj-26", "term_zh": "高的", "term_target": "높아요 / 커요", "pronunciation": ["Nopayo", "Keoyo"], "example": {"sentence": "키가 커요.", "translation": "個子高。"}, "usage_note": "高度(Nopayo)，身高(Keoyo)。", "image_file": "tall.png" },
        { "id": "adj-27", "term_zh": "年輕的", "term_target": "젊어요", "pronunciation": ["Jeolmeoyo"], "example": {"sentence": "젊은 사람.", "translation": "年輕人。"}, "usage_note": "年紀小。", "image_file": "young.png" },
        { "id": "adj-28", "term_zh": "老的/舊的", "term_target": "늙었어요 / 낡았어요", "pronunciation": ["Neulgeosseoyo", "Nalgasseoyo"], "example": {"sentence": "낡은 차.", "translation": "舊車。"}, "usage_note": "人老(Neul-), 物舊(Nal-)。", "image_file": "old.png" },
        { "id": "adj-29", "term_zh": "近的", "term_target": "가까워요", "pronunciation": ["Gakkawoyo"], "example": {"sentence": "집이 가까워요.", "translation": "離家近。"}, "usage_note": "距離近。", "image_file": "near.png" },
        { "id": "adj-30", "term_zh": "遠的", "term_target": "멀어요", "pronunciation": ["Meoreoyo"], "example": {"sentence": "여기서 멀어요.", "translation": "離這很遠。"}, "usage_note": "距離遠。", "image_file": "far.png" },
        { "id": "adj-31", "term_zh": "快的", "term_target": "빨라요", "pronunciation": ["Ppallayo"], "example": {"sentence": "너무 빨라요.", "translation": "太快了。"}, "usage_note": "速度快。", "image_file": "fast.png" },
        { "id": "adj-32", "term_zh": "慢的", "term_target": "느려요", "pronunciation": ["Neuryeoyo"], "example": {"sentence": "버스가 느려요.", "translation": "公車很慢。"}, "usage_note": "速度慢。", "image_file": "slow.png" },
        { "id": "adj-33", "term_zh": "正確的", "term_target": "맞아요", "pronunciation": ["Majayo"], "example": {"sentence": "네, 맞아요.", "translation": "對，沒錯。"}, "usage_note": "對的。", "image_file": "correct.png" },
        { "id": "adj-34", "term_zh": "錯誤的", "term_target": "틀려요", "pronunciation": ["Teullyeoyo"], "example": {"sentence": "이건 틀려요.", "translation": "這錯了。"}, "usage_note": "不對。", "image_file": "wrong.png" },
        { "id": "adj-35", "term_zh": "不同的", "term_target": "달라요", "pronunciation": ["Dallayo"], "example": {"sentence": "우리는 달라요.", "translation": "我們不同。"}, "usage_note": "差異。", "image_file": "different.png" },
        { "id": "adj-36", "term_zh": "真的", "term_target": "진짜", "pronunciation": ["Jinjja"], "example": {"sentence": "진짜예요?", "translation": "真的嗎？"}, "usage_note": "真實。", "image_file": "real.png" },
        { "id": "adj-37", "term_zh": "有趣的", "term_target": "재미있어요", "pronunciation": ["Jaemiisseoyo"], "example": {"sentence": "영화가 재미있어요.", "translation": "電影有趣。"}, "usage_note": "有意思。", "image_file": "interesting.png" },
        { "id": "adj-38", "term_zh": "飢餓的", "term_target": "배고파요", "pronunciation": ["Baegopayo"], "example": {"sentence": "저 배고파요.", "translation": "我餓了。"}, "usage_note": "餓。", "image_file": "hungry.png" },
        { "id": "adj-39", "term_zh": "有名的", "term_target": "유명해요", "pronunciation": ["Yumyeonghaeyo"], "example": {"sentence": "유명한 식당.", "translation": "有名的餐廳。"}, "usage_note": "知名。", "image_file": "famous.png" },
        { "id": "adj-40", "term_zh": "外國的", "term_target": "외국의", "pronunciation": ["Oegugui"], "example": {"sentence": "외국 사람.", "translation": "外國人。"}, "usage_note": "國外。", "image_file": "foreign.png" },
        { "id": "adj-41", "term_zh": "聰明的", "term_target": "똑똑해요", "pronunciation": ["Ttokttokaeyo"], "example": {"sentence": "그는 똑똑해요.", "translation": "他很聰明。"}, "usage_note": "腦袋好。", "image_file": "intelligent.png" },
        { "id": "adj-42", "term_zh": "危險的", "term_target": "위험해요", "pronunciation": ["Wiheomhaeyo"], "example": {"sentence": "거기는 위험해요.", "translation": "那裡危險。"}, "usage_note": "警示。", "image_file": "dangerous.png" },
        { "id": "adj-43", "term_zh": "仁慈的", "term_target": "친절해요", "pronunciation": ["Chinjeolhaeyo"], "example": {"sentence": "친절한 사람.", "translation": "親切的人。"}, "usage_note": "親切。", "image_file": "kind.png" },
        { "id": "adj-44", "term_zh": "所有的", "term_target": "모든", "pronunciation": ["Modeun"], "example": {"sentence": "모든 사람.", "translation": "所有人。"}, "usage_note": "全部。", "image_file": "every.png" },
        { "id": "adj-45", "term_zh": "喜愛的", "term_target": "가장 좋아하는", "pronunciation": ["Gajang joahaneun"], "example": {"sentence": "가장 좋아하는 가수.", "translation": "最愛的歌手。"}, "usage_note": "最喜歡。", "image_file": "favorite.png" }
      ]
    },
    {
      "id": "nouns",
      "name": "名詞",
      "items": [
        { "id": "n-01", "term_zh": "水", "term_target": "물", "pronunciation": ["Mul"], "example": {"sentence": "물 주세요.", "translation": "請給水。"}, "usage_note": "液體。", "image_file": "water.png" },
        { "id": "n-02", "term_zh": "食物", "term_target": "음식", "pronunciation": ["Eumsik"], "example": {"sentence": "한국 음식.", "translation": "韓國食物。"}, "usage_note": "吃的東西。", "image_file": "food.png" },
        { "id": "n-03", "term_zh": "錢", "term_target": "돈", "pronunciation": ["Don"], "example": {"sentence": "돈이 없어요.", "translation": "沒錢。"}, "usage_note": "錢。", "image_file": "money.png" },
        { "id": "n-04", "term_zh": "廁所", "term_target": "화장실", "pronunciation": ["Hwajangsil"], "example": {"sentence": "화장실 가요.", "translation": "去廁所。"}, "usage_note": "衛生間。", "image_file": "bathroom.png" },
        { "id": "n-05", "term_zh": "人", "term_target": "사람", "pronunciation": ["Saram"], "example": {"sentence": "좋은 사람.", "translation": "好人。"}, "usage_note": "人類。", "image_file": "people.png" },
        { "id": "n-06", "term_zh": "時間", "term_target": "시간", "pronunciation": ["Sigan"], "example": {"sentence": "시간 있어요?", "translation": "有時間嗎？"}, "usage_note": "時刻。", "image_file": "time.png" },
        { "id": "n-07", "term_zh": "朋友", "term_target": "친구", "pronunciation": ["Chingu"], "example": {"sentence": "제 친구예요.", "translation": "是我朋友。"}, "usage_note": "友人。", "image_file": "friend.png" },
        { "id": "n-08", "term_zh": "家庭", "term_target": "가족", "pronunciation": ["Gajok"], "example": {"sentence": "우리 가족.", "translation": "我們家人。"}, "usage_note": "家人。", "image_file": "family.png" },
        { "id": "n-09", "term_zh": "手機", "term_target": "휴대폰", "pronunciation": ["Hyudaepon"], "example": {"sentence": "제 휴대폰이에요.", "translation": "是我手機。"}, "usage_note": "或 Handphone。", "image_file": "phone.png" },
        { "id": "n-10", "term_zh": "車", "term_target": "차", "pronunciation": ["Cha"], "example": {"sentence": "차를 타요.", "translation": "搭車。"}, "usage_note": "汽車。", "image_file": "car.png" },
        { "id": "n-11", "term_zh": "巴士", "term_target": "버스", "pronunciation": ["Beoseu"], "example": {"sentence": "버스를 타요.", "translation": "搭公車。"}, "usage_note": "公車。", "image_file": "bus.png" },
        { "id": "n-12", "term_zh": "火車", "term_target": "기차", "pronunciation": ["Gicha"], "example": {"sentence": "기차 여행.", "translation": "火車旅行。"}, "usage_note": "列車。", "image_file": "train.png" },
        { "id": "n-13", "term_zh": "捷運/地鐵", "term_target": "지하철", "pronunciation": ["Jihacheol"], "example": {"sentence": "지하철 역.", "translation": "地鐵站。"}, "usage_note": "地下鐵。", "image_file": "subway.png" },
        { "id": "n-14", "term_zh": "車站", "term_target": "역", "pronunciation": ["Yeok"], "example": {"sentence": "서울역.", "translation": "首爾站。"}, "usage_note": "站點。", "image_file": "station.png" },
        { "id": "n-15", "term_zh": "機場", "term_target": "공항", "pronunciation": ["Gonghang"], "example": {"sentence": "인천공항.", "translation": "仁川機場。"}, "usage_note": "搭飛機處。", "image_file": "airport.png" },
        { "id": "n-16", "term_zh": "票", "term_target": "표", "pronunciation": ["Pyo"], "example": {"sentence": "표를 사요.", "translation": "買票。"}, "usage_note": "入場券或車票。", "image_file": "ticket.png" },
        { "id": "n-17", "term_zh": "飯店", "term_target": "호텔", "pronunciation": ["Hotel"], "example": {"sentence": "호텔 예약.", "translation": "訂飯店。"}, "usage_note": "住宿。", "image_file": "hotel.png" },
        { "id": "n-18", "term_zh": "護照", "term_target": "여권", "pronunciation": ["Yeogwon"], "example": {"sentence": "여권 보여주세요.", "translation": "請出示護照。"}, "usage_note": "出國必備。", "image_file": "passport.png" },
        { "id": "n-19", "term_zh": "地圖", "term_target": "지도", "pronunciation": ["Jido"], "example": {"sentence": "지도를 봐요.", "translation": "看地圖。"}, "usage_note": "指引。", "image_file": "map.png" },
        { "id": "n-20", "term_zh": "警察", "term_target": "경찰", "pronunciation": ["Gyeongchal"], "example": {"sentence": "경찰을 불러요.", "translation": "叫警察。"}, "usage_note": "求救用。", "image_file": "police.png" },
        { "id": "n-21", "term_zh": "台灣人", "term_target": "대만 사람", "pronunciation": ["Daeman saram"], "example": {"sentence": "저는 대만 사람입니다.", "translation": "我是台灣人。"}, "usage_note": "國籍。", "image_file": "taiwanese.png" },
        { "id": "n-22", "term_zh": "孩子", "term_target": "아이", "pronunciation": ["Ai"], "example": {"sentence": "아이가 있어요.", "translation": "有孩子。"}, "usage_note": "兒童。", "image_file": "child.png" },
        { "id": "n-23", "term_zh": "學生", "term_target": "학생", "pronunciation": ["Haksaeng"], "example": {"sentence": "저는 학생이에요.", "translation": "我是學生。"}, "usage_note": "在學者。", "image_file": "student.png" },
        { "id": "n-24", "term_zh": "文化", "term_target": "문화", "pronunciation": ["Munhwa"], "example": {"sentence": "한국 문화.", "translation": "韓國文化。"}, "usage_note": "文化。", "image_file": "culture.png" },
        { "id": "n-25", "term_zh": "問題", "term_target": "문제", "pronunciation": ["Munje"], "example": {"sentence": "문제 없어요.", "translation": "沒問題。"}, "usage_note": "難題。", "image_file": "problem.png" },
        { "id": "n-26", "term_zh": "公司", "term_target": "회사", "pronunciation": ["Hoesa"], "example": {"sentence": "회사에 가요.", "translation": "去公司。"}, "usage_note": "上班地點。", "image_file": "company.png" },
        { "id": "n-27", "term_zh": "男性", "term_target": "남자", "pronunciation": ["Namja"], "example": {"sentence": "남자 화장실.", "translation": "男廁。"}, "usage_note": "性別。", "image_file": "man.png" },
        { "id": "n-28", "term_zh": "女性", "term_target": "여자", "pronunciation": ["Yeoja"], "example": {"sentence": "여자 친구.", "translation": "女朋友。"}, "usage_note": "性別。", "image_file": "woman.png" },
        { "id": "n-29", "term_zh": "學校", "term_target": "학교", "pronunciation": ["Hakgyo"], "example": {"sentence": "학교에 가요.", "translation": "去學校。"}, "usage_note": "教育機構。", "image_file": "school.png" },
        { "id": "n-30", "term_zh": "老師", "term_target": "선생님", "pronunciation": ["Seonsaengnim"], "example": {"sentence": "안녕하세요 선생님.", "translation": "老師好。"}, "usage_note": "師長。", "image_file": "teacher.png" },
        { "id": "n-31", "term_zh": "電影", "term_target": "영화", "pronunciation": ["Yeonghwa"], "example": {"sentence": "영화를 봐요.", "translation": "看電影。"}, "usage_note": "影片。", "image_file": "movie.png" },
        { "id": "n-32", "term_zh": "電腦", "term_target": "컴퓨터", "pronunciation": ["Keompyuteo"], "example": {"sentence": "컴퓨터를 해요.", "translation": "用電腦。"}, "usage_note": "PC。", "image_file": "computer.png" },
        { "id": "n-33", "term_zh": "市場", "term_target": "시장", "pronunciation": ["Sijang"], "example": {"sentence": "시장에 가요.", "translation": "去市場。"}, "usage_note": "市集。", "image_file": "market.png" },
        { "id": "n-34", "term_zh": "衣服", "term_target": "옷", "pronunciation": ["Ot"], "example": {"sentence": "옷을 사요.", "translation": "買衣服。"}, "usage_note": "衣物。", "image_file": "clothes.png" },
        { "id": "n-35", "term_zh": "商店", "term_target": "가게", "pronunciation": ["Gage"], "example": {"sentence": "가게에 들어가요.", "translation": "進店裡。"}, "usage_note": "店家。", "image_file": "shop.png" },
        { "id": "n-36", "term_zh": "街道", "term_target": "길", "pronunciation": ["Gil"], "example": {"sentence": "이 길로 가요.", "translation": "走這條路。"}, "usage_note": "道路。", "image_file": "street.png" },
        { "id": "n-37", "term_zh": "房子", "term_target": "집", "pronunciation": ["Jip"], "example": {"sentence": "우리 집.", "translation": "我家。"}, "usage_note": "住宅。", "image_file": "house.png" },
        { "id": "n-38", "term_zh": "母親", "term_target": "어머니", "pronunciation": ["Eomeoni"], "example": {"sentence": "저의 어머니.", "translation": "我媽媽。"}, "usage_note": "媽媽。", "image_file": "mother.png" },
        { "id": "n-39", "term_zh": "父親", "term_target": "아버지", "pronunciation": ["Abeoji"], "example": {"sentence": "저의 아버지.", "translation": "我爸爸。"}, "usage_note": "爸爸。", "image_file": "father.png" },
        { "id": "n-40", "term_zh": "中文", "term_target": "중국어", "pronunciation": ["Junggugeo"], "example": {"sentence": "중국어를 해요.", "translation": "說中文。"}, "usage_note": "語言。", "image_file": "chinese.png" },
        { "id": "n-41", "term_zh": "包包", "term_target": "가방", "pronunciation": ["Gabang"], "example": {"sentence": "가방을 들어요.", "translation": "拿包包。"}, "usage_note": "提包。", "image_file": "bag.png" },
        { "id": "n-42", "term_zh": "杯子", "term_target": "컵", "pronunciation": ["Keop"], "example": {"sentence": "컵 주세요.", "translation": "請給杯子。"}, "usage_note": "杯具。", "image_file": "cup.png" },
        { "id": "n-43", "term_zh": "醫生", "term_target": "의사", "pronunciation": ["Uisa"], "example": {"sentence": "의사를 만나요.", "translation": "看醫生。"}, "usage_note": "醫師。", "image_file": "doctor.png" },
        { "id": "n-44", "term_zh": "醫院", "term_target": "병원", "pronunciation": ["Byeongwon"], "example": {"sentence": "병원에 가요.", "translation": "去醫院。"}, "usage_note": "醫療院所。", "image_file": "hospital.png" },
        { "id": "n-45", "term_zh": "座位", "term_target": "좌석 / 자리", "pronunciation": ["Jwaseok", "Jari"], "example": {"sentence": "자리 있어요?", "translation": "有位子嗎？"}, "usage_note": "位子。", "image_file": "seat.png" },
        { "id": "n-46", "term_zh": "門", "term_target": "문", "pronunciation": ["Mun"], "example": {"sentence": "문을 열어요.", "translation": "開門。"}, "usage_note": "門戶。", "image_file": "door.png" },
        { "id": "n-47", "term_zh": "房間", "term_target": "방", "pronunciation": ["Bang"], "example": {"sentence": "제 방이에요.", "translation": "我房間。"}, "usage_note": "室內。", "image_file": "room.png" },
        { "id": "n-48", "term_zh": "行李", "term_target": "짐", "pronunciation": ["Jim"], "example": {"sentence": "짐이 많아요.", "translation": "行李很多。"}, "usage_note": "包裹。", "image_file": "luggage.png" },
        { "id": "n-49", "term_zh": "櫃檯", "term_target": "카운터", "pronunciation": ["Kaunteo"], "example": {"sentence": "카운터로 가세요.", "translation": "請去櫃檯。"}, "usage_note": "服務台。", "image_file": "counter.png" },
        { "id": "n-50", "term_zh": "大廳", "term_target": "로비", "pronunciation": ["Robi"], "example": {"sentence": "로비에서 만나요.", "translation": "大廳見。"}, "usage_note": "接待處。", "image_file": "lobby.png" },
        { "id": "n-51", "term_zh": "預定", "term_target": "예약", "pronunciation": ["Yeyak"], "example": {"sentence": "예약했어요.", "translation": "我預約了。"}, "usage_note": "預約。", "image_file": "reservation.png" },
        { "id": "n-52", "term_zh": "入住", "term_target": "체크인", "pronunciation": ["Chekeuin"], "example": {"sentence": "체크인 할게요.", "translation": "我要辦理入住。"}, "usage_note": "Check-in。", "image_file": "check_in.png" },
        { "id": "n-53", "term_zh": "退房", "term_target": "체크아웃", "pronunciation": ["Chekeuaut"], "example": {"sentence": "체크아웃 시간.", "translation": "退房時間。"}, "usage_note": "Check-out。", "image_file": "check_out.png" },
        { "id": "n-54", "term_zh": "飲料", "term_target": "음료수", "pronunciation": ["Eumnyosu"], "example": {"sentence": "음료수 드실래요?", "translation": "要喝飲料嗎？"}, "usage_note": "飲品。", "image_file": "drink.png" },
        { "id": "n-55", "term_zh": "菜單", "term_target": "메뉴", "pronunciation": ["Menyu"], "example": {"sentence": "메뉴 주세요.", "translation": "請給菜單。"}, "usage_note": "Menu。", "image_file": "menu.png" },
        { "id": "n-56", "term_zh": "午餐", "term_target": "점심", "pronunciation": ["Jeomsim"], "example": {"sentence": "점심 먹어요.", "translation": "吃午餐。"}, "usage_note": "中餐。", "image_file": "lunch.png" },
        { "id": "n-57", "term_zh": "晚餐", "term_target": "저녁", "pronunciation": ["Jeonyeok"], "example": {"sentence": "저녁 먹어요.", "translation": "吃晚餐。"}, "usage_note": "晚餐。", "image_file": "dinner.png" },
        { "id": "n-58", "term_zh": "帳單", "term_target": "계산서", "pronunciation": ["Gyesanseo"], "example": {"sentence": "계산서 주세요.", "translation": "麻煩結帳。"}, "usage_note": "買單。", "image_file": "bill.png" },
        { "id": "n-59", "term_zh": "價錢", "term_target": "가격", "pronunciation": ["Gagyeok"], "example": {"sentence": "가격이 싸요.", "translation": "價格便宜。"}, "usage_note": "價格。", "image_file": "price.png" },
        { "id": "n-60", "term_zh": "收據", "term_target": "영수증", "pronunciation": ["Yeongsujeung"], "example": {"sentence": "영수증 주세요.", "translation": "請給收據。"}, "usage_note": "統一發票。", "image_file": "receipt.png" },
        { "id": "n-61", "term_zh": "尺寸", "term_target": "사이즈", "pronunciation": ["Saijeu"], "example": {"sentence": "큰 사이즈.", "translation": "大尺寸。"}, "usage_note": "大小。", "image_file": "size.png" },
        { "id": "n-62", "term_zh": "入口", "term_target": "입구", "pronunciation": ["Ipgu"], "example": {"sentence": "입구가 어디예요?", "translation": "入口在哪？"}, "usage_note": "進去的地方。", "image_file": "entrance.png" },
        { "id": "n-63", "term_zh": "出口", "term_target": "출구", "pronunciation": ["Chulgu"], "example": {"sentence": "3번 출구.", "translation": "3號出口。"}, "usage_note": "出去的地方。", "image_file": "exit.png" },
        { "id": "n-64", "term_zh": "台灣", "term_target": "대만", "pronunciation": ["Daeman"], "example": {"sentence": "대만에서 왔어요.", "translation": "來自台灣。"}, "usage_note": "地名。", "image_file": "taiwan.png" },
        { "id": "n-65", "term_zh": "一切事物", "term_target": "모든 것", "pronunciation": ["Modeun geot"], "example": {"sentence": "모든 것이 좋아요.", "translation": "一切都好。"}, "usage_note": "所有。", "image_file": "everything.png" },
        { "id": "n-66", "term_zh": "錢包", "term_target": "지갑", "pronunciation": ["Jigap"], "example": {"sentence": "지갑을 잃어버렸어요.", "translation": "掉了錢包。"}, "usage_note": "皮夾。", "image_file": "wallet.png" },
        { "id": "n-67", "term_zh": "身分證", "term_target": "신분증", "pronunciation": ["Sinbunjeung"], "example": {"sentence": "신분증 주세요.", "translation": "請出示證件。"}, "usage_note": "ID。", "image_file": "id.png" },
        { "id": "n-68", "term_zh": "餐廳", "term_target": "식당", "pronunciation": ["Sikdang"], "example": {"sentence": "맛있는 식당.", "translation": "好吃的餐廳。"}, "usage_note": "食堂。", "image_file": "restaurant.png" },
        { "id": "n-69", "term_zh": "場所", "term_target": "장소", "pronunciation": ["Jangso"], "example": {"sentence": "약속 장소.", "translation": "約定地點。"}, "usage_note": "地點。", "image_file": "place.png" },
        { "id": "n-70", "term_zh": "店員", "term_target": "점원", "pronunciation": ["Jeomwon"], "example": {"sentence": "점원에게 물어봐요.", "translation": "問店員。"}, "usage_note": "工作人員。", "image_file": "clerk.png" },
        { "id": "n-71", "term_zh": "超市", "term_target": "슈퍼마켓", "pronunciation": ["Syupeomaket"], "example": {"sentence": "슈퍼마켓에 가요.", "translation": "去超市。"}, "usage_note": "量販店。", "image_file": "supermarket.png" },
        { "id": "n-72", "term_zh": "月台", "term_target": "승강장", "pronunciation": ["Seunggangjang"], "example": {"sentence": "1번 승강장.", "translation": "第一月台。"}, "usage_note": "車站月台。", "image_file": "platform.png" }
      ]
    },
    {
      "id": "adverbs",
      "name": "副詞",
      "items": [
        { "id": "adv-01", "term_zh": "現在", "term_target": "지금", "pronunciation": ["Jigeum"], "example": {"sentence": "지금 가요.", "translation": "現在去。"}, "usage_note": "目前。", "image_file": "now.png" },
        { "id": "adv-02", "term_zh": "非常", "term_target": "매우 / 아주", "pronunciation": ["Maeu", "Aju"], "example": {"sentence": "아주 좋아요.", "translation": "非常好。"}, "usage_note": "強調。", "image_file": "very.png" },
        { "id": "adv-03", "term_zh": "真的", "term_target": "정말", "pronunciation": ["Jeongmal"], "example": {"sentence": "정말이에요?", "translation": "真的嗎？"}, "usage_note": "確認或強調。", "image_file": "really.png" },
        { "id": "adv-04", "term_zh": "經常", "term_target": "자주", "pronunciation": ["Jaju"], "example": {"sentence": "자주 와요.", "translation": "常來。"}, "usage_note": "頻率。", "image_file": "often.png" },
        { "id": "adv-05", "term_zh": "通常", "term_target": "보통", "pronunciation": ["Botong"], "example": {"sentence": "보통 7시에 일어나요.", "translation": "通常七點起床。"}, "usage_note": "習慣。", "image_file": "usually.png" },
        { "id": "adv-06", "term_zh": "只有", "term_target": "오직 / 만", "pronunciation": ["Ojik", "Man"], "example": {"sentence": "너만 좋아해.", "translation": "只喜歡你。"}, "usage_note": "唯一。", "image_file": "only.png" },
        { "id": "adv-07", "term_zh": "再次", "term_target": "다시", "pronunciation": ["Dasi"], "example": {"sentence": "다시 만나요.", "translation": "再見面吧。"}, "usage_note": "重複。", "image_file": "again.png" },
        { "id": "adv-08", "term_zh": "一起", "term_target": "같이", "pronunciation": ["Gachi"], "example": {"sentence": "같이 가요.", "translation": "一起去吧。"}, "usage_note": "共同。", "image_file": "together.png" },
        { "id": "adv-09", "term_zh": "或許", "term_target": "아마도", "pronunciation": ["Amado"], "example": {"sentence": "아마도 그럴 거예요.", "translation": "大概是那樣。"}, "usage_note": "不確定。", "image_file": "maybe.png" },
        { "id": "adv-10", "term_zh": "很快", "term_target": "곧", "pronunciation": ["Got"], "example": {"sentence": "곧 도착해요.", "translation": "快到了。"}, "usage_note": "不久後。", "image_file": "soon.png" },
        { "id": "adv-11", "term_zh": "已經", "term_target": "이미 / 벌써", "pronunciation": ["Imi", "Beolsseo"], "example": {"sentence": "벌써 왔어요?", "translation": "已經來了嗎？"}, "usage_note": "完成。", "image_file": "already.png" },
        { "id": "adv-12", "term_zh": "大約", "term_target": "약 / 쯤", "pronunciation": ["Yak", "Jjeum"], "example": {"sentence": "1시쯤 만나요.", "translation": "大約1點見。"}, "usage_note": "概數。", "image_file": "about.png" },
        { "id": "adv-13", "term_zh": "一點點", "term_target": "조금", "pronunciation": ["Jogeum"], "example": {"sentence": "조금만 주세요.", "translation": "請給一點點。"}, "usage_note": "少量。", "image_file": "a_little.png" },
        { "id": "adv-14", "term_zh": "之後", "term_target": "나중에", "pronunciation": ["Najunge"], "example": {"sentence": "나중에 봐요.", "translation": "待會見。"}, "usage_note": "稍後。", "image_file": "later.png" },
        { "id": "adv-15", "term_zh": "仍然", "term_target": "아직", "pronunciation": ["Ajik"], "example": {"sentence": "아직 안 왔어요.", "translation": "還沒來。"}, "usage_note": "持續。", "image_file": "still.png" },
        { "id": "adv-16", "term_zh": "一般來說", "term_target": "일반적으로", "pronunciation": ["Ilbanjeogeuro"], "example": {"sentence": "일반적으로 그래요.", "translation": "一般是那樣。"}, "usage_note": "通常。", "image_file": "normally.png" }
      ]
    },
    {
      "id": "questions",
      "name": "疑問詞",
      "items": [
        { "id": "q-01", "term_zh": "什麼", "term_target": "무엇 / 뭐", "pronunciation": ["Mueot", "Mwo"], "example": {"sentence": "이게 뭐예요?", "translation": "這是什麼？"}, "usage_note": "問事物。", "image_file": "what.png" },
        { "id": "q-02", "term_zh": "哪裡", "term_target": "어디", "pronunciation": ["Eodi"], "example": {"sentence": "어디 가요?", "translation": "去哪裡？"}, "usage_note": "問地點。", "image_file": "where.png" },
        { "id": "q-03", "term_zh": "何時", "term_target": "언제", "pronunciation": ["Eonje"], "example": {"sentence": "언제 와요?", "translation": "何時來？"}, "usage_note": "問時間。", "image_file": "when.png" },
        { "id": "q-04", "term_zh": "誰", "term_target": "누구", "pronunciation": ["Nugu"], "example": {"sentence": "누구세요?", "translation": "哪位？"}, "usage_note": "問人。", "image_file": "who.png" },
        { "id": "q-05", "term_zh": "為什麼", "term_target": "왜", "pronunciation": ["Wae"], "example": {"sentence": "왜 그래요?", "translation": "怎麼了(為什麼那樣)？"}, "usage_note": "問原因。", "image_file": "why.png" },
        { "id": "q-06", "term_zh": "如何", "term_target": "어떻게", "pronunciation": ["Eotteoke"], "example": {"sentence": "어떻게 가요?", "translation": "怎麼去？"}, "usage_note": "問方法。", "image_file": "how.png" },
        { "id": "q-07", "term_zh": "多少(錢)", "term_target": "얼마", "pronunciation": ["Eolma"], "example": {"sentence": "얼마예요?", "translation": "多少錢？"}, "usage_note": "問價格。", "image_file": "how_much.png" },
        { "id": "q-08", "term_zh": "多久/多少(量)", "term_target": "얼마나", "pronunciation": ["Eolmana"], "example": {"sentence": "얼마나 걸려요?", "translation": "要花多久？"}, "usage_note": "問程度或時間長度。", "image_file": "how_long.png" },
        { "id": "q-09", "term_zh": "哪一個", "term_target": "어느", "pronunciation": ["Eoneu"], "example": {"sentence": "어느 것이에요?", "translation": "是哪一個？"}, "usage_note": "選擇。", "image_file": "which.png" }
      ]
    },
    {
      "id": "time_place",
      "name": "時間與場所",
      "items": [
        { "id": "tp-01", "term_zh": "今天", "term_target": "오늘", "pronunciation": ["Oneul"], "example": {"sentence": "오늘은 더워요.", "translation": "今天很熱。"}, "usage_note": "本日。", "image_file": "today.png" },
        { "id": "tp-02", "term_zh": "明天", "term_target": "내일", "pronunciation": ["Naeil"], "example": {"sentence": "내일 봐요.", "translation": "明天見。"}, "usage_note": "隔天。", "image_file": "tomorrow.png" },
        { "id": "tp-03", "term_zh": "昨天", "term_target": "어제", "pronunciation": ["Eoje"], "example": {"sentence": "어제 왔어요.", "translation": "昨天來了。"}, "usage_note": "前一天。", "image_file": "yesterday.png" },
        { "id": "tp-04", "term_zh": "這裡", "term_target": "여기", "pronunciation": ["Yeogi"], "example": {"sentence": "여기요.", "translation": "這裡。"}, "usage_note": "近處。", "image_file": "here.png" },
        { "id": "tp-05", "term_zh": "那裡", "term_target": "거기 / 저기", "pronunciation": ["Geogi", "Jeogi"], "example": {"sentence": "저기 보세요.", "translation": "看那裡。"}, "usage_note": "Geogi(對方那), Jeogi(遠處)。", "image_file": "there.png" },
        { "id": "tp-06", "term_zh": "早上", "term_target": "아침", "pronunciation": ["Achim"], "example": {"sentence": "아침 먹어요.", "translation": "吃早餐。"}, "usage_note": "上午。", "image_file": "morning.png" },
        { "id": "tp-07", "term_zh": "晚上/夜晚", "term_target": "밤", "pronunciation": ["Bam"], "example": {"sentence": "밤에 자요.", "translation": "晚上睡覺。"}, "usage_note": "太陽下山後。", "image_file": "night.png" },
        { "id": "tp-08", "term_zh": "前面", "term_target": "앞", "pronunciation": ["Ap"], "example": {"sentence": "역 앞에서 만나요.", "translation": "車站前見。"}, "usage_note": "前方。", "image_file": "front.png" },
        { "id": "tp-09", "term_zh": "後面", "term_target": "뒤", "pronunciation": ["Dwi"], "example": {"sentence": "문 뒤에 있어요.", "translation": "在門後。"}, "usage_note": "後方。", "image_file": "behind.png" },
        { "id": "tp-10", "term_zh": "左邊", "term_target": "왼쪽", "pronunciation": ["Oenjjok"], "example": {"sentence": "왼쪽으로 가요.", "translation": "往左走。"}, "usage_note": "左。", "image_file": "left.png" },
        { "id": "tp-11", "term_zh": "右邊", "term_target": "오른쪽", "pronunciation": ["Oreunjjok"], "example": {"sentence": "오른쪽에 있어요.", "translation": "在右邊。"}, "usage_note": "右。", "image_file": "right.png" },
        { "id": "tp-12", "term_zh": "天(日)", "term_target": "일 / 날", "pronunciation": ["Il", "Nal"], "example": {"sentence": "좋은 날.", "translation": "好日子。"}, "usage_note": "日子。", "image_file": "day.png" },
        { "id": "tp-13", "term_zh": "年", "term_target": "년 / 해", "pronunciation": ["Nyeon", "Hae"], "example": {"sentence": "새해.", "translation": "新年。"}, "usage_note": "年度。", "image_file": "year.png" },
        { "id": "tp-14", "term_zh": "月", "term_target": "월 / 달", "pronunciation": ["Wol", "Dal"], "example": {"sentence": "이번 달.", "translation": "這個月。"}, "usage_note": "月份。", "image_file": "month.png" },
        { "id": "tp-15", "term_zh": "週", "term_target": "주", "pronunciation": ["Ju"], "example": {"sentence": "이번 주.", "translation": "這週。"}, "usage_note": "星期。", "image_file": "week.png" },
        { "id": "tp-16", "term_zh": "下午", "term_target": "오후", "pronunciation": ["Ohu"], "example": {"sentence": "오후 2시.", "translation": "下午2點。"}, "usage_note": "PM。", "image_file": "afternoon.png" },
        { "id": "tp-17", "term_zh": "中午", "term_target": "정오 / 낮", "pronunciation": ["Jeongo", "Nat"], "example": {"sentence": "낮에 만나요.", "translation": "中午見。"}, "usage_note": "12點。", "image_file": "noon.png" },
        { "id": "tp-18", "term_zh": "旁邊", "term_target": "옆", "pronunciation": ["Yeop"], "example": {"sentence": "제 옆에 앉아요.", "translation": "坐我旁邊。"}, "usage_note": "側邊。", "image_file": "beside.png" },
        { "id": "tp-19", "term_zh": "對面", "term_target": "건너편", "pronunciation": ["Geonneopyeon"], "example": {"sentence": "길 건너편.", "translation": "路對面。"}, "usage_note": "對側。", "image_file": "across_from.png" },
        { "id": "tp-20", "term_zh": "春天", "term_target": "봄", "pronunciation": ["Bom"], "example": {"sentence": "봄이 왔어요.", "translation": "春天來了。"}, "usage_note": "季節。", "image_file": "spring.png" },
        { "id": "tp-21", "term_zh": "夏天", "term_target": "여름", "pronunciation": ["Yeoreum"], "example": {"sentence": "여름은 더워요.", "translation": "夏天很熱。"}, "usage_note": "季節。", "image_file": "summer.png" },
        { "id": "tp-22", "term_zh": "秋天", "term_target": "가을", "pronunciation": ["Gaeul"], "example": {"sentence": "가을을 좋아해요.", "translation": "喜歡秋天。"}, "usage_note": "季節。", "image_file": "autumn.png" },
        { "id": "tp-23", "term_zh": "冬天", "term_target": "겨울", "pronunciation": ["Gyeoul"], "example": {"sentence": "겨울은 추워요.", "translation": "冬天很冷。"}, "usage_note": "季節。", "image_file": "winter.png" }
      ]
    },
    {
      "id": "numbers",
      "name": "數字",
      "items": [
        { "id": "num-0", "term_zh": "0", "term_target": "영 / 공", "pronunciation": ["Yeong / Gong"], "example": {"sentence": "영하.", "translation": "零下。"}, "usage_note": "零。", "image_file": "zero.png" },
        { "id": "num-1", "term_zh": "1", "term_target": "일 / 하나", "pronunciation": ["Il / Hana"], "example": {"sentence": "하나 주세요.", "translation": "請給我一個 (Hana)。"}, "usage_note": "數數用Hana，日期價格用Il。", "image_file": "one.png" },
        { "id": "num-2", "term_zh": "2", "term_target": "이 / 둘", "pronunciation": ["I / Dul"], "example": {"sentence": "두 명.", "translation": "兩個人 (Du myeong)。"}, "usage_note": "數數用Dul，日期價格用I。", "image_file": "two.png" },
        { "id": "num-3", "term_zh": "3", "term_target": "삼 / 셋", "pronunciation": ["Sam / Set"], "example": {"sentence": "세 개.", "translation": "三個 (Se gae)。"}, "usage_note": "數數用Set，日期價格用Sam。", "image_file": "three.png" },
        { "id": "num-4", "term_zh": "4", "term_target": "사 / 넷", "pronunciation": ["Sa / Net"], "example": {"sentence": "네 시.", "translation": "四點 (Ne si)。"}, "usage_note": "數數用Net，日期價格用Sa。", "image_file": "four.png" },
        { "id": "num-5", "term_zh": "5", "term_target": "오 / 다섯", "pronunciation": ["O / Daseot"], "example": {"sentence": "오 층.", "translation": "五樓 (O cheung)。"}, "usage_note": "五。", "image_file": "five.png" },
        { "id": "num-6", "term_zh": "6", "term_target": "육 / 여섯", "pronunciation": ["Yuk / Yeoseot"], "example": {"sentence": "여섯 살.", "translation": "六歲 (Yeoseot sal)。"}, "usage_note": "六。", "image_file": "six.png" },
        { "id": "num-7", "term_zh": "7", "term_target": "칠 / 일곱", "pronunciation": ["Chil / Ilgop"], "example": {"sentence": "칠 월.", "translation": "七月 (Chil wol)。"}, "usage_note": "七。", "image_file": "seven.png" },
        { "id": "num-8", "term_zh": "8", "term_target": "팔 / 여덟", "pronunciation": ["Pal / Yeodeol"], "example": {"sentence": "팔 층.", "translation": "八樓 (Pal cheung)。"}, "usage_note": "八。", "image_file": "eight.png" },
        { "id": "num-9", "term_zh": "9", "term_target": "구 / 아홉", "pronunciation": ["Gu / Ahop"], "example": {"sentence": "구 천원.", "translation": "九千元 (Gu cheonwon)。"}, "usage_note": "九。", "image_file": "nine.png" },
        { "id": "num-10", "term_zh": "10", "term_target": "십 / 열", "pronunciation": ["Sip / Yeol"], "example": {"sentence": "열 개.", "translation": "十個 (Yeol gae)。"}, "usage_note": "十。", "image_file": "ten.png" },
        { "id": "num-11", "term_zh": "11", "term_target": "십일 / 열하나", "pronunciation": ["Sibil / Yeolhana"], "example": {"sentence": "십일 일.", "translation": "11日。"}, "usage_note": "十一。", "image_file": "eleven.png" },
        { "id": "num-12", "term_zh": "12", "term_target": "십이 / 열둘", "pronunciation": ["Sibi / Yeoldul"], "example": {"sentence": "열두 시.", "translation": "12點 (Yeoldu si)。"}, "usage_note": "十二。", "image_file": "twelve.png" },
        { "id": "num-15", "term_zh": "15", "term_target": "십오 / 열다섯", "pronunciation": ["Sibo / Yeoldaseot"], "example": {"sentence": "십오 분.", "translation": "15分。"}, "usage_note": "十五。", "image_file": "fifteen.png" },
        { "id": "num-20", "term_zh": "20", "term_target": "이십 / 스물", "pronunciation": ["Isip / Seumul"], "example": {"sentence": "스무 살.", "translation": "20歲 (Seumu sal)。"}, "usage_note": "二十。", "image_file": "twenty.png" },
        { "id": "num-50", "term_zh": "50", "term_target": "오십 / 쉰", "pronunciation": ["Osip / Swin"], "example": {"sentence": "오십 원.", "translation": "50元。"}, "usage_note": "五十。", "image_file": "fifty.png" },
        { "id": "num-100", "term_zh": "100", "term_target": "백", "pronunciation": ["Baek"], "example": {"sentence": "백 점.", "translation": "一百分。"}, "usage_note": "百。", "image_file": "hundred.png" },
        { "id": "num-1000", "term_zh": "1000", "term_target": "천", "pronunciation": ["Cheon"], "example": {"sentence": "천 원.", "translation": "一千元。"}, "usage_note": "千。", "image_file": "thousand.png" },
        { "id": "num-10000", "term_zh": "10000", "term_target": "만", "pronunciation": ["Man"], "example": {"sentence": "만 원.", "translation": "一萬元。"}, "usage_note": "一萬。", "image_file": "ten_thousand.png" }
      ]
    },
    {
      "id": "grammar",
      "name": "基本句型",
      "items": [
        { "id": "g-01", "term_zh": "我是...", "term_target": "저는 ...입니다 / 예요", "pronunciation": ["Jeoneun ...imnida / yeyo"], "example": {"sentence": "저는 학생이에요.", "translation": "我是學生。"}, "usage_note": "最基本的肯定句。", "image_file": "i_am.png" },
        { "id": "g-02", "term_zh": "我正在...", "term_target": "...하고 있어요", "pronunciation": ["...hago isseoyo"], "example": {"sentence": "밥을 먹고 있어요.", "translation": "我正在吃飯。"}, "usage_note": "進行式。", "image_file": "ing.png" },
        { "id": "g-03", "term_zh": "我能夠(會)...", "term_target": "...할 수 있어요", "pronunciation": ["...hal su isseoyo"], "example": {"sentence": "운전할 수 있어요.", "translation": "我會開車。"}, "usage_note": "能力。", "image_file": "can.png" },
        { "id": "g-04", "term_zh": "我喜歡做...", "term_target": "...을/를 좋아해요", "pronunciation": ["...eul/reul joahaeyo"], "example": {"sentence": "독서를 좋아해요.", "translation": "我喜歡閱讀。"}, "usage_note": "興趣。", "image_file": "like_ing.png" },
        { "id": "g-05", "term_zh": "我想做...", "term_target": "...하고 싶어요", "pronunciation": ["...hago sipeoyo"], "example": {"sentence": "가고 싶어요.", "translation": "我想去。"}, "usage_note": "慾望。", "image_file": "want_to.png" },
        { "id": "g-06", "term_zh": "你是...嗎?", "term_target": "...입니까? / ...예요?", "pronunciation": ["...imnikka? / ...yeyo?"], "example": {"sentence": "학생이에요?", "translation": "你是學生嗎？"}, "usage_note": "確認身分。", "image_file": "are_you.png" },
        { "id": "g-07", "term_zh": "不要...", "term_target": "...하지 마세요", "pronunciation": ["...haji maseyo"], "example": {"sentence": "가지 마세요.", "translation": "請不要走。"}, "usage_note": "禁止/請求。", "image_file": "dont.png" },
        { "id": "g-08", "term_zh": "你有做...嗎?", "term_target": "...해요?", "pronunciation": ["...haeyo?"], "example": {"sentence": "운동해요?", "translation": "你有運動嗎？"}, "usage_note": "一般疑問句。", "image_file": "do_you.png" },
        { "id": "g-09", "term_zh": "你曾經...嗎?", "term_target": "...해 본 적 있어요?", "pronunciation": ["...hae bon jeok isseoyo?"], "example": {"sentence": "가 본 적 있어요?", "translation": "你有去過嗎？"}, "usage_note": "問經驗。", "image_file": "have_you_ever.png" },
        { "id": "g-10", "term_zh": "你何時做...?", "term_target": "언제 ...해요?", "pronunciation": ["Eonje ...haeyo?"], "example": {"sentence": "언제 자요?", "translation": "你何時睡？"}, "usage_note": "問時間點。", "image_file": "when_do_you.png" },
        { "id": "g-11", "term_zh": "你在哪裡做...?", "term_target": "어디서 ...해요?", "pronunciation": ["Eodiseo ...haeyo?"], "example": {"sentence": "어디서 사요?", "translation": "你在哪買？"}, "usage_note": "問地點。", "image_file": "where_do_you.png" },
        { "id": "g-12", "term_zh": "你如何做...?", "term_target": "어떻게 ...해요?", "pronunciation": ["Eotteoke ...haeyo?"], "example": {"sentence": "어떻게 가요?", "translation": "你怎麼去？"}, "usage_note": "問方法。", "image_file": "how_do_you.png" },
        { "id": "g-13", "term_zh": "我不是...", "term_target": "...이/가 아니에요", "pronunciation": ["...i/ga anieyo"], "example": {"sentence": "학생이 아니에요.", "translation": "我不是學生。"}, "usage_note": "否定身分。", "image_file": "i_am_not.png" },
        { "id": "g-14", "term_zh": "我不做...", "term_target": "안 ...해요 / ...지 않아요", "pronunciation": ["An ...haeyo / ...ji anayo"], "example": {"sentence": "안 먹어요.", "translation": "我不吃。"}, "usage_note": "否定動作。", "image_file": "i_dont.png" },
        { "id": "g-15", "term_zh": "我不能(會)...", "term_target": "못 ...해요 / ...할 수 없어요", "pronunciation": ["Mot ...haeyo / ...hal su eopseoyo"], "example": {"sentence": "운전할 수 없어요.", "translation": "我不會開車。"}, "usage_note": "能力否定。", "image_file": "i_cant.png" },
        { "id": "g-16", "term_zh": "我未曾...", "term_target": "...해 본 적 없어요", "pronunciation": ["...hae bon jeok eopseoyo"], "example": {"sentence": "먹어 본 적 없어요.", "translation": "我沒吃過這個。"}, "usage_note": "無此經驗。", "image_file": "i_have_never.png" },
        { "id": "g-17", "term_zh": "我不必...", "term_target": "...할 필요 없어요", "pronunciation": ["...hal piryo eopseoyo"], "example": {"sentence": "갈 필요 없어요.", "translation": "我不必去。"}, "usage_note": "無義務。", "image_file": "i_dont_have_to.png" },
        { "id": "g-18", "term_zh": "如果...的話", "term_target": "만약 ...라면", "pronunciation": ["Manyak ...ramyeon"], "example": {"sentence": "싸다면 살게요.", "translation": "如果便宜的話我就買。"}, "usage_note": "假設條件。", "image_file": "if.png" },
        { "id": "g-19", "term_zh": "當...時", "term_target": "...할 때", "pronunciation": ["...hal ttae"], "example": {"sentence": "어렸을 때.", "translation": "小時候。",}, "usage_note": "時間條件。", "image_file": "when_condition.png" },
        { "id": "g-20", "term_zh": "請你...好嗎?", "term_target": "...해 줄 수 있어요?", "pronunciation": ["...hae jul su isseoyo?"], "example": {"sentence": "도와줄 수 있어요?", "translation": "可以幫我嗎？"}, "usage_note": "請求。", "image_file": "can_you.png" },
        { "id": "g-21", "term_zh": "我們來做...吧", "term_target": "...합시다 / ...하자", "pronunciation": ["...hapsida / ...haja"], "example": {"sentence": "갑시다.", "translation": "走吧。"}, "usage_note": "提議。", "image_file": "lets.png" },
        { "id": "g-22", "term_zh": "我認為...", "term_target": "...라고 생각해요", "pronunciation": ["...rago saenggakaeyo"], "example": {"sentence": "좋다고 생각해요.", "translation": "我認為很好。"}, "usage_note": "表達想法。", "image_file": "i_think.png" },
        { "id": "g-23", "term_zh": "我必須...", "term_target": "...해야 해요", "pronunciation": ["...haeya haeyo"], "example": {"sentence": "일해야 해요.", "translation": "我必須工作。"}, "usage_note": "義務。", "image_file": "i_have_to.png" },
        { "id": "g-24", "term_zh": "做某事是...的", "term_target": "...하는 것은 ...해요", "pronunciation": ["...haneun geoseun ...haeyo"], "example": {"sentence": "먹는 것은 즐거워요.", "translation": "吃東西是開心的。"}, "usage_note": "動詞名詞化。", "image_file": "it_is_to.png" },
        { "id": "g-25", "term_zh": "我可以...嗎?", "term_target": "...해도 돼요?", "pronunciation": ["...haedo dwaeyo?"], "example": {"sentence": "사진 찍어도 돼요?", "translation": "我可以拍照嗎？"}, "usage_note": "請求許可。", "image_file": "can_i.png" },
        { "id": "g-26", "term_zh": "我比較喜歡...", "term_target": "...를 더 좋아해요", "pronunciation": ["...reul deo joahaeyo"], "example": {"sentence": "이걸 더 좋아해요.", "translation": "我比較喜歡這個。"}, "usage_note": "偏好。", "image_file": "prefer.png" },
        { "id": "g-27", "term_zh": "A比B更...", "term_target": "A가 B보다 더 ...해요", "pronunciation": ["Aga Bboda deo ...haeyo"], "example": {"sentence": "이게 저것보다 더 비싸요.", "translation": "這比那個貴。"}, "usage_note": "比較級。", "image_file": "more_than.png" },
        { "id": "g-28", "term_zh": "有(存在)...", "term_target": "...이/가 있어요", "pronunciation": ["...i/ga isseoyo"], "example": {"sentence": "강아지가 있어요.", "translation": "有一隻狗。"}, "usage_note": "存在。", "image_file": "there_is.png" },
        { "id": "g-29", "term_zh": "我曾經是/當時是...", "term_target": "...였어요 / 이었어요", "pronunciation": ["...yeosseoyo / ieosseoyo"], "example": {"sentence": "저는 학생이었어요.", "translation": "我曾經是學生。"}, "usage_note": "過去狀態。", "image_file": "i_was.png" },
        { "id": "g-30", "term_zh": "我將要...", "term_target": "...할 거예요", "pronunciation": ["...hal geoyeyo"], "example": {"sentence": "갈 거예요.", "translation": "我要去。"}, "usage_note": "未來意。", "image_file": "i_will.png" },
        { "id": "g-31", "term_zh": "我做過(過去式)...", "term_target": "...했어요", "pronunciation": ["...haesseoyo"], "example": {"sentence": "숙제 했어요.", "translation": "我做完功課了。"}, "usage_note": "過去動作。", "image_file": "i_did.png" }
      ]
    }
  ]
}