import { AppData } from '../types';

export const thaiData: AppData = 
{
  "meta": {
    "source_language": "zh-TW",
    "target_language": "th-TH",
    "version": "2.3",
    "description": "台灣人快速語言學習 - 泰文完整版 (包含所有原始列表單字與完整句型 - 羅馬拼音版)"
  },
  "categories": [
    {
      "id": "greetings",
      "name": "常用句",
      "items": [
        {
          "id": "greet-001",
          "term_zh": "你好",
          "term_target": "สวัสดี",
          "pronunciation": ["Sawatdee"],
          "example": { "sentence": "สวัสดีครับ / ค่ะ", "translation": "你好。" },
          "usage_note": "男生說 Sawatdee kráp，女生說 Sawatdee khâ。",
          "image_file": "hello.png"
        },
        {
          "id": "greet-002",
          "term_zh": "再見",
          "term_target": "ลาก่อน",
          "pronunciation": ["La gon"],
          "example": { "sentence": "ลาก่อน แล้วเจอกันใหม่", "translation": "再見，下次見。" },
          "usage_note": "正式道別。口語常用 Bye Bye。",
          "image_file": "goodbye.png"
        },
        {
          "id": "greet-003",
          "term_zh": "謝謝你",
          "term_target": "ขอบคุณ",
          "pronunciation": ["Khop khun"],
          "example": { "sentence": "ขอบคุณมากครับ / ค่ะ", "translation": "非常謝謝你。" },
          "usage_note": "加上 Mak (非常) 表示非常感謝。",
          "image_file": "thank_you.png"
        },
        {
          "id": "greet-004",
          "term_zh": "對不起",
          "term_target": "ขอโทษ",
          "pronunciation": ["Kho thot"],
          "example": { "sentence": "ขอโทษครับ / ค่ะ", "translation": "對不起。" },
          "usage_note": "道歉或藉過時使用。",
          "image_file": "sorry.png"
        },
        {
          "id": "greet-005",
          "term_zh": "早安",
          "term_target": "สวัสดีตอนเช้า",
          "pronunciation": ["Sawatdee ton chao"],
          "example": { "sentence": "สวัสดีตอนเช้าครับ / ค่ะ", "translation": "早安。" },
          "usage_note": "Ton chao 意思是「早上」。",
          "image_file": "good_morning.png"
        },
        {
          "id": "greet-006",
          "term_zh": "請問... / 借過",
          "term_target": "ขอถามหน่อย / ขอทางหน่อย",
          "pronunciation": ["Kho tham noi / Kho thang noi"],
          "example": { "sentence": "ขอถามหน่อยครับ ห้องน้ำอยู่ที่ไหน", "translation": "請問一下，廁所在哪裡？" },
          "usage_note": "發問用 Kho tham (請教)，借過用 Kho thang (借路)。",
          "image_file": "excuse_me.png"
        },
        {
          "id": "greet-007",
          "term_zh": "我不懂",
          "term_target": "ไม่เข้าใจ",
          "pronunciation": ["Mai khao jai"],
          "example": { "sentence": "ผมไม่เข้าใจภาษาไทย", "translation": "我不懂泰文。" },
          "usage_note": "Mai 是「不」，Khao jai 是「明白」。",
          "image_file": "dont_understand.png"
        },
        {
          "id": "greet-008",
          "term_zh": "這是什麼？",
          "term_target": "นี่คืออะไร?",
          "pronunciation": ["Ni khue arai?"],
          "example": { "sentence": "นี่คืออะไร? กินได้ไหม?", "translation": "這是什麼？能吃嗎？" },
          "usage_note": "指著東西問。",
          "image_file": "what_is_this.png"
        },
        {
          "id": "greet-009",
          "term_zh": "我想要這個",
          "term_target": "เอาอันนี้",
          "pronunciation": ["Ao an ni"],
          "example": { "sentence": "เอาอันนี้ครับ / ค่ะ", "translation": "我要這個。" },
          "usage_note": "Ao 是「要」，An ni 是「這個」。",
          "image_file": "i_want_this.png"
        },
        {
          "id": "greet-010",
          "term_zh": "請給我...",
          "term_target": "ขอ...หน่อย",
          "pronunciation": ["Kho ... noi"],
          "example": { "sentence": "ขอน้ำหน่อยครับ", "translation": "請給我水。" },
          "usage_note": "點餐或索取東西用。",
          "image_file": "please_give_me.png"
        },
        {
          "id": "greet-011",
          "term_zh": "廁所在哪裡？",
          "term_target": "ห้องน้ำอยู่ที่ไหน?",
          "pronunciation": ["Hong nam yu thi nai?"],
          "example": { "sentence": "ขอโทษครับ ห้องน้ำอยู่ที่ไหน?", "translation": "不好意思，廁所在哪裡？" },
          "usage_note": "旅遊必備。",
          "image_file": "where_bathroom.png"
        },
        {
          "id": "greet-012",
          "term_zh": "多少錢？",
          "term_target": "เท่าไหร่?",
          "pronunciation": ["Thao rai?"],
          "example": { "sentence": "อันนี้เท่าไหร่?", "translation": "這個多少錢？" },
          "usage_note": "購物用語。",
          "image_file": "how_much.png"
        },
        {
          "id": "greet-013",
          "term_zh": "請幫我",
          "term_target": "ช่วยด้วย",
          "pronunciation": ["Chuai duai"],
          "example": { "sentence": "ช่วยผมด้วย", "translation": "幫幫我。" },
          "usage_note": "Chuai 是「幫」，Duai 是語氣詞或「一起」。緊急時大喊 Chuai duai。",
          "image_file": "help_me.png"
        },
        {
          "id": "greet-014",
          "term_zh": "你可以再說一次嗎？",
          "term_target": "พูดอีกทีได้ไหม?",
          "pronunciation": ["Phut ik thi dai mai?"],
          "example": { "sentence": "ขอโทษครับ พูดอีกทีได้ไหม?", "translation": "抱歉，能再說一次嗎？" },
          "usage_note": "Phut (說)，Ik thi (再一次)。",
          "image_file": "say_again.png"
        },
        {
          "id": "greet-015",
          "term_zh": "你可以講慢一點嗎？",
          "term_target": "พูดช้าๆ หน่อยได้ไหม?",
          "pronunciation": ["Phut cha cha noi dai mai?"],
          "example": { "sentence": "กรุณาพูดช้าๆ หน่อย", "translation": "請講慢一點。" },
          "usage_note": "Cha cha 是「慢慢」。",
          "image_file": "speak_slowly.png"
        }
      ]
    },
    {
      "id": "pronouns",
      "name": "主詞（代名詞）",
      "items": [
        { "id": "pro-01", "term_zh": "我", "term_target": "ผม / ฉัน", "pronunciation": ["Phom / Chan"], "example": {"sentence": "ผมเป็นคนไต้หวัน", "translation": "我是台灣人。"}, "usage_note": "男生用 Phom，女生用 Chan。", "image_file": "i.png" },
        { "id": "pro-02", "term_zh": "你", "term_target": "คุณ", "pronunciation": ["Khun"], "example": {"sentence": "คุณชื่ออะไร?", "translation": "你叫什麼名字？"}, "usage_note": "通用且有禮貌的「你」。", "image_file": "you.png" },
        { "id": "pro-03", "term_zh": "他", "term_target": "เขา", "pronunciation": ["Khao"], "example": {"sentence": "เขาเป็นครู", "translation": "他是老師。"}, "usage_note": "第三人稱單數。", "image_file": "he.png" },
        { "id": "pro-04", "term_zh": "她", "term_target": "เธอ", "pronunciation": ["Thoe"], "example": {"sentence": "เธอสวยมาก", "translation": "她很漂亮。"}, "usage_note": "也可用 Khao。", "image_file": "she.png" },
        { "id": "pro-05", "term_zh": "我們", "term_target": "เรา", "pronunciation": ["Rao"], "example": {"sentence": "เราไปกันเถอะ", "translation": "我們走吧。"}, "usage_note": "我們。", "image_file": "we.png" },
        { "id": "pro-06", "term_zh": "他們", "term_target": "พวกเขา", "pronunciation": ["Phuak khao"], "example": {"sentence": "พวกเขาเป็นนักเรียน", "translation": "他們是學生。"}, "usage_note": "Phuak 表示複數群體。", "image_file": "they.png" },
        { "id": "pro-07", "term_zh": "這個", "term_target": "อันนี้ / นี่", "pronunciation": ["An ni / Ni"], "example": {"sentence": "อันนี้อร่อย", "translation": "這個好吃。"}, "usage_note": "近處。", "image_file": "this.png" },
        { "id": "pro-08", "term_zh": "那個/它", "term_target": "อันนั้น / นั่น / มัน", "pronunciation": ["An nan / Nan / Man"], "example": {"sentence": "นั่นคืออะไร?", "translation": "那是什麼？"}, "usage_note": "Nan (那)，Man (它)。", "image_file": "that.png" },
        { "id": "pro-09", "term_zh": "他的", "term_target": "ของเขา", "pronunciation": ["Khong khao"], "example": {"sentence": "รถของเขา", "translation": "他的車。"}, "usage_note": "所有格用 Khong + 代名詞。", "image_file": "his.png" },
        { "id": "pro-10", "term_zh": "她的", "term_target": "ของเธอ", "pronunciation": ["Khong thoe"], "example": {"sentence": "กระเป๋าของเธอ", "translation": "她的包包。"}, "usage_note": "所有格。", "image_file": "her.png" },
        { "id": "pro-11", "term_zh": "你的", "term_target": "ของคุณ", "pronunciation": ["Khong khun"], "example": {"sentence": "ชื่อของคุณ", "translation": "你的名字。"}, "usage_note": "所有格。", "image_file": "your.png" },
        { "id": "pro-12", "term_zh": "他們的", "term_target": "ของพวกเขา", "pronunciation": ["Khong phuak khao"], "example": {"sentence": "บ้านของพวกเขา", "translation": "他們的家。"}, "usage_note": "所有格。", "image_file": "their.png" },
        { "id": "pro-13", "term_zh": "我們的", "term_target": "ของเรา", "pronunciation": ["Khong rao"], "example": {"sentence": "โรงเรียนของเรา", "translation": "我們的學校。"}, "usage_note": "所有格。", "image_file": "our.png" },
        { "id": "pro-14", "term_zh": "這些", "term_target": "พวกนี้", "pronunciation": ["Phuak ni"], "example": {"sentence": "พวกนี้คือหนังสือ", "translation": "這些是書。"}, "usage_note": "近處複數。", "image_file": "these.png" },
        { "id": "pro-15", "term_zh": "那些", "term_target": "พวกนั้น", "pronunciation": ["Phuak nan"], "example": {"sentence": "พวกนั้นคือนก", "translation": "那些是鳥。"}, "usage_note": "遠處複數。", "image_file": "those.png" }
      ]
    },
    {
      "id": "verbs",
      "name": "動詞",
      "items": [
        { "id": "v-01", "term_zh": "是", "term_target": "เป็น / คือ", "pronunciation": ["Pen / Khue"], "example": {"sentence": "ผมเป็นนักเรียน", "translation": "我是學生。"}, "usage_note": "Pen (身分)，Khue (定義)。", "image_file": "be.png" },
        { "id": "v-02", "term_zh": "有（擁有）", "term_target": "มี", "pronunciation": ["Mi"], "example": {"sentence": "มีเงินไหม?", "translation": "有錢嗎？"}, "usage_note": "擁有或存在。", "image_file": "have.png" },
        { "id": "v-03", "term_zh": "去", "term_target": "ไป", "pronunciation": ["Pai"], "example": {"sentence": "ไปบ้าน", "translation": "回家。"}, "usage_note": "移動。", "image_file": "go.png" },
        { "id": "v-04", "term_zh": "做", "term_target": "ทำ", "pronunciation": ["Tham"], "example": {"sentence": "ทำการบ้าน", "translation": "做作業。"}, "usage_note": "執行動作。", "image_file": "do.png" },
        { "id": "v-05", "term_zh": "說", "term_target": "พูด", "pronunciation": ["Phut"], "example": {"sentence": "พูดสวัสดี", "translation": "說你好。"}, "usage_note": "說話。", "image_file": "say.png" },
        { "id": "v-06", "term_zh": "知道", "term_target": "รู้ / รู้จัก", "pronunciation": ["Ru / Ru-jak"], "example": {"sentence": "ผมรู้ / ผมรู้จักเขา", "translation": "我知道 / 我認識他。"}, "usage_note": "Ru (知道事情)，Ru-jak (認識人/地)。", "image_file": "know.png" },
        { "id": "v-07", "term_zh": "想/思考", "term_target": "คิด", "pronunciation": ["Khit"], "example": {"sentence": "ผมก็คิดแบบนั้น", "translation": "我也這麼覺得。"}, "usage_note": "思考。", "image_file": "think.png" },
        { "id": "v-08", "term_zh": "看見", "term_target": "เห็น", "pronunciation": ["Hen"], "example": {"sentence": "เห็นนกไหม?", "translation": "看見鳥了嗎？"}, "usage_note": "看見。", "image_file": "see.png" },
        { "id": "v-09", "term_zh": "製作", "term_target": "ทำ", "pronunciation": ["Tham"], "example": {"sentence": "ทำอาหาร", "translation": "做飯。"}, "usage_note": "與「做」同字。", "image_file": "make.png" },
        { "id": "v-10", "term_zh": "來", "term_target": "มา", "pronunciation": ["Ma"], "example": {"sentence": "มาที่นี่", "translation": "來這裡。"}, "usage_note": "過來。", "image_file": "come.png" },
        { "id": "v-11", "term_zh": "需要", "term_target": "ต้องการ", "pronunciation": ["Tong-kan"], "example": {"sentence": "ฉันต้องการน้ำ", "translation": "我需要水。"}, "usage_note": "需要。", "image_file": "need.png" },
        { "id": "v-12", "term_zh": "使用", "term_target": "ใช้", "pronunciation": ["Chai"], "example": {"sentence": "ใช้ปากกา", "translation": "用筆。"}, "usage_note": "使用。", "image_file": "use.png" },
        { "id": "v-13", "term_zh": "找到", "term_target": "หา / เจอ", "pronunciation": ["Ha / Je"], "example": {"sentence": "หาเจอแล้ว", "translation": "找到了。"}, "usage_note": "Ha (找)，Je (遇見/找到)。", "image_file": "find.png" },
        { "id": "v-14", "term_zh": "給", "term_target": "ให้", "pronunciation": ["Hai"], "example": {"sentence": "ให้ฉัน", "translation": "給我。"}, "usage_note": "給予。", "image_file": "give.png" },
        { "id": "v-15", "term_zh": "告訴", "term_target": "บอก", "pronunciation": ["Bok"], "example": {"sentence": "บอกฉันหน่อย", "translation": "告訴我。"}, "usage_note": "告知。", "image_file": "tell.png" },
        { "id": "v-16", "term_zh": "工作", "term_target": "ทำงาน", "pronunciation": ["Tham-ngan"], "example": {"sentence": "ผมทำงานที่นี่", "translation": "我在這工作。"}, "usage_note": "勞動。", "image_file": "work.png" },
        { "id": "v-17", "term_zh": "喜歡", "term_target": "ชอบ", "pronunciation": ["Chop"], "example": {"sentence": "ฉันชอบแมว", "translation": "我喜歡貓。"}, "usage_note": "喜好。", "image_file": "like.png" },
        { "id": "v-18", "term_zh": "起床/醒來", "term_target": "ตื่นนอน", "pronunciation": ["Tuen non"], "example": {"sentence": "ตื่นนอนตอนเช้า", "translation": "早上起床。"}, "usage_note": "起床。", "image_file": "wake_up.png" },
        { "id": "v-19", "term_zh": "說話", "term_target": "พูด", "pronunciation": ["Phut"], "example": {"sentence": "พูดภาษาไทย", "translation": "說泰文。"}, "usage_note": "講話。", "image_file": "speak.png" },
        { "id": "v-20", "term_zh": "聽見", "term_target": "ได้ยิน", "pronunciation": ["Dai-yin"], "example": {"sentence": "ได้ยินไหม?", "translation": "聽見了嗎？"}, "usage_note": "聽。", "image_file": "hear.png" },
        { "id": "v-21", "term_zh": "寫", "term_target": "เขียน", "pronunciation": ["Khian"], "example": {"sentence": "เขียนชื่อ", "translation": "寫名字。"}, "usage_note": "書寫。", "image_file": "write.png" },
        { "id": "v-22", "term_zh": "閱讀", "term_target": "อ่าน", "pronunciation": ["An"], "example": {"sentence": "อ่านหนังสือ", "translation": "看書。"}, "usage_note": "讀文字。", "image_file": "read.png" },
        { "id": "v-23", "term_zh": "等待", "term_target": "รอ", "pronunciation": ["Ro"], "example": {"sentence": "รอสักครู่", "translation": "等一下。"}, "usage_note": "等候。", "image_file": "wait.png" },
        { "id": "v-24", "term_zh": "嘗試", "term_target": "ลอง", "pronunciation": ["Long"], "example": {"sentence": "ลองอันนี้", "translation": "試試這個。"}, "usage_note": "試做。", "image_file": "try.png" },
        { "id": "v-25", "term_zh": "付錢", "term_target": "จ่ายเงิน", "pronunciation": ["Jai ngoen"], "example": {"sentence": "ผมจ่ายเอง", "translation": "我來付錢。"}, "usage_note": "支付。", "image_file": "pay.png" },
        { "id": "v-26", "term_zh": "住", "term_target": "อยู่ / อาศัย", "pronunciation": ["Yu / A-sai"], "example": {"sentence": "อาศัยในไทเป", "translation": "住台北。"}, "usage_note": "Yu (在/住)，A-sai (居住)。", "image_file": "live.png" },
        { "id": "v-27", "term_zh": "走路", "term_target": "เดิน", "pronunciation": ["Doen"], "example": {"sentence": "เดินกลับบ้าน", "translation": "走路回家。"}, "usage_note": "步行。", "image_file": "walk.png" },
        { "id": "v-28", "term_zh": "打開", "term_target": "เปิด", "pronunciation": ["Poet"], "example": {"sentence": "เปิดประตู", "translation": "開門。"}, "usage_note": "開啟。", "image_file": "open.png" },
        { "id": "v-29", "term_zh": "關閉", "term_target": "ปิด", "pronunciation": ["Pit"], "example": {"sentence": "ปิดหน้าต่าง", "translation": "關窗。"}, "usage_note": "關上。", "image_file": "close.png" },
        { "id": "v-30", "term_zh": "幫助", "term_target": "ช่วย", "pronunciation": ["Chuai"], "example": {"sentence": "ช่วยฉันด้วย", "translation": "幫我。"}, "usage_note": "協助。", "image_file": "help.png" },
        { "id": "v-31", "term_zh": "吃", "term_target": "กิน / ทาน", "pronunciation": ["Kin / Than"], "example": {"sentence": "กินข้าว", "translation": "吃飯。"}, "usage_note": "Kin (一般)，Than (禮貌)。", "image_file": "eat.png" },
        { "id": "v-32", "term_zh": "睡覺", "term_target": "นอน", "pronunciation": ["Non"], "example": {"sentence": "ไปนอน", "translation": "去睡覺。"}, "usage_note": "睡眠。", "image_file": "sleep.png" },
        { "id": "v-33", "term_zh": "買", "term_target": "ซื้อ", "pronunciation": ["Sue"], "example": {"sentence": "ซื้อเสื้อผ้า", "translation": "買衣服。"}, "usage_note": "購買。", "image_file": "buy.png" },
        { "id": "v-34", "term_zh": "乘坐/拿", "term_target": "นั่ง / เอา", "pronunciation": ["Nang / Ao"], "example": {"sentence": "นั่งรถเมล์", "translation": "搭公車(坐公車)。"}, "usage_note": "Nang (坐/搭乘)，Ao (拿取)。", "image_file": "take.png" },
        { "id": "v-35", "term_zh": "得到/拿", "term_target": "ได้รับ / เอา", "pronunciation": ["Dai rap / Ao"], "example": {"sentence": "ได้รับของขวัญ", "translation": "收到禮物。"}, "usage_note": "獲得。", "image_file": "get.png" },
        { "id": "v-36", "term_zh": "選擇", "term_target": "เลือก", "pronunciation": ["Lueak"], "example": {"sentence": "เลือกอันหนึ่ง", "translation": "選一個。"}, "usage_note": "挑選。", "image_file": "choose.png" },
        { "id": "v-37", "term_zh": "進入", "term_target": "เข้า", "pronunciation": ["Khao"], "example": {"sentence": "เข้าห้อง", "translation": "進房間。"}, "usage_note": "進入。", "image_file": "enter.png" },
        { "id": "v-38", "term_zh": "到達", "term_target": "ถึง", "pronunciation": ["Thueng"], "example": {"sentence": "ถึงแล้ว", "translation": "到了。"}, "usage_note": "抵達。", "image_file": "arrive.png" },
        { "id": "v-39", "term_zh": "帶來", "term_target": "นำมา / เอามา", "pronunciation": ["Nam ma / Ao ma"], "example": {"sentence": "เอาน้ำมา", "translation": "帶水來。"}, "usage_note": "攜帶。", "image_file": "bring.png" },
        { "id": "v-40", "term_zh": "變成", "term_target": "กลายเป็น", "pronunciation": ["Klai pen"], "example": {"sentence": "กลายเป็นครู", "translation": "變成老師。"}, "usage_note": "變化。", "image_file": "become.png" },
        { "id": "v-41", "term_zh": "開始", "term_target": "เริ่ม", "pronunciation": ["Roem"], "example": {"sentence": "เริ่มเดี๋ยวนี้", "translation": "現在開始。"}, "usage_note": "開始。", "image_file": "start.png" },
        { "id": "v-42", "term_zh": "結束", "term_target": "เสร็จ / จบ", "pronunciation": ["Set / Jop"], "example": {"sentence": "ทำงานเสร็จ", "translation": "工作結束(做完)。"}, "usage_note": "完成。", "image_file": "finish.png" },
        { "id": "v-43", "term_zh": "停止", "term_target": "หยุด", "pronunciation": ["Yut"], "example": {"sentence": "หยุดที่นี่", "translation": "停在這裡。"}, "usage_note": "停止。", "image_file": "stop.png" },
        { "id": "v-44", "term_zh": "記住", "term_target": "จำได้", "pronunciation": ["Jam dai"], "example": {"sentence": "จำฉันได้ไหม?", "translation": "記得我嗎？"}, "usage_note": "記憶。", "image_file": "remember.png" },
        { "id": "v-45", "term_zh": "見面", "term_target": "เจอ / พบ", "pronunciation": ["Je / Phop"], "example": {"sentence": "เจอกัน", "translation": "見面。"}, "usage_note": "會面。", "image_file": "meet.png" },
        { "id": "v-46", "term_zh": "放", "term_target": "วาง", "pronunciation": ["Wang"], "example": {"sentence": "วางที่นี่", "translation": "放這裡。"}, "usage_note": "放置。", "image_file": "put.png" },
        { "id": "v-47", "term_zh": "寄送", "term_target": "ส่ง", "pronunciation": ["Song"], "example": {"sentence": "ส่งอีเมล", "translation": "寄信。"}, "usage_note": "傳送。", "image_file": "send.png" },
        { "id": "v-48", "term_zh": "開車", "term_target": "ขับรถ", "pronunciation": ["Khap rot"], "example": {"sentence": "ขับรถไปทำงาน", "translation": "開車上班。"}, "usage_note": "駕駛。", "image_file": "drive.png" },
        { "id": "v-49", "term_zh": "讀書", "term_target": "เรียน", "pronunciation": ["Rian"], "example": {"sentence": "เรียนภาษาไทย", "translation": "讀泰文。"}, "usage_note": "學習。", "image_file": "study.png" },
        { "id": "v-50", "term_zh": "回去", "term_target": "กลับ", "pronunciation": ["Klap"], "example": {"sentence": "กลับบ้าน", "translation": "回家。"}, "usage_note": "歸返。", "image_file": "go_back.png" }
      ]
    },
    {
      "id": "adjectives",
      "name": "形容詞",
      "items": [
        { "id": "adj-01", "term_zh": "好的", "term_target": "ดี", "pronunciation": ["Di"], "example": {"sentence": "อากาศดี", "translation": "好天氣。"}, "usage_note": "正面。", "image_file": "good.png" },
        { "id": "adj-02", "term_zh": "壞的", "term_target": "ไม่ดี / เลว", "pronunciation": ["Mai di / Leo"], "example": {"sentence": "คนเลว", "translation": "壞人。"}, "usage_note": "Mai di (不好)，Leo (邪惡)。", "image_file": "bad.png" },
        { "id": "adj-03", "term_zh": "新的", "term_target": "ใหม่", "pronunciation": ["Mai"], "example": {"sentence": "มือถือใหม่", "translation": "新手機。"}, "usage_note": "全新。", "image_file": "new.png" },
        { "id": "adj-04", "term_zh": "大的", "term_target": "ใหญ่", "pronunciation": ["Yai"], "example": {"sentence": "บ้านใหญ่", "translation": "大房子。"}, "usage_note": "體積大。", "image_file": "big.png" },
        { "id": "adj-05", "term_zh": "小的", "term_target": "เล็ก", "pronunciation": ["Lek"], "example": {"sentence": "แมวตัวเล็ก", "translation": "小貓。"}, "usage_note": "體積小。", "image_file": "small.png" },
        { "id": "adj-06", "term_zh": "熱的", "term_target": "ร้อน", "pronunciation": ["Ron"], "example": {"sentence": "อากาศร้อน", "translation": "天氣熱。"}, "usage_note": "高溫。", "image_file": "hot.png" },
        { "id": "adj-07", "term_zh": "冷的", "term_target": "หนาว / เย็น", "pronunciation": ["Nao / Yen"], "example": {"sentence": "อากาศหนาว", "translation": "天氣冷。"}, "usage_note": "Nao (天氣)，Yen (物品)。", "image_file": "cold.png" },
        { "id": "adj-08", "term_zh": "簡單的", "term_target": "ง่าย", "pronunciation": ["Ngai"], "example": {"sentence": "มันง่าย", "translation": "這很簡單。"}, "usage_note": "容易。", "image_file": "easy.png" },
        { "id": "adj-09", "term_zh": "困難的", "term_target": "ยาก", "pronunciation": ["Yak"], "example": {"sentence": "ภาษาไทยยาก", "translation": "泰文很難。"}, "usage_note": "難。", "image_file": "difficult.png" },
        { "id": "adj-10", "term_zh": "美味的", "term_target": "อร่อย", "pronunciation": ["Aroi"], "example": {"sentence": "อาหารอร่อย", "translation": "好吃的食物。"}, "usage_note": "好吃。", "image_file": "delicious.png" },
        { "id": "adj-11", "term_zh": "忙碌的", "term_target": "ยุ่ง", "pronunciation": ["Yung"], "example": {"sentence": "ฉันยุ่ง", "translation": "我很忙。"}, "usage_note": "沒空。", "image_file": "busy.png" },
        { "id": "adj-12", "term_zh": "疲累的", "term_target": "เหนื่อย", "pronunciation": ["Nueai"], "example": {"sentence": "ฉันเหนื่อย", "translation": "我累了。"}, "usage_note": "狀態。", "image_file": "tired.png" },
        { "id": "adj-13", "term_zh": "快樂的/高興的", "term_target": "มีความสุข / ดีใจ", "pronunciation": ["Mi khwam suk / Di jai"], "example": {"sentence": "ฉันดีใจมาก", "translation": "我很高興。"}, "usage_note": "心情。", "image_file": "happy.png" },
        { "id": "adj-14", "term_zh": "悲傷的", "term_target": "เศร้า", "pronunciation": ["Sao"], "example": {"sentence": "เรื่องเศร้า", "translation": "悲傷的故事。"}, "usage_note": "難過。", "image_file": "sad.png" },
        { "id": "adj-15", "term_zh": "乾淨的", "term_target": "สะอาด", "pronunciation": ["Sa-at"], "example": {"sentence": "ห้องสะอาด", "translation": "乾淨的房間。"}, "usage_note": "無髒汙。", "image_file": "clean.png" },
        { "id": "adj-16", "term_zh": "髒的", "term_target": "สกปรก", "pronunciation": ["Sok-ka-prok"], "example": {"sentence": "มือสกปรก", "translation": "髒手。"}, "usage_note": "不乾淨。", "image_file": "dirty.png" },
        { "id": "adj-17", "term_zh": "便宜的", "term_target": "ถูก", "pronunciation": ["Thuk"], "example": {"sentence": "อันนี้ถูก", "translation": "這很便宜。"}, "usage_note": "價格低。", "image_file": "cheap.png" },
        { "id": "adj-18", "term_zh": "昂貴的", "term_target": "แพง", "pronunciation": ["Phaeng"], "example": {"sentence": "แพงเกินไป", "translation": "太貴了。"}, "usage_note": "價格高。", "image_file": "expensive.png" },
        { "id": "adj-19", "term_zh": "重要的", "term_target": "สำคัญ", "pronunciation": ["Sam-khan"], "example": {"sentence": "เรื่องสำคัญ", "translation": "重要的事。"}, "usage_note": "關鍵。", "image_file": "important.png" },
        { "id": "adj-20", "term_zh": "相同的", "term_target": "เหมือนกัน", "pronunciation": ["Muean kan"], "example": {"sentence": "ที่เดียวกัน", "translation": "同個地方。"}, "usage_note": "一樣。", "image_file": "same.png" },
        { "id": "adj-21", "term_zh": "第一的", "term_target": "ที่หนึ่ง / แรก", "pronunciation": ["Thi nueng / Raek"], "example": {"sentence": "ครั้งแรก", "translation": "第一次。"}, "usage_note": "順序。", "image_file": "first.png" },
        { "id": "adj-22", "term_zh": "上一個", "term_target": "ที่แล้ว / ก่อน", "pronunciation": ["Thi laeo / Kon"], "example": {"sentence": "อาทิตย์ที่แล้ว", "translation": "上週。"}, "usage_note": "過去的。", "image_file": "last.png" },
        { "id": "adj-23", "term_zh": "下一個", "term_target": "ถัดไป / หน้า", "pronunciation": ["That pai / Na"], "example": {"sentence": "สถานีถัดไป", "translation": "下一站。"}, "usage_note": "接下來。", "image_file": "next.png" },
        { "id": "adj-24", "term_zh": "長的", "term_target": "ยาว", "pronunciation": ["Yao"], "example": {"sentence": "ผมยาว", "translation": "長髮。"}, "usage_note": "長度。", "image_file": "long.png" },
        { "id": "adj-25", "term_zh": "多的", "term_target": "เยอะ / มาก", "pronunciation": ["Yoe / Mak"], "example": {"sentence": "คนเยอะ", "translation": "人很多。"}, "usage_note": "數量多。", "image_file": "many.png" },
        { "id": "adj-26", "term_zh": "高的", "term_target": "สูง", "pronunciation": ["Sung"], "example": {"sentence": "ตึกสูง", "translation": "高樓。"}, "usage_note": "高度。", "image_file": "tall.png" },
        { "id": "adj-27", "term_zh": "年輕的", "term_target": "หนุ่ม / สาว", "pronunciation": ["Num / Sao"], "example": {"sentence": "คนหนุ่มสาว", "translation": "年輕人。"}, "usage_note": "年紀小。", "image_file": "young.png" },
        { "id": "adj-28", "term_zh": "老的/舊的", "term_target": "แก่ / เก่า", "pronunciation": ["Kae / Kao"], "example": {"sentence": "รถเก่า", "translation": "舊車。"}, "usage_note": "人老用 Kae，物品舊用 Kao。", "image_file": "old.png" },
        { "id": "adj-29", "term_zh": "近的", "term_target": "ใกล้", "pronunciation": ["Klai"], "example": {"sentence": "ใกล้บ้าน", "translation": "離家近。"}, "usage_note": "距離近。", "image_file": "near.png" },
        { "id": "adj-30", "term_zh": "遠的", "term_target": "ไกล", "pronunciation": ["Klai"], "example": {"sentence": "ไกลมาก", "translation": "很遠。"}, "usage_note": "距離遠 (發音與近相似，聲調不同)。", "image_file": "far.png" },
        { "id": "adj-31", "term_zh": "快的", "term_target": "เร็ว", "pronunciation": ["Reo"], "example": {"sentence": "วิ่งเร็ว", "translation": "跑得快。"}, "usage_note": "速度快。", "image_file": "fast.png" },
        { "id": "adj-32", "term_zh": "慢的", "term_target": "ช้า", "pronunciation": ["Cha"], "example": {"sentence": "เดินช้า", "translation": "走得慢。"}, "usage_note": "速度慢。", "image_file": "slow.png" },
        { "id": "adj-33", "term_zh": "正確的", "term_target": "ถูกต้อง", "pronunciation": ["Thuk tong"], "example": {"sentence": "คำตอบถูกต้อง", "translation": "正確答案。"}, "usage_note": "對的。", "image_file": "correct.png" },
        { "id": "adj-34", "term_zh": "錯誤的", "term_target": "ผิด", "pronunciation": ["Phit"], "example": {"sentence": "มันผิด", "translation": "這錯了。"}, "usage_note": "不對。", "image_file": "wrong.png" },
        { "id": "adj-35", "term_zh": "不同的", "term_target": "ต่างกัน", "pronunciation": ["Tang kan"], "example": {"sentence": "สีต่างกัน", "translation": "不同顏色。"}, "usage_note": "差異。", "image_file": "different.png" },
        { "id": "adj-36", "term_zh": "真的", "term_target": "จริง", "pronunciation": ["Jing"], "example": {"sentence": "รักจริง", "translation": "真愛。"}, "usage_note": "真實。", "image_file": "real.png" },
        { "id": "adj-37", "term_zh": "有趣的", "term_target": "น่าสนใจ / สนุก", "pronunciation": ["Na son jai / Sanuk"], "example": {"sentence": "หนังสนุก", "translation": "有趣的電影。"}, "usage_note": "Sanuk (好玩)，Na son jai (感興趣)。", "image_file": "interesting.png" },
        { "id": "adj-38", "term_zh": "飢餓的", "term_target": "หิว", "pronunciation": ["Hio"], "example": {"sentence": "ฉันหิว", "translation": "我餓了。"}, "usage_note": "餓。", "image_file": "hungry.png" },
        { "id": "adj-39", "term_zh": "有名的", "term_target": "มีชื่อเสียง", "pronunciation": ["Mi chue siang"], "example": {"sentence": "ดารามีชื่อเสียง", "translation": "知名演員。"}, "usage_note": "知名。", "image_file": "famous.png" },
        { "id": "adj-40", "term_zh": "外國的", "term_target": "ต่างชาติ", "pronunciation": ["Tang chat"], "example": {"sentence": "คนต่างชาติ", "translation": "外國人。"}, "usage_note": "國外。", "image_file": "foreign.png" },
        { "id": "adj-41", "term_zh": "聰明的", "term_target": "ฉลาด", "pronunciation": ["Chalat"], "example": {"sentence": "เขาฉลาด", "translation": "他很聰明。"}, "usage_note": "腦袋好。", "image_file": "intelligent.png" },
        { "id": "adj-42", "term_zh": "危險的", "term_target": "อันตราย", "pronunciation": ["An-ta-rai"], "example": {"sentence": "มันอันตราย", "translation": "這很危險。"}, "usage_note": "警示。", "image_file": "dangerous.png" },
        { "id": "adj-43", "term_zh": "仁慈的", "term_target": "ใจดี", "pronunciation": ["Jai di"], "example": {"sentence": "คนใจดี", "translation": "好心人。"}, "usage_note": "心腸好。", "image_file": "kind.png" },
        { "id": "adj-44", "term_zh": "所有的", "term_target": "ทุก", "pronunciation": ["Thuk"], "example": {"sentence": "ทุกวัน", "translation": "每一天。"}, "usage_note": "全部。", "image_file": "every.png" },
        { "id": "adj-45", "term_zh": "喜愛的", "term_target": "ที่ชอบ", "pronunciation": ["Thi chop"], "example": {"sentence": "อาหารที่ชอบ", "translation": "最愛的食物。"}, "usage_note": "中意。", "image_file": "favorite.png" }
      ]
    },
    {
      "id": "nouns",
      "name": "名詞",
      "items": [
        { "id": "n-01", "term_zh": "水", "term_target": "น้ำ", "pronunciation": ["Nam"], "example": {"sentence": "ดื่มน้ำ", "translation": "喝水。"}, "usage_note": "液體。", "image_file": "water.png" },
        { "id": "n-02", "term_zh": "食物", "term_target": "อาหาร", "pronunciation": ["A-han"], "example": {"sentence": "อาหารอร่อย", "translation": "好吃的食物。"}, "usage_note": "吃的東西。", "image_file": "food.png" },
        { "id": "n-03", "term_zh": "錢", "term_target": "เงิน", "pronunciation": ["Ngoen"], "example": {"sentence": "ไม่มีเงิน", "translation": "沒錢。"}, "usage_note": "錢。", "image_file": "money.png" },
        { "id": "n-04", "term_zh": "廁所", "term_target": "ห้องน้ำ", "pronunciation": ["Hong nam"], "example": {"sentence": "ไปห้องน้ำ", "translation": "去廁所。"}, "usage_note": "衛生間。", "image_file": "bathroom.png" },
        { "id": "n-05", "term_zh": "人", "term_target": "คน", "pronunciation": ["Khon"], "example": {"sentence": "คนเยอะ", "translation": "很多人。"}, "usage_note": "人類。", "image_file": "people.png" },
        { "id": "n-06", "term_zh": "時間", "term_target": "เวลา", "pronunciation": ["Wela"], "example": {"sentence": "ไม่มีเวลา", "translation": "沒時間。"}, "usage_note": "時刻。", "image_file": "time.png" },
        { "id": "n-07", "term_zh": "朋友", "term_target": "เพื่อน", "pronunciation": ["Phuean"], "example": {"sentence": "เพื่อนของฉัน", "translation": "我朋友。"}, "usage_note": "友人。", "image_file": "friend.png" },
        { "id": "n-08", "term_zh": "家庭", "term_target": "ครอบครัว", "pronunciation": ["Khrop khrua"], "example": {"sentence": "ครอบครัวของฉัน", "translation": "我家。"}, "usage_note": "家人。", "image_file": "family.png" },
        { "id": "n-09", "term_zh": "手機", "term_target": "โทรศัพท์", "pronunciation": ["Thorasap"], "example": {"sentence": "โทรศัพท์ของฉัน", "translation": "我手機。"}, "usage_note": "也常用 Mue thue。", "image_file": "phone.png" },
        { "id": "n-10", "term_zh": "車", "term_target": "รถยนต์", "pronunciation": ["Rot yon"], "example": {"sentence": "ขับรถ", "translation": "開車。"}, "usage_note": "汽車。", "image_file": "car.png" },
        { "id": "n-11", "term_zh": "巴士", "term_target": "รถเมล์", "pronunciation": ["Rot me"], "example": {"sentence": "นั่งรถเมล์", "translation": "搭公車。"}, "usage_note": "公車。", "image_file": "bus.png" },
        { "id": "n-12", "term_zh": "火車", "term_target": "รถไฟ", "pronunciation": ["Rot fai"], "example": {"sentence": "นั่งรถไฟ", "translation": "搭火車。"}, "usage_note": "列車。", "image_file": "train.png" },
        { "id": "n-13", "term_zh": "捷運/地鐵", "term_target": "รถไฟใต้ดิน", "pronunciation": ["Rot fai tai din"], "example": {"sentence": "สถานีรถไฟใต้ดิน", "translation": "地鐵站。"}, "usage_note": "地下鐵。", "image_file": "subway.png" },
        { "id": "n-14", "term_zh": "車站", "term_target": "สถานี", "pronunciation": ["Sathani"], "example": {"sentence": "สถานีรถไฟ", "translation": "火車站。"}, "usage_note": "站點。", "image_file": "station.png" },
        { "id": "n-15", "term_zh": "機場", "term_target": "สนามบิน", "pronunciation": ["Sanam bin"], "example": {"sentence": "ไปสนามบิน", "translation": "去機場。"}, "usage_note": "搭飛機處。", "image_file": "airport.png" },
        { "id": "n-16", "term_zh": "票", "term_target": "ตั๋ว", "pronunciation": ["Tua"], "example": {"sentence": "ซื้อตั๋ว", "translation": "買票。"}, "usage_note": "入場券或車票。", "image_file": "ticket.png" },
        { "id": "n-17", "term_zh": "飯店", "term_target": "โรงแรม", "pronunciation": ["Rong raem"], "example": {"sentence": "จองโรงแรม", "translation": "訂飯店。"}, "usage_note": "住宿。", "image_file": "hotel.png" },
        { "id": "n-18", "term_zh": "護照", "term_target": "หนังสือเดินทาง", "pronunciation": ["Nang sue doen thang"], "example": {"sentence": "ขอดูหนังสือเดินทาง", "translation": "請出示護照。"}, "usage_note": "口語也用 Passport。", "image_file": "passport.png" },
        { "id": "n-19", "term_zh": "地圖", "term_target": "แผนที่", "pronunciation": ["Phaen thi"], "example": {"sentence": "ดูแผนที่", "translation": "看地圖。"}, "usage_note": "指引。", "image_file": "map.png" },
        { "id": "n-20", "term_zh": "警察", "term_target": "ตำรวจ", "pronunciation": ["Tam ruat"], "example": {"sentence": "เรียกตำรวจ", "translation": "叫警察。"}, "usage_note": "求救用。", "image_file": "police.png" },
        { "id": "n-21", "term_zh": "台灣人", "term_target": "คนไต้หวัน", "pronunciation": ["Khon Tai-wan"], "example": {"sentence": "ผมเป็นคนไต้หวัน", "translation": "我是台灣人。"}, "usage_note": "國籍。", "image_file": "taiwanese.png" },
        { "id": "n-22", "term_zh": "孩子", "term_target": "เด็ก", "pronunciation": ["Dek"], "example": {"sentence": "มีเด็ก", "translation": "有孩子。"}, "usage_note": "兒童。", "image_file": "child.png" },
        { "id": "n-23", "term_zh": "學生", "term_target": "นักเรียน", "pronunciation": ["Nak rian"], "example": {"sentence": "ผมเป็นนักเรียน", "translation": "我是學生。"}, "usage_note": "在學者。", "image_file": "student.png" },
        { "id": "n-24", "term_zh": "文化", "term_target": "วัฒนธรรม", "pronunciation": ["Watthanatham"], "example": {"sentence": "วัฒนธรรมไทย", "translation": "泰國文化。"}, "usage_note": "文化。", "image_file": "culture.png" },
        { "id": "n-25", "term_zh": "問題", "term_target": "ปัญหา", "pronunciation": ["Pan-ha"], "example": {"sentence": "ไม่มีปัญหา", "translation": "沒問題。"}, "usage_note": "難題。", "image_file": "problem.png" },
        { "id": "n-26", "term_zh": "公司", "term_target": "บริษัท", "pronunciation": ["Borisat"], "example": {"sentence": "ไปบริษัท", "translation": "去公司。"}, "usage_note": "上班地點。", "image_file": "company.png" },
        { "id": "n-27", "term_zh": "男性", "term_target": "ผู้ชาย", "pronunciation": ["Phu chai"], "example": {"sentence": "ห้องน้ำผู้ชาย", "translation": "男廁。"}, "usage_note": "性別。", "image_file": "man.png" },
        { "id": "n-28", "term_zh": "女性", "term_target": "ผู้หญิง", "pronunciation": ["Phu ying"], "example": {"sentence": "ห้องน้ำผู้หญิง", "translation": "女廁。"}, "usage_note": "性別。", "image_file": "woman.png" },
        { "id": "n-29", "term_zh": "學校", "term_target": "โรงเรียน", "pronunciation": ["Rong rian"], "example": {"sentence": "ไปโรงเรียน", "translation": "去學校。"}, "usage_note": "教育機構。", "image_file": "school.png" },
        { "id": "n-30", "term_zh": "老師", "term_target": "ครู", "pronunciation": ["Khru"], "example": {"sentence": "สวัสดีครับครู", "translation": "老師好。"}, "usage_note": "師長。", "image_file": "teacher.png" },
        { "id": "n-31", "term_zh": "電影", "term_target": "หนัง", "pronunciation": ["Nang"], "example": {"sentence": "ดูหนัง", "translation": "看電影。"}, "usage_note": "影片。", "image_file": "movie.png" },
        { "id": "n-32", "term_zh": "電腦", "term_target": "คอมพิวเตอร์", "pronunciation": ["Khom-phiu-toe"], "example": {"sentence": "ใช้คอมพิวเตอร์", "translation": "用電腦。"}, "usage_note": "PC。", "image_file": "computer.png" },
        { "id": "n-33", "term_zh": "市場", "term_target": "ตลาด", "pronunciation": ["Talat"], "example": {"sentence": "ไปตลาด", "translation": "去市場。"}, "usage_note": "市集。", "image_file": "market.png" },
        { "id": "n-34", "term_zh": "衣服", "term_target": "เสื้อผ้า", "pronunciation": ["Suea pha"], "example": {"sentence": "ซื้อเสื้อผ้า", "translation": "買衣服。"}, "usage_note": "衣物。", "image_file": "clothes.png" },
        { "id": "n-35", "term_zh": "商店", "term_target": "ร้านค้า", "pronunciation": ["Ran kha"], "example": {"sentence": "เข้าร้านค้า", "translation": "進店裡。"}, "usage_note": "店家。", "image_file": "shop.png" },
        { "id": "n-36", "term_zh": "街道", "term_target": "ถนน", "pronunciation": ["Thanon"], "example": {"sentence": "ถนนนี้", "translation": "這條路。"}, "usage_note": "道路。", "image_file": "street.png" },
        { "id": "n-37", "term_zh": "房子", "term_target": "บ้าน", "pronunciation": ["Ban"], "example": {"sentence": "บ้านฉัน", "translation": "我家。"}, "usage_note": "住宅。", "image_file": "house.png" },
        { "id": "n-38", "term_zh": "母親", "term_target": "แม่", "pronunciation": ["Mae"], "example": {"sentence": "แม่ของฉัน", "translation": "我媽媽。"}, "usage_note": "媽媽。", "image_file": "mother.png" },
        { "id": "n-39", "term_zh": "父親", "term_target": "พ่อ", "pronunciation": ["Pho"], "example": {"sentence": "พ่อของฉัน", "translation": "我爸爸。"}, "usage_note": "爸爸。", "image_file": "father.png" },
        { "id": "n-40", "term_zh": "中文", "term_target": "ภาษาจีน", "pronunciation": ["Phasa Jin"], "example": {"sentence": "พูดภาษาจีน", "translation": "說中文。"}, "usage_note": "語言。", "image_file": "chinese.png" },
        { "id": "n-41", "term_zh": "包包", "term_target": "กระเป๋า", "pronunciation": ["Krapao"], "example": {"sentence": "ถือกระเป๋า", "translation": "拿包包。"}, "usage_note": "提包。", "image_file": "bag.png" },
        { "id": "n-42", "term_zh": "杯子", "term_target": "แก้ว", "pronunciation": ["Kaeo"], "example": {"sentence": "ขอน้ำหนึ่งแก้ว", "translation": "請給一杯水。"}, "usage_note": "杯具。", "image_file": "cup.png" },
        { "id": "n-43", "term_zh": "醫生", "term_target": "หมอ", "pronunciation": ["Mo"], "example": {"sentence": "หาหมอ", "translation": "看醫生。"}, "usage_note": "醫師。", "image_file": "doctor.png" },
        { "id": "n-44", "term_zh": "醫院", "term_target": "โรงพยาบาล", "pronunciation": ["Rong phayaban"], "example": {"sentence": "ไปโรงพยาบาล", "translation": "去醫院。"}, "usage_note": "醫療院所。", "image_file": "hospital.png" },
        { "id": "n-45", "term_zh": "座位", "term_target": "ที่นั่ง", "pronunciation": ["Thi nang"], "example": {"sentence": "มีที่นั่งไหม?", "translation": "有位子嗎？"}, "usage_note": "位子。", "image_file": "seat.png" },
        { "id": "n-46", "term_zh": "門", "term_target": "ประตู", "pronunciation": ["Pratu"], "example": {"sentence": "เปิดประตู", "translation": "開門。"}, "usage_note": "門戶。", "image_file": "door.png" },
        { "id": "n-47", "term_zh": "房間", "term_target": "ห้อง", "pronunciation": ["Hong"], "example": {"sentence": "ห้องของฉัน", "translation": "我房間。"}, "usage_note": "室內。", "image_file": "room.png" },
        { "id": "n-48", "term_zh": "行李", "term_target": "กระเป๋าเดินทาง", "pronunciation": ["Krapao doen thang"], "example": {"sentence": "กระเป๋าเดินทางเยอะ", "translation": "行李很多。"}, "usage_note": "包裹。", "image_file": "luggage.png" },
        { "id": "n-49", "term_zh": "櫃檯", "term_target": "เคาน์เตอร์", "pronunciation": ["Khao-toe"], "example": {"sentence": "จ่ายที่เคาน์เตอร์", "translation": "櫃檯結帳。"}, "usage_note": "服務台。", "image_file": "counter.png" },
        { "id": "n-50", "term_zh": "大廳", "term_target": "ล็อบบี้", "pronunciation": ["Lop-bi"], "example": {"sentence": "รอที่ล็อบบี้", "translation": "在大廳等。"}, "usage_note": "接待處。", "image_file": "lobby.png" },
        { "id": "n-51", "term_zh": "預定", "term_target": "จอง", "pronunciation": ["Jong"], "example": {"sentence": "จองแล้ว", "translation": "預約了。"}, "usage_note": "預約。", "image_file": "reservation.png" },
        { "id": "n-52", "term_zh": "入住", "term_target": "เช็คอิน", "pronunciation": ["Chek-in"], "example": {"sentence": "ขอเช็คอิน", "translation": "我要辦理入住。"}, "usage_note": "Check-in。", "image_file": "check_in.png" },
        { "id": "n-53", "term_zh": "退房", "term_target": "เช็คเอาท์", "pronunciation": ["Chek-ao"], "example": {"sentence": "เช็คเอาท์กี่โมง", "translation": "退房是幾點？"}, "usage_note": "Check-out。", "image_file": "check_out.png" },
        { "id": "n-54", "term_zh": "飲料", "term_target": "เครื่องดื่ม", "pronunciation": ["Khrueang duem"], "example": {"sentence": "รับเครื่องดื่มอะไร?", "translation": "要喝什麼飲料？"}, "usage_note": "飲品。", "image_file": "drink.png" },
        { "id": "n-55", "term_zh": "菜單", "term_target": "เมนู", "pronunciation": ["Menu"], "example": {"sentence": "ขอเมนูหน่อย", "translation": "請給菜單。"}, "usage_note": "Menu。", "image_file": "menu.png" },
        { "id": "n-56", "term_zh": "午餐", "term_target": "อาหารเที่ยง", "pronunciation": ["A-han thiang"], "example": {"sentence": "กินอาหารเที่ยง", "translation": "吃午餐。"}, "usage_note": "中餐。", "image_file": "lunch.png" },
        { "id": "n-57", "term_zh": "晚餐", "term_target": "อาหารเย็น", "pronunciation": ["A-han yen"], "example": {"sentence": "กินอาหารเย็น", "translation": "吃晚餐。"}, "usage_note": "晚餐。", "image_file": "dinner.png" },
        { "id": "n-58", "term_zh": "帳單", "term_target": "เช็คบิล", "pronunciation": ["Chek bin"], "example": {"sentence": "เช็คบิลด้วย", "translation": "麻煩結帳。"}, "usage_note": "買單。", "image_file": "bill.png" },
        { "id": "n-59", "term_zh": "價錢", "term_target": "ราคา", "pronunciation": ["Rakha"], "example": {"sentence": "ราคาถูก", "translation": "價格便宜。"}, "usage_note": "價格。", "image_file": "price.png" },
        { "id": "n-60", "term_zh": "收據", "term_target": "ใบเสร็จ", "pronunciation": ["Baiset"], "example": {"sentence": "ขอใบเสร็จด้วย", "translation": "請給收據。"}, "usage_note": "統一發票。", "image_file": "receipt.png" },
        { "id": "n-61", "term_zh": "尺寸", "term_target": "ไซส์", "pronunciation": ["Sai"], "example": {"sentence": "ไซส์ใหญ่", "translation": "大尺寸。"}, "usage_note": "大小。", "image_file": "size.png" },
        { "id": "n-62", "term_zh": "入口", "term_target": "ทางเข้า", "pronunciation": ["Thang khao"], "example": {"sentence": "ทางเข้าอยู่ที่ไหน?", "translation": "入口在哪？"}, "usage_note": "進去的地方。", "image_file": "entrance.png" },
        { "id": "n-63", "term_zh": "出口", "term_target": "ทางออก", "pronunciation": ["Thang ok"], "example": {"sentence": "ทางออกทางนี้", "translation": "出口在這邊。"}, "usage_note": "出去的地方。", "image_file": "exit.png" },
        { "id": "n-64", "term_zh": "台灣", "term_target": "ไต้หวัน", "pronunciation": ["Tai-wan"], "example": {"sentence": "มาจากไต้หวัน", "translation": "來自台灣。"}, "usage_note": "地名。", "image_file": "taiwan.png" },
        { "id": "n-65", "term_zh": "一切事物", "term_target": "ทุกอย่าง", "pronunciation": ["Thuk yang"], "example": {"sentence": "ชอบทุกอย่าง", "translation": "全部喜歡。"}, "usage_note": "所有。", "image_file": "everything.png" },
        { "id": "n-66", "term_zh": "錢包", "term_target": "กระเป๋าเงิน", "pronunciation": ["Krapao ngoen"], "example": {"sentence": "ลืมกระเป๋าเงิน", "translation": "忘了錢包。"}, "usage_note": "皮夾。", "image_file": "wallet.png" },
        { "id": "n-67", "term_zh": "身分證", "term_target": "บัตรประชาชน", "pronunciation": ["Bat prachachon"], "example": {"sentence": "ขอดูบัตรประชาชน", "translation": "請出示證件。"}, "usage_note": "ID。", "image_file": "id.png" },
        { "id": "n-68", "term_zh": "餐廳", "term_target": "ร้านอาหาร", "pronunciation": ["Ran a-han"], "example": {"sentence": "ร้านอาหารอร่อย", "translation": "好吃的餐廳。"}, "usage_note": "食堂。", "image_file": "restaurant.png" },
        { "id": "n-69", "term_zh": "場所", "term_target": "สถานที่", "pronunciation": ["Sathanthi"], "example": {"sentence": "สถานที่นัดพบ", "translation": "約定地點。"}, "usage_note": "地點。", "image_file": "place.png" },
        { "id": "n-70", "term_zh": "店員", "term_target": "พนักงาน", "pronunciation": ["Phanak ngan"], "example": {"sentence": "ถามพนักงาน", "translation": "問店員。"}, "usage_note": "工作人員。", "image_file": "clerk.png" },
        { "id": "n-71", "term_zh": "超市", "term_target": "ซูเปอร์มาร์เก็ต", "pronunciation": ["Supphoe"], "example": {"sentence": "ไปซูเปอร์", "translation": "去超市。"}, "usage_note": "量販店。", "image_file": "supermarket.png" },
        { "id": "n-72", "term_zh": "月台", "term_target": "ชานชาลา", "pronunciation": ["Chan chala"], "example": {"sentence": "ชานชาลาที่ 1", "translation": "第一月台。"}, "usage_note": "車站月台。", "image_file": "platform.png" }
      ]
    },
    {
      "id": "adverbs",
      "name": "副詞",
      "items": [
        { "id": "adv-01", "term_zh": "現在", "term_target": "ตอนนี้", "pronunciation": ["Ton ni"], "example": {"sentence": "ไปตอนนี้", "translation": "現在去。"}, "usage_note": "目前。", "image_file": "now.png" },
        { "id": "adv-02", "term_zh": "非常", "term_target": "มาก", "pronunciation": ["Mak"], "example": {"sentence": "ดีมาก", "translation": "非常好。"}, "usage_note": "強調。", "image_file": "very.png" },
        { "id": "adv-03", "term_zh": "真的", "term_target": "จริงหรอ", "pronunciation": ["Jing ro"], "example": {"sentence": "จริงหรอ?", "translation": "真的嗎？"}, "usage_note": "確認或強調。", "image_file": "really.png" },
        { "id": "adv-04", "term_zh": "經常", "term_target": "บ่อยๆ", "pronunciation": ["Boi boi"], "example": {"sentence": "มาบ่อยๆ", "translation": "常來。"}, "usage_note": "頻率。", "image_file": "often.png" },
        { "id": "adv-05", "term_zh": "通常", "term_target": "ปกติ", "pronunciation": ["Pokkati"], "example": {"sentence": "ปกติตื่น 7 โมง", "translation": "通常七點起床。"}, "usage_note": "習慣。", "image_file": "usually.png" },
        { "id": "adv-06", "term_zh": "只有", "term_target": "แค่ / เท่านั้น", "pronunciation": ["Khae / Thao nan"], "example": {"sentence": "แค่คุณเท่านั้น", "translation": "只有你。"}, "usage_note": "唯一。", "image_file": "only.png" },
        { "id": "adv-07", "term_zh": "再次", "term_target": "อีกครั้ง", "pronunciation": ["Ik krang"], "example": {"sentence": "เจอกันอีกครั้ง", "translation": "再見面吧。"}, "usage_note": "重複。", "image_file": "again.png" },
        { "id": "adv-08", "term_zh": "一起", "term_target": "ด้วยกัน", "pronunciation": ["Duai kan"], "example": {"sentence": "ไปด้วยกัน", "translation": "一起去吧。"}, "usage_note": "共同。", "image_file": "together.png" },
        { "id": "adv-09", "term_zh": "或許", "term_target": "อาจจะ", "pronunciation": ["At ja"], "example": {"sentence": "อาจจะใช่", "translation": "大概是那樣。"}, "usage_note": "不確定。", "image_file": "maybe.png" },
        { "id": "adv-10", "term_zh": "很快", "term_target": "เร็วๆ นี้", "pronunciation": ["Reo reo ni"], "example": {"sentence": "เจอกันเร็วๆ นี้", "translation": "快到了。"}, "usage_note": "不久後。", "image_file": "soon.png" },
        { "id": "adv-11", "term_zh": "已經", "term_target": "แล้ว", "pronunciation": ["Laeo"], "example": {"sentence": "กินแล้ว", "translation": "已經吃了。"}, "usage_note": "完成。", "image_file": "already.png" },
        { "id": "adv-12", "term_zh": "大約", "term_target": "ประมาณ", "pronunciation": ["Praman"], "example": {"sentence": "ประมาณ 10 นาที", "translation": "大約10分鐘。"}, "usage_note": "概數。", "image_file": "about.png" },
        { "id": "adv-13", "term_zh": "一點點", "term_target": "นิดหน่อย", "pronunciation": ["Nit noi"], "example": {"sentence": "เผ็ดนิดหน่อย", "translation": "一點點辣。"}, "usage_note": "少量。", "image_file": "a_little.png" },
        { "id": "adv-14", "term_zh": "之後", "term_target": "ทีหลัง", "pronunciation": ["Thi lang"], "example": {"sentence": "เจอกันทีหลัง", "translation": "待會見。"}, "usage_note": "稍後。", "image_file": "later.png" },
        { "id": "adv-15", "term_zh": "仍然", "term_target": "ยัง", "pronunciation": ["Yang"], "example": {"sentence": "ยังไม่มา", "translation": "還沒來。"}, "usage_note": "持續。", "image_file": "still.png" },
        { "id": "adv-16", "term_zh": "一般來說", "term_target": "ธรรมดา", "pronunciation": ["Thammada"], "example": {"sentence": "เป็นเรื่องธรรมดา", "translation": "一般是那樣。"}, "usage_note": "通常。", "image_file": "normally.png" }
      ]
    },
    {
      "id": "questions",
      "name": "疑問詞",
      "items": [
        { "id": "q-01", "term_zh": "什麼", "term_target": "อะไร", "pronunciation": ["A-rai"], "example": {"sentence": "นี่คืออะไร?", "translation": "這是什麼？"}, "usage_note": "問事物。", "image_file": "what.png" },
        { "id": "q-02", "term_zh": "哪裡", "term_target": "ที่ไหน", "pronunciation": ["Thi nai"], "example": {"sentence": "ไปที่ไหน?", "translation": "去哪裡？"}, "usage_note": "問地點。", "image_file": "where.png" },
        { "id": "q-03", "term_zh": "何時", "term_target": "เมื่อไหร่", "pronunciation": ["Muea rai"], "example": {"sentence": "มาเมื่อไหร่?", "translation": "何時來？"}, "usage_note": "問時間。", "image_file": "when.png" },
        { "id": "q-04", "term_zh": "誰", "term_target": "ใคร", "pronunciation": ["Khrai"], "example": {"sentence": "ใครคะ?", "translation": "哪位？"}, "usage_note": "問人。", "image_file": "who.png" },
        { "id": "q-05", "term_zh": "為什麼", "term_target": "ทำไม", "pronunciation": ["Thammai"], "example": {"sentence": "ทำไมครับ?", "translation": "為什麼？"}, "usage_note": "問原因。", "image_file": "why.png" },
        { "id": "q-06", "term_zh": "如何", "term_target": "อย่างไร", "pronunciation": ["Yang rai"], "example": {"sentence": "ไปอย่างไร?", "translation": "怎麼去？"}, "usage_note": "問方法。口語常說 Yang ngai。", "image_file": "how.png" },
        { "id": "q-07", "term_zh": "多少(錢)", "term_target": "เท่าไหร่", "pronunciation": ["Thao rai"], "example": {"sentence": "เท่าไหร่ครับ?", "translation": "多少錢？"}, "usage_note": "問價格。", "image_file": "how_much.png" },
        { "id": "q-08", "term_zh": "多久/多少(量)", "term_target": "นานแค่ไหน", "pronunciation": ["Nan khae nai"], "example": {"sentence": "รอนานแค่ไหน?", "translation": "要等多久？"}, "usage_note": "問時間長度。", "image_file": "how_long.png" },
        { "id": "q-09", "term_zh": "哪一個", "term_target": "อันไหน", "pronunciation": ["An nai"], "example": {"sentence": "ชอบอันไหน?", "translation": "喜歡哪一個？"}, "usage_note": "選擇。", "image_file": "which.png" }
      ]
    },
    {
      "id": "time_place",
      "name": "時間與場所",
      "items": [
        { "id": "tp-01", "term_zh": "今天", "term_target": "วันนี้", "pronunciation": ["Wan ni"], "example": {"sentence": "วันนี้ร้อน", "translation": "今天很熱。"}, "usage_note": "本日。", "image_file": "today.png" },
        { "id": "tp-02", "term_zh": "明天", "term_target": "พรุ่งนี้", "pronunciation": ["Phrung ni"], "example": {"sentence": "เจอกันพรุ่งนี้", "translation": "明天見。"}, "usage_note": "隔天。", "image_file": "tomorrow.png" },
        { "id": "tp-03", "term_zh": "昨天", "term_target": "เมื่อวาน", "pronunciation": ["Muea wan"], "example": {"sentence": "เมื่อวานมาแล้ว", "translation": "昨天來了。"}, "usage_note": "前一天。", "image_file": "yesterday.png" },
        { "id": "tp-04", "term_zh": "這裡", "term_target": "ที่นี่", "pronunciation": ["Thi ni"], "example": {"sentence": "มาที่นี่", "translation": "來這裡。"}, "usage_note": "近處。", "image_file": "here.png" },
        { "id": "tp-05", "term_zh": "那裡", "term_target": "ที่นั่น", "pronunciation": ["Thi nan"], "example": {"sentence": "ไปที่นั่น", "translation": "去那裡。"}, "usage_note": "遠處。", "image_file": "there.png" },
        { "id": "tp-06", "term_zh": "早上", "term_target": "เช้า", "pronunciation": ["Chao"], "example": {"sentence": "ตอนเช้า", "translation": "在早上。"}, "usage_note": "上午。", "image_file": "morning.png" },
        { "id": "tp-07", "term_zh": "晚上/夜晚", "term_target": "กลางคืน", "pronunciation": ["Klang khuen"], "example": {"sentence": "ตอนกลางคืน", "translation": "晚上。"}, "usage_note": "太陽下山後。", "image_file": "night.png" },
        { "id": "tp-08", "term_zh": "前面", "term_target": "ข้างหน้า", "pronunciation": ["Khang na"], "example": {"sentence": "อยู่ข้างหน้า", "translation": "在前面。"}, "usage_note": "前方。", "image_file": "front.png" },
        { "id": "tp-09", "term_zh": "後面", "term_target": "ข้างหลัง", "pronunciation": ["Khang lang"], "example": {"sentence": "อยู่ข้างหลัง", "translation": "在後面。"}, "usage_note": "後方。", "image_file": "behind.png" },
        { "id": "tp-10", "term_zh": "左邊", "term_target": "ซ้าย", "pronunciation": ["Sai"], "example": {"sentence": "เลี้ยวซ้าย", "translation": "左轉。"}, "usage_note": "左。", "image_file": "left.png" },
        { "id": "tp-11", "term_zh": "右邊", "term_target": "ขวา", "pronunciation": ["Khwa"], "example": {"sentence": "อยู่ขวามือ", "translation": "在右邊。"}, "usage_note": "右。", "image_file": "right.png" },
        { "id": "tp-12", "term_zh": "天(日)", "term_target": "วัน", "pronunciation": ["Wan"], "example": {"sentence": "วันดี", "translation": "好日子。"}, "usage_note": "日子。", "image_file": "day.png" },
        { "id": "tp-13", "term_zh": "年", "term_target": "ปี", "pronunciation": ["Pi"], "example": {"sentence": "ปีนี้", "translation": "今年。"}, "usage_note": "年度。", "image_file": "year.png" },
        { "id": "tp-14", "term_zh": "月", "term_target": "เดือน", "pronunciation": ["Duean"], "example": {"sentence": "เดือนนี้", "translation": "這個月。"}, "usage_note": "月份。", "image_file": "month.png" },
        { "id": "tp-15", "term_zh": "週", "term_target": "อาทิตย์", "pronunciation": ["Athit"], "example": {"sentence": "อาทิตย์หน้า", "translation": "下週。"}, "usage_note": "星期。", "image_file": "week.png" },
        { "id": "tp-16", "term_zh": "下午", "term_target": "บ่าย", "pronunciation": ["Bai"], "example": {"sentence": "บ่าย 2 โมง", "translation": "下午2點。"}, "usage_note": "PM。", "image_file": "afternoon.png" },
        { "id": "tp-17", "term_zh": "中午", "term_target": "เที่ยง", "pronunciation": ["Thiang"], "example": {"sentence": "ตอนเที่ยง", "translation": "在中午。"}, "usage_note": "12點。", "image_file": "noon.png" },
        { "id": "tp-18", "term_zh": "旁邊", "term_target": "ข้างๆ", "pronunciation": ["Khang khang"], "example": {"sentence": "นั่งข้างๆ", "translation": "坐旁邊。"}, "usage_note": "側邊。", "image_file": "beside.png" },
        { "id": "tp-19", "term_zh": "對面", "term_target": "ตรงข้าม", "pronunciation": ["Trong kham"], "example": {"sentence": "อยู่ตรงข้าม", "translation": "在對面。"}, "usage_note": "對側。", "image_file": "across_from.png" },
        { "id": "tp-20", "term_zh": "春天", "term_target": "ฤดูใบไม้ผลิ", "pronunciation": ["Ruedu bai mai phli"], "example": {"sentence": "ฤดูใบไม้ผลิมาถึง", "translation": "春天來了。"}, "usage_note": "季節。", "image_file": "spring.png" },
        { "id": "tp-21", "term_zh": "夏天", "term_target": "ฤดูร้อน", "pronunciation": ["Ruedu ron"], "example": {"sentence": "ฤดูร้อนร้อนมาก", "translation": "夏天很熱。"}, "usage_note": "季節。", "image_file": "summer.png" },
        { "id": "tp-22", "term_zh": "秋天", "term_target": "ฤดูใบไม้ร่วง", "pronunciation": ["Ruedu bai mai ruang"], "example": {"sentence": "ชอบฤดูใบไม้ร่วง", "translation": "喜歡秋天。"}, "usage_note": "季節。", "image_file": "autumn.png" },
        { "id": "tp-23", "term_zh": "冬天", "term_target": "ฤดูหนาว", "pronunciation": ["Ruedu nao"], "example": {"sentence": "ฤดูหนาวหนาวมาก", "translation": "冬天很冷。"}, "usage_note": "季節。", "image_file": "winter.png" }
      ]
    },
    {
      "id": "numbers",
      "name": "數字",
      "items": [
        { "id": "num-0", "term_zh": "0", "term_target": "ศูนย์", "pronunciation": ["Sun"], "example": {"sentence": "ศูนย์", "translation": "零。"}, "usage_note": "零。", "image_file": "zero.png" },
        { "id": "num-1", "term_zh": "1", "term_target": "หนึ่ง", "pronunciation": ["Nueng"], "example": {"sentence": "หนึ่งอัน", "translation": "一個。"}, "usage_note": "一。", "image_file": "one.png" },
        { "id": "num-2", "term_zh": "2", "term_target": "สอง", "pronunciation": ["Song"], "example": {"sentence": "สองวัน", "translation": "兩天。"}, "usage_note": "二。", "image_file": "two.png" },
        { "id": "num-3", "term_zh": "3", "term_target": "สาม", "pronunciation": ["Sam"], "example": {"sentence": "สามคน", "translation": "三個人。"}, "usage_note": "三。", "image_file": "three.png" },
        { "id": "num-4", "term_zh": "4", "term_target": "สี่", "pronunciation": ["Si"], "example": {"sentence": "สี่โมง", "translation": "四點。"}, "usage_note": "四。", "image_file": "four.png" },
        { "id": "num-5", "term_zh": "5", "term_target": "ห้า", "pronunciation": ["Ha"], "example": {"sentence": "ห้าอัน", "translation": "五個。"}, "usage_note": "五。", "image_file": "five.png" },
        { "id": "num-6", "term_zh": "6", "term_target": "หก", "pronunciation": ["Hok"], "example": {"sentence": "หกชั่วโมง", "translation": "六小時。"}, "usage_note": "六。", "image_file": "six.png" },
        { "id": "num-7", "term_zh": "7", "term_target": "เจ็ด", "pronunciation": ["Jet"], "example": {"sentence": "เจ็ดวัน", "translation": "七天。"}, "usage_note": "七。", "image_file": "seven.png" },
        { "id": "num-8", "term_zh": "8", "term_target": "แปด", "pronunciation": ["Paet"], "example": {"sentence": "แปดปี", "translation": "八歲。"}, "usage_note": "八。", "image_file": "eight.png" },
        { "id": "num-9", "term_zh": "9", "term_target": "เก้า", "pronunciation": ["Kao"], "example": {"sentence": "เก้าโมง", "translation": "九點。"}, "usage_note": "九。", "image_file": "nine.png" },
        { "id": "num-10", "term_zh": "10", "term_target": "สิบ", "pronunciation": ["Sip"], "example": {"sentence": "สิบอัน", "translation": "十個。"}, "usage_note": "十。", "image_file": "ten.png" },
        { "id": "num-11", "term_zh": "11", "term_target": "สิบเอ็ด", "pronunciation": ["Sip-et"], "example": {"sentence": "สิบเอ็ดโมง", "translation": "11點。"}, "usage_note": "十一 (注意是一 Sip-et，不是 Sip-nueng)。", "image_file": "eleven.png" },
        { "id": "num-12", "term_zh": "12", "term_target": "สิบสอง", "pronunciation": ["Sip-song"], "example": {"sentence": "สิบสองเดือน", "translation": "12個月。"}, "usage_note": "十二。", "image_file": "twelve.png" },
        { "id": "num-15", "term_zh": "15", "term_target": "สิบห้า", "pronunciation": ["Sip-ha"], "example": {"sentence": "15 นาที", "translation": "15分。"}, "usage_note": "十五。", "image_file": "fifteen.png" },
        { "id": "num-20", "term_zh": "20", "term_target": "ยี่สิบ", "pronunciation": ["Yi-sip"], "example": {"sentence": "ยี่สิบบาท", "translation": "20銖。"}, "usage_note": "二十 (注意是 Yi-sip，不是 Song-sip)。", "image_file": "twenty.png" },
        { "id": "num-50", "term_zh": "50", "term_target": "ห้าสิบ", "pronunciation": ["Ha-sip"], "example": {"sentence": "ห้าสิบคน", "translation": "50人。"}, "usage_note": "五十。", "image_file": "fifty.png" },
        { "id": "num-100", "term_zh": "100", "term_target": "หนึ่งร้อย", "pronunciation": ["Nueng roi"], "example": {"sentence": "หนึ่งร้อยคะแนน", "translation": "一百分。"}, "usage_note": "百。", "image_file": "hundred.png" },
        { "id": "num-1000", "term_zh": "1000", "term_target": "หนึ่งพัน", "pronunciation": ["Nueng phan"], "example": {"sentence": "หนึ่งพันบาท", "translation": "一千銖。"}, "usage_note": "千。", "image_file": "thousand.png" },
        { "id": "num-10000", "term_zh": "10000", "term_target": "หนึ่งหมื่น", "pronunciation": ["Nueng muen"], "example": {"sentence": "หนึ่งหมื่นบาท", "translation": "一萬銖。"}, "usage_note": "一萬。", "image_file": "ten_thousand.png" }
      ]
    },
    {
      "id": "grammar",
      "name": "基本句型",
      "items": [
        { "id": "g-01", "term_zh": "我是...", "term_target": "ผม/ฉัน เป็น...", "pronunciation": ["Phom/Chan pen..."], "example": {"sentence": "ผมเป็นนักเรียน", "translation": "我是學生。"}, "usage_note": "是 (接名詞)。", "image_file": "i_am.png" },
        { "id": "g-02", "term_zh": "我正在...", "term_target": "ผม/ฉัน กำลัง...", "pronunciation": ["Phom/Chan kamlang..."], "example": {"sentence": "ผมกำลังกิน", "translation": "我正在吃。"}, "usage_note": "進行式。", "image_file": "ing.png" },
        { "id": "g-03", "term_zh": "我能夠(會)...", "term_target": "ผม/ฉัน ...ได้", "pronunciation": ["Phom/Chan ... dai"], "example": {"sentence": "ผมขับรถได้", "translation": "我會開車。"}, "usage_note": "能力。", "image_file": "can.png" },
        { "id": "g-04", "term_zh": "我喜歡做...", "term_target": "ผม/ฉัน ชอบ...", "pronunciation": ["Phom/Chan chop..."], "example": {"sentence": "ฉันชอบอ่านหนังสือ", "translation": "我喜歡閱讀。"}, "usage_note": "興趣。", "image_file": "like_ing.png" },
        { "id": "g-05", "term_zh": "我想做...", "term_target": "ผม/ฉัน อยาก...", "pronunciation": ["Phom/Chan yak..."], "example": {"sentence": "ฉันอยากไป", "translation": "我想去。"}, "usage_note": "慾望。", "image_file": "want_to.png" },
        { "id": "g-06", "term_zh": "你是...嗎?", "term_target": "คุณเป็น...ใช่ไหม?", "pronunciation": ["Khun pen ... chai mai?"], "example": {"sentence": "คุณเป็นนักเรียนใช่ไหม?", "translation": "你是學生嗎？"}, "usage_note": "確認身分。", "image_file": "are_you.png" },
        { "id": "g-07", "term_zh": "不要...", "term_target": "อย่า...", "pronunciation": ["Ya..."], "example": {"sentence": "อย่าไป", "translation": "不要走。"}, "usage_note": "禁止/請求。", "image_file": "dont.png" },
        { "id": "g-08", "term_zh": "你有做...嗎?", "term_target": "คุณ...ไหม?", "pronunciation": ["Khun ... mai?"], "example": {"sentence": "คุณกินไหม?", "translation": "你要吃嗎？"}, "usage_note": "一般疑問句。", "image_file": "do_you.png" },
        { "id": "g-09", "term_zh": "你曾經...嗎?", "term_target": "คุณเคย...ไหม?", "pronunciation": ["Khun khoei ... mai?"], "example": {"sentence": "คุณเคยไปไหม?", "translation": "你有去過嗎？"}, "usage_note": "問經驗。", "image_file": "have_you_ever.png" },
        { "id": "g-10", "term_zh": "你何時做...?", "term_target": "คุณ...เมื่อไหร่?", "pronunciation": ["Khun ... muea rai?"], "example": {"sentence": "คุณนอนเมื่อไหร่?", "translation": "你何時睡？"}, "usage_note": "問時間點。", "image_file": "when_do_you.png" },
        { "id": "g-11", "term_zh": "你在哪裡做...?", "term_target": "คุณ...ที่ไหน?", "pronunciation": ["Khun ... thi nai?"], "example": {"sentence": "คุณซื้อที่ไหน?", "translation": "你在哪買？"}, "usage_note": "問地點。", "image_file": "where_do_you.png" },
        { "id": "g-12", "term_zh": "你如何做...?", "term_target": "คุณ...อย่างไร?", "pronunciation": ["Khun ... yang rai?"], "example": {"sentence": "คุณไปอย่างไร?", "translation": "你怎麼去？"}, "usage_note": "問方法。", "image_file": "how_do_you.png" },
        { "id": "g-13", "term_zh": "我不是...", "term_target": "ผม/ฉัน ไม่ใช่...", "pronunciation": ["Phom/Chan mai chai..."], "example": {"sentence": "ผมไม่ใช่นักเรียน", "translation": "我不是學生。"}, "usage_note": "否定身分。", "image_file": "i_am_not.png" },
        { "id": "g-14", "term_zh": "我不做...", "term_target": "ผม/ฉัน ไม่...", "pronunciation": ["Phom/Chan mai..."], "example": {"sentence": "ฉันไม่กิน", "translation": "我不吃。"}, "usage_note": "否定動作。", "image_file": "i_dont.png" },
        { "id": "g-15", "term_zh": "我不能(會)...", "term_target": "ผม/ฉัน ...ไม่ได้", "pronunciation": ["Phom/Chan ... mai dai"], "example": {"sentence": "ผมขับรถไม่ได้", "translation": "我不會開車。"}, "usage_note": "能力否定。", "image_file": "i_cant.png" },
        { "id": "g-16", "term_zh": "我未曾...", "term_target": "ผม/ฉัน ไม่เคย...", "pronunciation": ["Phom/Chan mai khoei..."], "example": {"sentence": "ฉันไม่เคยกิน", "translation": "我一次都沒吃過。"}, "usage_note": "無此經驗。", "image_file": "i_have_never.png" },
        { "id": "g-17", "term_zh": "我不必...", "term_target": "ผม/ฉัน ไม่ต้อง...", "pronunciation": ["Phom/Chan mai tong..."], "example": {"sentence": "ผมไม่ต้องไป", "translation": "我不必去。"}, "usage_note": "無義務。", "image_file": "i_dont_have_to.png" },
        { "id": "g-18", "term_zh": "如果...的話", "term_target": "ถ้า...", "pronunciation": ["Tha..."], "example": {"sentence": "ถ้าถูกจะซื้อ", "translation": "如果便宜的話我就買。"}, "usage_note": "假設條件。", "image_file": "if.png" },
        { "id": "g-19", "term_zh": "當...時", "term_target": "เมื่อ...", "pronunciation": ["Muea..."], "example": {"sentence": "เมื่อตอนเป็นเด็ก", "translation": "小時候(當我是孩子時)。"}, "usage_note": "時間條件。", "image_file": "when_condition.png" },
        { "id": "g-20", "term_zh": "請你...好嗎?", "term_target": "คุณ...ได้ไหม?", "pronunciation": ["Khun ... dai mai?"], "example": {"sentence": "คุณช่วยฉันได้ไหม?", "translation": "可以幫我嗎？"}, "usage_note": "請求。", "image_file": "can_you.png" },
        { "id": "g-21", "term_zh": "我們來做...吧", "term_target": "...กันเถอะ", "pronunciation": ["... kan thoe"], "example": {"sentence": "ไปกันเถอะ", "translation": "走吧。"}, "usage_note": "提議。", "image_file": "lets.png" },
        { "id": "g-22", "term_zh": "我認為...", "term_target": "ผม/ฉัน คิดว่า...", "pronunciation": ["Phom/Chan khit wa..."], "example": {"sentence": "ฉันคิดว่าดี", "translation": "我認為很好。"}, "usage_note": "表達想法。", "image_file": "i_think.png" },
        { "id": "g-23", "term_zh": "我必須...", "term_target": "ผม/ฉัน ต้อง...", "pronunciation": ["Phom/Chan tong..."], "example": {"sentence": "ผมต้องทำงาน", "translation": "我必須工作。"}, "usage_note": "義務。", "image_file": "i_have_to.png" },
        { "id": "g-24", "term_zh": "做某事是...的", "term_target": "การ... มัน...", "pronunciation": ["Kan ... man ..."], "example": {"sentence": "การกินมันสนุก", "translation": "吃東西是開心的。"}, "usage_note": "動詞名詞化。", "image_file": "it_is_to.png" },
        { "id": "g-25", "term_zh": "我可以...嗎?", "term_target": "ผม/ฉัน ...ได้ไหม?", "pronunciation": ["Phom/Chan ... dai mai?"], "example": {"sentence": "ถ่ายรูปได้ไหม?", "translation": "我可以拍照嗎？"}, "usage_note": "請求許可。", "image_file": "can_i.png" },
        { "id": "g-26", "term_zh": "我比較喜歡...", "term_target": "ผม/ฉัน ชอบ...มากกว่า", "pronunciation": ["Phom/Chan chop ... mak kwa"], "example": {"sentence": "ฉันชอบอันนี้มากกว่า", "translation": "我比較喜歡這個。"}, "usage_note": "偏好。", "image_file": "prefer.png" },
        { "id": "g-27", "term_zh": "A比B更...", "term_target": "A ...กว่า B", "pronunciation": ["A ... kwa B"], "example": {"sentence": "อันนี้แพงกว่าอันนั้น", "translation": "這比那個貴。"}, "usage_note": "比較級。", "image_file": "more_than.png" },
        { "id": "g-28", "term_zh": "有(存在)...", "term_target": "มี...", "pronunciation": ["Mi..."], "example": {"sentence": "มีหมา", "translation": "有一隻狗。"}, "usage_note": "存在。", "image_file": "there_is.png" },
        { "id": "g-29", "term_zh": "我曾經是/當時是...", "term_target": "ผม/ฉัน เคยเป็น...", "pronunciation": ["Phom/Chan khoei pen..."], "example": {"sentence": "ผมเคยเป็นนักเรียน", "translation": "我曾經是學生。"}, "usage_note": "過去狀態。", "image_file": "i_was.png" },
        { "id": "g-30", "term_zh": "我將要...", "term_target": "ผม/ฉัน จะ...", "pronunciation": ["Phom/Chan ja..."], "example": {"sentence": "ฉันจะไป", "translation": "我要去。"}, "usage_note": "未來意。", "image_file": "i_will.png" },
        { "id": "g-31", "term_zh": "我做過(過去式)...", "term_target": "ผม/ฉัน ...แล้ว", "pronunciation": ["Phom/Chan ... laeo"], "example": {"sentence": "ผมทำการบ้านแล้ว", "translation": "我做完功課了。"}, "usage_note": "過去動作。", "image_file": "i_did.png" }
      ]
    }
  ]
}