import { AppData } from '../types';

export const vietnameseData: AppData =
 {
  "meta": {
    "source_language": "zh-TW",
    "target_language": "vi-VN",
    "version": "2.1",
    "description": "台灣人快速語言學習 - 越南文完整版 (僅 IPA 發音)"
  },
  "categories": [
    {
      "id": "greetings",
      "name": "常用句",
      "items": [
        {
          "id": "greet-001",
          "term_zh": "你好",
          "term_target": "Xin chào",
          "pronunciation": ["/sin˧ tɕaːw˨˩/"],
          "example": { "sentence": "Xin chào, bạn khỏe không?", "translation": "你好，你好嗎？" },
          "usage_note": "最通用的問候，任何時間對任何人都能用。",
          "image_file": "hello.png"
        },
        {
          "id": "greet-002",
          "term_zh": "再見",
          "term_target": "Tạm biệt",
          "pronunciation": ["/taːm˧˨ˀ ɓiət̚˧˨ˀ/"],
          "example": { "sentence": "Tạm biệt, hẹn gặp lại.", "translation": "再見，待會見。" },
          "usage_note": "發音很像中文的「暫別」。",
          "image_file": "goodbye.png"
        },
        {
          "id": "greet-003",
          "term_zh": "謝謝你",
          "term_target": "Cảm ơn",
          "pronunciation": ["/kaːm˧˩ ʔəːn˧/"],
          "example": { "sentence": "Cảm ơn rất nhiều.", "translation": "非常謝謝你。" },
          "usage_note": "發音跟台語的「感恩」非常像。",
          "image_file": "thank_you.png"
        },
        {
          "id": "greet-004",
          "term_zh": "對不起",
          "term_target": "Xin lỗi",
          "pronunciation": ["/sin˧ loj˦ˀ˥/"],
          "example": { "sentence": "Xin lỗi, tôi đến muộn.", "translation": "對不起，我遲到了。" },
          "usage_note": "做錯事道歉，或藉過時也可以用。",
          "image_file": "sorry.png"
        },
        {
          "id": "greet-005",
          "term_zh": "早安",
          "term_target": "Chào buổi sáng",
          "pronunciation": ["/tɕaːw˨˩ ɓuəj˧˩ saːŋ˧˥/"],
          "example": { "sentence": "Chào buổi sáng, mẹ.", "translation": "早安，媽。" },
          "usage_note": "早上見面使用。",
          "image_file": "good_morning.png"
        },
        {
          "id": "greet-006",
          "term_zh": "請問... / 借過",
          "term_target": "Xin hỏi / Cho tôi qua",
          "pronunciation": ["/sin˧ hɔj˧˩/  /tɕɔ˧ toj˧ kwaː˧/"],
          "example": { "sentence": "Xin hỏi, đây là đâu?", "translation": "請問，這是哪裡？" },
          "usage_note": "問問題說 Xin hỏi，借過說 Cho tôi qua。",
          "image_file": "excuse_me.png"
        },
        {
          "id": "greet-007",
          "term_zh": "我不懂",
          "term_target": "Tôi không hiểu",
          "pronunciation": ["/toj˧ xoŋ˧ hiəw˧˩/"],
          "example": { "sentence": "Xin lỗi, tôi không hiểu.", "translation": "抱歉，我不懂。" },
          "usage_note": "聽不懂時直接說。",
          "image_file": "dont_understand.png"
        },
        {
          "id": "greet-008",
          "term_zh": "這是什麼？",
          "term_target": "Cái này là cái gì?",
          "pronunciation": ["/kaːj˧˥ naj˨˩ laː˨˩ kaːj˧˥ zi˨˩/"],
          "example": { "sentence": "Cái này là cái gì? Ngon không?", "translation": "這是什麼？好吃嗎？" },
          "usage_note": "指著東西問。",
          "image_file": "what_is_this.png"
        },
        {
          "id": "greet-009",
          "term_zh": "我想要這個",
          "term_target": "Tôi muốn cái này",
          "pronunciation": ["/toj˧ muən˧˥ kaːj˧˥ naj˨˩/"],
          "example": { "sentence": "Tôi muốn mua cái này.", "translation": "我想買這個。" },
          "usage_note": "表達願望。",
          "image_file": "i_want_this.png"
        },
        {
          "id": "greet-010",
          "term_zh": "請給我...",
          "term_target": "Cho tôi...",
          "pronunciation": ["/tɕɔ˧ toj˧/"],
          "example": { "sentence": "Cho tôi một ly nước.", "translation": "請給我一杯水。" },
          "usage_note": "點餐必備：Cho tôi + 東西。",
          "image_file": "please_give_me.png"
        },
        {
          "id": "greet-011",
          "term_zh": "廁所在哪裡？",
          "term_target": "Nhà vệ sinh ở đâu?",
          "pronunciation": ["/ɲaː˨˩ ve˧˨ˀ siŋ˧ əː˧˩ ɗəw˧/"],
          "example": { "sentence": "Xin hỏi, nhà vệ sinh ở đâu?", "translation": "請問，廁所在哪？" },
          "usage_note": "旅遊最重要的一句。",
          "image_file": "where_bathroom.png"
        },
        {
          "id": "greet-012",
          "term_zh": "多少錢？",
          "term_target": "Bao nhiêu tiền?",
          "pronunciation": ["/ɓaːw˧ ɲiəw˧ tiən˨˩/"],
          "example": { "sentence": "Cái này bao nhiêu tiền?", "translation": "這個多少錢？" },
          "usage_note": "購物用語。",
          "image_file": "how_much.png"
        },
        {
          "id": "greet-013",
          "term_zh": "請幫我",
          "term_target": "Làm ơn giúp tôi",
          "pronunciation": ["/laːm˨˩ əːn˧ zup̚˧˥ toj˧/"],
          "example": { "sentence": "Làm ơn giúp tôi với.", "translation": "拜託幫幫我。" },
          "usage_note": "尋求協助。",
          "image_file": "help_me.png"
        },
        {
          "id": "greet-014",
          "term_zh": "你可以再說一次嗎？",
          "term_target": "Bạn nói lại được không?",
          "pronunciation": ["/ɓaːn˧˨ˀ nɔj˧˥ laːj˧˨ˀ ɗɨək̚˧˨ˀ xoŋ˧/"],
          "example": { "sentence": "Xin lỗi, bạn nói lại được không?", "translation": "抱歉，能再說一次嗎？" },
          "usage_note": "沒聽清楚時。",
          "image_file": "say_again.png"
        },
        {
          "id": "greet-015",
          "term_zh": "你可以講慢一點嗎？",
          "term_target": "Bạn nói chậm lại được không?",
          "pronunciation": ["/ɓaːn˧˨ˀ nɔj˧˥ tɕəm˧˨ˀ laːj˧˨ˀ ɗɨək̚˧˨ˀ xoŋ˧/"],
          "example": { "sentence": "Làm ơn nói chậm lại.", "translation": "請講慢一點。" },
          "usage_note": "請對方放慢速度。",
          "image_file": "speak_slowly.png"
        }
      ]
    },
    {
      "id": "pronouns",
      "name": "主詞（代名詞）",
      "items": [
        { "id": "pro-01", "term_zh": "我", "term_target": "Tôi", "pronunciation": ["/toj˧/"], "example": {"sentence": "Tôi là người Đài Loan.", "translation": "我是台灣人。"}, "usage_note": "最通用的自稱。", "image_file": "i.png" },
        { "id": "pro-02", "term_zh": "你", "term_target": "Bạn", "pronunciation": ["/ɓaːn˧˨ˀ/"], "example": {"sentence": "Bạn tên là gì?", "translation": "你叫什麼名字？"}, "usage_note": "朋友或平輩用。對長輩用 Anh(兄)/Chị(姐)。", "image_file": "you.png" },
        { "id": "pro-03", "term_zh": "他", "term_target": "Anh ấy", "pronunciation": ["/aɲ˧ əj˧˥/"], "example": {"sentence": "Anh ấy là giáo viên.", "translation": "他是老師。"}, "usage_note": "指男性。", "image_file": "he.png" },
        { "id": "pro-04", "term_zh": "她", "term_target": "Cô ấy", "pronunciation": ["/ko˧ əj˧˥/"], "example": {"sentence": "Cô ấy rất đẹp.", "translation": "她很漂亮。"}, "usage_note": "指女性。", "image_file": "she.png" },
        { "id": "pro-05", "term_zh": "我們", "term_target": "Chúng tôi", "pronunciation": ["/tɕuŋ˧˥ toj˧/"], "example": {"sentence": "Chúng tôi là gia đình.", "translation": "我們是家人。"}, "usage_note": "不包含聽話者用 Chúng tôi。", "image_file": "we.png" },
        { "id": "pro-06", "term_zh": "他們", "term_target": "Họ", "pronunciation": ["/hɔ˧˨ˀ/"], "example": {"sentence": "Họ là học sinh.", "translation": "他們是學生。"}, "usage_note": "第三人稱複數。", "image_file": "they.png" },
        { "id": "pro-07", "term_zh": "這個", "term_target": "Cái này", "pronunciation": ["/kaːj˧˥ naj˨˩/"], "example": {"sentence": "Cái này ngon.", "translation": "這個好吃。"}, "usage_note": "近處。", "image_file": "this.png" },
        { "id": "pro-08", "term_zh": "那個/它", "term_target": "Cái đó / Nó", "pronunciation": ["/kaːj˧˥ ɗɔ˧˥/  /nɔ˧˥/"], "example": {"sentence": "Cái đó là gì?", "translation": "那個是什麼？"}, "usage_note": "遠處用 Cái đó，它用 Nó。", "image_file": "that.png" },
        { "id": "pro-09", "term_zh": "他的", "term_target": "Của anh ấy", "pronunciation": ["/kuə˧˩ aɲ˧ əj˧˥/"], "example": {"sentence": "Xe của anh ấy.", "translation": "他的車。"}, "usage_note": "所有格用 Của。", "image_file": "his.png" },
        { "id": "pro-10", "term_zh": "她的", "term_target": "Của cô ấy", "pronunciation": ["/kuə˧˩ ko˧ əj˧˥/"], "example": {"sentence": "Túi của cô ấy.", "translation": "她的包包。"}, "usage_note": "所有格。", "image_file": "her.png" },
        { "id": "pro-11", "term_zh": "你的", "term_target": "Của bạn", "pronunciation": ["/kuə˧˩ ɓaːn˧˨ˀ/"], "example": {"sentence": "Tên của bạn.", "translation": "你的名字。"}, "usage_note": "所有格。", "image_file": "your.png" },
        { "id": "pro-12", "term_zh": "他們的", "term_target": "Của họ", "pronunciation": ["/kuə˧˩ hɔ˧˨ˀ/"], "example": {"sentence": "Nhà của họ.", "translation": "他們的家。"}, "usage_note": "所有格。", "image_file": "their.png" },
        { "id": "pro-13", "term_zh": "我們的", "term_target": "Của chúng tôi", "pronunciation": ["/kuə˧˩ tɕuŋ˧˥ toj˧/"], "example": {"sentence": "Trường của chúng tôi.", "translation": "我們的學校。"}, "usage_note": "所有格。", "image_file": "our.png" },
        { "id": "pro-14", "term_zh": "這些", "term_target": "Những cái này", "pronunciation": ["/ɲɨŋ˧ˀ˥ kaːj˧˥ naj˨˩/"], "example": {"sentence": "Những cái này là sách.", "translation": "這些是書。"}, "usage_note": "複數加 Những。", "image_file": "these.png" },
        { "id": "pro-15", "term_zh": "那些", "term_target": "Những cái đó", "pronunciation": ["/ɲɨŋ˧ˀ˥ kaːj˧˥ ɗɔ˧˥/"], "example": {"sentence": "Những cái đó là chim.", "translation": "那些是鳥。"}, "usage_note": "遠處複數。", "image_file": "those.png" }
      ]
    },
    {
      "id": "verbs",
      "name": "動詞",
      "items": [
        { "id": "v-01", "term_zh": "是", "term_target": "là", "pronunciation": ["/laː˨˩/"], "example": {"sentence": "Tôi là học sinh.", "translation": "我是學生。"}, "usage_note": "連結主詞和狀態。", "image_file": "be.png" },
        { "id": "v-02", "term_zh": "有（擁有）", "term_target": "có", "pronunciation": ["/kɔ˧˥/"], "example": {"sentence": "Tôi có tiền.", "translation": "我有錢。"}, "usage_note": "擁有。", "image_file": "have.png" },
        { "id": "v-03", "term_zh": "去", "term_target": "đi", "pronunciation": ["/ɗi˧/"], "example": {"sentence": "Đi về nhà.", "translation": "回家。"}, "usage_note": "移動。", "image_file": "go.png" },
        { "id": "v-04", "term_zh": "做", "term_target": "làm", "pronunciation": ["/laːm˨˩/"], "example": {"sentence": "Làm bài tập.", "translation": "做作業。"}, "usage_note": "執行動作。", "image_file": "do.png" },
        { "id": "v-05", "term_zh": "說", "term_target": "nói", "pronunciation": ["/nɔj˧˥/"], "example": {"sentence": "Nói xin chào.", "translation": "說你好。"}, "usage_note": "說話。", "image_file": "say.png" },
        { "id": "v-06", "term_zh": "知道", "term_target": "biết", "pronunciation": ["/ɓiət̚˧˥/"], "example": {"sentence": "Tôi biết bạn.", "translation": "我認識你。"}, "usage_note": "知曉。", "image_file": "know.png" },
        { "id": "v-07", "term_zh": "想/思考", "term_target": "nghĩ", "pronunciation": ["/ŋi˧ˀ˥/"], "example": {"sentence": "Tôi cũng nghĩ vậy.", "translation": "我也這麼覺得。"}, "usage_note": "思考。", "image_file": "think.png" },
        { "id": "v-08", "term_zh": "看見", "term_target": "thấy", "pronunciation": ["/tʰəj˧˥/"], "example": {"sentence": "Tôi thấy con chim.", "translation": "我看見一隻鳥。"}, "usage_note": "看見。", "image_file": "see.png" },
        { "id": "v-09", "term_zh": "製作", "term_target": "làm", "pronunciation": ["/laːm˨˩/"], "example": {"sentence": "Làm bánh.", "translation": "做蛋糕。"}, "usage_note": "與「做」同字。", "image_file": "make.png" },
        { "id": "v-10", "term_zh": "來", "term_target": "đến", "pronunciation": ["/ɗen˧˥/"], "example": {"sentence": "Đến đây.", "translation": "來這裡。"}, "usage_note": "抵達或過來。", "image_file": "come.png" },
        { "id": "v-11", "term_zh": "需要", "term_target": "cần", "pronunciation": ["/kən˨˩/"], "example": {"sentence": "Tôi cần nước.", "translation": "我需要水。"}, "usage_note": "需要。", "image_file": "need.png" },
        { "id": "v-12", "term_zh": "使用", "term_target": "dùng", "pronunciation": ["/zuŋ˨˩/"], "example": {"sentence": "Dùng bút.", "translation": "用筆。"}, "usage_note": "使用。", "image_file": "use.png" },
        { "id": "v-13", "term_zh": "找到", "term_target": "tìm thấy", "pronunciation": ["/tiːm˨˩ tʰəj˧˥/"], "example": {"sentence": "Tôi tìm thấy rồi.", "translation": "我找到了。"}, "usage_note": "尋獲。", "image_file": "find.png" },
        { "id": "v-14", "term_zh": "給", "term_target": "cho", "pronunciation": ["/tɕɔ˧/"], "example": {"sentence": "Cho tôi cái này.", "translation": "給我這個。"}, "usage_note": "給予。", "image_file": "give.png" },
        { "id": "v-15", "term_zh": "告訴", "term_target": "nói cho", "pronunciation": ["/nɔj˧˥ tɕɔ˧/"], "example": {"sentence": "Nói cho tôi biết.", "translation": "告訴我。"}, "usage_note": "給予。", "image_file": "tell.png" },
        { "id": "v-16", "term_zh": "工作", "term_target": "làm việc", "pronunciation": ["/laːm˨˩ viək̚˧˨ˀ/"], "example": {"sentence": "Tôi làm việc ở đây.", "translation": "我在這工作。"}, "usage_note": "勞動。", "image_file": "work.png" },
        { "id": "v-17", "term_zh": "喜歡", "term_target": "thích", "pronunciation": ["/tʰic̚˧˥/"], "example": {"sentence": "Tôi thích mèo.", "translation": "我喜歡貓。"}, "usage_note": "喜好。", "image_file": "like.png" },
        { "id": "v-18", "term_zh": "起床/醒來", "term_target": "thức dậy", "pronunciation": ["/tʰɨk̚˧˥ zəj˧˨ˀ/"], "example": {"sentence": "Thức dậy sớm.", "translation": "早起。"}, "usage_note": "起床。", "image_file": "wake_up.png" },
        { "id": "v-19", "term_zh": "說話", "term_target": "nói chuyện", "pronunciation": ["/nɔj˧˥ tɕwiən˧˨ˀ/"], "example": {"sentence": "Nói chuyện tiếng Việt.", "translation": "說越南語。"}, "usage_note": "交談。", "image_file": "speak.png" },
        { "id": "v-20", "term_zh": "聽見", "term_target": "nghe", "pronunciation": ["/ŋɛ˧/"], "example": {"sentence": "Bạn có nghe tôi không?", "translation": "你聽得到我嗎？"}, "usage_note": "聽。", "image_file": "hear.png" },
        { "id": "v-21", "term_zh": "寫", "term_target": "viết", "pronunciation": ["/viət̚˧˥/"], "example": {"sentence": "Viết tên.", "translation": "寫名字。"}, "usage_note": "書寫。", "image_file": "write.png" },
        { "id": "v-22", "term_zh": "閱讀", "term_target": "đọc", "pronunciation": ["/ɗawk͡p̚˧˨ˀ/"], "example": {"sentence": "Đọc sách.", "translation": "看書。"}, "usage_note": "讀文字。", "image_file": "read.png" },
        { "id": "v-23", "term_zh": "等待", "term_target": "đợi", "pronunciation": ["/ɗəːj˧˨ˀ/"], "example": {"sentence": "Đợi tôi với.", "translation": "等我一下。"}, "usage_note": "等候。", "image_file": "wait.png" },
        { "id": "v-24", "term_zh": "嘗試", "term_target": "thử", "pronunciation": ["/tʰɨ˧˩/"], "example": {"sentence": "Thử món này.", "translation": "試試這道菜。"}, "usage_note": "試。", "image_file": "try.png" },
        { "id": "v-25", "term_zh": "付錢", "term_target": "trả tiền", "pronunciation": ["/tɕaː˧˩ tiən˨˩/"], "example": {"sentence": "Tôi sẽ trả tiền.", "translation": "我會付錢。"}, "usage_note": "支付。", "image_file": "pay.png" },
        { "id": "v-26", "term_zh": "住", "term_target": "sống", "pronunciation": ["/soŋ˧˥/"], "example": {"sentence": "Tôi sống ở Đài Bắc.", "translation": "我住台北。"}, "usage_note": "居住。", "image_file": "live.png" },
        { "id": "v-27", "term_zh": "走路", "term_target": "đi bộ", "pronunciation": ["/ɗi˧ ɓo˧˨ˀ/"], "example": {"sentence": "Đi bộ về nhà.", "translation": "走路回家。"}, "usage_note": "步行。", "image_file": "walk.png" },
        { "id": "v-28", "term_zh": "打開", "term_target": "mở", "pronunciation": ["/məː˧˩/"], "example": {"sentence": "Mở cửa.", "translation": "開門。"}, "usage_note": "開啟。", "image_file": "open.png" },
        { "id": "v-29", "term_zh": "關閉", "term_target": "đóng", "pronunciation": ["/ɗɔŋ˧˥/"], "example": {"sentence": "Đóng cửa sổ.", "translation": "關窗。"}, "usage_note": "關上。", "image_file": "close.png" },
        { "id": "v-30", "term_zh": "幫助", "term_target": "giúp", "pronunciation": ["/zup̚˧˥/"], "example": {"sentence": "Giúp tôi.", "translation": "幫我。"}, "usage_note": "協助。", "image_file": "help.png" },
        { "id": "v-31", "term_zh": "吃", "term_target": "ăn", "pronunciation": ["/an˧/"], "example": {"sentence": "Ăn cơm.", "translation": "吃飯。"}, "usage_note": "進食。", "image_file": "eat.png" },
        { "id": "v-32", "term_zh": "睡覺", "term_target": "ngủ", "pronunciation": ["/ŋu˧˩/"], "example": {"sentence": "Đi ngủ.", "translation": "去睡覺。"}, "usage_note": "睡眠。", "image_file": "sleep.png" },
        { "id": "v-33", "term_zh": "買", "term_target": "mua", "pronunciation": ["/muə˧/"], "example": {"sentence": "Mua xe.", "translation": "買車。"}, "usage_note": "購買。", "image_file": "buy.png" },
        { "id": "v-34", "term_zh": "乘坐", "term_target": "đi", "pronunciation": ["/ɗi˧/"], "example": {"sentence": "Đi xe buýt.", "translation": "搭公車。"}, "usage_note": "搭乘交通工具常用「去」(đi)。", "image_file": "take.png" },
        { "id": "v-35", "term_zh": "得到/拿", "term_target": "nhận / lấy", "pronunciation": ["/ɲən˧˨ˀ/  /ləj˧˥/"], "example": {"sentence": "Nhận quà.", "translation": "收到禮物。"}, "usage_note": "拿取。", "image_file": "get.png" },
        { "id": "v-36", "term_zh": "選擇", "term_target": "chọn", "pronunciation": ["/tɕɔn˧˨ˀ/"], "example": {"sentence": "Chọn cái này.", "translation": "選這個。"}, "usage_note": "挑選。", "image_file": "choose.png" },
        { "id": "v-37", "term_zh": "進入", "term_target": "vào", "pronunciation": ["/vaːw˨˩/"], "example": {"sentence": "Vào nhà.", "translation": "進屋。"}, "usage_note": "進入。", "image_file": "enter.png" },
        { "id": "v-38", "term_zh": "到達", "term_target": "đến", "pronunciation": ["/ɗen˧˥/"], "example": {"sentence": "Đến nơi rồi.", "translation": "到了。"}, "usage_note": "抵達。", "image_file": "arrive.png" },
        { "id": "v-39", "term_zh": "帶來", "term_target": "mang", "pronunciation": ["/maːŋ˧/"], "example": {"sentence": "Mang ô.", "translation": "帶傘。"}, "usage_note": "攜帶。", "image_file": "bring.png" },
        { "id": "v-40", "term_zh": "變成", "term_target": "trở thành", "pronunciation": ["/tɕəː˧˩ tʰaɲ˨˩/"], "example": {"sentence": "Trở thành giáo viên.", "translation": "變成老師。"}, "usage_note": "變化。", "image_file": "become.png" },
        { "id": "v-41", "term_zh": "開始", "term_target": "bắt đầu", "pronunciation": ["/ɓat̚˧˥ ɗəw˨˩/"], "example": {"sentence": "Bắt đầu học.", "translation": "開始讀書。"}, "usage_note": "開始。", "image_file": "start.png" },
        { "id": "v-42", "term_zh": "結束", "term_target": "kết thúc", "pronunciation": ["/ket̚˧˥ tʰuk͡p̚˧˥/"], "example": {"sentence": "Công việc kết thúc.", "translation": "工作結束。"}, "usage_note": "發音像「結束」。", "image_file": "finish.png" },
        { "id": "v-43", "term_zh": "停止", "term_target": "dừng lại", "pronunciation": ["/zɨŋ˨˩ laːj˧˨ˀ/"], "example": {"sentence": "Dừng xe lại.", "translation": "停車。"}, "usage_note": "停止。", "image_file": "stop.png" },
        { "id": "v-44", "term_zh": "記住", "term_target": "nhớ", "pronunciation": ["/ɲəː˧˥/"], "example": {"sentence": "Tôi nhớ bạn.", "translation": "我記得你 (或我想你)。"}, "usage_note": "記憶或想念。", "image_file": "remember.png" },
        { "id": "v-45", "term_zh": "見面", "term_target": "gặp", "pronunciation": ["/ɣap̚˧˨ˀ/"], "example": {"sentence": "Gặp bạn.", "translation": "見朋友。"}, "usage_note": "會面。", "image_file": "meet.png" },
        { "id": "v-46", "term_zh": "放", "term_target": "đặt / để", "pronunciation": ["/ɗat̚˧˨ˀ/  /ɗe˧˩/"], "example": {"sentence": "Để ở đây.", "translation": "放這裡。"}, "usage_note": "放置。", "image_file": "put.png" },
        { "id": "v-47", "term_zh": "寄送", "term_target": "gửi", "pronunciation": ["/ɣɨj˧˩/"], "example": {"sentence": "Gửi email.", "translation": "寄信。"}, "usage_note": "傳送。", "image_file": "send.png" },
        { "id": "v-48", "term_zh": "開車", "term_target": "lái xe", "pronunciation": ["/laːj˧˥ sɛ˧/"], "example": {"sentence": "Lái xe đi làm.", "translation": "開車上班。"}, "usage_note": "駕駛。", "image_file": "drive.png" },
        { "id": "v-49", "term_zh": "讀書", "term_target": "học", "pronunciation": ["/hawk͡p̚˧˨ˀ/"], "example": {"sentence": "Học tiếng Việt.", "translation": "學越南語。"}, "usage_note": "學習。", "image_file": "study.png" },
        { "id": "v-50", "term_zh": "回去", "term_target": "về", "pronunciation": ["/ve˨˩/"], "example": {"sentence": "Về nhà.", "translation": "回家。"}, "usage_note": "歸返。", "image_file": "go_back.png" }
      ]
    },
    {
      "id": "adjectives",
      "name": "形容詞",
      "items": [
        { "id": "adj-01", "term_zh": "好的", "term_target": "tốt", "pronunciation": ["/tot̚˧˥/"], "example": {"sentence": "Thời tiết tốt.", "translation": "好天氣。"}, "usage_note": "正面。", "image_file": "good.png" },
        { "id": "adj-02", "term_zh": "壞的", "term_target": "xấu", "pronunciation": ["/səw˧˥/"], "example": {"sentence": "Người xấu.", "translation": "壞人。"}, "usage_note": "負面。", "image_file": "bad.png" },
        { "id": "adj-03", "term_zh": "新的", "term_target": "mới", "pronunciation": ["/məːj˧˥/"], "example": {"sentence": "Điện thoại mới.", "translation": "新手機。"}, "usage_note": "全新。", "image_file": "new.png" },
        { "id": "adj-04", "term_zh": "大的", "term_target": "to / lớn", "pronunciation": ["/tɔ˧/  /ləːn˧˥/"], "example": {"sentence": "Nhà to.", "translation": "大房子。"}, "usage_note": "體積大。", "image_file": "big.png" },
        { "id": "adj-05", "term_zh": "小的", "term_target": "nhỏ", "pronunciation": ["/ɲɔ˧˩/"], "example": {"sentence": "Con mèo nhỏ.", "translation": "小貓。"}, "usage_note": "體積小。", "image_file": "small.png" },
        { "id": "adj-06", "term_zh": "熱的", "term_target": "nóng", "pronunciation": ["/nawŋ͡m˧˥/"], "example": {"sentence": "Trời nóng.", "translation": "天熱。"}, "usage_note": "高溫。", "image_file": "hot.png" },
        { "id": "adj-07", "term_zh": "冷的", "term_target": "lạnh", "pronunciation": ["/lajŋ̟˧˨ˀ/"], "example": {"sentence": "Hôm nay lạnh.", "translation": "今天好冷。"}, "usage_note": "發音像「冷」。", "image_file": "cold.png" },
        { "id": "adj-08", "term_zh": "簡單的", "term_target": "dễ", "pronunciation": ["/ze˧ˀ˥/"], "example": {"sentence": "Cái này dễ.", "translation": "這很簡單。"}, "usage_note": "容易。", "image_file": "easy.png" },
        { "id": "adj-09", "term_zh": "困難的", "term_target": "khó", "pronunciation": ["/xɔ˧˥/"], "example": {"sentence": "Tiếng Việt khó.", "translation": "越南語很難。"}, "usage_note": "難。", "image_file": "difficult.png" },
        { "id": "adj-10", "term_zh": "美味的", "term_target": "ngon", "pronunciation": ["/ŋɔn˧/"], "example": {"sentence": "Món ăn ngon.", "translation": "好吃的菜。"}, "usage_note": "好吃。", "image_file": "delicious.png" },
        { "id": "adj-11", "term_zh": "忙碌的", "term_target": "bận", "pronunciation": ["/ɓən˧˨ˀ/"], "example": {"sentence": "Tôi bận.", "translation": "我很忙。"}, "usage_note": "沒空。", "image_file": "busy.png" },
        { "id": "adj-12", "term_zh": "疲累的", "term_target": "mệt", "pronunciation": ["/met̚˧˨ˀ/"], "example": {"sentence": "Tôi mệt.", "translation": "我累了。"}, "usage_note": "狀態。", "image_file": "tired.png" },
        { "id": "adj-13", "term_zh": "快樂的/高興的", "term_target": "vui", "pronunciation": ["/vuj˧/"], "example": {"sentence": "Tôi rất vui.", "translation": "我很高興。"}, "usage_note": "心情。", "image_file": "happy.png" },
        { "id": "adj-14", "term_zh": "悲傷的", "term_target": "buồn", "pronunciation": ["/ɓuən˨˩/"], "example": {"sentence": "Chuyện buồn.", "translation": "悲傷的事。"}, "usage_note": "難過。", "image_file": "sad.png" },
        { "id": "adj-15", "term_zh": "乾淨的/漂亮的", "term_target": "sạch / đẹp", "pronunciation": ["/sac̚˧˨ˀ/  /ɗɛp̚˧˨ˀ/"], "example": {"sentence": "Phòng sạch.", "translation": "乾淨的房間。"}, "usage_note": "乾淨是 sạch，漂亮是 đẹp。", "image_file": "clean.png" },
        { "id": "adj-16", "term_zh": "髒的", "term_target": "bẩn", "pronunciation": ["/ɓən˧˩/"], "example": {"sentence": "Tay bẩn.", "translation": "手很髒。"}, "usage_note": "不乾淨。", "image_file": "dirty.png" },
        { "id": "adj-17", "term_zh": "便宜的", "term_target": "rẻ", "pronunciation": ["/zɛ˧˩/"], "example": {"sentence": "Cái này rẻ.", "translation": "這很便宜。"}, "usage_note": "價格低。", "image_file": "cheap.png" },
        { "id": "adj-18", "term_zh": "昂貴的", "term_target": "đắt", "pronunciation": ["/ɗat̚˧˥/"], "example": {"sentence": "Quá đắt.", "translation": "太貴了。"}, "usage_note": "價格高。", "image_file": "expensive.png" },
        { "id": "adj-19", "term_zh": "重要的", "term_target": "quan trọng", "pronunciation": ["/kwaːn˧ tɕawŋ͡m˧˨ˀ/"], "example": {"sentence": "Việc quan trọng.", "translation": "重要的事。"}, "usage_note": "發音像「關重」。", "image_file": "important.png" },
        { "id": "adj-20", "term_zh": "相同的", "term_target": "giống nhau", "pronunciation": ["/zoŋ˧˥ ɲaw˧/"], "example": {"sentence": "Giống nhau.", "translation": "一樣。"}, "usage_note": "相同。", "image_file": "same.png" },
        { "id": "adj-21", "term_zh": "第一的", "term_target": "đầu tiên / nhất", "pronunciation": ["/ɗəw˨˩ tiən˧/  /ɲət̚˧˥/"], "example": {"sentence": "Thích nhất.", "translation": "最喜歡。"}, "usage_note": "Nhất 發音像「一」，表示最...。", "image_file": "first.png" },
        { "id": "adj-22", "term_zh": "上一個", "term_target": "trước", "pronunciation": ["/tɕɨək̚˧˥/"], "example": {"sentence": "Ngày hôm trước.", "translation": "前一天。"}, "usage_note": "之前的。", "image_file": "last.png" },
        { "id": "adj-23", "term_zh": "下一個", "term_target": "sau / tiếp theo", "pronunciation": ["/saw˧/  /tiəp̚˧˥ tʰɛw˧/"], "example": {"sentence": "Trạm tiếp theo.", "translation": "下一站。"}, "usage_note": "接下來。", "image_file": "next.png" },
        { "id": "adj-24", "term_zh": "長的", "term_target": "dài", "pronunciation": ["/zaːj˨˩/"], "example": {"sentence": "Tóc dài.", "translation": "長髮。"}, "usage_note": "長度。", "image_file": "long.png" },
        { "id": "adj-25", "term_zh": "多的", "term_target": "nhiều", "pronunciation": ["/ɲiəw˨˩/"], "example": {"sentence": "Nhiều người.", "translation": "很多人。"}, "usage_note": "數量多。", "image_file": "many.png" },
        { "id": "adj-26", "term_zh": "高的", "term_target": "cao", "pronunciation": ["/kaːw˧/"], "example": {"sentence": "Người cao.", "translation": "高個子。"}, "usage_note": "發音像「高」。", "image_file": "tall.png" },
        { "id": "adj-27", "term_zh": "年輕的", "term_target": "trẻ", "pronunciation": ["/tɕɛ˧˩/"], "example": {"sentence": "Người trẻ.", "translation": "年輕人。"}, "usage_note": "年紀小。", "image_file": "young.png" },
        { "id": "adj-28", "term_zh": "老的/舊的", "term_target": "già / cũ", "pronunciation": ["/zaː˨˩/  /ku˧ˀ˥/"], "example": {"sentence": "Sách cũ.", "translation": "舊書。"}, "usage_note": "人老用 già，物品舊用 cũ（音似古）。", "image_file": "old.png" },
        { "id": "adj-29", "term_zh": "近的", "term_target": "gần", "pronunciation": ["/ɣən˨˩/"], "example": {"sentence": "Gần nhà.", "translation": "離家近。"}, "usage_note": "距離近。", "image_file": "near.png" },
        { "id": "adj-30", "term_zh": "遠的", "term_target": "xa", "pronunciation": ["/saː˧/"], "example": {"sentence": "Xa nhà.", "translation": "離家遠。"}, "usage_note": "距離遠。", "image_file": "far.png" },
        { "id": "adj-31", "term_zh": "快的", "term_target": "nhanh", "pronunciation": ["/ɲajŋ̟˧/"], "example": {"sentence": "Chạy nhanh.", "translation": "跑得快。"}, "usage_note": "速度快。", "image_file": "fast.png" },
        { "id": "adj-32", "term_zh": "慢的", "term_target": "chậm", "pronunciation": ["/tɕəm˧˨ˀ/"], "example": {"sentence": "Đi chậm.", "translation": "走得慢。"}, "usage_note": "速度慢。", "image_file": "slow.png" },
        { "id": "adj-33", "term_zh": "正確的", "term_target": "đúng", "pronunciation": ["/ɗuŋ͡m˧˥/"], "example": {"sentence": "Đúng rồi.", "translation": "對了。"}, "usage_note": "對的。", "image_file": "correct.png" },
        { "id": "adj-34", "term_zh": "錯誤的", "term_target": "sai", "pronunciation": ["/saːj˧/"], "example": {"sentence": "Cái này sai.", "translation": "這錯了。"}, "usage_note": "不對。", "image_file": "wrong.png" },
        { "id": "adj-35", "term_zh": "不同的", "term_target": "khác", "pronunciation": ["/xalːk̚˧˥/"], "example": {"sentence": "Màu khác.", "translation": "顏色不同。"}, "usage_note": "差異。", "image_file": "different.png" },
        { "id": "adj-36", "term_zh": "真的", "term_target": "thật", "pronunciation": ["/tʰət̚˧˨ˀ/"], "example": {"sentence": "Thật không?", "translation": "真的嗎？"}, "usage_note": "真實。", "image_file": "real.png" },
        { "id": "adj-37", "term_zh": "有趣的", "term_target": "thú vị", "pronunciation": ["/tʰu˧˥ vi˧˨ˀ/"], "example": {"sentence": "Phim thú vị.", "translation": "有趣的電影。"}, "usage_note": "發音像「趣味」。", "image_file": "interesting.png" },
        { "id": "adj-38", "term_zh": "飢餓的", "term_target": "đói", "pronunciation": ["/ɗɔj˧˥/"], "example": {"sentence": "Tôi đói.", "translation": "我餓了。"}, "usage_note": "餓。", "image_file": "hungry.png" },
        { "id": "adj-39", "term_zh": "有名的", "term_target": "nổi tiếng", "pronunciation": ["/noj˧˩ tiəŋ˧˥/"], "example": {"sentence": "Người nổi tiếng.", "translation": "有名的人。"}, "usage_note": "知名。", "image_file": "famous.png" },
        { "id": "adj-40", "term_zh": "外國的", "term_target": "nước ngoài", "pronunciation": ["/nɨək̚˧˥ ŋwaːj˨˩/"], "example": {"sentence": "Người nước ngoài.", "translation": "外國人。"}, "usage_note": "國外。", "image_file": "foreign.png" },
        { "id": "adj-41", "term_zh": "聰明的", "term_target": "thông minh", "pronunciation": ["/tʰoŋ͡m˧ miɲ˧/"], "example": {"sentence": "Anh ấy thông minh.", "translation": "他很聰明。"}, "usage_note": "發音像「聰明」。", "image_file": "intelligent.png" },
        { "id": "adj-42", "term_zh": "危險的", "term_target": "nguy hiểm", "pronunciation": ["/ŋwi˧ hiəm˧˩/"], "example": {"sentence": "Rất nguy hiểm.", "translation": "很危險。"}, "usage_note": "發音像「危險」。", "image_file": "dangerous.png" },
        { "id": "adj-43", "term_zh": "仁慈的", "term_target": "tốt bụng", "pronunciation": ["/tot̚˧˥ ɓuŋ͡m˧˨ˀ/"], "example": {"sentence": "Người tốt bụng.", "translation": "好心人。"}, "usage_note": "心腸好。", "image_file": "kind.png" },
        { "id": "adj-44", "term_zh": "所有的", "term_target": "tất cả", "pronunciation": ["/tət̚˧˥ kaː˧˩/"], "example": {"sentence": "Tất cả mọi người.", "translation": "所有人。"}, "usage_note": "全部。", "image_file": "every.png" },
        { "id": "adj-45", "term_zh": "喜愛的", "term_target": "yêu thích", "pronunciation": ["/iəw˧ tʰic̚˧˥/"], "example": {"sentence": "Món ăn yêu thích.", "translation": "喜愛的菜。"}, "usage_note": "中意。", "image_file": "favorite.png" }
      ]
    },
    {
      "id": "nouns",
      "name": "名詞",
      "items": [
        { "id": "n-01", "term_zh": "水", "term_target": "nước", "pronunciation": ["/nɨək̚˧˥/"], "example": {"sentence": "Uống nước.", "translation": "喝水。"}, "usage_note": "液體。", "image_file": "water.png" },
        { "id": "n-02", "term_zh": "食物", "term_target": "đồ ăn", "pronunciation": ["/ɗo˨˩ an˧/"], "example": {"sentence": "Đồ ăn ngon.", "translation": "好吃的食物。"}, "usage_note": "吃的東西。", "image_file": "food.png" },
        { "id": "n-03", "term_zh": "錢", "term_target": "tiền", "pronunciation": ["/tiən˨˩/"], "example": {"sentence": "Không có tiền.", "translation": "沒錢。"}, "usage_note": "錢。", "image_file": "money.png" },
        { "id": "n-04", "term_zh": "廁所", "term_target": "nhà vệ sinh", "pronunciation": ["/ɲaː˨˩ ve˧˨ˀ siɲ˧/"], "example": {"sentence": "Đi nhà vệ sinh.", "translation": "去廁所。"}, "usage_note": "衛生間。", "image_file": "bathroom.png" },
        { "id": "n-05", "term_zh": "人", "term_target": "người", "pronunciation": ["/ŋɨəj˨˩/"], "example": {"sentence": "Nhiều người.", "translation": "很多人。"}, "usage_note": "人類。", "image_file": "people.png" },
        { "id": "n-06", "term_zh": "時間", "term_target": "thời gian", "pronunciation": ["/tʰəːj˨˩ zaːn˧/"], "example": {"sentence": "Không có thời gian.", "translation": "沒時間。"}, "usage_note": "發音像「時間」。", "image_file": "time.png" },
        { "id": "n-07", "term_zh": "朋友", "term_target": "bạn", "pronunciation": ["/ɓaːn˧˨ˀ/"], "example": {"sentence": "Bạn của tôi.", "translation": "我朋友。"}, "usage_note": "友人。", "image_file": "friend.png" },
        { "id": "n-08", "term_zh": "家庭/家人", "term_target": "gia đình", "pronunciation": ["/zaː˧ ɗiɲ˨˩/"], "example": {"sentence": "Gia đình tôi.", "translation": "我家。"}, "usage_note": "發音像「家庭」。", "image_file": "family.png" },
        { "id": "n-09", "term_zh": "手機", "term_target": "điện thoại", "pronunciation": ["/ɗiən˧˨ˀ tʰwaːj˧˨ˀ/"], "example": {"sentence": "Điện thoại của tôi.", "translation": "我手機。"}, "usage_note": "發音像「電話」。", "image_file": "phone.png" },
        { "id": "n-10", "term_zh": "車", "term_target": "xe", "pronunciation": ["/sɛ˧/"], "example": {"sentence": "Lái xe.", "translation": "開車。"}, "usage_note": "發音像「車」。", "image_file": "car.png" },
        { "id": "n-11", "term_zh": "巴士", "term_target": "xe buýt", "pronunciation": ["/sɛ˧ ɓwit̚˧˥/"], "example": {"sentence": "Đi xe buýt.", "translation": "搭公車。"}, "usage_note": "公車。", "image_file": "bus.png" },
        { "id": "n-12", "term_zh": "火車", "term_target": "tàu hỏa", "pronunciation": ["/taːw˨˩ hwaː˧˩/"], "example": {"sentence": "Đi tàu hỏa.", "translation": "搭火車。"}, "usage_note": "列車。", "image_file": "train.png" },
        { "id": "n-13", "term_zh": "捷運/地鐵", "term_target": "tàu điện ngầm", "pronunciation": ["/taːw˨˩ ɗiən˧˨ˀ ŋəm˨˩/"], "example": {"sentence": "Ga tàu điện ngầm.", "translation": "地鐵站。"}, "usage_note": "地下鐵。", "image_file": "subway.png" },
        { "id": "n-14", "term_zh": "車站", "term_target": "ga", "pronunciation": ["/ɣaː˧/"], "example": {"sentence": "Ga ở đâu?", "translation": "車站在哪？"}, "usage_note": "站點。", "image_file": "station.png" },
        { "id": "n-15", "term_zh": "機場", "term_target": "sân bay", "pronunciation": ["/sən˧ ɓaj˧/"], "example": {"sentence": "Đi sân bay.", "translation": "去機場。"}, "usage_note": "搭飛機處。", "image_file": "airport.png" },
        { "id": "n-16", "term_zh": "票", "term_target": "vé", "pronunciation": ["/vɛ˧˥/"], "example": {"sentence": "Mua vé.", "translation": "買票。"}, "usage_note": "入場券或車票。", "image_file": "ticket.png" },
        { "id": "n-17", "term_zh": "飯店", "term_target": "khách sạn", "pronunciation": ["/xajc̚˧˥ saːn˧˨ˀ/"], "example": {"sentence": "Đặt khách sạn.", "translation": "訂飯店。"}, "usage_note": "發音像「客棧」。", "image_file": "hotel.png" },
        { "id": "n-18", "term_zh": "護照", "term_target": "hộ chiếu", "pronunciation": ["/ho˧˨ˀ tɕiəw˧˥/"], "example": {"sentence": "Xem hộ chiếu.", "translation": "看護照。"}, "usage_note": "發音像「護照」。", "image_file": "passport.png" },
        { "id": "n-19", "term_zh": "地圖", "term_target": "bản đồ", "pronunciation": ["/ɓaːn˧˩ ɗo˨˩/"], "example": {"sentence": "Xem bản đồ.", "translation": "看地圖。"}, "usage_note": "發音像「版圖」。", "image_file": "map.png" },
        { "id": "n-20", "term_zh": "警察", "term_target": "cảnh sát", "pronunciation": ["/kajŋ̟˧˩ saːt̚˧˥/"], "example": {"sentence": "Gọi cảnh sát.", "translation": "叫警察。"}, "usage_note": "發音像「警察」。", "image_file": "police.png" },
        { "id": "n-21", "term_zh": "台灣人", "term_target": "người Đài Loan", "pronunciation": ["/ŋɨəj˨˩ ɗaːj˨˩ lwaːn˧/"], "example": {"sentence": "Tôi là người Đài Loan.", "translation": "我是台灣人。"}, "usage_note": "國籍。", "image_file": "taiwanese.png" },
        { "id": "n-22", "term_zh": "孩子", "term_target": "trẻ em", "pronunciation": ["/tɕɛ˧˩ ɛm˧/"], "example": {"sentence": "Có trẻ em.", "translation": "有孩子。"}, "usage_note": "兒童。", "image_file": "child.png" },
        { "id": "n-23", "term_zh": "學生", "term_target": "học sinh", "pronunciation": ["/hawk͡p̚˧˨ˀ siɲ˧/"], "example": {"sentence": "Tôi là học sinh.", "translation": "我是學生。"}, "usage_note": "發音像「學生」。", "image_file": "student.png" },
        { "id": "n-24", "term_zh": "文化", "term_target": "văn hóa", "pronunciation": ["/van˧ hwaː˧˥/"], "example": {"sentence": "Văn hóa Việt Nam.", "translation": "越南文化。"}, "usage_note": "發音像「文化」。", "image_file": "culture.png" },
        { "id": "n-25", "term_zh": "問題", "term_target": "vấn đề", "pronunciation": ["/vən˧˥ ɗe˨˩/"], "example": {"sentence": "Không có vấn đề.", "translation": "沒問題。"}, "usage_note": "發音像「問題」。", "image_file": "problem.png" },
        { "id": "n-26", "term_zh": "公司", "term_target": "công ty", "pronunciation": ["/koŋ͡m˧ ti˧/"], "example": {"sentence": "Đi công ty.", "translation": "去公司。"}, "usage_note": "發音像「公司」。", "image_file": "company.png" },
        { "id": "n-27", "term_zh": "男性", "term_target": "nam", "pronunciation": ["/naːm˧/"], "example": {"sentence": "Nhà vệ sinh nam.", "translation": "男廁。"}, "usage_note": "發音像「男」。", "image_file": "man.png" },
        { "id": "n-28", "term_zh": "女性", "term_target": "nữ", "pronunciation": ["/nɨ˧ˀ˥/"], "example": {"sentence": "Nhà vệ sinh nữ.", "translation": "女廁。"}, "usage_note": "發音像「女」。", "image_file": "woman.png" },
        { "id": "n-29", "term_zh": "學校", "term_target": "trường học", "pronunciation": ["/tɕɨəŋ˨˩ hawk͡p̚˧˨ˀ/"], "example": {"sentence": "Đi trường học.", "translation": "去學校。"}, "usage_note": "教育機構。", "image_file": "school.png" },
        { "id": "n-30", "term_zh": "老師", "term_target": "giáo viên", "pronunciation": ["/zaːw˧˥ viən˧/"], "example": {"sentence": "Chào giáo viên.", "translation": "老師好。"}, "usage_note": "發音像「教員」。", "image_file": "teacher.png" },
        { "id": "n-31", "term_zh": "電影", "term_target": "phim", "pronunciation": ["/fiːm˧/"], "example": {"sentence": "Xem phim.", "translation": "看電影。"}, "usage_note": "影片。", "image_file": "movie.png" },
        { "id": "n-32", "term_zh": "電腦", "term_target": "máy tính", "pronunciation": ["/maːj˧˥ tiŋ˧˥/"], "example": {"sentence": "Dùng máy tính.", "translation": "用電腦。"}, "usage_note": "計算機。", "image_file": "computer.png" },
        { "id": "n-33", "term_zh": "市場", "term_target": "chợ", "pronunciation": ["/tɕə˧˨ˀ/"], "example": {"sentence": "Đi chợ.", "translation": "去市場。"}, "usage_note": "市集。", "image_file": "market.png" },
        { "id": "n-34", "term_zh": "衣服", "term_target": "quần áo", "pronunciation": ["/kwən˨˩ aːw˧˥/"], "example": {"sentence": "Mua quần áo.", "translation": "買衣服。"}, "usage_note": "衣物。", "image_file": "clothes.png" },
        { "id": "n-35", "term_zh": "商店", "term_target": "cửa hàng", "pronunciation": ["/kɨə˧˩ haːŋ˨˩/"], "example": {"sentence": "Vào cửa hàng.", "translation": "進店裡。"}, "usage_note": "店家。", "image_file": "shop.png" },
        { "id": "n-36", "term_zh": "街道", "term_target": "đường", "pronunciation": ["/ɗɨəŋ˨˩/"], "example": {"sentence": "Đường này.", "translation": "這條路。"}, "usage_note": "道路。", "image_file": "street.png" },
        { "id": "n-37", "term_zh": "房子", "term_target": "nhà", "pronunciation": ["/ɲaː˨˩/"], "example": {"sentence": "Nhà to.", "translation": "大房子。"}, "usage_note": "住宅。", "image_file": "house.png" },
        { "id": "n-38", "term_zh": "母親", "term_target": "mẹ", "pronunciation": ["/mɛ˧˨ˀ/"], "example": {"sentence": "Mẹ của tôi.", "translation": "我媽媽。"}, "usage_note": "媽媽。", "image_file": "mother.png" },
        { "id": "n-39", "term_zh": "父親", "term_target": "bố", "pronunciation": ["/ɓo˧˥/"], "example": {"sentence": "Bố của tôi.", "translation": "我爸爸。"}, "usage_note": "爸爸。", "image_file": "father.png" },
        { "id": "n-40", "term_zh": "中文", "term_target": "tiếng Trung", "pronunciation": ["/tiəŋ˧˥ tɕuŋ͡m˧/"], "example": {"sentence": "Nói tiếng Trung.", "translation": "說中文。"}, "usage_note": "語言。", "image_file": "chinese.png" },
        { "id": "n-41", "term_zh": "包包", "term_target": "túi", "pronunciation": ["/tuj˧˥/"], "example": {"sentence": "Cầm túi.", "translation": "拿包包。"}, "usage_note": "提包。", "image_file": "bag.png" },
        { "id": "n-42", "term_zh": "杯子", "term_target": "cốc", "pronunciation": ["/kəwk͡p̚˧˥/"], "example": {"sentence": "Cốc nước.", "translation": "一杯水。"}, "usage_note": "杯具。", "image_file": "cup.png" },
        { "id": "n-43", "term_zh": "醫生", "term_target": "bác sĩ", "pronunciation": ["/ɓaːk̚˧˥ si˧ˀ˥/"], "example": {"sentence": "Gặp bác sĩ.", "translation": "看醫生。"}, "usage_note": "醫師。", "image_file": "doctor.png" },
        { "id": "n-44", "term_zh": "醫院", "term_target": "bệnh viện", "pronunciation": ["/ɓejŋ̟˧˨ˀ viən˧˨ˀ/"], "example": {"sentence": "Đi bệnh viện.", "translation": "去醫院。"}, "usage_note": "發音像「病院」。", "image_file": "hospital.png" },
        { "id": "n-45", "term_zh": "座位", "term_target": "chỗ ngồi", "pronunciation": ["/tɕo˧ˀ˥ ŋoj˨˩/"], "example": {"sentence": "Có chỗ ngồi không?", "translation": "有位子嗎？"}, "usage_note": "位子。", "image_file": "seat.png" },
        { "id": "n-46", "term_zh": "門", "term_target": "cửa", "pronunciation": ["/kɨə˧˩/"], "example": {"sentence": "Mở cửa.", "translation": "開門。"}, "usage_note": "門戶。", "image_file": "door.png" },
        { "id": "n-47", "term_zh": "房間", "term_target": "phòng", "pronunciation": ["/fawŋ͡m˨˩/"], "example": {"sentence": "Phòng của tôi.", "translation": "我房間。"}, "usage_note": "發音像「房」。", "image_file": "room.png" },
        { "id": "n-48", "term_zh": "行李", "term_target": "hành lý", "pronunciation": ["/haɲ˨˩ li˧˥/"], "example": {"sentence": "Nhiều hành lý.", "translation": "行李很多。"}, "usage_note": "發音像「行李」。", "image_file": "luggage.png" },
        { "id": "n-49", "term_zh": "櫃檯", "term_target": "quầy", "pronunciation": ["/kwəj˨˩/"], "example": {"sentence": "Thanh toán tại quầy.", "translation": "櫃檯結帳。"}, "usage_note": "服務台。", "image_file": "counter.png" },
        { "id": "n-50", "term_zh": "大廳", "term_target": "sảnh", "pronunciation": ["/sajŋ̟˧˩/"], "example": {"sentence": "Đợi ở sảnh.", "translation": "大廳等。"}, "usage_note": "接待處。", "image_file": "lobby.png" },
        { "id": "n-51", "term_zh": "預定", "term_target": "đặt trước", "pronunciation": ["/ɗat̚˧˨ˀ tɕɨək̚˧˥/"], "example": {"sentence": "Tôi đã đặt trước.", "translation": "我預約了。"}, "usage_note": "預約。", "image_file": "reservation.png" },
        { "id": "n-52", "term_zh": "入住", "term_target": "nhận phòng", "pronunciation": ["/ɲən˧˨ˀ fawŋ͡m˨˩/"], "example": {"sentence": "Tôi muốn nhận phòng.", "translation": "我要辦理入住。"}, "usage_note": "Check-in。", "image_file": "check_in.png" },
        { "id": "n-53", "term_zh": "退房", "term_target": "trả phòng", "pronunciation": ["/tɕaː˧˩ fawŋ͡m˨˩/"], "example": {"sentence": "Mấy giờ trả phòng?", "translation": "退房是幾點？"}, "usage_note": "Check-out。", "image_file": "check_out.png" },
        { "id": "n-54", "term_zh": "飲料", "term_target": "đồ uống", "pronunciation": ["/ɗo˨˩ uəŋ˧˥/"], "example": {"sentence": "Đồ uống gì?", "translation": "什麼飲料？"}, "usage_note": "飲品。", "image_file": "drink.png" },
        { "id": "n-55", "term_zh": "菜單", "term_target": "thực đơn", "pronunciation": ["/tʰɨk̚˧˨ˀ ɗəːn˧/"], "example": {"sentence": "Cho tôi thực đơn.", "translation": "請給菜單。"}, "usage_note": "Menu。", "image_file": "menu.png" },
        { "id": "n-56", "term_zh": "午餐", "term_target": "bữa trưa", "pronunciation": ["/ɓɨə˧ˀ˥ tɕɨə˧/"], "example": {"sentence": "Ăn bữa trưa.", "translation": "吃午餐。"}, "usage_note": "中餐。", "image_file": "lunch.png" },
        { "id": "n-57", "term_zh": "晚餐", "term_target": "bữa tối", "pronunciation": ["/ɓɨə˧ˀ˥ toj˧˥/"], "example": {"sentence": "Ăn bữa tối.", "translation": "吃晚餐。"}, "usage_note": "晚餐。", "image_file": "dinner.png" },
        { "id": "n-58", "term_zh": "帳單", "term_target": "hóa đơn", "pronunciation": ["/hwaː˧˥ ɗəːn˧/"], "example": {"sentence": "Cho tôi hóa đơn.", "translation": "麻煩結帳。"}, "usage_note": "發音像「化單」。", "image_file": "bill.png" },
        { "id": "n-59", "term_zh": "價錢", "term_target": "giá", "pronunciation": ["/zaː˧˥/"], "example": {"sentence": "Giá cao.", "translation": "價錢高。"}, "usage_note": "發音像「價」。", "image_file": "price.png" },
        { "id": "n-60", "term_zh": "收據", "term_target": "biên lai", "pronunciation": ["/ɓiən˧ laːj˧/"], "example": {"sentence": "Cho tôi biên lai.", "translation": "請給收據。"}, "usage_note": "統一發票。", "image_file": "receipt.png" },
        { "id": "n-61", "term_zh": "尺寸", "term_target": "cỡ", "pronunciation": ["/kəː˧ˀ˥/"], "example": {"sentence": "Không đúng cỡ.", "translation": "尺寸不合。"}, "usage_note": "大小。", "image_file": "size.png" },
        { "id": "n-62", "term_zh": "入口", "term_target": "lối vào", "pronunciation": ["/loj˧˥ vaːw˨˩/"], "example": {"sentence": "Lối vào ở đâu?", "translation": "入口在哪？"}, "usage_note": "進去的地方。", "image_file": "entrance.png" },
        { "id": "n-63", "term_zh": "出口", "term_target": "lối ra", "pronunciation": ["/loj˧˥ zaː˧/"], "example": {"sentence": "Lối ra ở kia.", "translation": "出口在那。"}, "usage_note": "出去的地方。", "image_file": "exit.png" },
        { "id": "n-64", "term_zh": "台灣", "term_target": "Đài Loan", "pronunciation": ["/ɗaːj˨˩ lwaːn˧/"], "example": {"sentence": "Đến từ Đài Loan.", "translation": "來自台灣。"}, "usage_note": "發音像「台灣」。", "image_file": "taiwan.png" },
        { "id": "n-65", "term_zh": "一切事物", "term_target": "tất cả", "pronunciation": ["/tət̚˧˥ kaː˧˩/"], "example": {"sentence": "Thích tất cả.", "translation": "全部喜歡。"}, "usage_note": "所有。", "image_file": "everything.png" },
        { "id": "n-66", "term_zh": "錢包", "term_target": "ví", "pronunciation": ["/vi˧˥/"], "example": {"sentence": "Quên ví.", "translation": "忘了錢包。"}, "usage_note": "皮夾。", "image_file": "wallet.png" },
        { "id": "n-67", "term_zh": "身分證", "term_target": "chứng minh thư", "pronunciation": ["/tɕɨŋ˧˥ miɲ˧ tʰɨ˧/"], "example": {"sentence": "Xem chứng minh thư.", "translation": "出示證件。"}, "usage_note": "發音像「證明書」。", "image_file": "id.png" },
        { "id": "n-68", "term_zh": "餐廳", "term_target": "nhà hàng", "pronunciation": ["/ɲaː˨˩ haːŋ˨˩/"], "example": {"sentence": "Nhà hàng ngon.", "translation": "好的餐廳。"}, "usage_note": "食堂。", "image_file": "restaurant.png" },
        { "id": "n-69", "term_zh": "場所", "term_target": "địa điểm", "pronunciation": ["/ɗiə˧˨ˀ ɗiəm˧˩/"], "example": {"sentence": "Địa điểm ở đâu?", "translation": "地點在哪？"}, "usage_note": "發音像「地點」。", "image_file": "place.png" },
        { "id": "n-70", "term_zh": "店員", "term_target": "nhân viên", "pronunciation": ["/ɲən˧ viən˧/"], "example": {"sentence": "Gọi nhân viên.", "translation": "叫店員。"}, "usage_note": "發音像「人員」。", "image_file": "clerk.png" },
        { "id": "n-71", "term_zh": "超市", "term_target": "siêu thị", "pronunciation": ["/siəw˧ tʰi˧˨ˀ/"], "example": {"sentence": "Mua ở siêu thị.", "translation": "在超市買。"}, "usage_note": "發音像「超市」。", "image_file": "supermarket.png" },
        { "id": "n-72", "term_zh": "月台", "term_target": "sân ga", "pronunciation": ["/sən˧ ɣaː˧/"], "example": {"sentence": "Đợi ở sân ga.", "translation": "在月台等。"}, "usage_note": "車站月台。", "image_file": "platform.png" }
      ]
    },
    {
      "id": "adverbs",
      "name": "副詞",
      "items": [
        { "id": "adv-01", "term_zh": "現在", "term_target": "bây giờ", "pronunciation": ["/ɓəj˧ zəː˨˩/"], "example": {"sentence": "Bây giờ đi.", "translation": "現在去。"}, "usage_note": "目前。", "image_file": "now.png" },
        { "id": "adv-02", "term_zh": "非常", "term_target": "rất", "pronunciation": ["/zət̚˧˥/"], "example": {"sentence": "Rất ngon.", "translation": "非常好吃。"}, "usage_note": "強調。", "image_file": "very.png" },
        { "id": "adv-03", "term_zh": "真的", "term_target": "thật sự", "pronunciation": ["/tʰət̚˧˨ˀ sɨ˧˨ˀ/"], "example": {"sentence": "Thật sự à?", "translation": "真的嗎？"}, "usage_note": "確認或強調。", "image_file": "really.png" },
        { "id": "adv-04", "term_zh": "經常", "term_target": "thường", "pronunciation": ["/tʰɨəŋ˨˩/"], "example": {"sentence": "Thường đến.", "translation": "常來。"}, "usage_note": "發音像「常」。", "image_file": "often.png" },
        { "id": "adv-05", "term_zh": "通常", "term_target": "thường thường", "pronunciation": ["/tʰɨəŋ˨˩ tʰɨəŋ˨˩/"], "example": {"sentence": "Thường thường là vậy.", "translation": "通常是那樣。"}, "usage_note": "習慣。", "image_file": "usually.png" },
        { "id": "adv-06", "term_zh": "只有", "term_target": "chỉ", "pronunciation": ["/tɕi˧˩/"], "example": {"sentence": "Chỉ có cái này.", "translation": "只有這個。"}, "usage_note": "發音像「只」。", "image_file": "only.png" },
        { "id": "adv-07", "term_zh": "再次", "term_target": "lại", "pronunciation": ["/laːj˧˨ˀ/"], "example": {"sentence": "Lại đến.", "translation": "會再來。"}, "usage_note": "重複。", "image_file": "again.png" },
        { "id": "adv-08", "term_zh": "一起", "term_target": "cùng nhau", "pronunciation": ["/kuŋ˨˩ ɲaw˧/"], "example": {"sentence": "Đi cùng nhau.", "translation": "一起去吧。"}, "usage_note": "共同。", "image_file": "together.png" },
        { "id": "adv-09", "term_zh": "或許", "term_target": "có lẽ", "pronunciation": ["/kɔ˧˥ lɛ˧ˀ˥/"], "example": {"sentence": "Có lẽ được.", "translation": "大概沒問題。"}, "usage_note": "不確定。", "image_file": "maybe.png" },
        { "id": "adv-10", "term_zh": "很快", "term_target": "sớm", "pronunciation": ["/səːm˧˥/"], "example": {"sentence": "Gặp lại sớm.", "translation": "待會見。"}, "usage_note": "不久後。", "image_file": "soon.png" },
        { "id": "adv-11", "term_zh": "已經", "term_target": "đã", "pronunciation": ["/ɗaː˧ˀ˥/"], "example": {"sentence": "Đã ăn rồi.", "translation": "已經吃了。"}, "usage_note": "完成。", "image_file": "already.png" },
        { "id": "adv-12", "term_zh": "大約", "term_target": "khoảng", "pronunciation": ["/xwaːŋ˧˩/"], "example": {"sentence": "Khoảng 10 phút.", "translation": "大約10分鐘。"}, "usage_note": "概數。", "image_file": "about.png" },
        { "id": "adv-13", "term_zh": "一點點", "term_target": "một chút", "pronunciation": ["/mot̚˧˨ˀ tɕut̚˧˥/"], "example": {"sentence": "Cay một chút.", "translation": "一點點辣。"}, "usage_note": "少量。", "image_file": "a_little.png" },
        { "id": "adv-14", "term_zh": "之後", "term_target": "sau", "pronunciation": ["/saw˧/"], "example": {"sentence": "Làm sau.", "translation": "之後做。"}, "usage_note": "稍後。", "image_file": "later.png" },
        { "id": "adv-15", "term_zh": "仍然", "term_target": "vẫn", "pronunciation": ["/vən˧ˀ˥/"], "example": {"sentence": "Vẫn chưa.", "translation": "還沒。"}, "usage_note": "持續。", "image_file": "still.png" },
        { "id": "adv-16", "term_zh": "一般來說", "term_target": "thông thường", "pronunciation": ["/tʰoŋ͡m˧ tʰɨəŋ˨˩/"], "example": {"sentence": "Thông thường là vậy.", "translation": "一般是那樣。"}, "usage_note": "發音像「通常」。", "image_file": "normally.png" }
      ]
    },
    {
      "id": "questions",
      "name": "疑問詞",
      "items": [
        { "id": "q-01", "term_zh": "什麼", "term_target": "cái gì", "pronunciation": ["/kaːj˧˥ zi˨˩/"], "example": {"sentence": "Đây là cái gì?", "translation": "這是什麼？"}, "usage_note": "問事物。", "image_file": "what.png" },
        { "id": "q-02", "term_zh": "哪裡", "term_target": "ở đâu", "pronunciation": ["/əː˧˩ ɗəw˧/"], "example": {"sentence": "Bạn ở đâu?", "translation": "你在哪裡？"}, "usage_note": "問地點。", "image_file": "where.png" },
        { "id": "q-03", "term_zh": "何時", "term_target": "khi nào", "pronunciation": ["/xi˧ naːw˨˩/"], "example": {"sentence": "Khi nào đi?", "translation": "何時去？"}, "usage_note": "問時間。", "image_file": "when.png" },
        { "id": "q-04", "term_zh": "誰", "term_target": "ai", "pronunciation": ["/aːj˧/"], "example": {"sentence": "Kia là ai?", "translation": "那是誰？"}, "usage_note": "問人。", "image_file": "who.png" },
        { "id": "q-05", "term_zh": "為什麼", "term_target": "tại sao", "pronunciation": ["/taːj˧˨ˀ saːw˧/"], "example": {"sentence": "Tại sao?", "translation": "為什麼？"}, "usage_note": "問原因。", "image_file": "why.png" },
        { "id": "q-06", "term_zh": "如何", "term_target": "như thế nào", "pronunciation": ["/ɲɨ˧ tʰe˧˥ naːw˨˩/"], "example": {"sentence": "Đi như thế nào?", "translation": "怎麼去？"}, "usage_note": "問方法。", "image_file": "how.png" },
        { "id": "q-07", "term_zh": "多少(錢)", "term_target": "bao nhiêu", "pronunciation": ["/ɓaːw˧ ɲiəw˧/"], "example": {"sentence": "Bao nhiêu tiền?", "translation": "多少錢？"}, "usage_note": "問價格。", "image_file": "how_much.png" },
        { "id": "q-08", "term_zh": "多久/多少(量)", "term_target": "bao lâu", "pronunciation": ["/ɓaːw˧ ləw˧/"], "example": {"sentence": "Mất bao lâu?", "translation": "要花多久？"}, "usage_note": "問時間長度。", "image_file": "how_long.png" },
        { "id": "q-09", "term_zh": "哪一個", "term_target": "cái nào", "pronunciation": ["/kaːj˧˥ naːw˨˩/"], "example": {"sentence": "Cái nào?", "translation": "哪一個？"}, "usage_note": "選擇。", "image_file": "which.png" }
      ]
    },
    {
      "id": "time_place",
      "name": "時間與場所",
      "items": [
        { "id": "tp-01", "term_zh": "今天", "term_target": "hôm nay", "pronunciation": ["/hom˧ naj˧/"], "example": {"sentence": "Hôm nay trời nóng.", "translation": "今天很熱。"}, "usage_note": "本日。", "image_file": "today.png" },
        { "id": "tp-02", "term_zh": "明天", "term_target": "ngày mai", "pronunciation": ["/ŋaːj˨˩ maːj˧/"], "example": {"sentence": "Hẹn ngày mai.", "translation": "明天見。"}, "usage_note": "隔天。", "image_file": "tomorrow.png" },
        { "id": "tp-03", "term_zh": "昨天", "term_target": "hôm qua", "pronunciation": ["/hom˧ kwaː˧/"], "example": {"sentence": "Hôm qua vui.", "translation": "昨天很開心。"}, "usage_note": "前一天。", "image_file": "yesterday.png" },
        { "id": "tp-04", "term_zh": "這裡", "term_target": "ở đây", "pronunciation": ["/əː˧˩ ɗəj˧/"], "example": {"sentence": "Đến ở đây.", "translation": "請來這裡。"}, "usage_note": "近處。", "image_file": "here.png" },
        { "id": "tp-05", "term_zh": "那裡", "term_target": "ở đó", "pronunciation": ["/əː˧˩ ɗɔ˧˥/"], "example": {"sentence": "Đi đến ở đó.", "translation": "去那裡。"}, "usage_note": "遠處。", "image_file": "there.png" },
        { "id": "tp-06", "term_zh": "早上", "term_target": "buổi sáng", "pronunciation": ["/ɓuəj˧˩ saːŋ˧˥/"], "example": {"sentence": "Ăn sáng.", "translation": "早餐。"}, "usage_note": "上午。", "image_file": "morning.png" },
        { "id": "tp-07", "term_zh": "晚上/夜晚", "term_target": "buổi tối", "pronunciation": ["/ɓuəj˧˩ toj˧˥/"], "example": {"sentence": "Ăn tối.", "translation": "晚餐。"}, "usage_note": "太陽下山後。", "image_file": "night.png" },
        { "id": "tp-08", "term_zh": "前面", "term_target": "phía trước", "pronunciation": ["/fiə˧˥ tɕɨək̚˧˥/"], "example": {"sentence": "Phía trước nhà ga.", "translation": "車站前。"}, "usage_note": "前方。", "image_file": "front.png" },
        { "id": "tp-09", "term_zh": "後面", "term_target": "phía sau", "pronunciation": ["/fiə˧˥ saw˧/"], "example": {"sentence": "Phía sau cửa.", "translation": "門後。"}, "usage_note": "後方。", "image_file": "behind.png" },
        { "id": "tp-10", "term_zh": "左邊", "term_target": "bên trái", "pronunciation": ["/ɓen˧ tɕaːj˧˥/"], "example": {"sentence": "Rẽ trái.", "translation": "左轉。"}, "usage_note": "左。", "image_file": "left.png" },
        { "id": "tp-11", "term_zh": "右邊", "term_target": "bên phải", "pronunciation": ["/ɓen˧ faːj˧˩/"], "example": {"sentence": "Nhìn bên phải.", "translation": "請看右邊。"}, "usage_note": "右。", "image_file": "right.png" },
        { "id": "tp-12", "term_zh": "天(日)", "term_target": "ngày", "pronunciation": ["/ŋaːj˨˩/"], "example": {"sentence": "Một ngày.", "translation": "某一天。"}, "usage_note": "日子。", "image_file": "day.png" },
        { "id": "tp-13", "term_zh": "年", "term_target": "năm", "pronunciation": ["/nam˧/"], "example": {"sentence": "Năm nay.", "translation": "今年。"}, "usage_note": "年度。", "image_file": "year.png" },
        { "id": "tp-14", "term_zh": "月", "term_target": "tháng", "pronunciation": ["/tʰaːŋ˧˥/"], "example": {"sentence": "Tháng này.", "translation": "這個月。"}, "usage_note": "月份。", "image_file": "month.png" },
        { "id": "tp-15", "term_zh": "週", "term_target": "tuần", "pronunciation": ["/twən˨˩/"], "example": {"sentence": "Tuần sau.", "translation": "下週。"}, "usage_note": "星期。", "image_file": "week.png" },
        { "id": "tp-16", "term_zh": "下午", "term_target": "buổi chiều", "pronunciation": ["/ɓuəj˧˩ tɕiəw˨˩/"], "example": {"sentence": "2 giờ chiều.", "translation": "下午2點。"}, "usage_note": "PM。", "image_file": "afternoon.png" },
        { "id": "tp-17", "term_zh": "中午", "term_target": "buổi trưa", "pronunciation": ["/ɓuəj˧˩ tɕɨə˧/"], "example": {"sentence": "Là buổi trưa.", "translation": "是中午。"}, "usage_note": "12點。", "image_file": "noon.png" },
        { "id": "tp-18", "term_zh": "旁邊", "term_target": "bên cạnh", "pronunciation": ["/ɓen˧ kaɲ˧˨ˀ/"], "example": {"sentence": "Bên cạnh tôi.", "translation": "我旁邊。"}, "usage_note": "側邊。", "image_file": "beside.png" },
        { "id": "tp-19", "term_zh": "對面", "term_target": "đối diện", "pronunciation": ["/ɗoj˧˥ ziən˧˨ˀ/"], "example": {"sentence": "Đối diện nhà ga.", "translation": "車站對面。"}, "usage_note": "發音像「對面」。", "image_file": "across_from.png" },
        { "id": "tp-20", "term_zh": "春天", "term_target": "mùa xuân", "pronunciation": ["/muə˨˩ swən˧/"], "example": {"sentence": "Mùa xuân đến.", "translation": "春天來了。"}, "usage_note": "季節。", "image_file": "spring.png" },
        { "id": "tp-21", "term_zh": "夏天", "term_target": "mùa hè", "pronunciation": ["/muə˨˩ hɛ˨˩/"], "example": {"sentence": "Mùa hè nóng.", "translation": "炎熱的夏天。"}, "usage_note": "季節。", "image_file": "summer.png" },
        { "id": "tp-22", "term_zh": "秋天", "term_target": "mùa thu", "pronunciation": ["/muə˨˩ tʰu˧/"], "example": {"sentence": "Thích mùa thu.", "translation": "喜歡秋天。"}, "usage_note": "季節。", "image_file": "autumn.png" },
        { "id": "tp-23", "term_zh": "冬天", "term_target": "mùa đông", "pronunciation": ["/muə˨˩ ɗəwŋ͡m˧/"], "example": {"sentence": "Mùa đông lạnh.", "translation": "冬天很冷。"}, "usage_note": "季節。", "image_file": "winter.png" }
      ]
    },
    {
      "id": "numbers",
      "name": "數字",
      "items": [
        { "id": "num-0", "term_zh": "0", "term_target": "không", "pronunciation": ["/xoŋ͡m˧/"], "example": {"sentence": "Số không.", "translation": "是零。"}, "usage_note": "零。", "image_file": "zero.png" },
        { "id": "num-1", "term_zh": "1", "term_target": "một", "pronunciation": ["/mot̚˧˨ˀ/"], "example": {"sentence": "Cho tôi một cái.", "translation": "請給我一個。"}, "usage_note": "一。", "image_file": "one.png" },
        { "id": "num-2", "term_zh": "2", "term_target": "hai", "pronunciation": ["/haːj˧/"], "example": {"sentence": "Hai cái.", "translation": "兩個。"}, "usage_note": "二。", "image_file": "two.png" },
        { "id": "num-3", "term_zh": "3", "term_target": "ba", "pronunciation": ["/ɓaː˧/"], "example": {"sentence": "Ba người.", "translation": "三個人。"}, "usage_note": "三。", "image_file": "three.png" },
        { "id": "num-4", "term_zh": "4", "term_target": "bốn", "pronunciation": ["/ɓon˧˥/"], "example": {"sentence": "Bốn giờ.", "translation": "四點。"}, "usage_note": "四。", "image_file": "four.png" },
        { "id": "num-5", "term_zh": "5", "term_target": "năm", "pronunciation": ["/nam˧/"], "example": {"sentence": "Năm cái.", "translation": "五個。"}, "usage_note": "五。", "image_file": "five.png" },
        { "id": "num-6", "term_zh": "6", "term_target": "sáu", "pronunciation": ["/saw˧˥/"], "example": {"sentence": "Sáu cái.", "translation": "六個。"}, "usage_note": "六。", "image_file": "six.png" },
        { "id": "num-7", "term_zh": "7", "term_target": "bảy", "pronunciation": ["/ɓəj˧˩/"], "example": {"sentence": "Bảy giờ.", "translation": "七點。"}, "usage_note": "七。", "image_file": "seven.png" },
        { "id": "num-8", "term_zh": "8", "term_target": "tám", "pronunciation": ["/taːm˧˥/"], "example": {"sentence": "Tám cái.", "translation": "八個。"}, "usage_note": "八。", "image_file": "eight.png" },
        { "id": "num-9", "term_zh": "9", "term_target": "chín", "pronunciation": ["/tɕiːn˧˥/"], "example": {"sentence": "Chín giờ.", "translation": "九點。"}, "usage_note": "九。", "image_file": "nine.png" },
        { "id": "num-10", "term_zh": "10", "term_target": "mười", "pronunciation": ["/mɨəj˨˩/"], "example": {"sentence": "Mười cái.", "translation": "十個。"}, "usage_note": "十。", "image_file": "ten.png" },
        { "id": "num-11", "term_zh": "11", "term_target": "mười một", "pronunciation": ["/mɨəj˨˩ mot̚˧˨ˀ/"], "example": {"sentence": "11 giờ.", "translation": "11點。"}, "usage_note": "十一。", "image_file": "eleven.png" },
        { "id": "num-12", "term_zh": "12", "term_target": "mười hai", "pronunciation": ["/mɨəj˨˩ haːj˧/"], "example": {"sentence": "Tháng 12.", "translation": "12月。"}, "usage_note": "十二。", "image_file": "twelve.png" },
        { "id": "num-15", "term_zh": "15", "term_target": "mười lăm", "pronunciation": ["/mɨəj˨˩ lam˧/"], "example": {"sentence": "15 phút.", "translation": "15分。"}, "usage_note": "十五。", "image_file": "fifteen.png" },
        { "id": "num-20", "term_zh": "20", "term_target": "hai mươi", "pronunciation": ["/haːj˧ mɨəj˧/"], "example": {"sentence": "Hai mươi nghìn.", "translation": "兩萬。"}, "usage_note": "二十。", "image_file": "twenty.png" },
        { "id": "num-50", "term_zh": "50", "term_target": "năm mươi", "pronunciation": ["/nam˧ mɨəj˧/"], "example": {"sentence": "Năm mươi người.", "translation": "五十人。"}, "usage_note": "五十。", "image_file": "fifty.png" },
        { "id": "num-100", "term_zh": "100", "term_target": "một trăm", "pronunciation": ["/mot̚˧˨ˀ tɕam˧/"], "example": {"sentence": "Một trăm nghìn.", "translation": "十萬(越盾)。"}, "usage_note": "百。", "image_file": "hundred.png" },
        { "id": "num-1000", "term_zh": "1000", "term_target": "một nghìn", "pronunciation": ["/mot̚˧˨ˀ ŋiːn˨˩/"], "example": {"sentence": "Một nghìn đồng.", "translation": "一千元。"}, "usage_note": "千。", "image_file": "thousand.png" },
        { "id": "num-10000", "term_zh": "10000", "term_target": "mười nghìn", "pronunciation": ["/mɨəj˨˩ ŋiːn˨˩/"], "example": {"sentence": "Mười nghìn đồng.", "translation": "一萬元。"}, "usage_note": "一萬。", "image_file": "ten_thousand.png" }
      ]
    },
    {
      "id": "grammar",
      "name": "基本句型",
      "items": [
        { "id": "g-01", "term_zh": "我是...", "term_target": "Tôi là...", "pronunciation": ["/toj˧ laː˨˩/"], "example": {"sentence": "Tôi là học sinh.", "translation": "我是學生。"}, "usage_note": "最基本的肯定句。", "image_file": "i_am.png" },
        { "id": "g-02", "term_zh": "我正在...", "term_target": "Tôi đang...", "pronunciation": ["/toj˧ ɗaːŋ˧/"], "example": {"sentence": "Tôi đang ăn.", "translation": "我正在吃。"}, "usage_note": "進行式。", "image_file": "ing.png" },
        { "id": "g-03", "term_zh": "我能夠(會)...", "term_target": "Tôi có thể...", "pronunciation": ["/toj˧ kɔ˧˥ tʰe˧˩/"], "example": {"sentence": "Tôi có thể lái xe.", "translation": "我會開車。"}, "usage_note": "能力。", "image_file": "can.png" },
        { "id": "g-04", "term_zh": "我喜歡做...", "term_target": "Tôi thích...", "pronunciation": ["/toj˧ tʰic̚˧˥/"], "example": {"sentence": "Tôi thích đọc sách.", "translation": "我喜歡閱讀。"}, "usage_note": "興趣。", "image_file": "like_ing.png" },
        { "id": "g-05", "term_zh": "我想做...", "term_target": "Tôi muốn...", "pronunciation": ["/toj˧ muən˧˥/"], "example": {"sentence": "Tôi muốn đi.", "translation": "我想去。"}, "usage_note": "想要。", "image_file": "want_to.png" },
        { "id": "g-06", "term_zh": "你是...嗎?", "term_target": "Bạn có phải là... không?", "pronunciation": ["/ɓaːn˧˨ˀ kɔ˧˥ faːj˧˩ laː˨˩... xoŋ͡m˧/"], "example": {"sentence": "Bạn có phải là học sinh không?", "translation": "你是學生嗎？"}, "usage_note": "確認身分。", "image_file": "are_you.png" },
        { "id": "g-07", "term_zh": "不要...", "term_target": "Đừng...", "pronunciation": ["/ɗɨŋ˨˩/"], "example": {"sentence": "Đừng đi.", "translation": "不要走。"}, "usage_note": "禁止/請求。", "image_file": "dont.png" },
        { "id": "g-08", "term_zh": "你有做...嗎?", "term_target": "Bạn có... không?", "pronunciation": ["/ɓaːn˧˨ˀ kɔ˧˥... xoŋ͡m˧/"], "example": {"sentence": "Bạn có ăn không?", "translation": "你要吃嗎？"}, "usage_note": "一般疑問句。", "image_file": "do_you.png" },
        { "id": "g-09", "term_zh": "你曾經...嗎?", "term_target": "Bạn đã từng... chưa?", "pronunciation": ["/ɓaːn˧˨ˀ ɗaː˧ˀ˥ tɨŋ˨˩... tɕɨə˧/"], "example": {"sentence": "Bạn đã từng đi chưa?", "translation": "你有去過嗎？"}, "usage_note": "問經驗。", "image_file": "have_you_ever.png" },
        { "id": "g-10", "term_zh": "你何時做...?", "term_target": "Khi nào bạn...?", "pronunciation": ["/xi˧ naːw˨˩ ɓaːn˧˨ˀ.../"], "example": {"sentence": "Khi nào bạn ngủ?", "translation": "你何時睡？"}, "usage_note": "問時間點。", "image_file": "when_do_you.png" },
        { "id": "g-11", "term_zh": "你在哪裡做...?", "term_target": "Bạn... ở đâu?", "pronunciation": ["/ɓaːn˧˨ˀ... əː˧˩ ɗəw˧/"], "example": {"sentence": "Bạn mua ở đâu?", "translation": "你在哪買？"}, "usage_note": "問地點。", "image_file": "where_do_you.png" },
        { "id": "g-12", "term_zh": "你如何做...?", "term_target": "Bạn... như thế nào?", "pronunciation": ["/ɓaːn˧˨ˀ... ɲɨ˧ tʰe˧˥ naːw˨˩/"], "example": {"sentence": "Bạn đi như thế nào?", "translation": "你怎麼去？"}, "usage_note": "問方法。", "image_file": "how_do_you.png" },
        { "id": "g-13", "term_zh": "我不是...", "term_target": "Tôi không phải là...", "pronunciation": ["/toj˧ xoŋ͡m˧ faːj˧˩ laː˨˩/"], "example": {"sentence": "Tôi không phải là học sinh.", "translation": "我不是學生。"}, "usage_note": "否定身分。", "image_file": "i_am_not.png" },
        { "id": "g-14", "term_zh": "我不做...", "term_target": "Tôi không...", "pronunciation": ["/toj˧ xoŋ͡m˧.../"], "example": {"sentence": "Tôi không ăn.", "translation": "我不吃。"}, "usage_note": "否定動作。", "image_file": "i_dont.png" },
        { "id": "g-15", "term_zh": "我不能(會)...", "term_target": "Tôi không thể...", "pronunciation": ["/toj˧ xoŋ͡m˧ tʰe˧˩/"], "example": {"sentence": "Tôi không thể lái xe.", "translation": "我不會開車。"}, "usage_note": "能力否定。", "image_file": "i_cant.png" },
        { "id": "g-16", "term_zh": "我未曾...", "term_target": "Tôi chưa bao giờ...", "pronunciation": ["/toj˧ tɕɨə˧ ɓaːw˧ zəː˨˩/"], "example": {"sentence": "Tôi chưa bao giờ ăn.", "translation": "我一次都沒吃過。"}, "usage_note": "無此經驗。", "image_file": "i_have_never.png" },
        { "id": "g-17", "term_zh": "我不必...", "term_target": "Tôi không cần...", "pronunciation": ["/toj˧ xoŋ͡m˧ kən˨˩/"], "example": {"sentence": "Tôi không cần đi.", "translation": "我不必去。"}, "usage_note": "無義務。", "image_file": "i_dont_have_to.png" },
        { "id": "g-18", "term_zh": "如果...的話", "term_target": "Nếu...", "pronunciation": ["/new˧˥/"], "example": {"sentence": "Nếu rẻ thì mua.", "translation": "如果便宜的話我就買。"}, "usage_note": "假設條件。", "image_file": "if.png" },
        { "id": "g-19", "term_zh": "當...時", "term_target": "Khi...", "pronunciation": ["/xi˧/"], "example": {"sentence": "Khi còn nhỏ.", "translation": "小時候(當我是孩子時)。"}, "usage_note": "時間條件。", "image_file": "when_condition.png" },
        { "id": "g-20", "term_zh": "請你...好嗎?", "term_target": "Bạn có thể... không?", "pronunciation": ["/ɓaːn˧˨ˀ kɔ˧˥ tʰe˧˩... xoŋ͡m˧/"], "example": {"sentence": "Bạn có thể giúp tôi không?", "translation": "可以幫我嗎？"}, "usage_note": "請求。", "image_file": "can_you.png" },
        { "id": "g-21", "term_zh": "我們來做...吧", "term_target": "Hãy cùng...", "pronunciation": ["/haj˧ˀ˥ kuŋ˨˩.../"], "example": {"sentence": "Hãy cùng đi.", "translation": "一起走吧。"}, "usage_note": "提議。", "image_file": "lets.png" },
        { "id": "g-22", "term_zh": "我認為...", "term_target": "Tôi nghĩ...", "pronunciation": ["/toj˧ ŋi˧ˀ˥/"], "example": {"sentence": "Tôi nghĩ là tốt.", "translation": "我認為很好。"}, "usage_note": "表達想法。", "image_file": "i_think.png" },
        { "id": "g-23", "term_zh": "我必須...", "term_target": "Tôi phải...", "pronunciation": ["/toj˧ faːj˧˩/"], "example": {"sentence": "Tôi phải làm việc.", "translation": "我必須工作。"}, "usage_note": "義務。", "image_file": "i_have_to.png" },
        { "id": "g-24", "term_zh": "做某事是...的", "term_target": "Làm... thì...", "pronunciation": ["/laːm˨˩... tʰi˨˩/"], "example": {"sentence": "Ăn thì vui.", "translation": "吃東西是開心的。"}, "usage_note": "描述動作。", "image_file": "it_is_to.png" },
        { "id": "g-25", "term_zh": "我可以...嗎?", "term_target": "Tôi có thể... không?", "pronunciation": ["/toj˧ kɔ˧˥ tʰe˧˩... xoŋ͡m˧/"], "example": {"sentence": "Tôi có thể chụp ảnh không?", "translation": "我可以拍照嗎？"}, "usage_note": "請求許可。", "image_file": "can_i.png" },
        { "id": "g-26", "term_zh": "我比較喜歡...", "term_target": "Tôi thích... hơn", "pronunciation": ["/toj˧ tʰic̚˧˥... hơːn˧/"], "example": {"sentence": "Tôi thích cái này hơn.", "translation": "我比較喜歡這個。"}, "usage_note": "偏好。", "image_file": "prefer.png" },
        { "id": "g-27", "term_zh": "A比B更...", "term_target": "A... hơn B", "pronunciation": ["/A... hơːn˧ B/"], "example": {"sentence": "Cái này đắt hơn cái kia.", "translation": "這比那個貴。"}, "usage_note": "比較級。", "image_file": "more_than.png" },
        { "id": "g-28", "term_zh": "有(存在)...", "term_target": "Có...", "pronunciation": ["/kɔ˧˥/"], "example": {"sentence": "Có con chó.", "translation": "有一隻狗。"}, "usage_note": "存在。", "image_file": "there_is.png" },
        { "id": "g-29", "term_zh": "我曾經是/當時是...", "term_target": "Tôi đã là...", "pronunciation": ["/toj˧ ɗaː˧ˀ˥ laː˨˩/"], "example": {"sentence": "Tôi đã là học sinh.", "translation": "我曾經是學生。"}, "usage_note": "過去狀態。", "image_file": "i_was.png" },
        { "id": "g-30", "term_zh": "我將要...", "term_target": "Tôi sẽ...", "pronunciation": ["/toj˧ sɛ˧ˀ˥/"], "example": {"sentence": "Tôi sẽ đi.", "translation": "我要去。"}, "usage_note": "未來意。", "image_file": "i_will.png" },
        { "id": "g-31", "term_zh": "我做過(過去式)...", "term_target": "Tôi đã...", "pronunciation": ["/toj˧ ɗaː˧ˀ˥/"], "example": {"sentence": "Tôi đã làm bài tập.", "translation": "我做完功課了。"}, "usage_note": "過去動作。", "image_file": "i_did.png" }
      ]
    }
  ]
};